openstreetmap/openstreetmap-website

- app/views/site/export.html.erb
See #4665.
This PR keeps 0123456789 digits with decimal dot and makes `-` always appear on the left side.
Before:
After:
> Force ltr direction in export inputs

- app/assets/stylesheets/common.scss
- app/views/layouts/_header.html.erb
- app/views/layouts/map.html.erb
Open the right sidebar, then open a dropdown menu ("more" or user menu):
Seems to work fine. Now make the screen smaller. If you get the intermediate width like in #4675, the dropdown menu will be covered by the sidebar:
Bootstrap sets z-index to 1000 on dropdowns which should be high enough, but we use even higher z-indexes on map ui elements. We do this to keep them above Leaflet's range of z-indexes. What we could do instead and what this PR does is to isolate Leaflet in its own [stacking context](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_positioned_layout/Understanding_z-index/Stacking_context). Here I set the entire map at z-0 with a Bootstrap utility class. The right sidebar gets z-2 to stay above the floating left sidebar, which gets z-1.
Open the right sidebar on a …
> Use Bootstrap utilities to set z-indexes of map ui and fix some bugs

- app/assets/stylesheets/common.scss
Not in use since https://github.com/openstreetmap/openstreetmap-website/commit/adfb4dc61945b7b441695885b3b273bfdf712332
> Remove .prose css selector

- app/assets/stylesheets/common.scss
- app/assets/stylesheets/parameters.scss
It had no effect inside .inbox-row selector because table cells override the background.
> Remove unused $offwhite color

- app/assets/stylesheets/common.scss
Was in "Rules for messages pages" for some reason.
> Move search form css to correct section

- app/assets/stylesheets/common.scss
We have a custom color for counter badges. But it's too bright for dark mode. It's too bright even for light mode because it's brightness is too close to the header background.
Light mode before:
Light mode after:
Dark mode before:
Dark mode after:
> Darken + add transparency to counter badges

- app/assets/stylesheets/common.scss
- app/views/browse/_tag.html.erb
- app/views/notes/index.html.erb
Previous attempts:
- #4669
- #4672
- #4693
- #4695
Assumptions:
- We're committed to style tables with `table-*` classes as if Bootstrap supports dark mode.
- Because Bootstrap actually doesn't support dark mode with `table-*` we want some isolated fix that's going to be removed once the support is there.  This fix is in the changes to `common.scss`.
- We don't want classes like `table-light` because we don't want table cells to stay light in dark mode. But this class was used in tags table for tag keys, so it has to be replaced with some other `table-*` class. It's replaced here with `table-secondary` although this makes tag key cells darker in light mode.
---
Tags table in light mode before the changes:
Tags table in light mode after the changes:
Tags table in dark mode after the …
> Support dark mode in notes and tags tables

- app/views/changesets/_changeset.html.erb
> Use "emphasis" link color in changeset lists instead of dark text

- app/assets/javascripts/index/directions.js
- app/assets/stylesheets/common.scss
There was a hover effect on rows in directions tables. It got broken probably when Bootstrap started setting background directly on table cells instead of table rows.
Here I'm using their standard hoverable rows. The color is different. We used to have a yellow highlight, but that one would have to be adapted to dark mode while the standard highlight works fine.
Before:
After:
> Use Bootstrap hoverable rows in directions tables

- config/environments/test.rb
- test/factories/user.rb
update: This is now ready to merge!
Doing a quick audit of the test harness, to see where time is being spent, and to try side-stepping some of it. 
I'm doing lots of this work locally, but defer to using Github Actions timing data as the gold standard for if I'm successful or not. 
[I have some live, detailed, time-stamped stream-of-consciousness notes here](https://gist.github.com/josh-works/552c7db716372431d5b181f19ee36804), might be helpful to future me or others.
I am primarily investigating 'just' the tests, rather than tweaking the build pipeline at all. Faster/easier tests are so low-risk, high-reward. 
Here's the test suite on `main`, right now, as I open this PR:
here's the detailed results on tests as being run on another PR: …
> Reduce test run time portion of build process (8:31 reduced to 3:51)

- app/assets/stylesheets/common.scss
- app/views/browse/_tag_details.html.erb
Fixes #4709, kind of.
Aside from differences in browser behavior, there's also a decision by the Bootstrap developers. [They disable `.text-break` in rtl mode](https://getbootstrap.com/docs/5.3/utilities/text/#word-break). They say that rtl is most likely Arabic and word breaks in Arabic are wrong therefore disable word breaks for any rtl. But in our case any long words in tags table are likely not Arabic but rather urls or something similar.
Here I'm putting the css properties that are normally in Bootstrap's `.text-break` to our custom css. This will restore word breaks in rtl tag tables, occasionally with "wrong" Arabic word breaks.
Screenshots in Chrome (Firefox does word wraps anyway for whatever reason):
Before:
After:
> Force word wrap in tag table

- app/views/shared/_pagination.html.erb
There is a [Bootstrap class](https://getbootstrap.com/docs/5.3/helpers/icon-link/) for displaying icons next to links. Shared pagination has "<"/">" icons which could be attached using this class. But initially I didn't use it because it's named a bit deceptively.
When we're on the first page, there's no link to the previous page yet we still want to attach the icon to the text in the disabled page item. Will `.icon-link` work in this case, without a link? Yes it will, Bootstrap [doesn't check](https://github.com/twbs/bootstrap/blob/ad0cc68b7e226d9e1c1feb39ca68c0404c304365/scss/helpers/_icon-link.scss#L1) if `.icon-link` is used on a link or on anything else.
> Use Bootstrap .icon-link in shared pagination

- app/assets/stylesheets/common.scss
- app/assets/stylesheets/parameters.scss
- app/views/messages/_message_summary.html.erb
- app/views/messages/_sent_message_summary.html.erb
- test/controllers/messages_controller_test.rb
- I remove the custom *unread message* background and replace it with `table-success`. The custom background was applied directly to table cells which we presumably don't want. This changes the green color used in the table.
- I extend dark mode overrides to cover `table-success`.
- I remove the `inbox-row` class. It was also used in the outbox.
Light mode before:
Light mode after:
Dark mode after:
> Adapt messages table to dark mode

- app/assets/stylesheets/common.scss
> Adapt Leaflet popups to dark mode

- app/assets/javascripts/user.js
- app/assets/stylesheets/common.scss
Leaflet may get confused if you use css `min-width` property on popup contents.
Examples in Chromium where scrollbars always take width.
Here I made the contents longer and limited the popup height while keeping css `min-width`:
This is with `minWidth` `.bindPopup` option, no horizontal scrollbars appear:
> Use bindPopup options to set min width of user popup

- app/assets/stylesheets/common.scss
- app/views/changesets/_changeset.html.erb
Like #4711 but for changeset history lists.
> Use Bootstrap actionable items in changeset lists

- app/assets/javascripts/index/search.js
The simulation is not required because the link is stretched.
I stretched links in https://github.com/openstreetmap/openstreetmap-website/commit/62ba143c3c0b7608dcd41f9604fe35ca22d126b4 but I was focused on removing the mouse pointer css and didn't change javascript.
> Remove simulating clicks on <a> when <li> is clicked

- app/assets/stylesheets/common.scss
For `<small>` Bootstrap sets the font size to almost the same, 12.25px vs our custom 12px:
https://github.com/twbs/bootstrap/blob/d7b22b77dbe7d1bd8d5cb03cec5d89b480500afb/scss/_reboot.scss#L211
Looks like we don't use `<aside>` anywhere.
> Remove custom small font size

- app/assets/stylesheets/common.scss
- app/helpers/application_helper.rb
- app/views/diary_entries/index.html.erb
- test/helpers/application_helper_test.rb
Removes custom classes `rsssmall` and `small_icon`.
> Use Bootstrap classes for diary navigation icons

- app/assets/stylesheets/common.scss
- app/views/site/fixthemap.html.erb
- app/views/site/welcome.html.erb
The icons should look the same as before:
> Remove custom css for note icons on welcome and fixthemap pages

- app/assets/stylesheets/common.scss
- Many images are not inside `<p>`, this css doesn't apply to them.
- `width: auto` is a default width
- `max-width: 100%` shrinks images that are too wide to fit on the screen. Images inside rich text (diaries, comments) already have this set elsewhere.
- It affects image on the [copyright](https://www.openstreetmap.org/copyright) page, but that image is narrow enough. If there's any wide image that requires shrinking, [`.img-fluid`](https://getbootstrap.com/docs/5.3/content/images/#responsive-images) can be used instead.
> Remove custom css applied to images inside paragraphs

- app/assets/stylesheets/common.scss
Before in light and dark mode:
After in light mode:
After in dark mode:
> Adapt Leaflet context menus to dark mode

- app/assets/stylesheets/common.scss
There's a message counter in the upper right corner (`#inboxanchor`). It was gray for a long time (https://github.com/openstreetmap/openstreetmap-website/commit/ff752b072f44aad142314a57eed79271928d181a) but why? Other counters are green, including the same counter in the dropdown menu.
Before in light mode:
Before in dark mode:
After in light mode:
After in dark mode:
> Remove color override for user dropdown message count

- app/assets/javascripts/messages.js
- app/views/messages/_message_summary.html.erb
- app/views/messages/_sent_message_summary.html.erb
They are not necessary because they select every table body row, and the table already has its own class.
They were added in #4562 to set up listeners that start fadeout deletion animations.
> Remove .message-summary css classes and selectors

- app/views/messages/_messages_table.html.erb
I accidentally changed display properties of table cells by using `.d-flex`, then I fixed it in #4702. However by that time `.d-flex` spread to more table cells in https://github.com/openstreetmap/openstreetmap-website/commit/3e69a4512f2d1b39f48719882a0d112d042da73a. Here I'm removing it from message actions header cell.
> Don't change display property of messages table header cell

- app/views/traces/_trace.html.erb
Try to move keyboard focus to a trace thumbnail while on a trace list page. This is what you'll see in Firefox:
After the fix:
`<img>` is an inline element by default, `<a>` is also an inline element, so a link with a thumbnail inside is as tall as a line of text. And it's shorter than the actual image size. You can see this in browser dev tools, both in Firefox and in Chrome. Chrome still draws the outline around the image but Firefox doesn't.
> Set trace thumbnail link display property to inline-block, fixing focus outline

- app/assets/stylesheets/common.scss
- app/views/layouts/map.html.erb
Map tiles are going to be too bright in dark mode. The question is then what to do with them. There are two options: dim them or invert them, and the existing dark themes like [this one](https://userstyles.world/style/15596/openstreetmap-dark-theme) may offer a choice.
Here I'm making a conservative choice of 80% dimming.
> Dim map tiles in dark mode

- config/routes.rb
- test/controllers/notes_controller_test.rb
Elements, changesets, notes had constraints in their id parameter in routes. https://github.com/openstreetmap/openstreetmap-website/commit/9748ce301c9488b9cd32439448770c3d4a38ebd6 removed this constraint for notes for unknown reason. Without this constraint notes controller needs different tests. The part of "browse_check" that checks negative ids had to be commented out.
This PR restores the constraint which allows to use the same "browse_check" as for every other entity formerly handled by browse controller.
> Restore constraints on note id parameter, simplify tests

- app/controllers/changesets_controller.rb
- test/controllers/changesets_controller_test.rb
Fixes #450, hiding previous/next empty changesets.
There's also an opposite request #3592.
> Link to previous/next nonempty user's changeset on changeset pages

- app/controllers/messages_controller.rb
- test/controllers/messages_controller_test.rb
Fixes #4750 by redirecting when "Mark as unread" is clicked on a message page. For example Github notifications work like that: if you mark a notification as unread it redirects you to the notifications list.
I rename the `unread_message` variable in tests because the message doesn't stay unread.
I reuse the xhr test lines for referer test because xhr is not in use since the Turbo update.
> Redirect to inbox after marking a message as read/unread

- test/controllers/messages_controller_test.rb
Remove tests with "... with no ID should fail ... assert_response :success" and like. They don't do what their comments say and never test missing ids.
Rails is being [smart with path helpers](https://thoughtbot.com/blog/avoid-making-path-helpers-guess) here. It sees that an id is missing and it uses the id from the previous request.
> Remove tests for message paths without ids

- app/assets/javascripts/auth_providers.js
- app/assets/javascripts/login.js
- app/assets/stylesheets/common.scss
- app/controllers/concerns/session_methods.rb
- app/controllers/sessions_controller.rb
- app/controllers/users_controller.rb
- app/helpers/user_helper.rb
- app/models/user.rb
- app/views/application/_auth_providers.html.erb
- app/views/layouts/_header.html.erb
- app/views/sessions/new.html.erb
- app/views/users/blocked.html.erb
- app/views/users/new.html.erb
- config/locales/en.yml
- test/controllers/confirmations_controller_test.rb
- test/controllers/users_controller_test.rb
- test/helpers/user_helper_test.rb
- test/integration/user_creation_test.rb
- test/system/confirmation_resend_test.rb
- test/system/user_signup_test.rb
Implements proposal discussed in [Issue 4128](https://github.com/openstreetmap/openstreetmap-website/issues/4128).
- Merge Signup screen and Terms screen during signup process.
- Use links to Contributor terms and Terms of use instead of in-place edit box.
- Terms screen used for accepting the new terms left unchanged.
- Re-arranged signup and login screens to feel like two tabs as in #4128.
- Add `preferred_auth_provider` parameter to signup and login screens, as well as the authorization request.
This allows 3rd party apps to initiate authorization by adding `preferred_auth_provider`
Screenshots in dev environment:
> Re-arrange login and signup screens as discussed in #4128

- Gemfile
- Gemfile.lock
The latest release of the `browser` gem, version 6.0.0, dropped support for ruby 3.0 and ruby 3.1. Ruby 3.0 is our minimum supported version, at least until we drop support for Ubuntu 20.04.
This PR constrains `browser` to "< 6" in order to keep supporting ruby 3.0
> Pin browser to versions that support ruby 3.0

- app/helpers/user_roles_helper.rb
Before:
You can see that the moderator star is significantly darker than the others and it is too dark for dark mode.
After:
> Lighten moderator icon color

- app/helpers/user_roles_helper.rb
> Make blank role icons transparent

- app/assets/javascripts/application.js
- app/assets/javascripts/bs-custom-file-input-init.js
- package.json
- yarn.lock
That was a [Bootstrap 4 plugin](https://getbootstrap.com/docs/4.6/components/forms/#file-browser). Bootstrap 5 docs [no longer recommend it](https://getbootstrap.com/docs/5.3/forms/form-control/#file-input). It doesn't do anything because there are no inputs matching [its selector](https://github.com/Johann-S/bs-custom-file-input/blob/a4cb893188f06e94c811bac1e5c3682bb4b0e459/src/selector.js#L2).
> Remove bs-custom-file-input javascript plugin

- app/controllers/accounts_controller.rb
- app/controllers/users_controller.rb
Add login.microsoftonline.com to CSP allow list for `/account/new`, `/account/edit` and `/users/new`
To reproduce:
`/account/edit`
- Login as existing user
- go to "My Settings"
- change "External Authentication" to Microsoft
- click "Save Changes"
- Page fails to load due to CSP violation
`/account/update` ?
`/users/new`
- Login to https://login.live.com with your existing MS account
- navigate to https://www.openstreetmap.com/login
- click on Microsoft Icon to use social account
- on `/user/new` page click "Sign up"
- Page fails to load due to CSP violation
> Fix CSP failures for Microsoft social sign-in

- app/views/sessions/new.html.erb
- app/views/users/new.html.erb
Fixes "bg-white" from #4773.
Before:
After:
> Use bg-body in "log in / sign up to access" messages

- CONTRIBUTING.md
- INSTALL.md
- README.md
- config/locales/README
There's also a gembundler.com link in INSTALL.md, is it supposed to be bundler.io?
> Use https links in documentation

- app/views/notes/new.html.erb
- config/locales/en.yml
- test/controllers/notes_controller_test.rb
Fixes #244.
The goal is to:
- tell users who are not registered and add notes why they might want to register
- tell users who forgot to log in that they might want to log in
> Add warnings when creating notes anonymously

- app/controllers/api_controller.rb
- app/controllers/application_controller.rb
- app/controllers/oauth_controller.rb
- config/locales/en.yml
- config/settings.yml
This extends the previous work to allow authentication basic auth and OAuth 1 to be disabled to return an error message so that users have some chance of discovering what is going on.
I'll make this a draft for now as we may want to add more detail to the messages...
> Return an error when a disabled authentication mechanism is used

- app/controllers/traces/icons_controller.rb
- app/controllers/traces/pictures_controller.rb
- app/models/trace.rb
This further simplifies the trace image controllers by adding an `imported` scope to the trace model which eliminates a duplicate "not found" branch.
It also drops some redundant code for handling legacy traces that should have been removed in #3491.
> Trace image cleanups

- app/controllers/api/user_preferences_controller.rb
- test/controllers/api/user_preferences_controller_test.rb
Anonymised log extract for an error captured in production:
```
Started PUT "/api/0.6/user/preferences/key" for a.b.c.d at 2024-05-16 15:53:45 +0000
Processing by Api::UserPreferencesController#update as */*
Parameters: {"preference_key"=>"key"}
API threw unexpected Encoding::CompatibilityError exception: incompatible encoding regexp match (UTF-8 regexp with ASCII-8BIT string)
/srv/www.openstreetmap.org/rails/app/validators/characters_validator.rb:6:in `match?'
/srv/www.openstreetmap.org/rails/app/validators/characters_validator.rb:6:in `validate_each'
/var/lib/gems/3.0.0/gems/activemodel-7.1.3.2/lib/active_model/validator.rb:155:in `block in validate'
/var/lib/gems/3.0.0/gems/activemodel-7.1.3.2/lib/active_model/validator.rb:151:in `each' …
```
> Fix exception uploading a unicode preference value

- app/views/site/fixthemap.html.erb
[
](https://validator.w3.org/nu/?showoutline=yes&doc=https%3A%2F%2Fwww.openstreetmap.org%2Ffixthemap#headingoutline)
> Don't skip heading levels on "fixthemap" page

- app/views/layouts/_header.html.erb
- app/views/layouts/_inbox.html.erb
This partial template used to be included from different places, but now it's included only from header. I want to make changes to it that are specific to the account button. It would make no sense for them to be in a different file.
Also `id="inboxanchor"` is not necessary after Turbo updates.
> Remove inbox template and anchor id

- app/views/layouts/_header.html.erb
Was used to replace the inbox counter before Turbo:
https://github.com/openstreetmap/openstreetmap-website/commit/1a7b7f5d18931f60f4171b7ac410ea4434828dd1#diff-305c268f66d28c4cd669b9a69449100d2de05f2b61da1e58914295c1eea45e16L22
`<span class='username'>` is also unnecessary but I'm going to use it later to limit the username width.
> Remove unnecessary user menu wrapper

- app/controllers/concerns/session_methods.rb
- app/controllers/sessions_controller.rb
- app/controllers/users_controller.rb
- app/views/sessions/new.html.erb
- app/views/users/new.html.erb
Using the session to persist the referer is not necessary and can be problematic in that if a login/signup is aborted partway through then the referer information can persist in the session and be reused during a later attempt.
> Stop using the session to persist the referer during login

- app/assets/javascripts/index/directions.js
- app/assets/javascripts/leaflet.layers.js
- app/assets/javascripts/leaflet.share.js
- app/assets/stylesheets/common.scss
- app/helpers/user_helper.rb
- app/views/accounts/edit.html.erb
- app/views/application/_auth_providers.html.erb
- app/views/browse/_node.html.erb
- app/views/browse/_relation.html.erb
- app/views/browse/_way.html.erb
- app/views/changesets/_heading.html.erb
- app/views/changesets/show.html.erb
- app/views/confirmations/confirm.html.erb
- app/views/dashboards/_contact.html.erb
- app/views/diary_entries/_diary_comment.html.erb
- app/views/diary_entries/_diary_entry.html.erb
- app/views/diary_entries/_diary_entry_heading.html.erb
- app/views/diary_entries/comments.html.erb
- app/views/issues/_comments.html.erb
- app/views/issues/_reports.html.erb
- app/views/issues/show.html.erb
- app/views/notes/show.html.erb
- app/views/oauth2_applications/_application.html.erb
- app/views/oauth2_applications/show.html.erb
- app/views/profiles/edit.html.erb
- app/views/sessions/new.html.erb
- app/views/traces/_trace.html.erb
- app/views/users/new.html.erb
- app/views/users/show.html.erb
- app/views/users/terms.html.erb
The `text-muted` class is [deprecated](https://getbootstrap.com/docs/5.3/migration/#utilities-1) and will be removed in bootstrap 6.
> Replace deprecated text-muted class with text-body-secondary

- app/assets/stylesheets/common.scss
- app/views/layouts/_header.html.erb
Removes pixel sizes specific to the logo.
`.icon-link` also makes the gap between the logo and "OpenStreetMap" slightly bigger:
> Use .icon-link to align logo

- app/views/layouts/_header.html.erb
This PR addresses "Top menu buttons" issue mentioned in the  #4773
I retrieved app/views/layouts/_header.html.erb Ln 107 to previous state in which it doesn't try to hide "Log In" and "Sign Up" buttons in header.
> Fixed "Top menu buttons" issue mentioned in the #4773

- app/views/sessions/new.html.erb
- app/views/users/new.html.erb
This PR addresses "Tab alignment" issue mentioned in the #4773
I removed px-3 class from ul tag defining area in which are "Log in" and "Sign up" tabs.
> Fixed "Tab alignment" issue described in #4773

- app/assets/stylesheets/common.scss
- app/views/notes/show.html.erb
- left margin is similar to what's being used on note comments
- bottom margin - I don't think it's required here because paragraphs inside descriptions already have bottom margins
> Remove custom css from note descriptions

- app/assets/stylesheets/common.scss
In small mode logo+h1 move up slightly. It seems like they shouldn't because there's `> * { height: 100%; ...}` css, but it doesn't do anything. What actually kept them from moving was `padding-top: 15px;` which I removed in #4823. I'm not going to put this padding back in. Instead I just set their height directly.
> Keep header h1 height equal to default header height

- app/assets/javascripts/leaflet.layers.js
- app/assets/stylesheets/common.scss
I use `.small` font size from Bootstrap which is slightly smaller than the current custom 13px size.
> Remove custom css from "Enable overlays" text

- app/controllers/site_controller.rb
Fixes problems like https://github.com/openstreetmap/iD/issues/10259.
This is a slight regression in #4627, as the code previously _appended_[^1] the additional CSP rules and now they are overwritten. I assume this was an oversight in the migration process, or was the omission of the existing `img-src` rules there on purpose? In that case, the `:data` type should be added as `policy.img_src("*", :blob, :data)`.
[^1]: see https://github.com/openstreetmap/openstreetmap-website/pull/4627/files#diff-c7e7144de4dcf44dbb148d4acc6aa4a9d8581c6a581966a0bbfb598e79730f14L139
> allow data URIs for images in iD

- app/controllers/site_controller.rb
* by now, all used Bing services are queried directly via REST APIs, so `dev.virtualearth.net` should not be required anymore
* `unsafe-eval` was added with 527ec293c2cd84e777e8f05b4bdcf2b3b611a5e0, but as far as I can see, neither the current mapillary SDK nor any other parts of iD perform any dirty tricks with `eval` & co.
> update script-src CSP rules for iD

- app/assets/stylesheets/common.scss
#4835 removes `#browse_status` but there's also `.browse_status`. I can't find any use of this class at any time.
> Remove unused .browse_status css class

- app/assets/stylesheets/common.scss
- app/views/accounts/edit.html.erb
- app/views/notes/new.html.erb
- app/views/notes/show.html.erb
See the deleted css comment for why it was used. You can achieve the same effect with [gutters](https://getbootstrap.com/docs/5.3/layout/gutters/) when using Bootstrap rows or with `.d-flex` + [gaps](https://getbootstrap.com/docs/5.3/utilities/spacing/#gap).
Account settings in a very narrow window:
Note edit buttons:
> Replace .btn-wrapper with Bootstrap gutters/gaps

- app/assets/stylesheets/common.scss
Like #4836 I can't find it ever being used. Maybe it was meant to be `<div id="content">`?
> Remove unused #container css

- app/assets/javascripts/application.js
- app/assets/stylesheets/common.scss
- app/views/layouts/_header.html.erb
Like #4723 + adjustments inside the user button + increased horizontal spacing between menu items (in #4723 the spacing decreased because with `display: flex` whitespace between items gets removed).
I get rid of `h1, nav, nav > ul, nav > ul > li` selector and do other changes in order to switch later to Bootstrap navbar and decrease the number of menu/sidebar visibility modes.
Before / after when not logged in:
Before / after with issues counter:
Before / after with message counter:
> Adjust vertical alignment of secondary header navigation

- app/controllers/site_controller.rb
Fixes a regression introduced by me in #4841. Fixes https://github.com/openstreetmap/iD/issues/10265
> reintroduce unsafe-eval CSP rule for iD (Mapillary layer)

- app/views/application/_auth_providers.html.erb
This PR addresses "auth_button_prefered alignment" issue mentioned in the #4773
In app/views/application/_auth_providers_html.erb, updated div's styles and updated layout (parent div + 2 (or 1) child div area). Here are the screenshots before and after the changes:
Before:
After:
> Fixed "auth_button_preferred alignment" issue described in #4773

- app/controllers/api/capabilities_controller.rb
- app/controllers/api/changeset_comments_controller.rb
- app/controllers/api/changesets_controller.rb
- app/controllers/api/map_controller.rb
- app/controllers/api/nodes_controller.rb
- app/controllers/api/notes_controller.rb
- app/controllers/api/old_elements_controller.rb
- app/controllers/api/permissions_controller.rb
- app/controllers/api/relations_controller.rb
- app/controllers/api/tracepoints_controller.rb
- app/controllers/api/traces_controller.rb
- app/controllers/api/user_blocks_controller.rb
- app/controllers/api/user_preferences_controller.rb
- app/controllers/api/users_controller.rb
- app/controllers/api/versions_controller.rb
- app/controllers/api/ways_controller.rb
- app/controllers/api_controller.rb
- test/controllers/api/capabilities_controller_test.rb
- test/controllers/api/versions_controller_test.rb
This PR addresses https://github.com/openstreetmap/openstreetmap-website/issues/4858 by standardising on not have `:except` lists for the `_readable` checks.
It also takes things one step further, by moving the before_action into the parent api_controller, and skipping that action in the only two controllers that need to skip it (and adding tests for those).
> Refactor api actions

- app/controllers/users_controller.rb
- test/integration/user_creation_test.rb
It does not add any additional guards against malicious users:
Malicious user may attempt to invoke `POST /users/new` with bogus values for `auth_provider` and `auth_uid` resulting with a new account to which user would have a way to login, other than sending a password reset request.
In some cases, re-authorization would introduce additional "Please login to your social account", or "Are you sure you want to be logged in" popup triggered by identity provider.
This PR removes the re-authorization request from `POST /users/new` in authorization flow.
> Social sign-in: avoid re-authorization in `users_controller#create`

- app/views/sessions/new.html.erb
- app/views/users/new.html.erb
This PR addresses "or divider" issue mentioned in the #4773
In app\views\sessions\new.html.erb and app\views\users\new.html.erb added mb-2 after "or" divider.
Before:
After:
> Fixed "or divider" issue described in #4773

- app/views/layouts/_search.html.erb
Should fix #1414 according to https://github.com/openstreetmap/openstreetmap-website/issues/1414#issuecomment-2130065798. I can't test it without an iPhone.
Changed small form controls to default ones. This makes font size to be 16px.
But there's another obstacle: the *Go* button. "Go" is short enough in English, but how about other languages. With a larger font it may get too large. To avoid that I replaced "Go" with a magnifying glass icon.
Before/after in English:
Before/after in Bulgarian (wider labels):
Before/after in Polish (already trying to replace "Go" with a symbol):
Before/after in Arabic:
200% zoom:
> Larger font size in search form, svg icon for "Go" button

- app/views/notes/show.html.erb
https://github.com/openstreetmap/openstreetmap-website/commit/c276625e7f35a1f9c31fe95325e150879f0b9a73 replaced html + interpolated attributes with `submit_tag`, but only for open note buttons. This PR does the same for closed note buttons.
> Write closed note controls using submit_tag

- app/helpers/browse_tags_helper.rb
- test/helpers/browse_tags_helper_test.rb
In links like [https://de.wikipedia.org/wiki/de:Test?uselang=en](https://de.wikipedia.org/wiki/de:Test?uselang=en) what do you need `de:` for? `de` is already in the domain name `de.wikipedia.org`. iD and Overpass Turbo don't include this prefix.
If the prefix in the path differs from domain name, as was in one of the test cases [https://fr.wikipedia.org/wiki/de:Test?uselang=en](https://fr.wikipedia.org/wiki/de:Test?uselang=en), you get a redirect, in this case to [https://de.wikipedia.org/wiki/Test?uselang=en](https://de.wikipedia.org/wiki/Test?uselang=en). Just generate this url instead.
> Don't include language prefix in wikipedia links

- app/assets/javascripts/index/note.js
- app/views/notes/show.html.erb
To make sure that #1353 is not a problem even on very narrow screens. `<button>` allows word wrap inside; if you need several words for example for "comment and close", they'll still fit on screen as long as every individual word fits.
Changesets already use `<button>` in discussion forms.
Before:
After:
> Use button elements that allow word wrap for note controls

- app/helpers/open_graph_helper.rb
On the actual osm website `og:image:secure_url` is the same as `og:image`, therefore it's not [an alternate url](https://ogp.me/#structured).
~~~
<meta property="og:image" content="https://www.openstreetmap.org/assets/osm_logo_256-ed028f90468224a272961c380ecee0cfb73b8048b34f4b4b204b7f0d1097875d.png">
<meta property="og:image:secure_url" content="https://www.openstreetmap.org/assets/osm_logo_256-ed028f90468224a272961c380ecee0cfb73b8048b34f4b4b204b7f0d1097875d.png">
~~~
Same for OpenHistoricalMap and probably every publicly available openstreetmap-website instance.
Removing `og:image:secure_url` would make it easier to replace the image if necessary, like #1361.
> Remove Open Graph og:image:secure_url property

- app/assets/javascripts/index/search.js
When you type a search query and click directions button, the *From* field is supposed to be filled based on your query.
This has been broken since at least https://github.com/openstreetmap/openstreetmap-website/commit/f7b8b114a63f58015a8f0645cda6e0578cbe9f42 when the button css classes changed.
> Fix setting "From" in directions form based on search query

- app/views/changesets/show.html.erb
- app/views/diary_entries/show.html.erb
- config/locales/en.yml
They are used not in javascript but rather in .html.erb templates.
> Remove javascripts.changesets locale strings

- app/views/users/show.html.erb
- config/locales/en.yml
This PR addresses "Add last edited date to user profile" issue mentioned in the #3437 
In app/views/users/show.html.erb added new definition for "Last map edit" as date of the user's last changeset modification or "No activity yet" label if user has not edited map yet (previously mentioned '-' could be misunderstood as website error). Also, added labels to translation files.
Before:
After:
> Fixed "Add last edited date to user profile" issue described in #3437

- config/locales/en.yml
Since https://github.com/openstreetmap/openstreetmap-website/commit/a0a18f428f5e77ad1d1321a1a08fa63bf1a8ba0f
> Remove unused map link locale strings

- app/assets/javascripts/richtext.js
Richtext preview div has its width set to the edit textarea, but why?
Make the browser window wide enough and start editing some text:
Click *Preview* and start shrinking the window. You may get something like this because the preview wouldn't shrink:
---
Preview and Help won't overlap if the width setting code is removed:
> Don't set width of richtext preview

- app/models/diary_comment.rb
- app/models/note_comment.rb
- app/models/user.rb
- app/views/users/show.html.erb
- db/migrate/20240605134916_add_notes_and_diary_comments_counter_caches.rb
- db/structure.sql
This PR addresses "Add note and comment counts too the user profile" issue mentioned in the #1643 
In app\views\users\show.html.erb added displaying notes and diary comments counts for both cases when displaying user's own profile page and when displaying user's profile page to the public. Also, added using built-in cached counts for displayed counts.
Before:
After:
> Add note and comment counts to the user profile

- app/helpers/open_graph_helper.rb
It makes sense to add "OpenStreetMap" to `<title>` of every page, but for Open Graph there's already `og:site_name`. I looked at various sites like github, osm forum, they don't add site name to `og:title`.
> Don't add site name to og:title when page title is provided

- app/abilities/ability.rb
- app/controllers/diary_comments_controller.rb
- app/controllers/diary_entries_controller.rb
- app/views/diary_comments/index.html.erb
- config/locales/en.yml
- config/routes.rb
- test/abilities/abilities_test.rb
- test/controllers/diary_comments_controller_test.rb
- test/controllers/diary_entries_controller_test.rb
There was a diary comment model but no controller. Everything related to comments was in the diary entries controller.
Here I'm moving `diary_entries#comments` to `diary_comments#index`. There are at least three other comment actions, I'll move them later.
> Move diary comments index action to comments controller

- app/assets/javascripts/index/directions/graphhopper.js
GraphHopper's routing icon map is missing some entries that are [possible in the results](https://docs.graphhopper.com/#operation/getRoute!c=200&path=paths/instructions/sign&t=response). They are represented as a straight arrow because this icon is at offset zero in the routing sprite svg.
[Keep left/right](https://www.openstreetmap.org/directions?engine=graphhopper_car&route=53.2390%2C14.0022%3B53.3071%2C13.9935) before/after:
[U-turn](https://www.openstreetmap.org/directions?engine=graphhopper_car&route=59.92761%2C30.29539%3B59.92773%2C30.29552) before/after:
> Add missing graphhopper icons

- app/assets/javascripts/index/directions.js
`/directions` javascript has an `awaitingGeocode` state variable, which is true when one of endpoints awaits geocoding results. But each endpoint has its own `awaitingGeocode` state variable too. Endpoint methods manipulate both global and their own state. Why do they need the global state? Only to decide if they need to run `getRoute()`. But `getRoute()` checks `awaitingGeocode` on endpoints anyway. There's no need for the global state.
> Remove global "awaiting geocode" routing state

- app/assets/javascripts/index/directions.js
Currently `.error` is added to these inputs, but it doesn't make them look any different.
> Use .is-invalid to highlight routing inputs with failed geocode lookups

- app/assets/javascripts/index/directions.js
Directions page javascript controller has two route endpoint objects. They manage from/to inputs and markers. When inputs and markers are updated, endpoint objects call `getRoute` method of the controller to redraw the route. But why should endpoints know anything about the entire route? They only need to report that an input or a marker was updated and let the outside code decide what to do in response.
> Use callbacks instead of direct getRoute() calls from route endpoints

- Gemfile
- Gemfile.lock
- app/helpers/open_graph_helper.rb
- test/controllers/diary_entries_controller_test.rb
Fixes #4890.
I used an URI parser to construct absolute URIs, but that thing is stricter than browsers.
<s>Now I only parse urls that don't start with http[s]: and catch invalid URI exceptions.</s>
> Parse og:image urls using Addressable::URI

- app/helpers/browse_tags_helper.rb
- test/helpers/browse_tags_helper_test.rb
Fix https://github.com/openstreetmap/openstreetmap-website/issues/4851 by using the opposite approach to #4855 and what's currently deployed: urlencode everything unless it needs to be unencoded. Things that are not urlencoded:
- `:` in language prefix
- `#` before article section name
Urls will get uglier, especially non-English ones.
> Fully encode wikipedia tag values

- app/controllers/site_controller.rb
- app/views/site/copyright.html.erb
- config/locales/en.yml
I'm moving the title string from `.legal_babble.title_html` to `.title` because it's not in that section and not html.
> Add title to copyright page

- app/views/browse/_common_details.html.erb
- app/views/changesets/_changeset.html.erb
- app/views/changesets/show.html.erb
- app/views/traces/_trace.html.erb
The problem and links to previous solutions are in #2869. Changeset descriptions were made to use italics "to make them look more like quotes" but that doesn't work well with Chinese and maybe other writing systems and large blocks of italics don't look good. How else can the descriptions be rendered? I tried a few options:
- Bold font: looks too bold. Intermediate font weights: not clear if they are going to be available with every font and writing system that might be in use.
- Decorations like underline: can't use them because descriptions sometimes are links, sometimes are not links, sometimes they contain links inside.
- Colors: also don't look right. Primary color is blue, that looks like a link. Secondary is gray we use for deemphasising. Other colors we mostly don't use, they …
> Use font size instead of italic for changeset/trace descriptions

- .rubocop.yml
If you have multiple alter commands in a migration (like adding two columns to an existing table) this cop will suggest combining them using `change_table :foo, :bulk => true`.
However, Strong Migrations can't inspect `change_table` blocks, and therefore suggests using `safety_assured`, which mostly defeats the purpose of using Strong Migrations in the first place.
Instead, we should stick with the individual alter commands. Since postgres runs DDL changes in a transaction anyway, there is not enough benefit from the `change_table` approach to be worth losing the safety net of the Strong Migrations checks.
* Refs https://github.com/ankane/strong_migrations/issues/204
* Refs https://github.com/openstreetmap/openstreetmap-website/pull/4481
> Disable Rails/BulkChangeTable cop

- app/helpers/browse_tags_helper.rb
- test/helpers/browse_tags_helper_test.rb
Fixes #4914.
Standard urlencoding without underscores for spaces.
> Url-encode wikimedia_commons tag values

- app/views/layouts/_search.html.erb
Before:
After:
One of the complaints in #3123: "button to reverse directions is visually disconnected from directions".
> Move reverse directions button to the right of from/to inputs

- app/controllers/geocoder_controller.rb
- app/views/geocoder/search.html.erb
- test/controllers/geocoder_controller_test.rb
This PR addresses "Link to nominatim including search query" issue mentioned in the #3205 
Fixes #3205. Added caching of nominatim URL query parameters in GeocoderController#search for both direct and reverse geocoding. In app/views/geocoder/search.html.erb added displaying cached URL as forwarding link when clicked on "OpenStreetMap Nominatim" label.
> Added link to nominatim results in searching results

- app/controllers/geocoder_controller.rb
- app/views/geocoder/search.html.erb
- config/locales/en.yml
- test/http/nominatim.yml
This avoids having to build them in multiple places and also ensures we link to what was actually searched rather than some random string from the locale file.
> Simplify handling of geocoder URLs

- config/routes.rb
- test/controllers/api/notes_controller_test.rb
Remove endpoints listed in #4588.
- they are undocumented
- they don't do anything that documented endpoints can't
- [nobody seems to be using them](https://github.com/openstreetmap/openstreetmap-website/issues/4588#issuecomment-2004302883)
- you can't easily move their routes inside resources because they'll overwrite path helpers of documented endpoints
> Remove old note api endpoints

- app/helpers/user_helper.rb
- app/views/application/_auth_providers.html.erb
- test/helpers/user_helper_test.rb
As discussed in #4773, in auth button sizes section it was proposed that 36px should remain as the default size for the auth buttons. This PR addresses that comment.
> Arrange button sizes to default size of 36px

- app/helpers/user_helper.rb
- app/views/application/_auth_providers.html.erb
- test/helpers/user_helper_test.rb
This PR addresses #4773  discussion regarding auth_button_preferred css classes section. Auth anchor tags now use button styles as base style which will enforce consistency with other buttons.
The login screen maintains the same ui structure with minor styling enchancments
> Style auth buttons using .btn & .btn-light classes

- app/views/sessions/new.html.erb
- app/views/shared/_section_divider.html.erb
- app/views/users/new.html.erb
This PR refactors the "hr with words" section divider into a reusable partial to address the post-merge UI review for #4455. The implementation now utilizes the `<hr>` tag for improved semantics and accessibility. The visual appearance of the UI remains unchanged.
- Created `_section_divider.html.erb` partial for the section divider.
- Updated all instances to use the new partial for consistency and maintainability.
- Utilized the `<hr>` tag for the section divider.
#4773 Post-merge UI review for #4455
> Improve Section Divider with Reusable Component

- app/assets/javascripts/embed.js.erb
- test/system/embed_test.rb
`/export/embed` page has the "Report a problem" link which is supposed to be localized depending on the browser's accept-language header. But that doesn't happen because javascript waits for `window.onload` before setting the language. By that time `L.Control.OSMReportAProblem` is already created with a default locale.
> Set i18n locale before writing "report a problem" on embed page

- config/locales/en.yml
Unused since https://github.com/openstreetmap/openstreetmap-website/commit/a3617b492e67e280790442b77addbd25b896f07e
> Remove aol and wordpress auth provider locale strings

- app/views/users/new.html.erb
- config/locales/en.yml
This PR addresses the need for distinct translatable messages for the privacy policy link in different contexts within the signup form mentioned in #4773.
In the signup form, the privacy_policy_link and its respective label were reused in two different sentences (in email help HTML and by signing up HTML messages). Different contexts may require distinct translations due to language-specific rules, such as declension.
- Added separate translation keys for the privacy policy link in the email_help and by_signing_up sections.
- Updated the form to use these new translation keys, ensuring the correct link label is used in each context.
This PR aims to solve the issue of translation nuances by providing separate translatable messages for the privacy policy link in different contexts within …
> Separate translatable messages for privacy policy link in signup form

- app/controllers/geocoder_controller.rb
- test/controllers/geocoder_controller_test.rb
This PR addresses "Accept coordinates with a slash in search" issue mentioned in the [#4285](https://github.com/openstreetmap/openstreetmap-website/issues/4285)
Added '/' (slash) as an option in the validation and split regex of the search input. Fixes [#4285](https://github.com/openstreetmap/openstreetmap-website/issues/4285)
> Accept coordinates with a slash in search

- app/views/sessions/new.html.erb
This PR addresses issue #4773: "Raw HTML input used for password field." The login form previously used raw HTML for the password input field, which bypassed the automatic HTML attribute generation and site-wide overrides provided by form helpers.
- Replaced the raw HTML input for the password field with the f.password_field helper.
- Ensured the alignment of the password label and the "forgot password" link using Bootstrap classes.
> Refactor login form to use form helpers for password field

- config/locales/en.yml
- test/helpers/user_helper_test.rb
Auth provider images have `alt` attributes that instead of describing the images say what's going to happen when they are clicked. This is wrong and redundant because their buttons already have titles that say "Log in with ...":
This PR changes the alt texts to "... logo", similar to the alt text of OSM logo:
> Change auth provider logo alt texts to indicate that these are logos

- app/assets/javascripts/leaflet.share.js
- app/assets/javascripts/leaflet.sidebar.js
- app/assets/stylesheets/common.scss
- test/system/index_test.rb
This PR addresses "Share button unusable on a cell phone" issue mentioned in the #3988 
Added class to track if "Share", "Layer" and "Map Key" buttons have been clicked. Fixes #3988  
Change affects "Share" button, "Map Key" button and "Layer" button.
To follow the style of the website, all of them have the same visual as "Add a note to the map" button had.
Add a note to the map:
Share:
Map Key:
Layer:
When both "Add a note to the map" and "Share" are displayed, their visual is same as before:
> Share button unusable on a cell phone

- app/views/application/_auth_providers.html.erb
Continuing #4941 for OpenID button that had its image alt attribute set to its title text.
> Use alt text in OpenID image alt attribute

- app/views/users/blocked.html.erb
#4826 didn't remove `px-3` from all pages. One more page with login/signup tabs is the blocked signup page.
Before:
After:
> Remove padding around tabs on blocked signup page

- app/assets/stylesheets/common.scss
- app/views/sessions/new.html.erb
- app/views/users/blocked.html.erb
- app/views/users/new.html.erb
Currently login pages with preferred auth provider look like [this](https://www.openstreetmap.org/login?referer=https%3A%2F%2Fexample.com%2F%3Fpreferred_auth_provider%3Dgoogle):
The buttons don't fit in one row even on max width. This happens because the page width is still 600px, the logo images were increased to 36px and they are allowed to take only half of the page width.
Now we can remember that 600px is an arbitrary page width (#4773, Page width). It was chosen likely because the standard width is too high for login pages. The other width we use is 760px on [the about page](https://www.openstreetmap.org/about). We can use it for login pages too in exactly the same manner, without special `.auth-container` classes:
Now the buttons fit.
> Set "login/signup" page width equal to "about" page width

- app/assets/javascripts/index/contextmenu.js
- app/assets/javascripts/index/search.js
- app/controllers/geocoder_controller.rb
`whereami` was introduced in #1968. It's only used to suppress another parameter `latlon_digits` which indicates that we're not sure if the query string is "lat,lon" or "lon,lat". `whereami=1` says that we know it's "lat,lon". But why don't we use `lat` and `lon` parameters directly?
> Remove "whereami" search parameter, use "lat" and "lon" instead

- app/controllers/users_controller.rb
Users controller has a `save_new_user` method. Its entire body is wrapped by `if check_signup_allowed(current_user.email)`.
There's only one place where `save_new_user` is called. It's also wrapped by `if check_signup_allowed(current_user.email)`:
https://github.com/openstreetmap/openstreetmap-website/blob/e3c919275818d46a515c183cf373d7a53bc6942a/app/controllers/users_controller.rb#L90-L105
Why do we need to call `check_signup_allowed` both inside and outside of `save_new_user`?
> Don't call check_signup_allowed inside save_new_user

- app/controllers/changeset_comments_controller.rb
- test/controllers/changeset_comments_controller_test.rb
This PR addresses "Order of comments in changeset comments feeds" issue mentioned in the [#4613](https://github.com/openstreetmap/openstreetmap-website/issues/4613)
Reverse the output of the changeset comments feed from "created_at" ascending order to descending. Fixes [#4613](https://github.com/openstreetmap/openstreetmap-website/issues/4613)
> Order of comments in changeset comments feeds

- app/helpers/user_helper.rb
- app/views/application/_auth_providers.html.erb
- test/helpers/user_helper_test.rb
Currently auth buttons have horizontal margins that create horizontal gaps and nothing to create vertical gaps. It's easier to set the gap class on their flex container and get gaps in both directions.
Before/after:
> Add gap between rows of auth buttons

- app/helpers/user_helper.rb
.rounded is the default rounding for this button type.
.fs-6 is the default font size for this button type.
> Remove unnecessary classes from preferred auth button

- app/views/dashboards/show.html.erb
- app/views/diary_entries/_form.html.erb
- app/views/profiles/edit.html.erb
Fixes possible overlap of dropdown menus and maps, most likely on `/dashboard` page.
Before/after:
> Always set z-index of embedded maps

- app/views/sessions/new.html.erb
- app/views/users/blocked.html.erb
- app/views/users/new.html.erb
They are unnecessary after #4954.
One of them had unused id `login_login`.
> Remove former .auth-container wrapper divs

- app/helpers/user_helper.rb
- app/views/application/_auth_providers.html.erb
- config/locales/en.yml
- test/helpers/user_helper_test.rb
- Get rid of html locale string `openid_html: "%{logo} OpenID"` just to prepend the logo image.
- Make the label read "OpenID URL", which includes removing the logo alt text inside the label. In this case the logo is just a visual cue, you don't want screen readers to read its alt text and then read the actual label. I added "URL" because it's present on [the livejournal login page](https://www.livejournal.com/identity/login.bml), where OpenID originated.
> Update OpenID input label

- app/assets/javascripts/auth_providers.js
- app/views/application/_auth_providers.html.erb
It's not a link. It doesn't have a proper href, that's why `#` was used.
> Change OpenID provider link to button

- app/assets/javascripts/auth_providers.js
- app/views/application/_auth_providers.html.erb
There's an attempt to wrap auth buttons below the preferred button with `flex-wrap` here:
https://github.com/openstreetmap/openstreetmap-website/blob/bc8ce5729da0a7df4306ae5f785f68980a9bf47b/app/views/application/_auth_providers.html.erb#L2
That's not going to work after the children of this flex container got 50% width in #4849. They always fit in one row, no matter how narrow 50% of that row is.
Here I'm using Bootstrap's grid system with two-column row above the small width breakpoint if there's a preferred auth button.
Before/after:
> Stack preferred auth button over other auth buttons on small screens

- app/assets/javascripts/auth_providers.js
- app/views/application/_auth_providers.html.erb
- test/system/user_signup_test.rb
When the login page is loaded, this form gets hidden by javascript:
Later if the OpenID button is clicked, it gets shown.
Actually not quite. The form is always visible, what's getting shown/hidden are the div containing the url input and the *Continue* button. But there's not reason to show/hide them separately when you can show/hide the entire form.
> Show/hide entire OpenID form

- .rubocop_todo.yml
- app/controllers/geocoder_controller.rb
- test/controllers/geocoder_controller_test.rb
This fixes #4950 by modifying the geocoder to avoid printing results in scientific notation.
The main fix is simply to avoid converting the user entered string to numeric format and back but for DMS style inputs we need to convert them to numeric form so we can do calculations so we use bigdecimal rather than float as it can force fixed precision format when converting to a string.
> Avoid use of scientific notation in geocoder results

- test/controllers/geocoder_controller_test.rb
Since we decided that numbers can't end with `.` and changed the geocoder regexps, it makes sense to change the test regexps too.
> Check that fractional part is present after . in geocoder latlon tests

- app/assets/javascripts/index.js
- app/assets/javascripts/index/layers/data.js
- app/assets/javascripts/index/layers/notes.js
We have a bunch of things named "browse". On the client side we have the `OSM.Browse` controller for single element pages: https://github.com/openstreetmap/openstreetmap-website/blob/ecd091c976cc8f2a3cf96fe08dc3211aad689ae2/app/assets/javascripts/index.js#L327
But there's also [browse.js](https://github.com/openstreetmap/openstreetmap-website/blob/ecd091c976cc8f2a3cf96fe08dc3211aad689ae2/app/assets/javascripts/index/browse.js). It initializes the data layer:
This is confusing because most of controllers, for example `OSM.Directions`, are in their own javascript files. You'd expect to find `OSM.Browse` in `browse.js` but no, `browse.js` is something completely different.
This pull request renames everything "browse" about `browse.js` and moves the file into the `layers` directory. And it …
> Rename map layer javascript files

- app/controllers/geocoder_controller.rb
- test/controllers/geocoder_controller_test.rb
Current parsing tries to have as many numbers in longitude as there are in longitude, sometimes splitting "12" (12 deg) into (1 deg 2 min).
Before/after:
> Parse lat and lon independently when using dms notation

- app/assets/javascripts/auth_providers.js
- app/views/application/_auth_providers.html.erb
That javascript comes from [ages ago](https://github.com/openstreetmap/openstreetmap-website/commit/ebd109c946d71b3ccc616ea3966e56ae019638d7) when each auth provider button was setting its own value.
> Set OpenID URL input value in html instead of javascript

- app/assets/javascripts/leaflet.share.js
- app/controllers/export_controller.rb
- config/locales/en.yml
- test/controllers/export_controller_test.rb
This PR addresses "When downloading image by 'Share', allow other map styles with static image APIs" issue mentioned in the https://github.com/openstreetmap/openstreetmap-website/issues/1886
Added API for downloading Transport and Cycle Map images, as they are supported by the [ThunderForest](https://www.thunderforest.com/docs/static-maps-api/). Also changed unsupported map text to show that not only Standard, but Transport and Cycle Map layers also have downloading capability. Fixes https://github.com/openstreetmap/openstreetmap-website/issues/1886
Transport layer:
Cycle Map layer:
Unsupported Humanitarian layer:
> When downloading image by "Share", allow other map styles with static image APIs

- app/helpers/user_helper.rb
- app/views/application/_auth_providers.html.erb
- test/helpers/user_helper_test.rb
`auth_button` and `auth_button_preferred` helpers have the following first two arguments:
- `name`, which is an auth provider name
- `provider`, which is also an auth provider name, exactly the same
They used to be different [at some point](https://github.com/openstreetmap/openstreetmap-website/commit/e434cb154c5ccecd7fc0ce672e4de79bd9e7e06f), but not anymore. Now the calls look like `auth_button provider, provider`.
We can remove the `name` argument.
> Remove name argument from auth button helpers

- Dockerfile
This PR addresses #4989. 
Errors is encountered when attempting to run `bundle exec rails eslint` inside the Docker container terminal,after following the instructions in the `DOCKER.md` file.
After updating `Dockerfile` to use Node.js v18, we can rebuild the container using `docker compose up --build -d ` command; resulting in expected result when running `bundle exec rails eslint`
```bash
$ bundle exec rails eslint
warning: parser/current is loading parser/ruby30, which recognizes 3.0.7-compliant syntax, but you are running 3.0.2.
Please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
yarn run v1.22.22
$ /app/node_modules/.bin/eslint -c /app/config/eslint.js /app/app/assets/config/manifest.js /app/app/assets/javascripts/application.js …
```
> Update Docker Image to use Node.js v18

- app/assets/javascripts/index/search.js
- test/system/search_test.rb
Fixes https://github.com/openstreetmap/openstreetmap-website/pull/4959#issuecomment-2232620015
Fixes #4997
> Set search input value to 'lat, lon' params if query param is missing

- app/views/application/_auth_providers.html.erb
If prefered_auth_button_available == true, we've already found @preferred_auth_provider among all available providers, no need to look for it again.
> Remove unnecessary loop when rendering preferred auth provider button

- app/views/layouts/_search.html.erb
- test/system/search_test.rb
Fixes setting search input value after full page reloads that only seems to work because of [autocompletion](https://github.com/openstreetmap/openstreetmap-website/pull/4959#issuecomment-2233238733).
`_search.html.erb` fills the input with `params[:query]` which is not going to exist after geocoder's `normalize_params`.
> Set search input value when searching for coordinates

- app/views/accounts/edit.html.erb
- app/views/application/_auth_providers.html.erb
- lib/auth.rb
`_auth_providers.html.erb` iterates over `%w[google facebook microsoft github wikipedia]` and checks which provider is available. But the `Auth` module already does that. `Auth` is only used on account settings pages and has a "provider" "None" specific to these pages. If "None" is removed, `Auth` can be reused in `_auth_providers.html.erb`.
> Use Auth.providers in auth providers template

- app/controllers/messages_controller.rb
- test/controllers/messages_controller_test.rb
> Fix marking muted messages as read/unread

- app/assets/javascripts/auth_providers.js
- app/views/application/_auth_providers.html.erb
Show form and hide auth buttons with [Bootstrap collapse](https://getbootstrap.com/docs/5.3/components/collapse/) when OpenID is clicked:
Allows to remove `.show()` / `.hide()` javascript.
> Use Bootstrap collapse to toggle OpenID login form

- app/views/user_blocks/edit.html.erb
- test/controllers/user_blocks_controller_test.rb
Let's suppose you create a block and you set its duration to 12 hours. Then you realize you need to edit this block. You go to `/user_blocks/:id/edit` and you see among other things a duration select set to 12 hours as expected:
But what if you come an hour later? Now the remaining duration is 11 hours which is not one of the available select options. The select will look like this, defaulting to 0 hours, probably not the best choice:
Here I set the select to the closest available value.
> Select closest value to remaining duration when editing a block

- app/abilities/ability.rb
- app/controllers/diary_entries_controller.rb
- app/views/diary_entries/_diary_entry.html.erb
- test/controllers/diary_entries_controller_test.rb
Does [this](https://github.com/openstreetmap/openstreetmap-website/pull/4540#discussion_r1610270567) but for `:update` ability (which includes `:edit` ability).
> Check diary entry edit/update ability using CanCanCan

- config/routes.rb
- test/controllers/diary_comments_controller_test.rb
This is how path are going to look if comments are turned into nested resources of diary entries:
- `newcomment` => POST on `comments`
- `hidecomment/:comment` => `comments/:comment/hide`
- `unhidecomment/:comment` => `comments/:comment/unhide`
All changed paths are POST paths, changing them shouldn't break anything.
> Change diary comment post paths

- app/controllers/user_blocks_controller.rb
- app/views/user_blocks/_block.html.erb
- app/views/user_blocks/show.html.erb
- config/locales/en.yml
- test/controllers/user_blocks_controller_test.rb
Expired/revoked blocks have no edit links. Editing them results in "The block has already expired and cannot be edited."
This PR removes the `active?` check on update actions which allows editing inactive blocks.
Some block are issued automatically and there are false positives among them. Any moderator can revoke erroneous blocks but it's also desirable to edit the block messages. This may be impossible for two reasons:
1. Revoked block is already expired.
2. Revoked block was created by a different moderator.
This PR removes reason 1.
> Allow to edit inactive blocks

- test/controllers/issues_controller_test.rb
- test/models/user_test.rb
Rubocop would complain about something like `assert issue.open?` and it gets changed to `assert_predicate`, but `assert_not issue.open?` is left alone for some reason.
I already did this change in #4454. I guess I missed some.
> Use assert_not_predicate instead of assert_not next to assert_predicate

- config/routes.rb
If we want to [avoid](https://github.com/openstreetmap/openstreetmap-website/pull/4248#discussion_r1326279791) `:as` for api path helpers we can move resources to a namespace that will add the `api` prefix automatically.
This PR shouldn't rename any path helpers.
> Move notes and blocks resources to api namespace

- test/abilities/api_capability_test.rb
- test/controllers/api/changeset_comments_controller_test.rb
- test/controllers/api/user_preferences_controller_test.rb
- test/factories/oauth_access_token.rb
This converts some tests which are testing OAuth 1 tokens and which don't have an OAuth 2 equivalent to use OAuth 2 instead.
> Convert tests using OAuth 1 tokens to use OAuth 2 tokens

- .rubocop_todo.yml
- app/abilities/api_capability.rb
- app/controllers/api/messages_controller.rb
- app/views/api/messages/_message.json.jbuilder
- app/views/api/messages/_message.xml.builder
- app/views/api/messages/inbox.json.jbuilder
- app/views/api/messages/inbox.xml.builder
- app/views/api/messages/outbox.json.jbuilder
- app/views/api/messages/outbox.xml.builder
- app/views/api/messages/show.json.jbuilder
- app/views/api/messages/show.xml.builder
- config/locales/en.yml
- config/routes.rb
- config/settings.yml
- lib/oauth.rb
- test/controllers/api/messages_controller_test.rb
...as discussed in [Proposal for Messages API - Issue #4509](https://github.com/openstreetmap/openstreetmap-website/issues/4509) and documented in [Messaging API reference](https://wiki.openstreetmap.org/w/index.php?title=Messaging_API_proposal)
> Add Messages API

- app/helpers/trace_helper.rb
- app/views/traces/_trace.html.erb
Since [loading trace images](https://www.openstreetmap.org/traces) from AWS S3 might take a bit, users are currently experiencing a re-rendering of the page. I found this a bit annoying, and added a fixed 50x50 size for the trace png now. With the change in place, the re-rendering of the page no longer happens. The trace png is shown initially as a blank spot.
> Define fixed size for trace images

- app/views/layouts/_header.html.erb
We have user image helpers:
https://github.com/openstreetmap/openstreetmap-website/blob/bbd6140f4bdc7746ecbd4d109316b2dd0b6d047f/app/helpers/user_helper.rb#L4-L41
But there's something suspicious in their code. `options` has different keys merged in different places: sometimes it's `:size`, sometimes it's `:width`/`:height`. Are we supposed to be able to pass our own size to the helpers? If yes, which keys should we use?
Easier question is *do we actually try to pass our own size*? There's only one place where we do, the one I remove in this pull request. Does it have any effect, given that helpers sometimes overwrite it? There are different code paths depending on the type of the image. The only path that uses those `:width => 25, :height => 25` is unprocessed attached image, when this …
> Don't pass width/height to user menu thumbnail

- lib/rich_text.rb
- test/lib/rich_text_test.rb
It's possible to add images to markdown rich text without the `![]()` syntax, by using html `<img ...>`. Such images are not detected by #4882 because they have a different type in the kramdown parse tree. This PR enables detection of `<img ...>`.
> Detect <img> images in markdown rich text

- app/assets/javascripts/richtext.js
- app/views/shared/_richtext_field.html.erb
- test/controllers/diary_entries_controller_test.rb
Why are the *Edit* and *Preview* buttons inside the help card? The *Preview* button there makes it inconvenient to preview on small screens because you'll have to scroll to the end of the help pane to press the button and then scroll back to see the preview.
Before:
After:
Uses https://getbootstrap.com/docs/5.3/components/navs-tabs/#javascript-behavior to switch between tab panes.
Compatible with #5023.
> Replace richtext edit/preview buttons with tabs

- app/controllers/site_controller.rb
- config/locales/en.yml
PR is alternative to #4894 for displaying indicator, using bootstrap alerts, if (message, diary entry, diary entry comment) body is empty and user selects Preview button.
Fixes #3748. Added check to SiteController#preview to detect if (message, diary entry, diary entry comment) body is empty and if positive, returns rendered bootstrap alert "Nothing to preview" to be displayed in richtext_field.
After:
> Added bootstrap alert when body preview is empty

- app/views/api/changesets/index.xml.builder
XML rendering is much more consistent already. I only found one location where we are still calling `render` inside a loop.
> Changeset: avoid XML rendering in loop

- app/views/api/changesets/index.json.jbuilder
- app/views/api/messages/inbox.json.jbuilder
- app/views/api/messages/outbox.json.jbuilder
- app/views/api/notes/index.json.jbuilder
- app/views/api/users/index.json.jbuilder
Similar to the change in #4958, this PR addresses the remaining locations where JSON partials were rendered in a loop, instead of using collections.
~NB: 6268335ccdcdcb6629f32e5cae0d182c05b5593a has a typo in the description, it should read "Notes".~
I split this up into multiple commits, since the changes are in different parts of the API. If that's not needed, please Squash&merge instead.
> JSON partial rendering in loop

- script/cleanup
This extends the existing cleanup script that runs every night in production to deal with OAuth 2 grants and tokens.
> Add expiry for OAuth 2 grants and tokens

- test/controllers/diary_entries_controller_test.rb
- test/controllers/user_blocks_controller_test.rb
Ordering by id [happens by default](https://api.rubyonrails.org/classes/ActiveRecord/FinderMethods.html#method-i-last).
Some more `order(:id)` are removed in #5054.
> Don't order by id when getting last records

- app/assets/javascripts/richtext.js
- app/views/shared/_richtext_field.html.erb
- config/locales/en.yml
As I said in #5042 you have to scroll to the end of the help card in order to reach the edit/preview buttons. But you also have to scroll there in order to reach the submit button which is also annoying. What if we don't display the help card on small screens unless the user requests it?
When the screen is wide enough the UI looks like it did before:
When the screen is narrow:
> Move richtext help to a tab on small screens

- app/assets/javascripts/index/directions-endpoint.js
- app/assets/javascripts/index/directions.js
Continues #4902. Apparently it's too tempting to put the routing logic back into endpoints code (https://github.com/openstreetmap/openstreetmap-website/pull/4904#pullrequestreview-2228123839, https://github.com/openstreetmap/openstreetmap-website/pull/4904#pullrequestreview-2230576231). Moving the code to another file will hopefully dissuade that.
> Move directions endpoints code to its own module

- app/controllers/diary_entries_controller.rb
- app/helpers/open_graph_helper.rb
- app/views/layouts/_meta.html.erb
- lib/rich_text.rb
- test/controllers/diary_entries_controller_test.rb
- test/lib/rich_text_test.rb
Uses the first paragraph with text truncated to 500 characters as an OpenGraph description on diary entry pages. Uses the default text on other pages or if no paragraph with text is found.
Fixes #1361
> Set og:description meta tag to diary entry description

- app/assets/javascripts/index/directions-endpoint.js
- app/assets/javascripts/index/directions.js
This is a smaller part of #5064 that can be applied independently.
Instead of two methods to pass values/positions to endpoint (`setValue`, `setLatLng`) you get one, `setValue`. `setValue` after this PR has two arguments, `value` and `latlng`, and the next step is to remove `latlng` and let the endpoint figure out itself if `value` contains coordinates or if it doesn't.
> Remove setLatLng() from directions endpoint interface

- app/assets/javascripts/richtext.js
- test/system/rich_text_test.rb
Before you'd click the submit button and nothing would happen if the text is invalid:
With this PR the *Edit* pane shows which lets you see the validation message:
> Switch to edit pane if rich text field validation fails

- Gemfile
- Gemfile.lock
This is included in new rails 7+ apps, so let's include it too.
This also means it's available on ruby 3.0, and is automatically updated on newer versions of ruby too.
I've copied this directly from [the upstream `rails new` Gemfile template](https://github.com/rails/rails/blob/eaa74eedba945e1bdcedd7fa6ac38c6493edd735/railties/lib/rails/generators/rails/app/templates/Gemfile.tt#L45-L46).
> Add debug gem

- app/controllers/diary_entries_controller.rb
- app/helpers/open_graph_helper.rb
- test/controllers/diary_entries_controller_test.rb
Mastodon seems to be using it:
https://en.osm.town/@openstreetmap/112670776752214880
> Add article:published_time meta tag to diary entries

- app/assets/javascripts/index/directions-endpoint.js
- app/assets/javascripts/index/directions.js
Another piece of #5064 which changes how callbacks work. The code outside endpoints module shouldn't care if geocoding was performed or not. Previously there was a special callback for completed geocoding, you waited for it and then you built the route. But if you passed coordinates to endpoint.setValue you knew that geocoding may not happen therefore you had to try to build the route right away. Now you just always wait for a callback because it happens even without geocoding.
> Rename geocodeCallback to changeCallback, call it from latlon setValue

- app/controllers/user_blocks_controller.rb
- config/locales/en.yml
- test/controllers/user_blocks_controller_test.rb
See https://github.com/openstreetmap/openstreetmap-website/pull/5069/files#r1715714691
Let's disable block reactivations first.
> Prevent reactivating inactive blocks

- app/views/user_blocks/edit.html.erb
- test/system/user_blocks_test.rb
Since #5082 removed the ability to reactivate blocks, we can remove the inputs for doing that too. Inactive blocks will have only editable reason input.
> Remove duration and needs_view inputs from inactive block edit form

- app/views/user_blocks/_navigation.html.erb
- app/views/user_blocks/edit.html.erb
- config/locales/en.yml
Before:
After:
The last tab leads to the block show page and is selected even if we're on edit page. I don't think it's worth it to add another tab just for the edit page.
> Add navigation tabs to edit block pages

- app/assets/stylesheets/common.scss
- app/views/user_blocks/_block.html.erb
> Truncate long usernames in blocks tables

- app/assets/javascripts/index/directions.js
When you close the directions form there's this code that tries to use the "From" value for searching.
It does so by opening the url `/?query=...`. The url is wrong, it should be `/search?query=...`, thus nothing happens.
I could have fixed it by using `/search?query=...`, but I don't like that it runs the search right away, when the close button is clicked. Instead I set the search input value.
> Copy "From" endpoint value to search input when closing directions

- app/assets/javascripts/osm.js.erb
This changes the number of fractional digits to log10(pixels / degrees) with pixels = 2**(8 + zoom) and degrees = 180.
---
If you apply the entire #5064, zoom in to the max zoom level, place an endpoint marker and try to drag it around, you'll notice it moves by jumping several pixels. This is because I limit its coordinates to zoom precision and zoom precision is not high enough. Its current version was introduced in https://github.com/openstreetmap/openstreetmap-website/commit/b28511faca45d8d8abc0d3c2fde5a501bbe94062. You can notice something strange about it: the zoom value went from being an argument of `Math.pow` to an argument of `Math.log`. `zoom` is already on a log scale, why do you need to take its log again?
| zoom | old zoomPrecision | new zoomPrecision |
| --- | --- | --- |
| …
> Change zoom precision function

- app/controllers/user_blocks_controller.rb
- test/controllers/user_blocks_controller_test.rb
If you edit an inactive block, you can change its text but you can't reactivate it. You are prevented from reactivating it by keeping the block duration at 0. But even setting the duration to 0 changes the block end time, because it's set to now + duration. This in turn affects the duration as reported on the block show page, that shows duration = end_at - created_at. You wanted to just update the text, yet you altered the duration too. That's not something you expect to happen.
This PR keeps old ends_at time when updating inactive blocks.
Example with 0-hour block edited months later:
Before:
After:
> Don't update ends_at when editing inactive blocks

- app/assets/javascripts/index/directions-endpoint.js
- app/assets/javascripts/index/directions.js
Part of #5064.
`getRoute` shouldn't know anything about geocoding, doesn't need to wait for every kind of geocoding (namely for reverse one), therefore shouldn't command the endpoints to do it. All necessary geocoding is triggered by `endpoint.setValue` and input event listeners.
> Don't call getGeocode from getRoute

- app/controllers/user_blocks_controller.rb
- test/controllers/user_blocks_controller_test.rb
You can deactivate a block using the revoke action. But you can also deactivate a block by editing it and setting duration=0 + needs_view=false. The difference is that you're not being recorded as a revoker if you do that. This PR records you as a revoker in this case too.
This kind of editing is only available to you if you're the block creator. The point of this PR is to relax this check later and let any moderator revoke blocks by editing, then remove the revoke action. Instead of first going to the revoke confirmation page with "Are you sure you wish to revoke this block?" and then possibly going to the edit page, moderators will be able to edit the block reason and revoke the block from the same page.
> Record revokers when deactivating blocks by editing

- app/assets/javascripts/index/directions.js
Fix for #5088.
If the "From" value is long enough [like this](https://www.openstreetmap.org/directions?from=7%2C%20Bell%20Yard%2C%20Gray%27s%20Inn%2C%20Holborn%2C%20London%2C%20Greater%20London%2C%20England%2C%20WC2A%202JR%2C%20United%20Kingdom) and you close the directions form, you'll get the search value overlapping with "Where is this?".
Also sometimes it's possible to delete the value, close the directions and get a blank search input without "Where is this?".
> Show/hide "Where is this?" when setting search value from directions

- app/views/user_blocks/_navigation.html.erb
- app/views/user_blocks/new.html.erb
- config/locales/en.yml
Similar to #5086
Before:
...
After:
...
Related to #3267 where back buttons get outlines. This PR removes one of these buttons.
> Add navigation tabs to new block pages

- app/assets/javascripts/index/contextmenu.js
- app/assets/javascripts/index/directions-endpoint.js
- app/assets/javascripts/index/directions.js
Part of the problem #5064 tries to solve are the result of the context menu using addresses from endpoint inputs.
You right click somewhere, select "Directions from here" and it goes to and url like this: `/directions?from=51.420436%2C-0.174805&to=`. Then you right click somewhere else, select "Directions to here" and the url becomes something like this: `/directions?from=Park%20Road%2C%20Collier%27s%20Wood%2C%20London%20Borough%20of%20Merton%2C%20London%2C%20Greater%20London%2C%20England%2C%20SW19%202HT%2C%20United%20Kingdom&to=51.420563%2C-0.171007`. The coordinates in `from` got replaced by an address. It's impossible to get the original coordinates from an address.
The solution here is to save the coordinates to `data-lat` and `data-lon` attributes of inputs. The context menu then can …
> Always use coordinates when using directions from context menu

- .gitignore
- .overcommit.yml
- CONTRIBUTING.md
- Gemfile
- Gemfile.lock
- package.json
- yarn.lock
As suggested in https://github.com/openstreetmap/openstreetmap-website/pull/4988#issuecomment-2285568484 this adds support overcommit to install git gooks to run checks.
With this change `bundle exec overcommit --install` will install hooks to run a variety of checks.
> Add overcommit to manage git hooks

- app/assets/javascripts/index/directions-endpoint.js
Originally was in #5064 but I took it out because it solves a different problem.
The problem is:
1. right-click somewhere on the map, select "Directions from here": a starting marker appears on the map
2. right-click some other place, select "Directions to here": first, another marker appears, then a route
3. close the directions form so you're no longer on the directions page but don't do a full page reload
4. scroll to a different place on the map
5. right-click and select "Directions from here"
What do you expect to happen after step 5? Probably the same thing that happened after step 1: a starting marker appearing. But that's not what's going to happen. A route is going to be built from your new start to an old destination you picked in step 2. This will likely be accompanied by an …
> Clear endpoint values when leaving directions page

- app/controllers/user_blocks_controller.rb
- app/helpers/user_blocks_helper.rb
- app/models/user_block.rb
- db/migrate/20240813070506_add_deactivates_at_to_user_blocks.rb
- db/structure.sql
- test/controllers/user_blocks_controller_test.rb
- test/factories/user_blocks.rb
- test/integration/user_blocks_test.rb
Block deactivation dates that take needs_view-block views into account were derived using updated_at. This was possible because inactive blocks couldn't be edited and their updated_at date wouldn't change. The logic is explained here:
https://github.com/openstreetmap/openstreetmap-website/blob/e0e6c7f1c26fcddff883dad38a6207475150f323/app/helpers/user_blocks_helper.rb#L20-L24
With editing of inactive blocks enabled deactivation date needs to be saved explicitly. It is defined for blocks that don't have `needs_view` and will time out even if the user doesn't look at them. Block with `needs_view` don't have a defined deactivation date. It's going to be set as soon as the user views the block and clears `needs_view`. Its value is going to be either the block end date if it's in the future or …
> Add deactivates_at date to user blocks

- app/abilities/ability.rb
- app/controllers/user_blocks_controller.rb
- app/views/user_blocks/_block.html.erb
- app/views/user_blocks/edit.html.erb
- app/views/user_blocks/show.html.erb
- config/locales/en.yml
- test/abilities/abilities_test.rb
- test/controllers/user_blocks_controller_test.rb
- test/factories/user_blocks.rb
- test/system/user_blocks_test.rb
Continues #5094.
Moderators who didn't create an active block can open its edit page and the form for them will look like this:
They can update the reason and click revoke. They'll be recorded as revokers and the block will be deactivated.
> Edit unrevoked block

- app/views/diary_comments/_page.html.erb
- app/views/diary_entries/_page.html.erb
- app/views/shared/_pagination.html.erb
- app/views/traces/_page.html.erb
- app/views/user_blocks/_blocks.html.erb
- app/views/users/_page.html.erb
Something had to break after #4646.
Turbo handles all links inside its frames unless told not to. If any link leads to a page that has some javascript running on load, it's going to be broken. The most common javascript in our case is rich rext controls code. If you go to a diaries page and click "comment", turbo takes you to a diary entry page with broken richtext javascript. And it's not as easy to fix as adding the page onload code to an equivalent turbo event because now you also have to clean up when leaving the page (using a back button for example), something that wasn't possible before (except on our map layout pages with our special router).
I did here the same as in #4565: set `data-turbo="false"` on the entire frame and set it to true just on previous/next page links.
> Disable turbo on all links inside pagination frames except older/newer

- app/controllers/issues_controller.rb
- app/views/issues/_page.html.erb
- app/views/issues/index.html.erb
- config/locales/en.yml
- test/system/issues_test.rb
This PR addresses heavy calls and long load time of the Issues page. Problem was mentioned in https://github.com/openstreetmap/openstreetmap-website/pull/4990 by @AntonKhorev.
Added pagination functionality. When pagination buttons will be clicked, next or previous 50 issues will be called and displayed without a page refresh (Turbo will make a call and render returned Turbo Frame). In terms of performance, on the local environment I have 1000 users and 1000 issues. Initial loading time was decreased from ~8s to ~1s and after that every pagination needs ~150ms. In the real environment, it will have much better improvement, as instead of searching for 30000 issues, it will take only 50 (in theory, the difference should be 30x better in the real environment, then it is on my local machine). …
> Add pagination to Issues page

- public/robots.txt
Recent scraping incidents have made think that a friendly pointer to planet.osm.org probably wouldn't hurt.
> Add planet link and explanation to robots.txt

- app/views/diary_entries/_diary_comment.html.erb
- config/routes.rb
- test/controllers/diary_comments_controller_test.rb
Changes routes from 
`/user/:display_name/diary/:id/comments/:comment/hide`
to
`/diary_comments/:comment/hide`
\+ the same for unhide.
This is what you'll get if you define comments as a shallow nested resource like this:
```ruby
resources :users, :path => "user", :param => :display_name do
resources :diary_entries, :path => "diary" do
resources :diary_comments, :shallow => true do
...
end
end
end
```
Paths with display_name and diary entry id are too long and these names/ids are not used for anything in the controller.
> Use shallow routes for diary comments

- app/controllers/messages_controller.rb
- app/views/messages/show.html.erb
- test/controllers/messages_controller_test.rb
PR adds Reply button when displaying sent messages, so users can send follow-ups
 
Fixes #3497. Adds Reply button when displaying sent messages (app/views/messages/show.html.erb) and allows replying to messages for which sender is current user (app/controllers/messages_controller.rb).
> Allows sending follow-ups for sent messages

- app/controllers/issues_controller.rb
- app/views/issues/_page.html.erb
- app/views/issues/index.html.erb
- config/locales/en.yml
- test/system/issues_test.rb
This extends #5057 to use turbo when changing search parameters on the issue list.
The user not found message when searching for an unknown user has been moved from the flash message into the results pane to ensure it can be updated when a search is done.
> Use turbo to update issue search results

- app/assets/javascripts/index.js
- app/controllers/changesets_controller.rb
- app/helpers/browse_helper.rb
- app/views/changesets/_elements.html.erb
- app/views/changesets/_paging_nav.html.erb
- app/views/changesets/show.html.erb
- lib/classic_pagination/pagination_helper.rb
- test/system/changeset_elements_test.rb
Fixes https://github.com/openstreetmap/openstreetmap-website/issues/4561. Updated version without doing #4563 first. I don't do the entire sidebar with Turbo. The only change to javascript here is to suppress our router.js when a pagination turbo link is clicked. I have to mark those links explicitly for now with `data-turbo="true"`.
> Reload only element type sections with Turbo frames

- test/system/issues_test.rb
This PR addresses "Test failures on issues pagination" issue mentioned in the https://github.com/openstreetmap/openstreetmap-website/issues/5127
Test was modified. Now instead of checking the number of `tr`, test tries to search for the specific issues. According to the [Capybara Documentation](https://github.com/teamcapybara/capybara#asynchronous-javascript-ajax-and-friends), this approach should fix occasional failing of issues page tests.
> Test failures on issues pagination

- test/controllers/oauth2_applications_controller_test.rb
Will fail if #5058 is applied because https://github.com/openstreetmap/openstreetmap-website/pull/5058#pullrequestreview-2272966401.
> Test oauth2 application list with moderator permission icon

- app/assets/javascripts/leaflet.map.js
`name: I18n.t("javascripts.map.base.gps")` was added in https://github.com/openstreetmap/openstreetmap-website/commit/df17b997b33fc9d0c60360de7f27aadc76b930a0 without a translation provided. Went unnoticed because the name is not actually used anywhere, see https://github.com/openstreetmap/openstreetmap-website/pull/5133#issuecomment-2323053456.
> Remove unused reference to missing gps layer name

- config/locales/en.yml
Not in use after https://github.com/openstreetmap/openstreetmap-website/commit/e7e12a38c6585763bfa29ff189cf4c9cea646281 and https://github.com/openstreetmap/openstreetmap-website/commit/3fd083d9d4f3c266ad9bc8bbf337f44c184d15a2.
> Remove unused not_an_admin locale string

- config/locales/en.yml
They were replaced by more specific messages in https://github.com/openstreetmap/openstreetmap-website/commit/1e3b3c1f10213c48a40083e8bbca1429d9f819d6.
> Remove unused fail locale strings from user role grant/revoke

- config/locales/en.yml
Added for `app/views/site/_josm.html.erb` in https://github.com/openstreetmap/openstreetmap-website/commit/cd66a5db99fda4920ed559ec71163d5d01ba1f4a which was removed in https://github.com/openstreetmap/openstreetmap-website/commit/c3453cf57df864b008dca6479f84504f81c0b131 a few hours later.
> Remove unused no_iframe_support message

- config/locales/en.yml
There was a donation link in the footer but it was removed in https://github.com/openstreetmap/openstreetmap-website/commit/6d5ce8d49293afa79a86300f38d698426557b9a8 because there's one in the map corner now.
> Remove unused donation strings

- config/locales/en.yml
This got left in when dropping OAuth 1 support...
> Drop unused oauth_10a_disabled translation

- config/locales/en.yml
There used to be a tooltip on the diaries tab. Added in https://github.com/openstreetmap/openstreetmap-website/commit/f7985046696958688b8a220a91c4b96ce16d4b65, removed in https://github.com/openstreetmap/openstreetmap-website/commit/6adcce4e5d75fa21dea85742fa36ee3b97247b01.
> Remove unused user_diaries_tooltip locale string

- app/views/messages/_heading.html.erb
By moving the translation outside the loop and calling t(...) with explicitly stated keys, `bundle exec i18n-tasks unused` no longer reports the keys as unused.
Should we rename `i18n_key` to something different as well?
> I18N: messages: avoid dynamic translation keys

- app/controllers/changesets_controller.rb
PR fixes bug causing bad error message when requested displaying missing changeset
Fixes #5148. Added forgotten @type = "changeset" in ChangesetsController#show.
Before:
After:
> Fixed bug causing bad error message when requested missing changeset

- config/i18n-tasks.yml
Ignores doorkeeper namespace from reporting in `bundle exec i18n-tasks unused`
Although the translations are part of the osm website repo, we have no real control over how they're being used by third party components (that's at least my conclusion at the moment, I hope this is correct).
They were originally added in e996ee5dbca8b7ed26dbf55fcc116fa947f60188 by moving doorkeeper_openid_connect.en.yml to our own en.yml translation file. I suppose they were automatically added when installing doorkeeper openid connect (link: https://github.com/doorkeeper-gem/doorkeeper-openid_connect/blob/master/config/locales/en.yml)
`doorkeeper.flash.applications.create.notice` was originally defined by Doorkeeper in https://github.com/doorkeeper-gem/doorkeeper/blob/main/config/locales/en.yml#L134 and then …
> I18n: ignore unused third party translations

- config/locales/en.yml
Changeset lists stopped using them in https://github.com/openstreetmap/openstreetmap-website/commit/e098d52424c3a0c8025cb62193a03bb42477c85c but they we also used in note lists, that stopped in https://github.com/openstreetmap/openstreetmap-website/commit/9d3b419aad3069db13fc0169049a30fbc2b2a288.
> Remove unused locale strings for former changeset tables

- app/controllers/api/permissions_controller.rb
- app/controllers/api_controller.rb
- app/controllers/application_controller.rb
- config/locales/en.yml
- config/settings.yml
- test/controllers/api/changeset_comments_controller_test.rb
- test/controllers/api/changesets_controller_test.rb
- test/controllers/api/nodes_controller_test.rb
- test/controllers/api/notes_controller_test.rb
- test/controllers/api/old_nodes_controller_test.rb
- test/controllers/api/old_relations_controller_test.rb
- test/controllers/api/old_ways_controller_test.rb
- test/controllers/api/permissions_controller_test.rb
- test/controllers/api/relations_controller_test.rb
- test/controllers/api/traces_controller_test.rb
- test/controllers/api/user_preferences_controller_test.rb
- test/controllers/api/users_controller_test.rb
- test/controllers/api/ways_controller_test.rb
- test/integration/compressed_requests_test.rb
- test/integration/user_blocks_test.rb
- test/integration/user_terms_seen_test.rb
- test/test_helper.rb
This drops support for basic authentication and converts all tests which used it to use OAuth instead.
> Drop support for basic authentication

- app/models/node.rb
- app/models/old_node.rb
Not used, was last used for Potlatch undelete that was removed in  #3038.
`node.tags` is a hash anyway.
> Remove node.tags_as_hash method

- app/abilities/api_capability.rb
- test/abilities/api_capability_test.rb
I looked at Coveralls and noticed that `token.user` is never accessed:
I guess this branch is not required after #5058.
> Remove OAuth 1 ApiCapability user branch

- config/locales/en.yml
Added in https://github.com/openstreetmap/openstreetmap-website/commit/272d73e9a76ff55a05a0889bd02a9e3c31a35910. The button was removed from message lists in https://github.com/openstreetmap/openstreetmap-website/commit/be8617dfdc9fdf941705272ec9ba152b95677249.
> Remove messages.message_summary.reply_button string

- test/controllers/api/changeset_comments_controller_test.rb
- test/controllers/api/messages_controller_test.rb
- test/controllers/api/old_nodes_controller_test.rb
- test/controllers/api/old_relations_controller_test.rb
- test/controllers/api/old_ways_controller_test.rb
- test/controllers/api/permissions_controller_test.rb
- test/controllers/api/user_preferences_controller_test.rb
- test/controllers/api/users_controller_test.rb
Uses the new features added to the bearer_authorization_header while dropping basic authentication support to simplify the creation of bearer authorization headers for API tests.
This is an alternative to #5154 that goes further in simplifying things.
> Simplify creation of bearer authorization headers

- app/views/geocoder/search.html.erb
- config/locales/en.yml
PR addresses repeated "Results" in sidebar described in #5065 
Fixes #5065. Replaced "Search Results" with "Search".
Before
After
Before
After
> Compacted repeated "Results" into one sentence

- config/locales/en.yml
The redesign happened in https://github.com/openstreetmap/openstreetmap-website/commit/6adcce4e5d75fa21dea85742fa36ee3b97247b01. Some of the texts went to the *About* page in https://github.com/openstreetmap/openstreetmap-website/commit/3ebad9ec2f59f2ba5716952f6169cdbb4972f931.
> Remove strings unused since Oct 2013 frontpage redesign

- app/views/site/about.html.erb
They were added together with the section template in https://github.com/openstreetmap/openstreetmap-website/commit/7c4dff7445568b9791f79b5c201c808eb83d100e to support rendering texts from within that template. That template was removed in https://github.com/openstreetmap/openstreetmap-website/commit/459995ab51e9ceb19f12e5baf70d72b2560c9887.
> Remove unnecessary site.about locale scopes from About page

- config/locales/en.yml
Was used in a photo gallery on the *About* page. The gallery was added in https://github.com/openstreetmap/openstreetmap-website/commit/3ebad9ec2f59f2ba5716952f6169cdbb4972f931, commented out in https://github.com/openstreetmap/openstreetmap-website/commit/0f6ee7407c173fa21075a68b8b99d520ace43225 and removed in https://github.com/openstreetmap/openstreetmap-website/commit/07c6d714c557d79924c09139e875de0f5eb80e81.
> Remove unused site.about.next string

- app/views/oauth2_applications/_form.html.erb
- config/initializers/doorkeeper.rb
- lib/oauth.rb
After OAuth1 was removed, all scopes are OAuth2 scopes. Former OAuth2-only scopes now can be combined with the rest.
> Remove Oauth::OAUTH2_SCOPES

- app/abilities/ability.rb
See https://github.com/openstreetmap/openstreetmap-website/pull/5012#issuecomment-2245708279. This leaves only one odd `:edit` ability on `:site`.
> Remove :edit abilities implied by :update abilities

- DOCKER.md
- Dockerfile
Fixes #5010
A few notes regarding this issue and PR:
- Since @tomhughes mentioned in this [comment](https://github.com/openstreetmap/openstreetmap-website/pull/5070#issuecomment-2329719170) that all the production and development servers are now on Debian 12, I thought this would be a good time to sync the Docker image and revisit the previous work.
- The issues noted in this [comment](https://github.com/openstreetmap/openstreetmap-website/issues/5010#issuecomment-2261537069) have been resolved. These were likely caused by geckodriver v0.34 being incompatible with the newer version of Firefox, which was reflected in the test logs afterwards.
- Node.js and osmosis are now installed as a system packages, and ESLint is working correctly out of the box again.
- I encountered an issue when …
> Switch from ubuntu to debian and refactor Dockerfile

- config/locales/en.yml
Was added in https://github.com/openstreetmap/openstreetmap-website/commit/3e69a4512f2d1b39f48719882a0d112d042da73a together with `messages.messages_table.actions`, but only the latter is in use.
> Remove unused messages.outbox.actions string

- config/locales/en.yml
Not in use since this text was replaced by an icon in https://github.com/openstreetmap/openstreetmap-website/commit/3a9db4cf30899d256558f2e03a7c4c30d66669fd
> Remove unused site.search.get_directions string

- app/controllers/user_blocks_controller.rb
This helps `i18n-tasks` to see that these strings are used and stops `i18n-tasks unused` from reporting them.
> Move ?: operator outside of t() for "Only ... can edit" block messages

- config/locales/en.yml
PR removed 2 unused translations pairs from en.yml:  traces.make_public.made_public (started / ended using in 95595ee / 5651714) and traces.trace_optionals.tags (started / ended using in c30f141 / 7410b59).
There are 2 more unused translations (traces.page.newer and traces.page.older) probably forgotten to be put under t("") (or waiting for more pagination functionality) - didn't touch them.
> Removed 2 unused translations from Traces namespace

- app/assets/javascripts/richtext.js
See the discussion at #5111 and [this Turbo Handbook section](https://turbo.hotwired.dev/handbook/building#installing-javascript-behavior).
Things that are installed once in `$(document).ready()`:
- delegated Bootstrap tab events
- window resize listener
Things that are installed in `$(document).on("turbo:load")`:
- textarea listeners because can't delegate `invalid` events
- help updater that moves the help card between a tab pane and a sidebar is called once
> Adapt richtext javascript to Turbo

- app/views/notes/_notes_paging_nav.html.erb
- config/locales/en.yml
Smaller PR compared to #4532. I'm just changing how the paging buttons look on `/user/:name/notes` pages.
Before:
After:
> Bootstrap notes pagination

- app/abilities/api_capability.rb
- test/controllers/api/old_nodes_controller_test.rb
- test/controllers/api/old_relations_controller_test.rb
- test/controllers/api/old_ways_controller_test.rb
Continues #4387.
Requires `write_redactions` scope to redact. Previously it was possible to redact with either `write_redactions` or `write_api`.
> Disable redactions with write_api scope

- app/views/diary_comments/_page.html.erb
- app/views/diary_entries/_page.html.erb
- app/views/issues/_page.html.erb
- app/views/shared/_pagination.html.erb
- app/views/traces/_page.html.erb
- app/views/user_blocks/_blocks.html.erb
- app/views/users/_page.html.erb
- config/i18n-tasks.yml
- config/locales/en.yml
- test/system/issues_test.rb
See https://github.com/openstreetmap/openstreetmap-website/pull/5174#issuecomment-2338001493
- "Older/Newer" strings are moved to the `shared.pagination` scope. 
- `shared.pagination` is ignored by `i18n-tasks`.
- Instead of receiving (multiple, currently two but possibly more in the future) translation keys, the `shared/pagination` template receives one translation scope.
- Actually it's not necessary to pass this scope in most of the cases because it can be guessed from the controller name.
> Translation scope for shared pagination

- app/views/layouts/_flash.html.erb
Annotate flash messages as temporary to prevent them from being cached/restored by Turbo:
https://turbo.hotwired.dev/handbook/building#preparing-the-page-to-be-cached
> Adapt flash messages to Turbo

- config/locales/en.yml
PR removes user_role.{grant,revoke}.{title, heading, confirm} translation keys from en.yml started / ended using in 30d5e78 and 8a7040e / 5f33656.
> Removed unused translations in user_role namespace

- app/views/redactions/index.html.erb
- config/locales/en.yml
There's no link to the new redaction page from [redactions list](https://www.openstreetmap.org/redactions) for anyone, even though other buttons like Edit and Delete are present on each redaction page.
> Add New Redaction button to redactions page

- app/views/redactions/show.html.erb
- test/system/redaction_destroy_test.rb
The existing `:method => "delete" ...` don't entirely work for some reason. The browser gets stuck on redirects after the request is done.
> Replace 'remove this redaction' confirmation and request with Turbo

- app/controllers/users_controller.rb
This view uses cursor based pagination but then undermines that by counting the total number of users so limit the effect of that but counting a maximum of ten pages of users.
> Limit the number of users counted for users#index

- app/controllers/friendships_controller.rb
- test/system/friendships_test.rb
If you try to add too many friends, you're supposed to see this message:
But you won't see it because of `flash.now` followed by a redirect.
> Fix friendships limit flash message

- config/i18n-tasks.yml
- config/locales/en.yml
PR removes unused translations activerecord.errors.messages.{invalid_email_address, email_address_not_routable} started / ended using in 63862d0 / 90a7efc and updated i18n-tasks.yml to ignore reporting auth.providers.* as unused although they are used in app/views/application/_auth_providers.html.erb, ..
> Removed unused translations from activerecord.errors and updated i18n-tasks.yml

- .rubocop_todo.yml
- app/assets/javascripts/user.js
- test/system/users_test.rb
This reworks the event handling to allow the "select all" checkbox to work after changing page in the user list.
> Make select all checkbox on users list work with turbo

- app/helpers/browse_helper.rb
Fixes #5105, see https://github.com/openstreetmap/openstreetmap-website/issues/5105#issuecomment-2349260230.
`body` in `|body|` gets assigned the entire array, while `body` in `|(body)|` gets the first element, which is the intended effect.
> Fix element pagination width calculation

- app/views/nodes/timeout.html.erb
- app/views/old_nodes/timeout.html.erb
- app/views/old_relations/timeout.html.erb
- app/views/old_ways/timeout.html.erb
- app/views/relations/timeout.html.erb
- app/views/ways/timeout.html.erb
- config/locales/en.yml
- test/controllers/nodes_controller_test.rb
- test/controllers/old_nodes_controller_test.rb
- test/controllers/old_relations_controller_test.rb
- test/controllers/old_ways_controller_test.rb
- test/controllers/relations_controller_test.rb
- test/controllers/ways_controller_test.rb
Like #5178, was part of https://github.com/openstreetmap/openstreetmap-website/pull/4617.
Shows messages like this on element, element version and element history page timeouts:
Currently those are failing with "Missing template .../timeout".
> Fix browse elements timeouts

- app/helpers/browse_helper.rb
- app/views/changesets/_paging_nav.html.erb
What I tried to achieve previously was to save space. If the page links fit to the right of the heading, let them be there.
But this works fine only with full sidebar reloads. With turbo frame reloads it's more noticeable when the links become wider, don't fit and move below the heading. Here I'm making them always be below.
Before:
After:
> Always show changeset element page links below headings

- app/views/users/show.html.erb
PR proposes displaying "Send Message", "Add Friend" and "Unfriend" links (buttons) on user profile page only if user is signed in. Previously, these links (buttons) were always displayed.
Fixes #5199 
Signed In:
Signed Out:
> Displays links for friend options on user profile only if user is signed in

- app/controllers/users_controller.rb
- app/models/user.rb
- app/views/users/_user.html.erb
- app/views/users/show.html.erb
- script/update-spam-blocks
- test/controllers/users_controller_test.rb
This replaces `creation_ip` with `creation_address` and ignores `creation_ip` in preparation for removing it.
> Replace creation_ip with creation_address

- app/views/user_mailer/friendship_notification.html.erb
- app/views/user_mailer/friendship_notification.text.erb
PR adds greeting 'Hi {user display name},' to friendship notification messages (both HTML and TEXT). As a side effect, user_mailer.friendship_notification.hi is not anymore reported as unused.
> Added greeting to friendship notification

- app/controllers/changesets_controller.rb
Changeset elements in the history view are being paginated but no order is being specified so stepping through the pages may not give consistent results and may skip elements or show them twice - this is currently visible in the form of occasional test failures in `test_show_paginated_element_links` when it doesn't show elements in the order `create_list` created them.
> Order changeset elements for consistent pagination

- app/views/traces/new.html.erb
- config/locales/en.yml
PR adds client and server side checking if supplied trace file has GPX extension
Adds "GPX File (*.gpx)" filter to Open File dialog. Adds checking to TracesController#create if sent file has "gpx" extension (before parsing) by first converting file name to lowercase and then checking if it ends with .gpx. In case of failure, it reports error using bootstrap alert:
> Improved error messages and UI when importing GPS trace files

- config/locales/en.yml
PR makes following changes:
1. Updates i18n-tasks.yml to ignore unused translations for keys from changesets.paging_nav.* (because they are used in pagination mechanism using string interpolation),
2. Pulls out ?: operator from t() in changesets/show.html.erb so changesets.show.{comment_by_html, hidden_comment_by_html} translation keys are no longer reported as unused and
3. Removes unused translation keys changesets.{changeset.anonymous, no_such_entry.title} from en.yml because .anonymous was added in fddda4e and was stopped being used in 3e305fb and .title was added in f0764d3 but never used.
> Removed unused translations in changesets namespace

- lib/osm_community_index.rb
- test/lib/osm_community_index_test.rb
In #5210, updating the OSM community index failed due to invalid replacement tokens. This issue needs to be resolved upstream. However, we can add a bit of error handling and still apply the update. EN is used for erroneous translations.
> OCI: ignore invalid replacement token

- config/locales/en.yml
PR removes changeset_comments.feeds.comments.comment (added / removed 5cd417f / 2cf3861), issues.index.link_to_reports (added / removed 79bd177 / 05ae075) and sessions.new.register now (added / removed 5197124 / 9649b19) unused translation keys.
> Removed various unused translation keys

- config/locales/en.yml
PR removes user_blocks.show.{confirm, needs_view, show} translation keys added at daa2496. confirm and show has never been used, while needs_view ended being used at ca06b3c.
> Removed unused translations in user_blocks

- config/i18n-tasks.yml
- config/locales/en.yml
- test/system/issues_test.rb
This PR:
- adds time.formats.{blog, friendly} translation keys under ignore_unused in i18n-tasks.yml since used on numerous places for formatting dates / times,
- removes site.sidebar.close because started being used at 3a51160 and ended being used at 6adcce4 and
- removes sessions.new.title because started being used at f18baae and has been used only in test/system/issues_test.rb (from which we removed it because tests are always in EN).
Mentioned translation keys are no longer reported as unused.
> Masked off reporting as unused various keys

- app/controllers/api/capabilities_controller.rb
- app/controllers/api/changeset_comments_controller.rb
- app/controllers/api/changesets_controller.rb
- app/controllers/api/map_controller.rb
- app/controllers/api/messages_controller.rb
- app/controllers/api/nodes_controller.rb
- app/controllers/api/notes_controller.rb
- app/controllers/api/old_elements_controller.rb
- app/controllers/api/permissions_controller.rb
- app/controllers/api/relations_controller.rb
- app/controllers/api/tracepoints_controller.rb
- app/controllers/api/traces_controller.rb
- app/controllers/api/user_blocks_controller.rb
- app/controllers/api/user_preferences_controller.rb
- app/controllers/api/users_controller.rb
- app/controllers/api/versions_controller.rb
- app/controllers/api/ways_controller.rb
- app/controllers/api_controller.rb
Fixes #4861
Since the around_action is defined before authorize_resource is called, the handler needs to pass on the CanCan::AccessDenied exception.
I've added the timeouts where I think they were missing (e.g. UserPreferencesController) but I've kept the exception for changeset#upload and traces#create
> Move api error handling and timeouts to parent class

- vendor/assets/iD/iD.js
updates the editor layer index again, this time addressing https://github.com/openstreetmap/iD/issues/10486
> Update to iD v2.30.4

- .github/workflows/labeling.yml
- Dangerfile
- Gemfile
- Gemfile.lock
This PR proposes possible solution for labeling pull requests using Danger described in #4912
Proposed solution introduces new workflow, executed whenever new PR is created or updated. Workflow checks if PR is too big (>500 changed lines) or changes one of translation files (YML, except en.yml) or contains merge-commits and generates appropriate labels using Danger and danger-auto_label plugin. If none of these is found, green "Good PR" is generated.
> Added workflow for PR labeling using Danger

- app/controllers/diary_entries_controller.rb
- app/helpers/open_graph_helper.rb
- test/controllers/diary_entries_controller_test.rb
When diary posts are shared they might look like this on small screens:
The problem is that the title starts with "User's Diary |". The actual title comes after that and may be cut off significantly. Since that "User's Diary |" is not actually a diary entry title, I'm removing it from Open Graph `og:title` here.
Where am I putting it instead? Currently nowhere because:
- I considered putting it in `og:site_name` so instead of "OpenStreetMap" there's something like "User's Diary on OpenStreetMap", but that might confuse services that expect the site name to correspond to the domain name.
- There's an obvious [article:author](https://ogp.me/#type_article) property, however, looking at Mastodon and Discourse source code, it doesn't seem to be widely supported.
- What's worse, there [isn't …
> Remove "User's Diary" from diary entry og:title

- app/views/shared/_pagination.html.erb
Do the suggestion https://github.com/openstreetmap/openstreetmap-website/pull/5262#pullrequestreview-2369829924. It's somewhat related to that pull request because pagination buttons will take more space. Maybe we don't want that if the page contents is small.
With this PR pagination buttons are shown as usual if there's more than one page:
But if there's only one page, they are removed:
> Don't show older/newer buttons if all items fit on one page

- app/views/layouts/_search.html.erb
That space on the top of direction forms is too wasteful.
Before/after:
> Decrease padding between close button and inputs in directions form

- app/assets/javascripts/index/note.js
https://github.com/openstreetmap/openstreetmap-website/commit/a796c41881c26e6da8828a71dbfb533613e5a83f added a callback to `function initialize()` in `note.js`. It's called at the very end of the function. Not scheduled in some event, not skipped by early termination, nothing runs after it. Passing a callback to `initialize()` is the same as running `initialize(); callback();`
> Remove callback from initialize() in note js controller

- config/locales/en.yml
- test/controllers/messages_controller_test.rb
- test/controllers/user_roles_controller_test.rb
Most strings used single quotes, and a few used
opening backticks. Now it's single quotes everywhere.
> Consistent use of quotes

- config/locales/en.yml
There are articles before "ramp" everywhere,
and it sounds more correct with articles
before "exit" and "roundabout", too.
> Add articles before "exit" and "roundabout"

- .github/workflows/danger.yml
- .github/workflows/labeling.yml
- Dangerfile
- Gemfile
- Gemfile.lock
This gets the danger workflow working by switching to my fixed version (current open upstream as https://github.com/danger/danger/pull/1501) and also tweaks a few other things:
* Renames the workflow to reflect that this is not just about labelling
* Drops the `run-name` so that he runs will be names after the PR instead of all having the same name
* Adjusts the label names to be consistent with our other labels.
> Improvements to danger workflow

- app/controllers/api/notes_controller.rb
- app/models/note.rb
- app/models/note_subscription.rb
- app/models/user.rb
- db/migrate/20241022141247_create_note_subscriptions.rb
- db/structure.sql
- test/controllers/api/notes_controller_test.rb
Part one of #5283. Creates the note subscription table and starts adding subscriptions for anyone who comments a note. These subscriptions are not yet used for anything, email notifications still go to all note commenters.
> Note subscriptions db table

- Dangerfile
Updated the Dangerfile by adding a new rule that checks if the Gemfile is updated while the Gemfile.lock is not, and if so, generates the "gemfile-lock-outdated" PR label.
Created upon the [suggestion](https://github.com/openstreetmap/openstreetmap-website/pull/5295#issuecomment-2447849335).
Tested by running RuboCop locally and by committing changes to my personal fork before creating a problematic PR.
> Added new Danger rule for catching outdated Gemfile.lock

- app/assets/javascripts/index/query.js
- app/assets/stylesheets/common.scss
Fixes #5305.
Currently query markers are animated using javascript which requires managing timed events. We don't do it correctly, we don't cancel them when markers are removed. That's why #5305 happens.
This PR replaces the javascript animation with the css which doesn't require any event handlers. I could have added animation end events to remove the marker layer but once faded out it doesn't affect anything and it's cleaned up in `page.unload`.
> Replace query marker fade animation with css

- app/controllers/api/notes_controller.rb
- test/controllers/api/notes_controller_test.rb
- test/factories/note_subscriptions.rb
Part 3 of #5283. Start using the subscriptions table to send notifications.
> Send notifications to note subscribers instead of commenters

- app/assets/javascripts/richtext.js
- app/views/shared/_richtext_field.html.erb
Richtext preview loading animation was added in https://github.com/openstreetmap/openstreetmap-website/commit/eb789dbf757e760e8348e0aa75343eb53996b7e3 but later probably got broken. Its `loading` css class was removed in https://github.com/openstreetmap/openstreetmap-website/commit/df1ec6b6809b533829fc2c171699540bbb92a85b but javascript still adds/removes it to no effect.
This PR adds a Bootstrap spinner to the preview pane.
> Restore loading spinner in richtext previews

- app/controllers/sessions_controller.rb
- app/views/sessions/new.html.erb
- test/controllers/sessions_controller_test.rb
The "remember me" checkbox has not been working properly, or rather it has been treated as checked even when it isn't.
The reason is the "Gotcha" details in the [check_box documentation](https://api.rubyonrails.org/classes/ActionView/Helpers/FormBuilder.html#method-i-check_box) which means that the parameter has the value `"0"` when unticked.
> Make the "remember me" option work as intended

- .github/workflows/danger.yml
- Gemfile
- Gemfile.lock
Let's have another go at getting danger working shall we...
This avoids the need to path danger, and resolves the problems with not fetching enough history for PRs with many commits, by prefetching the data and creating local `danger_base` and `danger_head` branches which are the default names that danger looks for.
> Create base and head branches before running danger

- app/controllers/user_blocks_controller.rb
- test/controllers/user_blocks_controller_test.rb
When a blocked user visits their block page, its deactivation time is recorded. Problem is this only needs to happen if there's no deactivation time set. If it's already set, it should be kept at what it is.
The possible bug is that if the user visits their block page after the block is lifted, that visit time gets into `deactivates_at` and is reported as the block end time despite the block ending earlier.
> Don't update deactivates_at if block was already viewed

- app/assets/javascripts/index.js
- app/assets/javascripts/richtext.js
- app/assets/stylesheets/common.scss
Similarly to #5307, we can avoid scheduling/unscheduling js events to show spinners in the richtext preview #5311 and the sidebar loader:
There's a delay to avoid blinking on fast loads, that delay can be implemented using a css animation.
And we also can stop using `vendor/assets/jquery/jquery.timers.js` which does some ill-advised things like [listening to `unload`](https://developer.mozilla.org/en-US/docs/Web/API/Window/unload_event).
> Use CSS animations to show delayed loading spinner

- app/assets/javascripts/index/new_note.js
https://github.com/openstreetmap/openstreetmap-website/commit/51dcf86f40200bf4728097868f45aa2fe12968f3 added the "removenote" timer. Its use was removed in https://github.com/openstreetmap/openstreetmap-website/commit/d380ce79aabcd98ade3eabe8f982e516311f6aee but the `stopTime` cleanup stuck.
> Remove unused timer from new note js controller

- Vagrantfile
- script/vagrant/setup/provision.sh
Similar to #5157 this switches the vagrant configuration to use Debian 12 instead of Ubuntu.
Only tested with the libvirt provider at the moment.
> Switch vagrant to use Debian 12

- CONFIGURE.md
- CONTRIBUTING.md
- DOCKER.md
- FAQ.md
This PR combines a few minor changes to the docs that I noticed while working on #5318 
* Add missing top-level headers to two files
* Standardise on fenced code blocks in markdown, for consistency and to allow language declarations
* Use language declarations for yaml code blocks
I also considered adding language information for code intended to be typed at the console, but then that turns out to be more complex with a choice of declarations (e.g. `bash` vs `console`) and whether to add `$ ` as a guide that it should be typed, and what to do with things that start with a console command but is then mainly `irb` from that point on, so I'll leave all that for some other time.
> Minor changes to docs

- app/assets/javascripts/index.js
- app/assets/javascripts/index/search.js
- app/assets/javascripts/router.js
- app/assets/stylesheets/common.scss
- app/views/layouts/_header.html.erb
Version of #4854 that also moves *History* to secondary navigation.
> Move History and Export buttons to secondary nav

- app/assets/javascripts/index.js
- app/assets/javascripts/index/search.js
- app/assets/javascripts/router.js
- app/assets/stylesheets/common.scss
- app/views/layouts/_header.html.erb
*Export* is no longer a green outline button but rather a gray secondary navigation item.
The main reason for this is to allow *Export* to collapse into *More*. This lets the header to be narrower in *compact mode*. Hopefully then *compact mode* will be available above the Bootstrap medium breakpoint of 768px, which then can be made a fixed breakpoint for going between *small* and *compact* modes. (If not, maybe try moving the *History* button next.) See #4130.
I also don't hide the *Edit* button because it's easier not to hide it. If I kept it hidden exactly like it was before, the *History* button in the small mode menu would have had rounded borders only on one side. So coincidentally I also do here what #4839 tried to do except I don't need a vertical button group for …
> Move Export button to secondary nav

- app/assets/stylesheets/common.scss
In dark mode tiles are actually darker than I intended them to be:
See https://github.com/openstreetmap/openstreetmap-website/pull/5325#issuecomment-2478943023 and https://github.com/openstreetmap/openstreetmap-website/pull/5325#issuecomment-2479026722 for explanations.
> Apply dimming filter to tiles directly

- app/views/traces/_trace.html.erb
As recommended in https://getbootstrap.com/docs/5.3/components/badge/#background-colors, this sets both background and text colors in one declaration, with text depending on background.
See https://github.com/openstreetmap/openstreetmap-website/issues/5329#issuecomment-2478795244
> Set colors for trace visibility badges using .text-bg-*

- app/helpers/user_helper.rb
- app/views/application/_auth_providers.html.erb
- test/helpers/user_helper_test.rb
See https://github.com/openstreetmap/openstreetmap-website/issues/5329#issue-2661831842
Before:
After:
> Style small auth buttons similarly to preferred auth buttons

- app/assets/stylesheets/common.scss
This PR increases the specificity of the dark mode attribution selector. The style was first added in #4764, but didn't overwrite Leaflet's default link selector. That increased specificity fixes #5329's bug report about this by @Nekzuris
| before | after |
|-|-|
| ![image](https://github.com/user-attachments/assets/ff079ae9-0c21-49cb-b6dd-1ceca1c09b6f) | ![image](https://github.com/user-attachments/assets/934381e1-6e39-4273-a52f-2faae5ea9a08) |
> Enable dark mode attribution font color

- app/controllers/notes_controller.rb
- app/views/notes/index.html.erb
- config/locales/en.yml
- test/controllers/notes_controller_test.rb
This PR partly addresses #832 and serves as a smaller alternative to #5255 as suggested in comments. It aims to enhance user experience on user note pages by providing filtering functionality for notes by status. The `with_status` scope is added to the `Note` model, and the `NotesController` is updated accordingly. Default behavior remains unchanged since the status preselected value is set to `All` by default.
Test for the new scope is added to note model test to ensure functionality is working as expected.
> Add status filter to user's note page

- app/abilities/api_capability.rb
- app/controllers/api/note_subscriptions_controller.rb
- config/routes.rb
- test/controllers/api/note_subscriptions_controller_test.rb
Part 4 of #5283
Adds API endpoints to subscribe/unsubscribe from a note.
This is like the changeset subscribe/unsubscribe
https://wiki.openstreetmap.org/wiki/API_v0.6#Subscribe:_POST_/api/0.6/changeset/#id/subscribe
but since we like resourceful routes, instead of `POST .../subscribe` and `POST .../unsubscribe`, this PR adds:
- `POST /api/0.6/notes/:id/subscription` to add a subscription
- `DELETE /api/0.6/notes/:id/subscription` to remove a subscription
> Note subscriptions API

- app/assets/javascripts/leaflet.map.js
Can we have a proper map layer configuration that can be edited without going into javascript and altering bits across different files? I started doing this, here's a subtask of making a configuration for layer credits. It removes a bunch of interdependent variables like `var cyclosm_link`, `var osm_france_link`, `var cyclosm` etc.
> Collect map layer credits into a data structure

- app/assets/javascripts/index/note.js
- app/views/notes/show.html.erb
- config/locales/en.yml
- test/system/note_comments_test.rb
Part 5 of https://github.com/openstreetmap/openstreetmap-website/pull/5283 that adds the button to subscribe/unsubscribe from a note.
> Add subscribe/unsubscribe buttons to note pages

- app/assets/images/browse/node.svg
- app/assets/images/browse/relation.svg
- app/assets/images/browse/way.svg
- app/assets/stylesheets/common.scss
Add icons for elements that don't have any icon defined by their tags.
Those are the standard node/way/relation icons as used in the wiki, taginfo etc with small modifications. The most visible modification is that I made the borders lighter. I did this to make them stand out less when displayed along with tag icons:
Actually I'm doing this to try out some vertical space saving changes to #5317 that are going to look better if every list element item has something to act as a bullet point. That would be an icon, so it's better to always have one.
> Add default browse icons for nodes, ways, relations

- .erb_lint.yml
- .rubocop_todo.yml
- app/helpers/user_mailer_helper.rb
- app/views/layouts/user_mailer.html.erb
This allows us to enable output safety checks for all code within erb files.
`rubocop --auto-gen-config` ignores code within the erb files, so it is easier to maintain an exclusion on the helper than inside the layout.
> Move html_safe declaration for user_mailer from layout to helper

- app/views/layouts/_header.html.erb
There's a problem with truncated usernames if their directionality doesn't match the ui. This PR fixes the current username in the header.
Before:
After:
There's also a bigger issue #3428 and some stale pull requests trying to fix it.
> Set dir=auto on username in header

- app/views/user_blocks/_block.html.erb
Same as #5364 but for block lists.
Before:
After:
> Set dir=auto on usernames in block lists

- app/assets/stylesheets/common.scss
- app/views/user_blocks/_navigation.html.erb
- config/locales/en.yml
Before:
After:
Usernames have `dir=auto` to support truncation on the correct side:
> Truncate usernames in block navigation tabs

- app/views/browse/_containing_relation.html.erb
- config/locales/en.yml
> Use relation icon instead of word in containing relations

- app/views/traces/index.html.erb
- config/locales/en.yml
Similar to #5366.
Before:
After:
> Truncate usernames in trace navigation tabs

- app/controllers/application_controller.rb
We have `allow_thirdparty_images` policy on some pages that sets `img-src` policy to `*`. But `*` does not include data uris. That causes some of the ui elements to disappear.
For example, on `/account/edit` there's no dropdown icon:
After this fix:
> Include data: when using allow_thirdparty_images CSP

- app/controllers/issues_controller.rb
If you have both moderator and admin flags, the issue search form is going to have "User" twice.
Before:
After:
> Don't show types twice in issue type select

- app/controllers/issues_controller.rb
- app/views/issues/show.html.erb
- config/locales/en.yml
The title of `/issues/:id` pages is constructed by substituting the status into the locale string, making it difficult to translate.
This PR makes it closer to what we have for note titles:
https://github.com/openstreetmap/openstreetmap-website/blob/fe81ac334cfef04751a959297dca24e472cb025f/config/locales/en.yml#L2977-L2979
> Don't interpolate type in issue title

- app/assets/stylesheets/common.scss
- app/views/layouts/_header.html.erb
> Let header username expand to screen width in small nav mode

- app/controllers/api/relations_controller.rb
Was added in https://github.com/openstreetmap/openstreetmap-website/commit/2b7a40069f7af2e72c81f9488411135f286515f9. A similar debug statement also existed for nodes, added in https://github.com/openstreetmap/openstreetmap-website/commit/328d47e506972fededfa1080967224928c36a4cf, later removed.
> Remove logger.debug from relation update action

- app/assets/javascripts/leaflet.layers.js
- app/assets/javascripts/leaflet.map.js
Now you can (re)define other options accepted by Leaflet tile layers, for example `url` or `maxZoom`. Also you define new tile layers that are not present in `leaflet.osm.js` because `leafletOsmId` is no longer mandatory.
This lets you add, for example, dark version of  Transport Map by adding to `config/layers.yml`:
```yml
- url: 'https://{s}.tile.thunderforest.com/transport-dark/{z}/{x}/{y}{r}.png?apikey={apikey}'
maxZoom: 21
code: "U"
keyId: "transportmapdark"
nameId: "transport_map"
apiKeyId: "THUNDERFOREST_KEY"
credit:
id: "thunderforest_credit"
children:
thunderforest_link:
id: "andy_allan"
href: "https://www.thunderforest.com/"
```
> Allow specifying extra layer options in layers.yml

- app/assets/javascripts/index.js
- app/controllers/application_controller.rb
An alternative to #3760.
Uses no-cors mode https://github.com/openstreetmap/openstreetmap-website/pull/3760#issuecomment-1290363544 which should work with Potlatch. Requires a browser that is not too old (probably 5 years old max).
> Use fetch() instead of iframe to make remote control requests

- app/abilities/api_ability.rb
- app/controllers/api/traces/data_controller.rb
- app/controllers/api/traces_controller.rb
- config/routes.rb
- test/controllers/api/traces/data_controller_test.rb
- test/controllers/api/traces_controller_test.rb
This is only for `/api/0.6/gpx/`. There are other trace-related routes such as `/api/0.6/user/gpx_files` that are not changed here.
A couple of caveats:
- We have a nonstandard trace metadata path `gpx/:id/details` since https://github.com/openstreetmap/openstreetmap-website/commit/01cfcbd845c5d8d33f83bb22a24cf35932da2e29. Later a standard path `gpx/:id` was added in https://github.com/openstreetmap/openstreetmap-website/commit/71f1554212620cd0078bb04b0e666e0cbf4eb95c. Both path are currently supported. It's possible to convert `details` into a nested resource to give it a resourceful route. This will require keeping some copy-pasted code. How about instead we don't do that, keep the `details` path non-resourceful and deprecate it?
- We have a nonstandard create trace path `gpx/create`. A …
> Resourceful routes for traces API

- app/assets/stylesheets/common.scss
- app/assets/stylesheets/parameters.scss
- app/assets/stylesheets/screen-auto-ltr.scss
- app/assets/stylesheets/screen-auto-rtl.rtlcss.scss
- app/assets/stylesheets/screen-ltr.scss
- app/assets/stylesheets/screen-manual-ltr.scss
- app/assets/stylesheets/screen-manual-rtl.rtlcss.scss
- app/assets/stylesheets/screen-rtl.rtlcss.scss
- app/controllers/application_controller.rb
- app/controllers/preferences_controller.rb
- app/views/layouts/_head.html.erb
- app/views/layouts/site.html.erb
- app/views/preferences/edit.html.erb
- app/views/preferences/show.html.erb
- config/locales/en.yml
- test/controllers/preferences_controller_test.rb
Includes #5339. Implements step 5 from https://github.com/openstreetmap/openstreetmap-website/issues/5324#issuecomment-2504102012.
> Map color mode preference

- app/assets/stylesheets/parameters.scss
- app/assets/stylesheets/screen-auto-ltr.scss
- app/assets/stylesheets/screen-auto-rtl.rtlcss.scss
- app/assets/stylesheets/screen-ltr.scss
- app/assets/stylesheets/screen-manual-ltr.scss
- app/assets/stylesheets/screen-manual-rtl.rtlcss.scss
- app/assets/stylesheets/screen-rtl.rtlcss.scss
- app/controllers/application_controller.rb
- app/controllers/preferences_controller.rb
- app/views/layouts/_head.html.erb
- app/views/layouts/site.html.erb
- app/views/preferences/edit.html.erb
- app/views/preferences/show.html.erb
- config/locales/en.yml
- test/controllers/preferences_controller_test.rb
The same as #5337 but stores the preferred color scheme value in user preferences db table instead of cookies.
> Color mode preference stored in db

- app/assets/stylesheets/common.scss
If a filter is applied to every tile separately, it's possible that the gaps between tiles become visible when zooming. I've only seen this happening in Chrome, both on desktop and mobile.
It could have been the reason why I applied the filter to `.leaflet-tile-container` in the first place, which I had to undo in #5330. Now I'm applying the filter to the container again, but I disable the unexpected filer inheritance (which is disabled in the current unreleased Leaflet code).
Before:
https://github.com/user-attachments/assets/cfa6b459-b1b1-4a7e-8523-5c656e62d3ca
After:
https://github.com/user-attachments/assets/92d9c6b4-bb08-4f16-ac01-edfdecc0fc76
> Disable filter inheritance on tiles, apply filter to tile container

- app/assets/javascripts/id.js
When the `map` hash parameter is changed (and was not not triggered by map interaction from inside iD itself): pan to the new location.
This mirrors the behaviour when manually editing the `map` hash parameter on osm.org outside of iD.
This also fixes https://github.com/openstreetmap/iD/issues/10592 (error in js console when iD is opened outside of an iframe by directly navigating to osm.org/id).
> iD: listen to URL hash changes

- app/controllers/oauth2_authorizations_controller.rb
- test/controllers/oauth2_authorizations_controller_test.rb
Redirect to `/offline` from `/oauth2/authorize` if the database is offline.
Instead of this:
users will see this:
Fixes #5400
> Check if db is writable on oauth authorization pages

- app/controllers/notes_controller.rb
- app/views/notes/new_readonly.html.erb
- config/locales/en.yml
- test/system/create_note_test.rb
Show this on `/note/new` if the api is not online:
This is shown in read-only mode, offline mode already has a different message "Database offline for maintenance".
Fixes #5404.
> Show 'api offline' message on new note page

- config/routes.rb
- test/controllers/api/messages_controller_test.rb
A standard HTTP verb for update action in Rails is PATCH/PUT, but for messages API [it was made POST for some reason](https://wiki.openstreetmap.org/wiki/Messaging_API_proposal#Update_read_status_of_a_message). Here I'm adding PATCH/PUT. I'm keeping POST outside of the resources, but we should deprecate it.
Also I'm moving the resources to the api namespace. This allows to remove `:as`.
> Add standard patch/put api message update action

- lib/social_share_button_helper.rb
It was trying to pass the literal text `params[:url]` as the URL due to incorrect quoting.
> Pass correct URL to Facebook sharing

- app/helpers/application_helper.rb
- app/helpers/social_share_button_helper.rb
- test/helpers/social_share_button_helper_test.rb
This converts the confusingly named `SocialShareButtonHelper` which is really a library, but tested by a helper test, into a real helper and moves the actual `render_social_share_buttons` helper there from the application helper.
The other methods are then private as they're only used by `render_social_share_buttons` so are no longer tested separately as they're not visible to the test but will be tested implicitly by the calls to `render_social_share_buttons` in the other tests so coverage should be the same.
> Convert social share helper library into a real helper

- app/assets/javascripts/social_share_button.js
What the existing share popup window placement does is it places the popup horizontally in the center of the screen. I don't know if the popup can get placed literally in the corner (https://github.com/openstreetmap/openstreetmap-website/issues/5414#issuecomment-2551615977), maybe with a multi-monitor setup? But it still could be a surprising location if the monitor is large enough. Here the logic is changed to place the popup in the center of the browser window. Is it less surprising?
The only alternative to a popup window is a new tab, which is already available with middle click or context menu on share links.
> Center share popup inside the browser window

- app/assets/javascripts/index/note.js
- test/system/create_note_test.rb
- test/system/note_comments_test.rb
- test/system/resolve_note_test.rb
- Add test that would have failed in #5359.
- Change the code that selects the text input from `$("textarea")` to `content.find("textarea")`. This should stop the html share code from getting posted to notes, although I couldn't reproduce that happening like @SomeoneElseOSM reported it yesterday. When you press *Hide* the textarea inside the left sidebar exists and is the first one on the page, I don't know how that other textarea got selected instead.
> Improve note testing and text handling

- app/helpers/social_share_button_helper.rb
- app/views/diary_entries/show.html.erb
- test/helpers/social_share_button_helper_test.rb
This implements the refactorings suggested in #5415 and also improves the testing of the generated HTML to ensure that all the buttons are generated and reference the correct URL and title.
> Refactor social sharing helper

- app/assets/javascripts/leaflet.share.js
- config/layers.yml
- config/locales/en.yml
Follows #5388. Removes hardcoded layer id checks in *Share > Image*, except for one special mapnik check.
If a layer that can't be downloaded is selected, the message shows a list of available layers:
Before:
After:
> Add 'canDownloadImage' layer option

- test/system/resolve_note_test.rb
Follows #5419.
I figured out why bug on *Hide* was happening. It was happening when hiding resolved notes because there's no textarea for resolved notes. #5419 fixed that bug. Here I'm adding a test that would have failed.
> Test share textarea not to leak into note text on hiding resolved notes

- app/abilities/ability.rb
- app/abilities/api_ability.rb
- app/abilities/api_capability.rb
Use [CanCanCan's `:read` alias](https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md#can-actions) instead of `:index` and `:show` abilities. Similar to https://github.com/openstreetmap/openstreetmap-website/pull/5164 and https://github.com/openstreetmap/openstreetmap-website/pull/5185.
I made a couple of exceptions:
- `Note` has `:show` and `:index` abilities in different branches. I kept them. It's probably because one is on map layout, another one is on site layout and we try to avoid redirecting to the 403 page from map layout.
- I kept `:index` for `:site`. `:index` here means an entirely different thing.
> Replace show and index abilities with read ability

- config/routes.rb
- test/controllers/api/user_preferences_controller_test.rb
- test/integration/oauth2_test.rb
Done to eventually move all api routes to api namespace.
Gives `api_` prefix to path helpers.
> Move user preferences routes to api namespace

- test/controllers/api/messages_controller_test.rb
Mostly changes
```
api_message_path(:id => msg.id)
```
to
```
api_message_path(msg)
```
in tests.
> Simplify calls to api_message_path helper

- app/controllers/user_blocks_controller.rb
- test/controllers/api/user_blocks_controller_test.rb
- test/controllers/user_blocks_controller_test.rb
Similar to #5424, for `*_user_block_path` helpers.
> Simplify calls to user block path helpers

- config/initializers/field_error.rb
This `.field_with_errors` writer was added in https://github.com/openstreetmap/openstreetmap-website/commit/933b0913304fdd581c7cb3f1ec30450d6e04c63a, but the class was not used since https://github.com/openstreetmap/openstreetmap-website/commit/df1ec6b6809b533829fc2c171699540bbb92a85b.
> Remove code that added now-unused field_with_errors css class

- config/routes.rb
This is deprecated in rails 8.0 and 8.1 will remove it.
> Don't map multiple paths in a single route

- app/controllers/api/messages_controller.rb
This check was moved to `ApiController` superclass in #4859, but `MessagesController` was written before that and merged after that in #4605.
> Remove check_api_readable from api messages controller

- app/controllers/users_controller.rb
- test/application_system_test_case.rb
- test/system/user_signup_test.rb
Currently `save_new_user` does other things like redirects after the actual save. That obscures which pages are reachable from actions that call `save_new_user`, see https://github.com/openstreetmap/openstreetmap-website/issues/5431#issuecomment-2564561794.
Also `save_new_user` accesses referer in two different ways: as a function argument and as `params[:referer]`.
---
Added test for clicking *Sign Up*, filling out email-login-password, clicking *Sign Up*, opening confirmation link from email.
> Move code that runs after user save from save_new_user to create method

- .rubocop_todo.yml
- app/abilities/ability.rb
- app/controllers/user_blocks_controller.rb
- app/controllers/users/issued_blocks_controller.rb
- app/controllers/users/received_blocks_controller.rb
- app/views/user_blocks/_navigation.html.erb
- app/views/user_blocks/_page.html.erb
- app/views/users/issued_blocks/show.html.erb
- app/views/users/received_blocks/edit.html.erb
- app/views/users/received_blocks/show.html.erb
- app/views/users/show.html.erb
- config/locales/en.yml
- config/routes.rb
- test/controllers/user_blocks/table_test_helper.rb
- test/controllers/user_blocks_controller_test.rb
- test/controllers/users/issued_blocks_controller_test.rb
- test/controllers/users/received_blocks_controller_test.rb
- test/controllers/users_controller_test.rb
- test/system/user_blocks_test.rb
This creates `:issued_blocks` and `:received_blocks` resources for users. `:revoke_all` action is changed to deleting received blocks.
> Resourceful routes for received/issued blocks

- app/assets/javascripts/index/new_note.js
- app/assets/javascripts/leaflet.note.js
- app/views/notes/new.html.erb
- test/system/create_note_test.rb
If
- you open `/note/new` while your zoom is too low as described in #1291 
- you zoom out far enough while on `/note/new`,
show a warning message and disable the submit button.
Fixes #1291 and another bug: note marker was disappearing together with notes layer when visible area became too large.
> New note page on low zooms

- test/controllers/sessions_controller_test.rb
This test was about tokens that don't exist since #4535. That PR modified the test by removing the assert that checked the number of tokens in https://github.com/openstreetmap/openstreetmap-website/commit/4dff06a6293971c3e17f8508859a1d80717a23f6. Yet the test was kept although it doesn't do what it was supposed to do.
It also has `post user_save_path` that used to happen after `post user_new_path` when the terms page was shown during signups. This is not happening after #4455, and `post user_save_path` was removed from other tests in https://github.com/openstreetmap/openstreetmap-website/commit/1276fb944a8024884f3121d21577ef892353dfd1.
> Remove test_logout_removes_session_token

- config/routes.rb
- test/controllers/messages_controller_test.rb
This changes the path from
`/message/new/:display_name`
to
`/messages/new/:display_name`
> Use resourceful route for new message

- test/controllers/diary_entries_controller_test.rb
`commit` is the name of the submit button, but it's never checked by the controller and its value is not "save" in the actual forms.
> Remove commit parameter from diary controller test

- app/abilities/ability.rb
- app/controllers/messages/replies_controller.rb
- app/controllers/messages_controller.rb
- app/mailers/user_mailer.rb
- app/views/messages/show.html.erb
- config/locales/en.yml
- config/routes.rb
- test/controllers/messages/replies_controller_test.rb
- test/controllers/messages_controller_test.rb
Creates a nested `reply` resource for messages.
Changes reply path from `/messages/:id/reply` to `/messages/:id/reply/new` because it's a new reply.
Removes unused POST route. It was previously removed in https://github.com/openstreetmap/openstreetmap-website/commit/40cab845fbabb3f0aa8131c16e48cd3d58b6dcb3, then restored because it was still in use. I don't think it's in use now.
> Use resourceful route for message reply

- app/views/accounts/edit.html.erb
- app/views/application/_auth_providers.html.erb
- lib/auth.rb
There's `Auth` module that lists currently enabled auth providers. It's used in two different places: auth providers template for login/signup pages and account edit page.
What the module actually does is it prepares options for `<select>` on the account edit page. That's why it includes localization strings as keys of a hash. The template on login/signup pages needs different strings and ignores the keys. Why do we need then to include the localization strings in `Auth` at all?
> Convert Auth.providers into array

- app/controllers/application_controller.rb
- app/controllers/diary_comments_controller.rb
- test/controllers/diary_comments_controller_test.rb
- test/controllers/users_controller_test.rb
When you write something like `allow_thirdparty_images :only => :index` you'd expect the CSP to be altered only on `index` action. But actually `:only => ...` was ignored and `allow_thirdparty_images` ran on all actions because `content_security_policy` didn't receive `options` correctly.
Other `allow_` methods from `app/controllers/application_controller.rb` should be similarly fixed, except I haven't figured out whether they are required at all. For example `allow_all_form_action` in `app/controllers/oauth2_authorizations_controller.rb` came from https://github.com/openstreetmap/openstreetmap-website/commit/b96f3867e61dad3d7f14a0d8da01ea0cab1c83ec, but are redirects done using form actions? Forms in `app/views/oauth2_authorizations/new.html.erb` have actions pointing to the osm website.
> Fix allow_thirdparty_images options

- app/assets/javascripts/index/history.js
https://github.com/openstreetmap/openstreetmap-website/commit/6b194ed6278d4b05a04a20d6907203ed329bef77 added a map zoom listener to history pages because rendered changeset rectangles depend on the map scale. But the listener is never removed on unload.
> Remove zoomend listener on history unload

- app/assets/javascripts/index/changeset.js
- app/assets/javascripts/leaflet.map.js
- app/helpers/changesets_helper.rb
- app/views/changesets/_changeset.html.erb
- app/views/changesets/show.html.erb
Fixes #4081 on `/changeset/:id` pages.
Previously changeset bbox was loaded using `L.OSM.DataLayer`. That requied additional http request. Also `L.OSM.DataLayer` assumed that all changesets have bounding boxes which is not true.
> Pass bbox to changeset page via data attribute

- app/controllers/messages_controller.rb
- test/controllers/messages_controller_test.rb
Currently if you send a new message, you are redirected to your inbox. But you probably want to see the result of the message being sent, and that is in the outbox.
Redirect to inbox existed long ago https://github.com/openstreetmap/openstreetmap-website/commit/e6af088dda8e85f53b11ffbaddb11edf08e4a046, before there was outbox, which was added in https://github.com/openstreetmap/openstreetmap-website/commit/d736a158bee0ff17bdba30496b87e1bfe20e2910.
> Show outbox after sending new message

- app/controllers/old_nodes_controller.rb
- app/controllers/old_relations_controller.rb
- app/controllers/old_ways_controller.rb
- app/views/browse/not_found.html.erb
- app/views/changesets/_not_found_message.html.erb
- app/views/nodes/_not_found_message.html.erb
- app/views/notes/_not_found_message.html.erb
- app/views/old_nodes/_not_found_message.html.erb
- app/views/old_nodes/not_found.html.erb
- app/views/old_relations/_not_found_message.html.erb
- app/views/old_relations/not_found.html.erb
- app/views/old_ways/_not_found_message.html.erb
- app/views/old_ways/not_found.html.erb
- app/views/relations/_not_found_message.html.erb
- app/views/ways/_not_found_message.html.erb
- config/locales/en.yml
- test/controllers/old_nodes_controller_test.rb
- test/controllers/old_relations_controller_test.rb
- test/controllers/old_ways_controller_test.rb
*Not found* pages for various types became slightly different. This PR makes them similar to each other.
The types are (Old)(Node/Way/Relation), Note and Changeset.
- The main template is kept at `browse/not_found`. 
- The type-specific part is the message displayed on that page, it's kept in `not_found_message` templates.
- The string with word substitution "Sorry, %{type} #%{id} could not be found." is replaced by type-specific strings like "Sorry, changeset #%{id} could not be found." where only id (and version numbers in some cases) are substituted. Those should be easier to translate.
> Make browse not found pages consistent

- app/helpers/user_blocks_helper.rb
- test/helpers/user_blocks_helper_test.rb
Blocks table update in #4200 was done before `deactivates_at` was introduced. Because of that there's still code that checks `updated_at` instead of `deactivates_at`.
This PR fixes a bug which should be difficult to notice because it happens only with zero-duration blocks that don't need to be viewed. Usually it doesn't make sense to create such blocks. These blocks are incorrectly reported as "read" in the table even if they weren't read because `updated_at` is slightly greater than `ends_at`.
> Check deactivates_at to report if block was read after its end date

- app/assets/javascripts/leaflet.map.js
- test/system/browse_test.rb
Makes relation node members (for example, bus stops in routes) *interesting* again.
Fixes https://github.com/openstreetmap/leaflet-osm/pull/43#issuecomment-2574558124.
> Update arguments of data overlay interestingNode()

- app/views/layouts/_header.html.erb
- app/views/layouts/map.html.erb
- app/views/notes/new.html.erb
- app/views/site/fixthemap.html.erb
- config/routes.rb
- test/controllers/confirmations_controller_test.rb
- test/controllers/users_controller_test.rb
- test/integration/user_creation_test.rb
- `user_new_path` helper renamed to `new_user_path`
- user create action moved from `POST /user/new` to `POST /user`, which corresponds to `users_path` helper
> Use resourceful routes for user new/create actions

- app/helpers/user_blocks_helper.rb
- test/helpers/user_blocks_helper_test.rb
I changed `updated_at` to `deactivates_at` in #5476 and forgot to make the same change on the next line. This can cause block update dates to be reported as block read dates. Those dates are different for blocks that were edited by moderators after they were read. The reason text can still be updated for such blocks.
> Report deactivates_at as block read date

- Gemfile
- Gemfile.lock
https://bugs.ruby-lang.org/issues/18673 affects some methods using anonymous blocks, and was fixed in ruby 3.1.3. However, debian/bookworm ruby 3.1 package is based on 3.1.2 and does not yet contain this fix.
Since bookworm is used in our Docker build, and also used in production by OSMF, then we can restrict dry-schema to a version that does not use anonymous blocks.
Fixes #5482
> Restrict version of dry-schema for ruby 3.1.2 compatibility

- CONTRIBUTING.md
> Update documentation to avoid erb_lint deprecations

- app/controllers/diary_entries_controller.rb
- test/controllers/diary_entries_controller_test.rb
This allows users to review their post and use the social share buttons more easily.
Refs #1391
> Show diary entry after creation

- app/views/user_mailer/_gpx_description.html.erb
- app/views/user_mailer/_gpx_description.text.erb
- app/views/user_mailer/gpx_failure.html.erb
- app/views/user_mailer/gpx_failure.text.erb
- app/views/user_mailer/gpx_success.html.erb
- app/views/user_mailer/gpx_success.text.erb
- config/locales/en.yml
- test/mailers/user_mailer_test.rb
Fixes #4012. As I say in https://github.com/openstreetmap/openstreetmap-website/issues/4012#issuecomment-2529365698 the current success/failure sentences are too long because we try to put in trace name/description/tags into them. I don't think anyone wants to read sentences that long. Shorter sentences won't have to be combined from parts, which will improve translatability.
HTML success email:
HTML success email:
HTML failure email:
Plaintext success email:
```
Hi fakeuser1,
It looks like your file loaded successfully with 295 out of a possible 295 points.
Your file details:
Filename
11716462.gpx
URL
http://openstreetmap.example.com/user/fakeuser1/traces/100
Description
new trace description here
Tags
new, trace, tags, here
All your successfully uploaded GPX traces can be found at …
```
> Move trace descriptions out of success/failure sentences in emails

- app/assets/javascripts/index/new_note.js
- app/controllers/concerns/session_methods.rb
- app/controllers/confirmations_controller.rb
- app/controllers/notes_controller.rb
- app/views/notes/new.html.erb
- config/locales/en.yml
In the French community, we've had a problem for over a year with someone creating a huge number of anonymous notes, which hampers the processing of other relevant notes in the same area. See [this discussion](https://forum.openstreetmap.fr/t/notes-anonymes-a-gogo/18362) on the French community forum.
I thought it would be a good idea to count the number of anonymous notes created in the same browser and to display a warning when this number becomes too high, to encourage visitors to become users and contributors.
This PR creates a new warning in the UI of the new note form if an anonymous visitor has already created too many anonymous notes (threshold set at 20 for now)
**Changes**:
- in template views/note/new.html.erb
- add a new div element displaying the warning (hidden at first)
- …
> display an encouragement to contribute after many anonymous notes

- test/system/create_note_test.rb
Tests I used for #5468. They create 10 anonymous notes and check that the encouragement message appears, then log in or sign up and check that the message disappears.
> Test anonymous notes counter

- .rubocop_todo.yml
- config/locales/en.yml
A couple of unused translation strings and a rubocop ignore.
> Remove references to OAuth 1 client_application model

- config/locales/en.yml
After merging 967e6d4 preferences.show.{preferred_editor, preferred_languages} are not used anymore. PR removes these translation keys.
> Removed unused translations in preferences.show

- app/abilities/ability.rb
- app/controllers/accounts/terms_controller.rb
- config/locales/en.yml
After the terms page was taken out of the signup process, its controller still had the code for this kind of use by unregistered users. Later I moved the page to `/account/terms` which implies that its only for active users, but I still haven't removed the code.
Here I'm actually removing the unused code. Things like `redirect_to login_path(:referer => request.fullpath) if current_user.nil?` are handled by abilities, only active users are able to access the terms.
> Remove account terms code unreachable for unregistered users

- app/models/note.rb
- app/views/notes/index.html.erb
- app/views/notes/show.html.erb
- test/models/note_test.rb
- test/system/report_note_test.rb
- test/system/report_user_test.rb
PR adds `description` and `author_id` (`author_ip` is already there) methods to Note model file. Methods use first comment for retrieving requested information. Also, adds unit tests for testing functionality of added methods.
This PR is 1st from set of PRs described [here](https://github.com/openstreetmap/openstreetmap-website/pull/5485#pullrequestreview-2545467592).
Automated unit tests and manual testing
> Adds description and author_id methods to Note

- app/models/note.rb
- db/migrate/20250104140952_add_description_to_notes.rb
- db/structure.sql
PR adds migration script for adding new columns (`description`, `user_id`, `user_ip`) to `notes` table. Also, migration adds foreign key (with turned OFF validation) connecting `notes` and `users` tables (using `user_id` column).
This PR is 2nd from set of PRs described [here](https://github.com/openstreetmap/openstreetmap-website/pull/5485#pullrequestreview-2545467592).
Automated unit tests and manual testing
> Adds migration for adding description, user_id, user_ip columns to notes

- app/assets/javascripts/index/layers/notes.js
https://github.com/openstreetmap/openstreetmap-website/commit/de78176e04961c52f1fa1283812ec06ce6eb90cf added `layeradd`/`layerremove` listeners on `map` that check the layer and only do something if it's `noteLayer`. Later https://github.com/openstreetmap/openstreetmap-website/commit/85282f5cdd5b37016027feda0a16d8cbdc6a2581 added `click` listener directly on `noteLayer`. But `layeradd`/`layerremove` could also be installed directly on `noteLayer`, then comparing the layers wouldn't be necessary.
Elsewhere the same thing is considered for data layer: https://github.com/openstreetmap/openstreetmap-website/pull/5474#issuecomment-2584926028
> Install add/remove event listeners directly on note layer

- app/views/follows/show.html.erb
Originally the make/remove friend pages contained a form:
https://github.com/openstreetmap/openstreetmap-website/blob/17323257685bf5134d9286f5baefaddcae65478c/app/views/friendships/make_friend.html.erb#L5-L10
#5261 replaces these two pages with one `/user/:user/follow` page. That have doesn't have a form. Instead it has a link styled as a button. This is probably because there were multiple changes to paths during the development of that PR. But I don't know why it shouldn't be a true button with the paths we eventually settled on. Also the link has a small button css class on it. I don't know why the button that is the only thing on the page should be small. Probably it was a copypasted code from subscribe/unsubscribe buttons or something similar.
Before:
After:
> Use form with normal-sized button on follows show pages

- app/views/dashboards/_contact.html.erb
- test/system/dashboard_test.rb
Non-friend nearby users section wasn't covered by tests.
> Fix missing translation of Follow links on dashboard

- app/views/accounts/edit.html.erb
- config/locales/en.yml
There's the *Public editing* line on the `/account/edit` page between *External Authentication* and *Contributor Terms*. I don't think it's useful anymore. All of the accounts created in the last 15 years have public editing enabled. All new users are invited to start editing on the welcome page, so they know they can edit. All users who have been around for a while know they can edit. They don't need to be told that they can edit on the *Settings* page. This PR removes the *Public editing* line.
Before:
After:
---
For a few users that still have an account without public editing enabled, this line is useless anyway because there's an entire section at the bottom of the page about public editing.
Before when not gone public:
After when not gone public:
> Remove "Public editing" line from settings page

- db/migrate/20250105154621_validate_foreign_key_on_notes.rb
- db/structure.sql
PR adds migration for validation foreign key in `notes` table referencing `users` table.
This PR is 3rd from set of PRs described [here](https://github.com/openstreetmap/openstreetmap-website/pull/5485#pullrequestreview-2545467592).
Automated unit tests and manual testing.
> Adds validating of notes foreign key

- app/controllers/follows_controller.rb
- app/views/follows/show.html.erb
More *friend* cleanups. Removes `lookup_friend` method that sets `@friend` variable, replacing it with `lookup_user` that sets `@user`. `@user` will allow to treat `follow` as a nested resource of a user.
> Replace lookup_friend with lookup_user in FollowsController

- config/routes.rb
- test/controllers/api/tracepoints_controller_test.rb
Doesn't do much, mostly changes `trackpoints_path` to `api_tracepoints_path`, with `api_` prefix like other api paths.
> Use resourceful routes for api tracepoints

- config/eslint.js
We've been on 2015 for a long time as we no longer care about IE there's probably no good reason not to bump it.
I've had a look at the support matrices and up to 2022 just about everything seems to be supported in all current browsers. Detailed results can be found:
* [ECMAScript 2016](https://caniuse.com/?feats=array-includes,mdn-javascript_operators_exponentiation)
* [ECMAScript 2017](https://caniuse.com/?feats=async-functions,object-values,object-entries,mdn-javascript_builtins_object_getownpropertydescriptors,pad-start-end,mdn-javascript_grammar_trailing_commas_trailing_commas_in_functions)
* [ECMAScript 2018](https://caniuse.com/?feats=mdn-javascript_builtins_regexp_dotall,js-regexp-lookbehind,mdn-javascript_builtins_symbol_asynciterator,mdn-javascript_functions_method_definitions_as …
> Bump allowed ECMAScript version to 2021 (ES12)

- app/controllers/users/changeset_comments_controller.rb
- app/controllers/users/diary_comments_controller.rb
I noticed that the comment views were loading objects one by one and this should make it more efficient.
> Preload parent objects for user comments

- app/models/changeset_comment.rb
- app/models/diary_comment.rb
- db/migrate/20250121191749_add_user_comment_indexes.rb
- db/structure.sql
This adds indexes on `user+id` to diary and changeset comments to make comment views more efficient.
Once this is merged we can switch the `diary_comments` association on users to sort by id instead of creation date and then drop the creation date indexes.
> Add indexes on user+id to changeset and diary comments

- app/assets/javascripts/osm.js.erb
As reported in #3971, some URLs like https://www.openstreetmap.org/?mlat=53.32607&mlon=-1.49033 reset the currently selected layers. In order to restore the previous setting, a user needs to select both map and overlay layers after clicking on the link. 
It seems a bit premature to simply override the current layers with default values, in case the link does not include any layer information.
Instead, this PR unconditionally extracts the current layers from the _osm_location cookie, so it can be applied consistently across different url parsing alternatives.
As before, if the link includes layers in the hash value, that information takes precedence.
This change mainly impacts line 144 below:
```
mapParams.layers = hash.layers || (loc && loc[3]) || '';
```
loc[3] will now always contain …
> Consistent usage of layer information in _osm_location cookie

- app/controllers/user_blocks_controller.rb
If a block is created without `needs_view`, it's less likely to get noticed by the receiving user. Nobody could come up with any reason why blocks shouldn't be `needs_view` by default.
> Set needs_view by default for new blocks

- .rubocop_todo.yml
- app/controllers/traces_controller.rb
I'm not sure why the other files were in rubocop_todo, perhaps they had been refactored since the file was last generated.
> Use flash.now for messages to be shown during this request

- app/controllers/traces/data_controller.rb
- app/controllers/traces_controller.rb
- config/routes.rb
- test/controllers/traces/data_controller_test.rb
- test/controllers/traces_controller_test.rb
Adds a resource for downloading the trace at `/traces/:id/data` with redirect from `/trace/:id/data`.
There's already a similar resource on the api side.
> Trace data resource

- test/abilities/api_abilities_test.rb
- test/abilities/api_capability_test.rb
- test/controllers/oauth2_authorized_applications_controller_test.rb
- test/factories/oauth_access_grant.rb
- test/factories/oauth_access_token.rb
- test/models/user_test.rb
- test/test_helper.rb
It's annoying to type
```
create(:oauth_access_token, :resource_owner_id => user.id, ...
```
This PR shortens it to
```
create(:oauth_access_grant, :user => user, ...
```
Doorkeper classes don't have actual associations with our models and looks like this line in `oauth_access_grant` factory never worked
```
resource_owner_id :factory => :user
```
And I also have to tell RuboCop not to enforce these associations.
> Add user transient attribute to oauth factories

- app/controllers/application_controller.rb
`deny_access` was split into `web_deny_access` and `api_deny_access` in https://github.com/openstreetmap/openstreetmap-website/commit/8f70fb21146b1e8b90125e02d54e70bceea1d5fd. Later `api_deny_access` was moved to `ApiController` in https://github.com/openstreetmap/openstreetmap-website/commit/742291a840ea9dd741ef439e8678c50d1537973b. However the token-checking branch was left in `ApplicationController`. You're not going to have `doorkeeper_token` outside of the api, right?
> Remove doorkeeper_token branch from web deny_access

- app/controllers/api_controller.rb
- app/controllers/application_controller.rb
`scope_enabled?` is only called from api controllers/views and it references `doorkeeper_token` available only during api calls.
> Move scope_enabled? to ApiController

- app/controllers/api/notes_controller.rb
- test/controllers/api/notes_controller_test.rb
`scope_enabled?` returns nil if there's no `doorkeeper_token`, then `author` stays undefined. The else branch removed in this PR would have done the same because there's no `current_user` in this case too.
> Simplify write_notes scope check in api notes controller

- .rubocop.yml
- app/abilities/ability.rb
- app/controllers/messages/mutes_controller.rb
- app/controllers/messages/read_marks_controller.rb
- app/controllers/messages_controller.rb
- app/views/messages/mailboxes/_message.html.erb
- app/views/messages/show.html.erb
- config/locales/en.yml
- config/routes.rb
- test/controllers/messages/mutes_controller_test.rb
- test/controllers/messages/read_marks_controller_test.rb
- test/controllers/messages_controller_test.rb
Converts remaining actions of messages controller that RuboCop doesn't like into resources:
- `read_mark` which can be created and destroyed instead of `mark` action
- `mute` which can be destroyed instead of `unmute` action
> Message read_mark and mute resources

- app/assets/javascripts/index/layers/data.js
- config/locales/en.yml
As discussed in https://github.com/openstreetmap/openstreetmap-website/pull/5474#issuecomment-2585349128, this PR adds error handling for failed API calls when displaying the data layer.
Sample screenshot:
Oh well, and this one is a topic for another PR:
> Added error handling for data layer

- app/assets/javascripts/application.js
That's what was happening before https://github.com/openstreetmap/openstreetmap-website/commit/d7b4f88d5e342b5c2b4f2435d0394e4286524678, but after that the init code was moved inside `$(document).ready( ... )`. That means it may not run before other code wants to use it, like https://github.com/openstreetmap/openstreetmap-website/pull/5402#discussion_r1923067165. `<head>` already exists by the time application.js runs, it should be possible to read html attributes from there.
> Initialize I18n and OSM as soon as application.js loads

- app/assets/javascripts/index.js
- app/assets/javascripts/index/layers/data.js
- app/assets/javascripts/index/layers/notes.js
- app/assets/javascripts/leaflet.layers.js
- app/assets/javascripts/leaflet.map.js
- app/assets/javascripts/leaflet.share.js
- app/assets/javascripts/router.js
This is fix #5466 After merging https://github.com/openstreetmap/leaflet-osm/pull/43 flame graph looks like this:
https://share.firefox.dev/4a2Wc9Z
Most of the time is spent on two handlers that update information about the current location and elements in the right sidebar. 
Unfortunately, replacing `layeradd layerremove` with `baselayerchange overlaylayerchange` (https://github.com/openstreetmap/openstreetmap-website/issues/5466#issuecomment-2571570472) is difficult, since in addition to the Map Data layer, other elements may be displayed on the map. For example, the currently selected object on the map. It is not clear how to separate changes to Map Data objects and changes to the selected element. It is necessary to track changes in the active element, otherwise at least the Edit …
> Use baselayerchange/overlayadd/overlayremove instead of layeradd/layerremove

- app/assets/javascripts/index/layers/data.js
#5551 added a window with an error if the user is trying to download too much data. But this window cannot be closed, only turn off the Map Data layer. But what if you have already turned it off?
https://github.com/user-attachments/assets/0b40a9ed-c3b7-47ee-90fb-67b264880ff9
Now it looks like this (similar to the warning about loading a large amount of data):
> Close button for loading error alert

- app/assets/javascripts/index/layers/data.js
After #5474, data rendering is no longer a bottle of performance. Modern browsers do a great job with moving the map, which displays many objects (moreover, it can also be accelerated)
The only exception is mobile browsers. Therefore, I stopped at 4000 objects.
> Increase the limit when a warning about a large number of objects is displayed

- app/assets/javascripts/leaflet.map.js
`layersAdded` is a leftover from `updateLayers` logic before #5474, when there was a single loop that both added and removed layers. Now there are two loops, the first one is removing layers, while the second one is adding, but it can only add one layer.
Before this PR:
- the second loop checks the layer code
- if it matches, the layer is added and its code is recorded into `layersAdded`
- on the final iteration if there's no match, `layersAdded` is checked
- if it's empty, layer[0] is added
After:
- the second loop checks the layer code match OR if it's the final iteration *
- if the condition is true, the layer is added and the function returns because there's nothing else to do
Looks like I also fixed a bug: you could construct an url with several base layers like this …
> Remove layersAdded variable from map.updateLayers()

- app/assets/javascripts/index/layers/data.js
This targets Internet Explorer 8, a browser that wouldn't work for many other reasons.
> Remove IE conditional compilation that limited max features

- app/assets/javascripts/index/layers/data.js
The message doesn't have max number of features in it, only the current number is present:
The max number use was added in https://github.com/openstreetmap/openstreetmap-website/commit/8027dc85b13af383ce03044d46ef6d7a471859ec and removed in https://github.com/openstreetmap/openstreetmap-website/commit/b903d8b7462519d6ef8f9175fdbde1df6620ccbb.
> Remove unused max_features parameter from feature warning

- app/models/note.rb
- test/models/note_test.rb
PR removes author_id, author_ip methods from Note model because they are not used anymore. Also, removed associated unit tests.
Tested only using automated tests and by searching sources for potential usages.
> Removes author_{id, ip} methods from Note model

- app/assets/javascripts/index/layers/data.js
- app/assets/javascripts/leaflet.map.js
https://github.com/openstreetmap/leaflet-osm/pull/44 introduced OSM JSON support in the underlying leaflet osm package. This PR enables the new feature by requesting application/json format (via Accept header).
> DataLayer to consume JSON format responses

- app/assets/stylesheets/common.scss
- app/controllers/issues_controller.rb
- app/views/issues/_page.html.erb
- config/locales/en.yml
- test/system/issues_test.rb
This PR addresses "Show 'reporting user' on 'issues' screen" issue mentioned in the https://github.com/openstreetmap/openstreetmap-website/issues/2273
On the issues page, there was added a new column called "Reporter Users". It will show unique reporters of the item. If there are more than reporters for the given item than the size of the block can handle, ellipsis will be shown at the end of the line. Each of user display name will have a link to the user. Fixes https://github.com/openstreetmap/openstreetmap-website/issues/2273
Update:
Added fixed max-width for reporters' column. If the text can't be fitted, ellipsis will be shown. On hover, box shows all the reporters.
Screenshot:
> Show "reporting user" on "issues" screen

- app/assets/javascripts/leaflet.map.js
This is a first commit of another fix which I didn't finish yet because of https://github.com/openstreetmap/openstreetmap-website/pull/5570#issuecomment-2621121469 and some other things[^1] but it should fix the same problem #5570 fixes. Unlike #5570 this PR removes references to `"M"` being the default layer. #5570 add a bunch more. I want to remove `"M"`s because the layer config is in `config/layers.yml` and you just read the code from there.
`map.updateLayers` already has an assumption that the first layer is the default one in addition to the assumption that it's  `"M"`. Potentially these assumptions may diverge, so it's better to remove one, and I'd rather remove `"M"` because it's also avoids the situation of what if there's no `"M"` layer. And that's not impossible, M used to …
> Don't remove-readd standard layer with visible overlays

- app/assets/javascripts/index/layers/data.js
The message was added in #5551.
There is a slight difference, the flex wrapper shrinks the alert paragraph. We don't do that in `displayFeatureWarning`.
Before:
After:
> Remove unnecessary wrapper divs from data layer error message

- app/assets/javascripts/index/layers/notes.js
- test/system/note_layer_test.rb
Currently note markers in note layers don't necessarily display note descriptions. There's no check if the first "comment" returned by the api is a description or is it a regular comment because the description is hidden:
https://github.com/user-attachments/assets/50af9642-0067-4b9a-941e-64826c0271d0
I wrote this comment https://github.com/openstreetmap/openstreetmap-website/pull/5511#discussion_r1931817739 where I say that it can be fixed by adding attributes to comments that indicate whether they are descriptions or actually comments. But that is not necessary because there's a status attribute, and if its value is `opened`, the "comment" is a description. This PR adds this check to note layer.
> Show only description as a marker tooltip in note layer

- app/controllers/issues_controller.rb
#4990 added the *Reporter Users* column. It uses reports to sort the users, but actually all it needs to get from the db are user ids. The existing version with `map` fetches the entire report by doing `SELECT "reports".*`. Here I'm replacing it with `pluck` that does `SELECT "reports"."user_id"`.
> Select user ids from reports using pluck

- app/assets/javascripts/index/layers/data.js
Currently data layer loading is only aborted when a new request starts. It's possible to enable data layer, start a long load, disable data layer, and then after a while receive a warning about too much data despite the layer is already disabled.
> Abort loading when data layer is removed

- app/controllers/api/relations_controller.rb
- app/controllers/api/ways_controller.rb
There was a method called `to_xml_node` defined on way models. It had a cache parameter, and `visible_nodes` was passed as this parameter in https://github.com/openstreetmap/openstreetmap-website/commit/6300fa2a4fa717ef60f715a5303916b85d951c47. Later in https://github.com/openstreetmap/openstreetmap-website/commit/363155a2a86796d27ee9161f1ee9b74d6fa307e5 xml output was rewritten and `to_xml_node` was no longer used. The method was removed in https://github.com/openstreetmap/openstreetmap-website/commit/2b1bac1279e268c8e5fcca34c950f30d2c06ec1c. Same for relations.
However `visible_nodes` stayed. It's being written to but is never read.
> Remove unused visible_nodes hashes from api element controllers

- app/assets/javascripts/index/contextmenu.js
- app/assets/javascripts/index/directions-endpoint.js
- app/assets/javascripts/index/directions.js
- app/assets/javascripts/index/export.js
- app/assets/javascripts/index/query.js
- app/assets/javascripts/index/search.js
- app/assets/javascripts/leaflet.map.js
- app/assets/javascripts/osm.js.erb
- app/assets/javascripts/user.js
The amount of `latlng.lat/lng.toFixed(precision)` calls has been bugging me.
I've put a function next to OSM.zoomPrecision that outputs a latlng array that can be destructured, spread and `join`ed.
> Add coordinate precision function

- app/controllers/api/maps_controller.rb
Another instance of `visible_nodes` like in #5584, but this time it's being read. However it's largely useless because nodes are already collected into `@nodes`. Same for `way_ids`.
> Remove ids collected in parallel to model instances in map api

- app/controllers/api/maps_controller.rb
...instead of calling `flatten!` on the result
> Use flat_map to collect way node ids in maps controller

- app/helpers/social_share_button_helper.rb
- test/helpers/social_share_button_helper_test.rb
Fixes #5587.
I think it's safer to always use `URI.encode_uri_component` instead of `URI.encode_www_form_component`. Space is going to be encoded as `%20`. Space as `+` sometimes doesn't work.
> Use URI.encode_uri_component when generating share urls

- app/assets/javascripts/index/directions-endpoint.js
- app/assets/javascripts/index/directions.js
There was a number of bugs related to route endpoint locations caused by various reasons. Some of there reasons were already addressed. The one left is Nominatim deciding to do reverse geocoding when receiving something that looks like coordinates in its freeform query. The query itself is *not* a reverse geocoding query (`/reverse?...`), yet Nominatim will do reverse geocoding if it consists of two floating point numbers.
The problem is that we have inputs that can contain either addresses or coordinates. Then the seemingly obvious thing to get coordinates is to pass this input contents to Nominatim. And this is how you get bugs. It the input already contained coordinates, Nominatim would reverse-geocode them to some place and return the coordinates of that place that are different from …
> Always do reverse geocoding when routing

- app/assets/javascripts/application.js
- app/assets/javascripts/auth_providers.js
- app/assets/javascripts/edit/id.js.erb
- app/assets/javascripts/index.js
- app/assets/javascripts/index/contextmenu.js
- app/assets/javascripts/index/directions.js
- app/assets/javascripts/index/new_note.js
- app/assets/javascripts/index/query.js
- app/assets/javascripts/index/search.js
- app/assets/javascripts/leaflet.map.js
- app/assets/javascripts/osm.js.erb
- package.json
- test/javascripts/osm_test.js
- yarn.lock
As javascript now has a builtin way to parse URL search parameters we don't really need the qs module any more, so replace it with the builtin support.
> Replace qs with URLSearchParams

- test/system/create_note_test.rb
If I'm making purely ui tests here I can't possibly know id of new notes, therefore I shouldn't check them.
But the actual reason is that it looks like `assert_content "Unresolved note ##{Note.last.id}"` line is sometimes reached before db writes are complete. `Note.last.id` is not going to have an expected value in these cases.
> Don't check ids of new notes in create note system tests

- app/assets/javascripts/index/contextmenu.js
- app/assets/javascripts/index/search.js
See https://github.com/openstreetmap/openstreetmap-website/pull/5592#discussion_r1938530806
In practice this should make no difference because lat/lon don't contain any characters that need escaping. But there's still no reason for attempting to escape them twice.
> Don't apply extra encodeURIComponent to lat/lon search params

- app/helpers/note_helper.rb
- app/models/note.rb
- app/views/api/notes/_note.rss.builder
- app/views/notes/index.html.erb
- app/views/notes/show.html.erb
- config/locales/en.yml
It seems to me that #5511 didn't go in satisfying direction, so, created new PR based on [original suggestion](https://github.com/openstreetmap/openstreetmap-website/pull/5485#pullrequestreview-2545467592).
PR adds optional use of author and description from notes (in case data-migration is done) and author and description from first visible note comment (in case data-migration is not done). Also, adds author association to Note model.
Automated unit tests and manual testing. Also tested after applying [migration script](https://github.com/openstreetmap/openstreetmap-website/pull/5485/commits/3981e9e02daec8441340bda6572111c795df82cb).
> Adds optional use of note's author and description v2

- app/views/issues/_comments.html.erb
- config/locales/en.yml
- test/system/issues_test.rb
Says who the issue is going to be reassigned to. You can have both admin and mod roles, in this case it's not obvious what the new role is. Also it's not obvious if you don't know that issues are assigned to roles and not to users.
> Write the new role in reassign checkbox label

- app/assets/javascripts/osm.js.erb
- config/eslint.js
- lib/tasks/eslint.rake
- package.json
- yarn.lock
Fixes #5523
Closes #5549
Includes https://github.com/gravitystorm/openstreetmap-website/pull/296
> Add eslint-plugin-erb to provide linting of .js.erb files

- config/routes.rb
- test/controllers/api/changesets_controller_test.rb
- test/controllers/api/nodes_controller_test.rb
- test/controllers/api/relations_controller_test.rb
- test/controllers/api/ways_controller_test.rb
Part of #5590.
Makes element index paths resourceful:
- `/api/0.6/nodes`
- `/api/0.6/ways`
- `/api/0.6/relations`
Aside from the `index` action, enables `create` by posting at these paths.
However, `create` already exists in the api at `PUT /api/0.6/node/create` etc. This is not a standard way to define `create` actions. `PUT` is supposed to be [idempotent](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/PUT), but obviously `create` create is not. You do `PUT /api/0.6/node/create`, you get one new node. You do it twice, you get two.[^1] I'm keeping the existing put-creates by mapping them to the same actions as proper post-creates.
[^1]: That also means that `update` actions which are implemented with `PUT`s are wrong because they create as many new versions as there are `PUT`s. …
> API element resources - index paths

- app/abilities/api_ability.rb
- app/controllers/api/nodes_controller.rb
- app/controllers/api/relations_controller.rb
- app/controllers/api/ways_controller.rb
- config/routes.rb
- test/controllers/api/nodes_controller_test.rb
- test/controllers/api/relations_controller_test.rb
- test/controllers/api/ways_controller_test.rb
Follows #5591.
- Renames `delete` actions to standard `destroy`.
- Adds tests for `Last-Modified` headers when showing elements.
- Adds more tests for the contents of element `show` and `full` responses.
> API element resources - show/update/delete paths

- app/views/notes/show.html.erb
The description is already html-safe after to_html.
This is a leftover from https://github.com/openstreetmap/openstreetmap-website/commit/01aa27031526280d8b1d219902a7b4c97617d19f, we don't explicitly escape other text->richtext->html like note comments.
> Don't html-escape note description

- app/abilities/api_ability.rb
- app/controllers/api/relations_controller.rb
- app/controllers/api/ways_controller.rb
- app/views/api/relations/full.json.jbuilder
- app/views/api/relations/full.xml.builder
- app/views/api/relations/show.json.jbuilder
- app/views/api/relations/show.xml.builder
- app/views/api/ways/full.json.jbuilder
- app/views/api/ways/full.xml.builder
- app/views/api/ways/show.json.jbuilder
- app/views/api/ways/show.xml.builder
- config/routes.rb
- test/controllers/api/relations_controller_test.rb
- test/controllers/api/ways_controller_test.rb
`full` is not a standard action name, but it's also not really a nested resource. Here I'm mapping them to `show` action with a parameter. A similar thing is done with changeset discussions where the discussion/comment elements are extra things added to the usual `show` output if a parameter is set.
Also there were `user/details` in #5433 which we didn't turn into a nested resource.
> API element resources - full paths

- app/controllers/notes_controller.rb
- test/controllers/notes_controller_test.rb
This is a follow on to #5609 that does a couple of things.
Firstly it adds a test for a note whose original author has been deleted.
Secondly it corrects the test for whether to drop the first comment to align with what the note model does in the `comments` association so that the first comment is only dropped if the author was active because in other cases the model will already have excluded it. This primarily affects users in state `suspended` I think.
> Improvements for notes with deleted authors

- app/assets/javascripts/index/directions/fossgis_osrm.js
- app/assets/javascripts/index/directions/fossgis_valhalla.js
- app/assets/javascripts/index/directions/graphhopper.js
Untangling `FOSSGISOSRMEngine` and moving from `push`ing `for` loops to `.map()` for the other engines.
The three routing engines' code now follows a similar structure:
```js
function ...Engine (id, ...) {
function _processDirections(...) {...}
return {
...,
getRoute: function (points, callback) {
data = {...};
return $.ajax({
...,
success: function // that calls the callback with _processDirections
});
}
};
};
```
Creating a conditional dev tools breakpoint and shoving it all in there.
> Refactor direction engines and unify structure

- config/eslint.js
- lib/tasks/eslint.rake
Following on from @AntonKhorev's observation in #5631 this moves eslint ignore rules to the configuration.
Instead of having the rake task select which files to check, we just check the whole tree and have eslint ignore third party files and generated files that we don't control.
> Move eslint ignore rules to the configuration file

- app/controllers/api/nodes/relations_controller.rb
- app/controllers/api/nodes/ways_controller.rb
- app/controllers/api/relations/relations_controller.rb
- app/controllers/api/ways/relations_controller.rb
Use subqueries to do the selection in one go in the database which also avoids to deduplicate in rails.
Also pushes all visibility filtering into the query.
> Use subqueries to find nested members more efficiently

- app/controllers/api/old_nodes_controller.rb
- app/controllers/api/old_relations_controller.rb
- app/controllers/api/old_ways_controller.rb
- app/views/old_elements/_actions.html.erb
- config/routes.rb
- test/controllers/api/old_nodes_controller_test.rb
- test/controllers/api/old_relations_controller_test.rb
- test/controllers/api/old_ways_controller_test.rb
- test/controllers/api/relations_controller_test.rb
- test/controllers/old_nodes_controller_test.rb
- test/controllers/old_relations_controller_test.rb
- test/controllers/old_ways_controller_test.rb
Declares `versions` resources with `show` action on these API paths: `node/:id/:version`, `way/:id/:version`, `relation/:id/:version`.
> Make API old element show paths resourceful

- app/controllers/application_controller.rb
- app/controllers/site_controller.rb
- app/views/layouts/_offline_flash.erb
- app/views/site/_not_public_flash.erb
- app/views/site/edit.html.erb
- config/locales/en.yml
- config/settings.yml
The current message doesn't say much about how long the api/db is expected to stay down.
on map layout:
on site layout:
> Add date and url settings for offline message

- test/controllers/api/old_nodes_controller_test.rb
- test/controllers/api/old_relations_controller_test.rb
- test/controllers/api/old_ways_controller_test.rb
- test/integration/node_versions_test.rb
- test/integration/way_versions_test.rb
The only non-resourceful thing in the elements API is `redact` action. However before I can do anything with it I need to take care of tests.
You'd expect controller action tests to first set up the state of the elements, then perform the request and finally check the response and the new state. Unfortunately tests for redacting/unredacting element versions don't do that. Instead of checking the state after the action they do new show/index requests and check responses to those. This is double-checking show/index actions for redacted/unredacted states which is already done. But what's worse, if I'm to move (un)redacting to a different controller, the test would check actions of different controllers. They'll become integration tests.
But wait, some would-be integration tests already exist …
> Create integration tests for element versions

- config/locales/en.yml
Fixed issue #5258 by adding `busway: "Busway"` into the highway section of en.yml. When querying features, busways no longer show the prefix "Yes".
> Added prefix for busways in en.yml

- test/controllers/api/old_nodes_controller_test.rb
- test/controllers/api/old_relations_controller_test.rb
- test/controllers/api/old_ways_controller_test.rb
This PR changes redact/unredact tests for the reasons stated in #5645.
Tests will have this structure:
```ruby
node = create(:node, :with_history, :version => 2)
old_node = node.old_nodes.find_by(:version => 1)
redaction = create(:redaction)
auth_header = ...
post node_version_redact_path(*old_node.id), :params => { :redaction => redaction.id }, :headers => auth_header
assert_response ...
assert ... old_node.reload.redaction
```
Element redaction property is checked after every response. Previously it wasn't checked after failed responses.
> Refactor API old element redaction tests

- app/controllers/api/notes_controller.rb
- app/models/note.rb
- db/migrate/20250206202905_add_text_index_to_notes.rb
- db/structure.sql
PR updates notes filtering (querying) to search for query text in both note comments and note's description.
Using automated tests before and after migration plus manual tests before and after migration.
> Updates notes filtering to search description too

- app/assets/javascripts/index/directions.js
- app/assets/javascripts/index/directions/fossgis_osrm.js
- app/assets/javascripts/index/directions/fossgis_valhalla.js
- app/assets/javascripts/index/directions/graphhopper.js
- test/system/directions_test.rb
Start to move from $.ajax to fetch with the thing I recently restructured.
> Get directions using fetch

- app/controllers/api/notes_controller.rb
Adds storing note's description, author_id and author_ip to notes table too when creating new note.
Automatic tests, manual testing before and after data migration.
> Adds storing note's properties to notes

- app/assets/javascripts/edit/id.js.erb
Splitting parameter population and assignment, enabling a singular later default zoom value definition.
A new take on what was dropped in #5597.
> Set iD map param with array

- app/assets/javascripts/edit/id.js.erb
The current version of iD (v2.31, before the fix for https://github.com/openstreetmap/iD/issues/10761: https://github.com/openstreetmap/iD/pull/10766), does not fully support `x-www-form-urlencoded` "query-style" strings in the hash: Specifically, spaces encoded as `+` will not be decoded back to ` `.
This workaround essentially temporarily reverts the behaviour of the website to the state before #5592, and can be dropped again with the next minor version upgrade of iD (`v2.32`).
> Workaround for iD "bug" #10761

- app/abilities/api_ability.rb
- app/controllers/api_controller.rb
- config/locales/en.yml
- lib/oauth.rb
- test/abilities/api_abilities_test.rb
- test/abilities/api_capability_test.rb
- test/controllers/api/changeset_comments_controller_test.rb
This PR introduces `write_changeset_comments` OAuth scope that allows creating changeset comments (and hiding/unhiding them for moderators). This is a subset of what `write_api` allows.
`write_api` still works as before looking from outside. Internally it's translated to `write_changeset_comments` and `write_map`. `write_map` is not exposed anywhere, it's only known to `ApiController` and `ApiAbility`. Doorkeeper doesn't know about it. Later it can be added as a selectable scope, but that would require updating cgimap.
Fixes #2631.
> Comment changesets scope

- app/controllers/api_controller.rb
Unreachable because if there's no `doorkeeper_token`, there's also no `current_user`.
This is the only place in the api where `current_user` is set:
https://github.com/openstreetmap/openstreetmap-website/blob/f5af8befa9ffe0c95f4a3c58d2fbb63a2e971ab0/app/controllers/api_controller.rb#L105
> Remove current_user branch from ApiController#deny_access

- app/controllers/api/notes_controller.rb
Previously it was possible to create a note while authorized but having no write_notes scope. The scope check was added to fix #4362.
Currently it's not possible to create notes in this manner and there's a test for that:
https://github.com/openstreetmap/openstreetmap-website/blob/f5af8befa9ffe0c95f4a3c58d2fbb63a2e971ab0/test/controllers/api/notes_controller_test.rb#L233-L242
> Check user instead of scope when getting note author info

- app/assets/javascripts/index.js
- app/assets/javascripts/index/history.js
- app/assets/javascripts/index/layers/data.js
- app/assets/javascripts/index/layers/notes.js
- app/assets/javascripts/index/query.js
- app/assets/javascripts/index/search.js
- app/assets/javascripts/leaflet.map.js
Moves all AJAX requests that don't need OAuth to fetch. (except Matomo as this fetches a script)
Logpoints and quite a bit of erratic map movement to check for aborts
> Transition more requests to fetch

- app/abilities/api_ability.rb
- app/controllers/api/user_blocks/active_lists_controller.rb
- app/controllers/api_controller.rb
- app/views/api/user_blocks/_user_block.json.jbuilder
- app/views/api/user_blocks/_user_block.xml.builder
- app/views/api/user_blocks/active_lists/show.json.jbuilder
- app/views/api/user_blocks/active_lists/show.xml.builder
- app/views/api/user_blocks/show.json.jbuilder
- config/routes.rb
- test/controllers/api/user_blocks/active_lists_controller_test.rb
See https://community.openstreetmap.org/t/is-this-the-same-person/123461/30
Problem: how an app accessing OSM API can determine that the current user is blocked, and tell them that they're blocked? Here's a method I came up with: https://github.com/streetcomplete/StreetComplete/issues/6062#issuecomment-2565450817. It has two hacky steps:
1. accessing `/api/0.6/user/#id` without auth header, because `/api/0.6/user/details` is inaccessible while blocked
2. generating a login link with referrer pointing to the block list
Some people access an endpoint that is known to generate 403 errors only when blocked instead of **1**, but there's no guarantee that things will stay that way. `/api/0.6/user/#id` may also become inaccessible without authorization in the future. This PR does **1** in an …
> API active blocks list

- app/abilities/ability.rb
- app/controllers/accounts/pd_declarations_controller.rb
- app/controllers/accounts/terms_controller.rb
- app/controllers/users_controller.rb
- app/views/accounts/edit.html.erb
- app/views/accounts/pd_declarations/show.html.erb
- app/views/accounts/terms/show.html.erb
- app/views/users/new.html.erb
- config/locales/en.yml
- config/routes.rb
- test/controllers/accounts/pd_declarations_controller_test.rb
- test/controllers/accounts/terms_controller_test.rb
- test/integration/user_creation_test.rb
- test/system/account_pd_declaration_test.rb
See https://github.com/openstreetmap/openstreetmap-website/pull/4455#issuecomment-1899125291, https://github.com/openstreetmap/openstreetmap-website/pull/4455#discussion_r1509952021, https://github.com/openstreetmap/openstreetmap-website/pull/4455#issuecomment-2069941509 for reasons to remove the checkbox from the signup page.
The checkbox is confusingly placed right above the *Sign Up* button:
Users might think they have to check it in order to proceed, but they actually don't have to do it. If they check it accidentally and register an account, there's no way to undo it.
I also removed a similar checkbox from the terms page. That page is currently not accessible for new accounts because terms are accepted by signing up. But that's probably going to change because the terms page could be …
> Remove public domain checkbox from signup and terms pages

- app/assets/javascripts/leaflet.map.js
- app/assets/javascripts/leaflet.sidebar.js
This PR fixes multiple issues about the map resetting its position when opening various menus on mobile devices.
https://github.com/openstreetmap/openstreetmap-website/issues/4755
https://github.com/openstreetmap/openstreetmap-website/issues/991 (partly because the sidebar can still cover the selected object in the Map data layer)
...
1. Get rid of the hardcoded left sidebar width.
2. On mobile devices, use adjust the height, not the width of the map
<table>
<tr> 
<th>
Before
https://github.com/user-attachments/assets/9c283266-b43a-48d2-9f25-ffe73752c837
<tr> 
<th>
After
https://github.com/user-attachments/assets/9cf73154-c043-430a-a143-f8d47ad0f080
<th>
After with RTL
https://github.com/user-attachments/assets/ed973523-98d2-46a8-be2b-ca8619e1085f
</tr> 
</table>
> Fix left/right sidebar resizing on mobile devices

- lib/gpx.rb
Currently uploaded gpx files are unpacked and parsed each time the `points` method is called. This happens a dozen of times: once for storing the trackpoints in the db, once for generating a thumbnail and once for each frame of an animated trace image. Even if we don't mind reparsing the files over and over, there's another problem. I started adding parse error handling in #5226 and I want to handle one more error (invalid characters in xml), thus I want parse errors to happen in a predictable place.
To avoid parsing files again I store trackpoint coordinates while reading each file. These coordinates are later used to draw images.
> Process trace files once

- config/settings/test.yml
- test/application_system_test_case.rb
- test/teaspoon_env.rb
Addresses #5488 by providing a setting instead of workarounds such as modifying `test/application_system_test_case.rb`.
I'm also using these workarounds and it's annoying because you can accidentally commit them. But if there's a setting, I can put it in some file that's ignored by git, for example in `config/settings/test.local.yml` (assuming tests run in test environment; teaspoon tests by default don't but you can run them with `RAILS_ENV=test bundle exec teaspoon`).
> Add option to override Firefox binary used in system tests

- app/assets/javascripts/index.js
- app/assets/javascripts/index/changeset.js
- app/assets/javascripts/index/note.js
Fix for #865. Unfortunately, the code is slightly different when handling OSM objects (nodes/ways/relations), notes or changesets. I tried to make it a little bit more coherent by always using the `map.addObject({}, callback)` approach to zoom to the location only if the `hash` parameters had no location information.
> fix map panning to objects when url hash is not empty but has no map location

- app/assets/stylesheets/errors.scss
- app/views/layouts/_head.html.erb
- app/views/layouts/_meta.html.erb
- app/views/layouts/error.html.erb
You can debate what changes are needed on error pages.  #5130 does some, referring to #3532, but that issue proposes some things I wouldn't agree with.
For comparison here's what I'd change.
> Update error pages

- app/abilities/api_ability.rb
- app/controllers/api/user_blocks_controller.rb
- config/locales/en.yml
- config/routes.rb
- lib/oauth.rb
- test/controllers/api/user_blocks_controller_test.rb
This lets block users by id, which helps in case they frequently change their username.
> Add user block api call

- app/assets/javascripts/index.js
Long term we should fix the sidebar to use turbo but for now this fixes #5663.
> Prevent caching a partial XHR response as a full page URL

- app/abilities/ability.rb
- app/assets/javascripts/index.js
- app/assets/javascripts/index/home.js
- app/controllers/accounts/homes_controller.rb
- app/views/accounts/homes/show.html.erb
- app/views/layouts/_header.html.erb
- app/views/layouts/map.html.erb
- config/locales/en.yml
- config/routes.rb
- test/system/account_home_test.rb
This adds a home location page with its own URL similar to what's suggested in https://github.com/openstreetmap/openstreetmap-website/issues/670#issuecomment-31867047, without sidebar and extra controls. Instead of `/:username/home` I use the path `/account/home` because it's easier to implement, no need to check `:username`.
A link to this page is available on every other page with the user dropdown menu. This fixes #1810.
It's possible to leave this page for another map page. In this case the javascript controller removes the home location marker. This fixes #669 and #670.
> Home Location page

- config/locales/en.yml
- test/application_system_test_case.rb
- test/system/issues_test.rb
- test/system/user_signup_test.rb
In almost all tab navs we already use [title case](https://en.wikipedia.org/wiki/Title_case), and this PR changes the remaining few to match.
> Use title case consistently for nav tab labels

- app/views/accounts/edit.html.erb
- app/views/layouts/_header.html.erb
- app/views/users/show.html.erb
- config/locales/en.yml
- test/system/user_suspension_test.rb
It's hard to make a distinction between 'Preferences' and 'Settings' in some languages, and many other sites use the term 'Account' for things like changing email.
> Use 'My Account' for account pages

- config/settings/test.yml
- test/application_system_test_case.rb
- test/teaspoon_env.rb
Continues #5672.
System test normally run in a headless browser, which is what you want if you run the entire test suite. But when writing and running a single test, it's useful to see what's happening. This PR adds a setting to choose whether tests should run in a headless Firefox.
> Add option to use headless Firefox in system tests

- app/abilities/api_ability.rb
- app/controllers/api/changeset_comments_controller.rb
- app/controllers/api/changesets_controller.rb
- app/controllers/api/notes_controller.rb
- app/controllers/changeset_comments/feeds_controller.rb
- app/controllers/concerns/query_methods.rb
- app/views/api/changeset_comments/_changeset_comment.json.jbuilder
- app/views/api/changeset_comments/_changeset_comment.xml.builder
- app/views/api/changeset_comments/index.json.jbuilder
- app/views/api/changeset_comments/index.xml.builder
- app/views/api/changesets/_changeset.json.jbuilder
- app/views/api/changesets/_changeset.xml.builder
- config/routes.rb
- config/settings.yml
- test/controllers/api/changeset_comments_controller_test.rb
- test/controllers/api/notes_controller_test.rb
Similar to https://github.com/openstreetmap/openstreetmap-website/pull/4248, but for the api. This is the first part that doesn't require any db changes. The next step is to add searching by user who created the commented changeset, then it will be possible to have a user's discussed changeset list like on https://hdyc.neis-one.org/.
- There was a choice of route to add this request to, either `index` (used by changeset search), or `search` (used by notes search). I chose `index` because you like resourceful routes and there's no other obvious request to put at `index`.
- Common user, time interval from/to, limit methods moved to a mixin.
- Since `limit` parameter already existed for changeset comment feeds, added default/max limit settings like the ones for notes and changesets.
> Add changeset comment search api with filtering by author and time

- app/assets/javascripts/index/note.js
Fixes #5683 (a regression in #5679): the problem was that when clicking on a new note on the map, the URL hash with the `map` parameter is cleared somewhere before  `pushstate` gets called, resulting in the map to be panned in `map.addObject` during the `initialize` step. It's now solved by passing an additional parameter to `initialize` and only do the map centering there.
This also allowed to fix #648 via 793757a6f.
> don't re-pan the map when selecting another note that is already on screen

- app/models/user.rb
I think this should be reasonably safe - it will need three reports to trigger a suspension or possibly less if there are already links in the content adding to a score.
Given the negative influence of edits on the score it's unlikely that people reporting users for map spam will manage to trigger this, leaving the normal DWG management and edit rate limits to deal with those.
> Include spam reports on unresolved issues in the spam score

- app/assets/javascripts/index.js
Shows node versions like in #4930 but without complications https://github.com/openstreetmap/openstreetmap-website/pull/4930#issuecomment-2198493197 and without saving api calls.
> Display old node versions on map view

- app/controllers/reports_controller.rb
- app/models/user.rb
- test/controllers/reports_controller_test.rb
As suggested in #5676 this triggers a spam check on a reported user after the report is saved, as their score may have changed.
> Make reports trigger a spam check on the reported user

- test/application_system_test_case.rb
Make sure system tests clear deliveries before and after running as controller and integration tests already do.
Fixes #5687.
> Clear test deliveries before and after system tests

- .github/workflows/danger.yml
- .github/workflows/docker.yml
- .github/workflows/lint.yml
- .github/workflows/tests.yml
There's generally no point running on multiple versions as the important things like ruby are not the OS versions in any case and production runs on Debian now not Ubuntu.
> Use ubuntu-latest for all workflows

- test/controllers/accounts_controller_test.rb
- test/controllers/api/changeset_comments_controller_test.rb
- test/controllers/api/notes_controller_test.rb
- test/controllers/confirmations_controller_test.rb
- test/controllers/diary_comments_controller_test.rb
- test/controllers/follows_controller_test.rb
- test/controllers/messages_controller_test.rb
- test/controllers/passwords_controller_test.rb
- test/controllers/users_controller_test.rb
- test/integration/user_creation_test.rb
- test/system/user_email_change_test.rb
These were not needed at the end of most tests for quite some time, since rails clears them by default for controller and integration tests, and also no longer required in system tests after #5691
There's still some calls that could be removed, for example by also automatically clearing `job` tests and by slightly reworking one of the mega tests in the `passwords_controller_test`.
> Remove some unnecessary calls to clear the mail queue

- test/controllers/api/changesets_controller_test.rb
Make `assert_single_changeset` check attributes that are always present in changeset responses.
> Always check changes/comments counts in single changeset tests

- app/assets/javascripts/index.js
If we care about errors when using editors like Potlatch,
rc note loading gives an error in Potlatch anyway because Potlatch doesn't have the `import` command. In case of Potlatch there's no way to check what commands are supported. Potlatch won't even tell that it's Potlatch, unlike JOSM that sends this header: `Server: JOSM RemoteControl`. And we can't assume that it's Potlatch when there's no server header because we don't get to read the response as long as we make cors-avoiding requests (https://github.com/openstreetmap/openstreetmap-website/pull/3760).
The error message that is displayed when the note import fails is not helpful. It tells the user to check if the editor is launched and rc enabled. But we already know that it's the case because otherwise the first (`load_and_zoom`) …
> Don't display error messages when second scheduled rc command fails

- package.json
- yarn.lock
At least vscode (derivates) provide first class intellisense support out of the box with that.
before
after
> Add jquery editor support

- app/assets/javascripts/edit/id.js.erb
Fixes https://github.com/openstreetmap/iD/issues/10779, closes #5698
Before the regression from #5632, the location source table was:
typ |           |          | hash-loc | !hash-loc
:-: |  :------: |  :-----: | :------: | :------:
n/w |  data-loc |  map-obj | hash-loc | nil
rel | !data-loc |  map-obj | hash-loc | nil
gpx |  data-loc | !map-obj | data-loc | data-loc
nil | !data-loc | !map-obj | map-loc  | map-loc
I changed it to this:
typ |           |          | hash-loc | !hash-loc
:-: |  :------: |  :-----: | :------: | :------:
n/w |  data-loc |  map-obj | hash-loc | data-loc
rel | !data-loc |  map-obj | hash-loc | nil
gpx |  data-loc | !map-obj | data-loc | data-loc
nil | !data-loc | !map-obj | map-loc  | map-loc
And I took the opportunity to restructure the conditions in the spirit …
> Pre-center objects with embed-data

- test/controllers/api/changesets_controller_test.rb
Tags were tested in json responses but together with comments, however tests for comments already exist with various conditions (hidden comments, hidden comments shown to moderators).
Tags in xml responses weren't tested.
> Test changeset tags in api changeset show responses

- config/routes.rb
- test/controllers/api/changesets_controller_test.rb
- test/controllers/api/relations_controller_test.rb
Like #5591 but for changesets, with the same modification for `create` action.
> API changeset resources - index path

- app/assets/javascripts/index/directions.js
- config/locales/en.yml
Closes #5224 by adding a link below the instructions table to download the route as a geoJSON:
The functionality? Locally.
The translation? Changed on Thursday.
> Enable exporting direction paths

- app/views/changesets/index.atom.builder
- app/views/changesets/show.html.erb
- config/routes.rb
- test/controllers/api/changesets_controller_test.rb
- test/controllers/api/relations_controller_test.rb
Continues #5713 by declaring changesets resources with `show` and `update` actions.
> API changeset resources - show path

- app/controllers/users/lists_controller.rb
- app/views/users/lists/show.html.erb
- config/locales/en.yml
- test/controllers/users/lists_controller_test.rb
Extends the user list interface used by administrators to allow searching by name or email which will be one less thing I have to in database directly.
> Extend user list to allow searching by name or email

- app/abilities/api_ability.rb
- app/controllers/api/changesets/downloads_controller.rb
- app/controllers/api/changesets_controller.rb
- app/views/api/changesets/downloads/show.xml.builder
- app/views/changesets/index.atom.builder
- app/views/changesets/show.html.erb
- config/routes.rb
- test/controllers/api/changesets/downloads_controller_test.rb
- test/controllers/api/changesets_controller_test.rb
Continues #5717.
Creates `download` resources on changesets instead of `download` actions.
> API changeset download resource

- app/controllers/api/changeset_comments_controller.rb
- app/views/changesets/show.html.erb
- config/routes.rb
- test/controllers/api/changeset_comments_controller_test.rb
Paths are not changed because there was no `PUT .../create` for creating changeset comments.
The only thing that's going to look a little strange is the path helper. It's named `api_changeset_changeset_comments_path` with "changeset" twice. That's how rails normally names it because we have `Changeset` parent model/controller and `ChangesetComment` child model/controller, and `Changeset`+`ChangesetComment` gives `changeset_changeset_comments`. To avoid that it's possible to rename the child resources to just `comments` and get `api_changeset_comments_path` helper, however this name is already occupied by changeset comments that are not nested in changesets: #4359.
> Make changeset comment create action resourceful

- .github/workflows/danger.yml
- .github/workflows/lint.yml
- .github/workflows/tests.yml
- .rubocop.yml
- Dockerfile
- Gemfile
- Gemfile.lock
- INSTALL.md
- app/helpers/svg_helper.rb
- bin/setup
- lib/osm.rb
We are now running ruby 3.4 in production so there's no longer any need to keep 3.1 support and dropping it enables us to stop holding back several gems and opens the path to a rails 8 upgrade.
> Update minimum ruby version to 3.2

- app/assets/favicons/manifest.json.erb
I broke the webmanifest icon list by not removing gsub.
But I'm making up for it by adding an SVG icon.
> Fix webmanifest icon list

- app/assets/javascripts/index/directions.js
The listener is not going to be run once if it's constructed inside the `locateactivate` listener. It's going to be run however many times `locateactivate` happens.
Actually neither this custom event nor `locateactivate` is required, but that's for the next pull request.
> Register startinglocation listener as a named function

- app/assets/javascripts/embed.js.erb
- app/assets/javascripts/index.js
- app/assets/javascripts/index/changeset.js
- app/assets/javascripts/index/directions.js
- app/assets/javascripts/index/history.js
- app/assets/javascripts/index/note.js
- app/assets/javascripts/index/query.js
- app/assets/javascripts/leaflet.map.js
- app/assets/javascripts/login.js
- app/assets/javascripts/matomo.js
- app/assets/javascripts/osm.js.erb
- app/assets/javascripts/router.js
- app/assets/javascripts/welcome.js
- test/javascripts/osm_test.js
Currently we have in use:
- `location`
- `window.location`
- `document.location`
The only one that's missing is `window.document.location`. These are [mostly the same](https://stackoverflow.com/questions/2430936/whats-the-difference-between-window-location-and-document-location).
We can just use `location` everywhere because it's shorter.
> Use location instead of window.location and document.location

- CONTRIBUTING.md
See #5672.
It didn't take me long to forget how to run teaspoon, go to the docs, copy the command and see it fail.
> Set the environment variable in teaspoon example

- app/assets/javascripts/leaflet.share.js
We're supporting WebP format for map downloads now. The change is a left over from https://github.com/openstreetmap/openstreetmap-website/pull/5607#issuecomment-2660979843
> Added WebP as new output format for map download

- app/assets/javascripts/application.js
- app/assets/javascripts/auth_providers.js
- app/assets/javascripts/diary_entry.js
- app/assets/javascripts/edit/id.js.erb
- app/assets/javascripts/fixthemap.js
- app/assets/javascripts/index.js
- app/assets/javascripts/login.js
- app/assets/javascripts/matomo.js
- app/assets/javascripts/messages.js
- app/assets/javascripts/social_share_button.js
- app/assets/javascripts/user.js
- app/assets/javascripts/welcome.js
`$(document).ready(...)` is deprecated since jQuery 3.0, see https://api.jquery.com/ready/
> Replace $(document).ready(...) with $(...)

- docker-compose.yml
The 'version' top-level Docker Compose element is deprecated since April 2024: https://github.com/docker/docs/commit/007ac90154c05f34045f607631b93a95c81d4807#diff-948ba582fe1c0dd6e8a5446ed8d8831e8ff65d0df7552f0eaa22b9ff7945b3e3R7
On my Mac using the latest Docker Desktop app. I got no warnings and it still builds successfully!
> Remove obsolete element from docker-compose.yml

- app/assets/javascripts/application.js
- config/eslint.config.mjs
- package.json
- yarn.lock
Required to correctly translate tooltips in #5402.
Actually it's already required for "Show My Location" tooltips.
Adds pluralizers from [make-plural](https://github.com/eemeli/make-plural/) as recommended by [i18n-js docs](https://fnando.github.io/i18n/v4.5.1/classes/Pluralization.html). Not exactly like on that page because we're still using an older version of i18n-js which is [not compatible with the new one](https://github.com/fnando/i18n-js/blob/main/MIGRATING_FROM_V3_TO_V4.md).
I'm not sure if pluralization in i18n-js v3 is documented anywhere. [This comment](https://github.com/fnando/i18n-js/issues/133#issuecomment-41999391) has an outdated link to the source code, but I think the entire repository was overwritten since.
> Add pluralizers to I18n

- app/assets/javascripts/index.js
- app/views/changesets/show.html.erb
> Add permalinks to changeset comments

- app/models/note.rb
- test/controllers/api/notes_controller_test.rb
- test/factories/note_comments.rb
- test/factories/notes.rb
- test/models/issue_test.rb
- test/models/note_test.rb
- test/system/index_test.rb
- test/system/note_layer_test.rb
- test/system/report_note_test.rb
PR removes optional using of note's first comments records for retrieving note's description and author in Note model file. 
Also, adds note's initializing when created using `note_comments` factory by initializing note's `description`, `user_ip` and `user_id` from note's comment (this is used only when notes are created by `create(:note_comment, ...)`) in unit tests.
Automated unit tests and manual testing on previously created set of notes (with special cases).
> Removes optional using first comments records

- app/assets/javascripts/index.js
- app/assets/javascripts/index/directions-endpoint.js
- app/assets/javascripts/index/directions.js
- app/assets/stylesheets/common.scss
- app/views/directions/search.html.erb
- app/views/layouts/map.html.erb
- config/locales/en.yml
Other sidebar pages have at least a heading and some placeholder in their `.html.erb` template, for example [geocoder search](https://github.com/openstreetmap/openstreetmap-website/blob/84aa7f455ae58b4b051368e35dbc43f780b3aa0f/app/views/geocoder/search.html.erb). Directions search is the exception, it's template is [essentially empty](https://github.com/openstreetmap/openstreetmap-website/blob/84aa7f455ae58b4b051368e35dbc43f780b3aa0f/app/views/directions/search.html.erb). Instead everything is written by `directions.js`.
Here I'm moving the directions heading to `.html.erb`.
This is a prerequisite for:
- Also putting routing icons into the erb template. This allows to remove the routing sprite and its css where the icons are referenced by numbers instead of names, and remove the dark mode …
> Write directions sidebar header using .erb template

- app/views/changesets/_changeset.html.erb
Addresses https://github.com/openstreetmap/openstreetmap-website/issues/5329#issuecomment-2704353857, although it's not a dark mode issue and not a recent change issue. Contrast was low all along.
Before:
After:
> Increase contrast of comments/changes counters in history

- test/controllers/issues_controller_test.rb
Closes #4056. The issue was already fixed, this PR only adds a test.
> Test resolving deleted user's note issue

- app/models/note.rb
- app/models/trace.rb
- db/migrate/20250304172758_add_gpx_files_user_id_id_index.rb
- db/migrate/20250304172798_add_notes_user_id_created_at_index.rb
- db/structure.sql
This PR adds database indexes to improve query performance for the user activity feature as part of #5298. Specifically, it adds concurrent indexes on:
- `gpx_files` table: `[user_id, timestamp]` index to optimize retrieval of user's GPS trace uploads
- `notes` table: `[user_id, created_at]` index to optimize retrieval of user's note activities
These indexes will support efficient querying of user activities without table scans, improving performance for the activity feed implementation.
Testing was performed by:
1. Running the migrations locally to verify successful index creation
2.  Checking the database schema to confirm indexes are present
> Add date indexes on gpx_files and notes tables

- app/views/issues/_page.html.erb
- app/views/issues/index.html.erb
- config/locales/en.yml
- test/system/issues_test.rb
Issues have `updated_at` and `user_updated` attributes. They are updated separately, sometimes without new `user_updated` being written. This makes "Last Updated / (date) by (user)" statements as they are shown in issue tables possibly incorrect:
Various solutions were discussed, some in #3211, but it's still not obvious which one is the best. The simplest one however is to stop claiming that the user from `user_updated` did their update at `updated_at`. This can be done by displaying the user in another column:
The column title suggested by @SomeoneElseOSM was "last managed by" but I don't want to stretch the table too much horizontally. Or we might need a wider table.
> Create last managing user column in issues table

- app/views/changesets/_changeset.html.erb
Long usernames without spaces were causing flex container wraps, pushing comment/edit counts below.
Before:
After:
> Fix comments/changes counts wrapping on history pages

- app/assets/javascripts/index.js
- app/assets/javascripts/index/directions.js
- app/assets/javascripts/leaflet.sidebar-pane.js
- app/assets/javascripts/leaflet.sidebar.js
- app/assets/stylesheets/common.scss
- app/views/application/_sidebar_header.html.erb
- app/views/layouts/_sidebar_close.html.erb
- app/views/layouts/map.html.erb
- test/system/directions_test.rb
- test/system/index_test.rb
Previous version: #4825
The changes are:
- https://github.com/openstreetmap/openstreetmap-website/pull/4825#issuecomment-2123914398, light gray background when scrolled, but with a shadow instead of a border for some separation.
- https://github.com/openstreetmap/openstreetmap-website/pull/4825#issuecomment-2131233781, the transparent area around the button was supposedly suggesting that it's clickable, therefore I removed it. Now I'm using a smaller non-transparent area that is clickable.
So I went from a larger transparent area to a smaller area with a shadow to indicate that the button is floating above the scrolled sidebar content.
Looks as usual when the sidebar contents is not scrolled:
Gets a slightly gray background and a shadow when scrolled:
Focus:
Dark mode:
Right sidebar: …
> Sticky close button v2

- app/assets/javascripts/index/directions.js
- config/eslint.config.mjs
There was an issue #3888 that asked to make directions distances translatable. It was done, but not entirely. Step distances were still untranslatable after the issue was closed.
Before in Russian:
Notice that the total distance units are "км", but the first step has untranslated "km".
After:
---
I undid some of the changes from #5633 that made it difficult to find where strings like `distance_km` are used. To do that I had to disable `no-else-return` eslint rule introduced in #5643. This is not one of the [recommended rules](https://eslint.org/docs/latest/rules/).
> Translate step distance units

- app/assets/javascripts/application.js
- config/initializers/i18n.rb
A few fixes and cleanups for I18n fallback:
* Disable client side fallback in javascript that isn't doing anything as we only load one locale - note that in the embed view the story is different as we load all locales there.
* Drop an old monkey patch that no longer seems to be needed.
* Fix the Norwegian fallback to work - currently it is being overwritten after it is added.
> I18n fallback fixes

- app/controllers/issues/reporters_controller.rb
- app/controllers/issues_controller.rb
- app/models/issue.rb
Reports on `/issues/:id` weren't sorted in any particular order. This is usually unnoticeable because typically they come in the creation order from the db. But that doesn't always happen.
This PR sorts the reports by id explicitly.
I don't know if we need an index on (issue_id, report_id). If there aren't many reports per issue, maybe not.
Same thing is probably required for issue comments.
> Order issue reports by id

- app/helpers/issues_helper.rb
- app/views/issues/show.html.erb
- config/locales/en.yml
- test/helpers/issues_helper_test.rb
Allows to see if the reported item wasn't created/changed recently. For reported users shows only the account creation date.
Before:
After:
> Show dates of reported items on issue pages

- app/controllers/users/lists_controller.rb
- app/views/users/lists/show.html.erb
- config/locales/en.yml
- test/controllers/users/lists_controller_test.rb
This allows the user list that administrators use to be filtered by whether a user does, or does not, have edits as requested by @Firefishy.
> Allow user list to be filtered for the presence of edits

- app/views/layouts/_sidebar_close.html.erb
Sticky close buttons have a layer that covers their shadows when sidebars are not scrolled. That layer is slightly larger than it needs to be. It overlaps with the heading and can block out letters in the heading. I'm making the cover layer smaller in this PR.
Before:
After:
Actually with this PR the cover layer is slightly smaller than it needs to be to fully block the shadow, but hopefully it's unnoticeable. If it becomes a problem, I'll have to set sizes directly in css, currently they are set in Bootstrap units. There's also a tradeoff between not having this overlap and the heading width, given that the heading content is variable.
> Fix overlap between left sidebar heading and close button

- app/helpers/issues_helper.rb
- app/views/issues/show.html.erb
- config/locales/en.yml
- test/helpers/issues_helper_test.rb
In #5787 I appended `created on %{datetime_created} ...` to the reported item in the heading. That can't be translated correctly because I'm constructing a sentence and "created"/"updated" need to agree with the subject in grammatical gender etc. The entire subheading needs to be translated together.
I'm also removing the double "Note":
Before:
After:
> Convert reportable_dates helper into heading helper

- config/locales/en.yml
I've sent up this change again as I messed up the Git flow for my last PR. Hopefully this will not need any further changes!
This Pull Request is to tackle the grammatical mistake mentioned in Issue #5772. In particular, the use of "sign-in" and "log-in" as a noun in this context is incorrect, as it is inconsistent with the other verbs within the permission list.
Fixes:
- "Sign-in" has been changed to "sign in" (without the hyphen).
- "Log-in" has been changed to "log in" (without the hyphen).
Required citations, credited to @maro-21 in the comment of the original issue, are as follows:
- https://www.oxfordlearnersdictionaries.com/definition/english/sign-in?q=sign-in
- https://en.wiktionary.org/wiki/sign-in
- https://www.dictionary.com/browse/sign-in
- …
> Fixed the grammatical mistake regarding the hyphen in "sign-up" and "log-in" mentioned in Issue #5772

- app/assets/config/manifest.js
- app/assets/javascripts/heatmap.js
- app/assets/stylesheets/common.scss
- app/controllers/users_controller.rb
- app/views/users/show.html.erb
- config/locales/en.yml
- package.json
- test/controllers/users_controller_test.rb
- yarn.lock
This PR addresses #5373 by adding a heatmap visualization on user profile pages to display daily contribution activity over the past year. 
**Key changes include:**
- Added a heatmap container in the user profile view (`users/show.html.erb`).
- Implemented JavaScript logic (`heatmap.js`) using CalHeatmap to render the heatmap dynamically based on contribution data.
- Updated localization (`config/locales/en.yml`) to include tooltips and month/weekday labels for the heatmap.
- Added tests in `users_controller_test.rb` to validate heatmap data handling.
Screenshots:
- Verified heatmap rendering with mock data for different users and activity levels.
- Tested responsiveness and theme support (light/dark mode).
- Checked correct localization of tooltips, month names, and weekday labels.
- Ran …
> Add user profile heatmap visualization for contributions

- app/controllers/users/lists_controller.rb
- app/views/users/lists/_page.html.erb
- test/controllers/users/lists_controller_test.rb
Some fixes for the user list view:
* Fix a server error if the user hits confirm or hide without selecting any users
* Preserve the user and edit filters across a confirm or hide action
* Drop redundant parameters from a form URL that duplicate hidden fields
> User list fixes

- app/assets/javascripts/index/directions.js
Here's some strange behavior:
1. Zoom in close enough.
2. Build a route, like [this one](https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=48.861246%2C2.345002%3B48.862012%2C2.341391#map=18/48.861833/2.343210).
3. Look at the browser location bar. It's going to contain the coordinates of endpoints. Notice that they have 5-6 digits after decimal point.
4. Zoom out to see the entire planet.
5. Click *Go* to rebuild the route. This will zoom you back to the same route.
6. Look at the location bar again. Now the coordinates have only one digit after decimal point and they are the same for starting/ending points. That can't be right.
7. Click *Reload* and you'll be taken to some other place and the route will be gone.
The `OSM.cropLocation` that I'm removing (and whatever …
> Don't crop coordinates when replacing directions url

- app/assets/javascripts/index/layers/data.js
- app/assets/javascripts/leaflet.layers.js
- app/assets/javascripts/leaflet.map.js
- vendor/assets/leaflet/leaflet.osm.js
This PR addresses "Map Data checkbox: perhaps use toggle slider instead" issue mentioned in the https://github.com/openstreetmap/openstreetmap-website/issues/4931
Several changes were made to the data loading functionality:
1. Clicking "Map Data" checkbox will add loading spinner to the label. It will be shown until back end collects and returns all the information (see "Loading Video"). After all the information is returned, spinner will be removed.
2. After getting information and agreeing to show it on the map, rendering process will be asynchronous. Therefore, there will be no more browser or page freezes and it will have animation like visual (see "Render Video").
3. If user unchecks "Map Data" checkbox, removing process will be also asynchronous and there won't be any freezes. It …
> Map Data checkbox: perhaps use toggle slider instead

- app/assets/javascripts/leaflet.map.js
- test/system/browse_test.rb
Fixes #5798.
I see #5009 and its commit mentioning only "Map Data checkbox". The object layer is not related to that checkbox and the code that uses the object layer doesn't expect async loading.
> Disable asynchronous object layer loading

- app/views/changesets/_changeset.html.erb
Moves "Closed (date) by (user)" lines down slightly if necessary to align with edit counters.
Before / after for different users:
Before / after for a single user:
> Align bottoms of date-username-changeset_id and counters in history

- app/assets/stylesheets/common.scss
- app/views/layouts/_search.html.erb
- Changes search form to explicit display-flex, removing the need for col divs.
- Moves the directions form's routing markers inside the input field to be more compact.
before:
after:
and in rtl:
> Revise search forms

- app/abilities/api_ability.rb
- app/controllers/api/changeset_subscriptions_controller.rb
- app/controllers/api/changesets_controller.rb
- app/views/api/changeset_subscriptions/create.json.jbuilder
- app/views/api/changeset_subscriptions/create.xml.builder
- app/views/api/changeset_subscriptions/destroy.json.jbuilder
- app/views/api/changeset_subscriptions/destroy.xml.builder
- app/views/changesets/show.html.erb
- config/routes.rb
- test/controllers/api/changeset_subscriptions_controller_test.rb
- test/controllers/api/changesets_controller_test.rb
Similar to web changeset subscriptions https://github.com/openstreetmap/openstreetmap-website/pull/5535, but for the api.
Adds `/api/0.6/changeset/:changeset_id/subscription` path at which you can POST/DELETE to subscribe/unsubscribe.
> API changeset subscription resource

- config/initializers/selenium.rb
Firefox 136 has started binding an extra port at startup when running via selenium but unfortunately it always uses port 9222 which causes problems running tests in parallel as discussed in https://github.com/mozilla/geckodriver/issues/2218.
This monkey patches things to try and allocate unique ports.
I believe this is the cause of the sporadic test failures we've been seeing the last few days - on my machine it happens basically every time since 136 came out but I probably have much high parallelism than Actions.
> Monkey patch Selenium to allocate unique bidi ports

- app/assets/javascripts/heatmap.js
- app/assets/javascripts/index/history.js
- app/controllers/changesets_controller.rb
- app/controllers/users_controller.rb
- app/views/changesets/history.html.erb
- app/views/changesets/index.html.erb
- app/views/users/show.html.erb
- test/controllers/changesets_controller_test.rb
- test/controllers/users_controller_test.rb
- test/system/history_test.rb
Because navigating through user history is difficult, I wanted this: https://github.com/openstreetmap/openstreetmap-website/issues/5804#issuecomment-2726693156
This PR makes it that clicking on a nonempty calendar cell takes you to the corresponding day in the user's changeset history.
> Add links to days in user history from heatmap

- app/assets/javascripts/heatmap.js
Fixes #5802
Before when simulating some place in the US (Chrome dev tools > Sensors > Location):
After:
> Fix heatmap month titles in Western Hemisphere

- app/assets/javascripts/embed.js.erb
- app/assets/javascripts/leaflet.map.js
- app/assets/javascripts/osm.js.erb
- config/layers.yml
- lib/map_layers.rb
This PR expands on and closes #5352, building onto the `MapLayers` library and also reusing the keys for the embed layer selection (`leafletOsmId` instead of `layer`).
Only the difference to #5352
> Put api keys directly in js layer definitions

- app/assets/javascripts/edit/id.js.erb
This removes the workaround from #5661 that has become unnecessary with #5750
> Remove workaround for iD 2.31

- app/views/layouts/_search.html.erb
- Adds more space between Close and Reverse buttons. See "The close button is a bit too close the reverse directions button" in https://github.com/openstreetmap/openstreetmap-website/issues/3123#issuecomment-2726356151
- Places Close button exactly above Sidebar Close button.
> Move directions form buttons closer to edges

- config/initializers/selenium.rb
As pointed out in https://github.com/mozilla/geckodriver/issues/2218#issuecomment-2735625538 you can use port zero to ask Firefox to dynamically allocate a port which should make this more robust as well as much simpler.
> Switch to dynamic allocation for the Firefox bidi port

- app/assets/javascripts/index/history.js
- app/controllers/changesets_controller.rb
- app/views/changesets/index.html.erb
- test/controllers/changesets_controller_test.rb
- test/system/history_test.rb
If you get to the user's history page from the heatmap, it will start on a selected date. You can scroll down, press *Load more* and and load changesets that were created before the initially visible set. But what if you want to see changesets created after the date?
This PR adds a *Load more* button in frond of the changeset list, if there are any changesets that were opened after the ones in the list.
> Add 'Load more' button that loads newer changesets to history pages

- config/wiki_pages.yml
- script/misc/update-wiki-pages
This perl script was last run in #5668, which caused the links for some keys like [`host=*`](https://osm.wiki/Key:host) to disappear, because these pages were migrated from [`Template:KeyDescription`](https://osm.wiki/Template:KeyDescription) to [`Template:ChangesetKeyDescription`](https://osm.wiki/Template:ChangesetKeyDescription)[^1][^2].
This PR updates the script to support [`Template:ChangesetKeyDescription`](https://osm.wiki/Template:ChangesetKeyDescription), which is used by pages under the `Key:` namespace, and/or the `ChangesetKey:` namespace.
Ran the perl script and commited the relevant changes.
[^1]: [`Key:changesets_count` diff#2685844](https://osm.wiki/w/index.php?title=Key:changesets_count&diff=2685844&oldid=2685832)
[^2]: [`Key:host` …
> update-wiki-pages: process ChangesetKey template

- app/assets/javascripts/edit/id.js.erb
In some cases, an expired session only causes the window in the iframe to reload on the `/edit` page.
This fixes #5807 (the issue for that bug)
> Add reload on iframe redirect

- app/assets/javascripts/embed.js.erb
- app/assets/javascripts/id.js
Removes hard-coding of URLs, e.g. not forcing a protocol onto the user.
> Make URLs more relative

- test/system/directions_test.rb
Routing icons were updated to be referenced by names instead of numbers, but there was test code that still used numbers. This didn't affect the functioning of the tests because the icons weren't checked.
This PR updates the *straight routing stub* to use named icons:
> Update straight routing in tests to use named directions icons

- app/views/directions/search.html.erb
There's a pull request #5776 that claims to *reuse mirrored turn icons*, however most of the changes there are not related to mirroring.
This pull request keeps only the mirroring changes from #5776.
You can see all of the directions icons by adding the following test to `test/system/directions_test.rb` and running it:
```ruby
test "show all routing icons" do
visit directions_path
extra_steps = %w[
straight
slight-right right sharp-right u-turn-right
slight-left left sharp-left u-turn-left
roundabout
fork-right fork-left
merge-left merge-right
end-of-road-right end-of-road-left
exit-right exit-left
ferry
].map { |name| "[points[1], '#{name}', '#{name}', 0, [points[1]]]" }.join(",")
stub_routing <<~CALLBACK
const distance = points[0].distanceTo(points[1]);
const time = distance * 30; …
```
> Reuse mirrored turn icons

- app/assets/javascripts/edit/id.js.erb
- app/assets/javascripts/embed.js.erb
- app/assets/javascripts/fixthemap.js
- app/assets/javascripts/heatmap.js
- app/assets/javascripts/index.js
- app/assets/javascripts/index/changeset.js
- app/assets/javascripts/index/note.js
- app/assets/javascripts/osm.js.erb
- app/assets/javascripts/welcome.js
- test/javascripts/osm_test.js
Removes `OSM.params()` in favor of `new URLSearchParams(location.search)`.
Adds `location.hash` as a default parameter for `OSM.parseHash`.
> Remove OSM.params in favor of URLSearchParams

- app/assets/javascripts/heatmap.js
Changed heatmap color range interpolation.
That changes the heatmap to be not comparable from one user to another, but better shows the day to day changes of one user.
Runtime changes in devTools
fix #5831
> Change heatmap color to sqrt from 0 to max changes

- app/assets/javascripts/heatmap.js
In some languages month names when used inside dates may differ from month names when used alone as titles. `OSM.i18n.t("date.abbr_month_names")` gives you month names for dates. That doesn't work with calendar month titles.
Example in Russian:
"May" = "май"
"21 May, 2024" = "21 мая 2024"
You don't want "мая" as a title, you want "май".
Before:
After:
> Use Date().toLocaleString() to construct month titles

- app/views/changesets/show.html.erb
- app/views/notes/show.html.erb
- test/controllers/changesets_controller_test.rb
- test/controllers/notes_controller_test.rb
Our `/changeset/:id` and `/note/:id` pages have comments in the sidebar. Those comments are marked up as list items: 
```html
<ul>
<li id="c1">...</li>
<li id="c2">...</li>
...
</ul>
```
Turn out there's a drawback to that: list items redefine text alignment inside them. Normally you wouldn't notice that everything is either left-aligned or right-aligned in case of rtl. But if you want mixed ltr and rtl text inside, you'll have to override `text-align`. See https://github.com/openstreetmap/openstreetmap-website/pull/5835#issuecomment-2745310604, see "Add text-align: start; to the mx-2 class CSS." in #5785.
Another way to mark up comments is to use `<article>` elements. There are examples of that on [mdn](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/article) and in the [html …
> Put changeset and note comments in <article> elements

- lib/rich_text.rb
(the edit history of this comment contains some questions that are no longer relevant)
This PR adds `dir="auto"` to user-generated content that uses the classes in `lib/rich_text.rb`, such as changeset comments, map notes, and the discussions under them. It also applies a necessary CSS rule for text alignment on those discussions.
This would solve a significant portion of #3428. It *might* have some overlap with #3429, ~~but at a glance it doesn't seem like it~~. It seems some of the changes in that PR would have affected the same content, however they would have done so with less finesse.
I never used Ruby before (and technically, I still haven't... see "How has this been tested?"), so this change is entirely based on the documentation found …
> add dir="auto" to paragraphs in rich_text.rb

- app/helpers/user_helper.rb
Not in use since https://github.com/openstreetmap/openstreetmap-website/commit/f70edc02f086d97727453e738e9f0083c68ec706. Whatever it did would only apply to Gravatar images and not to other kind of images.
> Remove unused options argument from user_image_url

- app/assets/javascripts/index/history.js
- test/system/history_test.rb
The goal here is when viewing history to be able to go back to roughly the same place after visiting a changeset page. It works like this:
- when the changeset list is scrolled down and some item leaves the viewport, the current page location gets changed to include a `before=:changeset_id` parameter, `:changeset_id` being the id of the changeset that left the viewport
- when the changeset list is scrolled up, same thing happens with `after=:changeset_id`
- when the history page is visited and its url includes a `before` parameter, the sidebar is scrolled so the first item is at the top of the viewport
- when the history page is visited and its url includes an `after` parameter, the sidebar is scrolled so the last item is at the bottom of the viewport
With these changes you can open a …
> Rewrite history page url when scrolling

- app/controllers/confirmations_controller.rb
Fixed a minor typo in a comment to reflect correct spelling and proper noun usage. No functional changes to the codebase.
No tests were necessary, as this change only affects a code comment and does not alter runtime behavior.
> Fix typo in comment about Gravatar setting

- app/helpers/browse_helper.rb
- app/views/changesets/_paging_nav.html.erb
- config/locales/en.yml
We use counter badges in other places. We can use them on changeset pages in element headings instead of numbers in ().
Before/after:
> Show changeset element counts using badges

- Gemfile
- Gemfile.lock
We previously pinned to an old version for ruby 3.1 support, but that's no longer required since rails needs 3.2 anyway.
Fixes #5845
I'll follow up with the issue about why CI didn't catch this.
> Update strong_migrations to be compatible with rails 8

- .github/workflows/tests.yml
- db/structure.sql
Fixes #5847 by forcing migrations to run in test, and fixing some noise that had crept into the structure as a result of them not running.
> Test migrations

- app/assets/javascripts/index/note.js
- test/system/resolve_note_test.rb
There's no comment textarea on resolved note pages, but pressing *Hide* if you're a moderator still tries to read a value and submit it as a comment.
With this PR the value is read only if the textarea is present.
> Fix "undefined" comment when hiding resolved notes

- README.md
> Fix GitHub badges in readme

- config/settings.yml
- lib/rich_text.rb
- test/lib/rich_text_test.rb
#5855 replaces `wiki.openstreetmap.org` with `osm.wiki`, and now wiki link text has `... wiki/wiki ...` which looks redundant. Osm wiki is set up so that prefix is optional in most of the cases, that's why there's a proposal to remove the prefix: https://github.com/openstreetmap/openstreetmap-website/pull/5855#issuecomment-2758382889. When the prefix is actually optional is determined by mod_rewrite rules as I commented in https://github.com/openstreetmap/openstreetmap-website/pull/5855#issuecomment-2759174982. I don't want to reproduce those rules to check when it's safe to remove `/wiki`. Instead I'm using a simpler rule: `/wiki` can be removed if it's followed by `/` and an uppercase Latin letter, which is going to be true for most of the articles. Special pages skipped using …
> Remove /wiki prefix from wiki urls in linkify

- app/views/directions/search.html.erb
The way the directions icons are currently drawn, the diagonal arrows are a fair bit smaller than the arrows in cardinal directions. The size stays consistent when the arrows are instead drawn with a marker.
Compare the icons in this chart, where the old icon is red, the new one green, and the overlap yellow:
This requires the SVG element to be visible, so d-none was swapped.
in-browser
> Replace differently sized direction icon arrows with a marker

- app/views/directions/search.html.erb
Reverts #5866. Before replacing "differently sized direction icon arrows" it would have been preferable to figure out why they are differently sized.
Arrows after #5866 on 1x pixel density display:
The original arrows this PR restores:
> Revert "Replace differently sized arrows with a marker"

- app/assets/javascripts/diary_entry.js
- app/assets/javascripts/index/directions-endpoint.js
- app/assets/javascripts/index/directions.js
- app/assets/javascripts/index/home.js
- app/assets/javascripts/index/layers/notes.js
- app/assets/javascripts/index/new_note.js
- app/assets/javascripts/index/note.js
- app/assets/javascripts/index/search.js
- app/assets/javascripts/leaflet.map.js
- app/assets/javascripts/osm.js.erb
- app/assets/javascripts/user.js
- app/views/dashboards/_contact.html.erb
- app/views/dashboards/show.html.erb
OSM.getUserIcon() was used for much more than just the icons on the user page.
I've made it work with the icon paths already stored in the OSM object and made it compatible with the note icons to eliminate the `noteIcons` objects.
I previously included a variant of this in #5854, but I think it makes more sense as a separate PR.
> Consolidate leaflet marker creation in OSM.getMarker

- app/assets/javascripts/diary_entry.js
- app/assets/javascripts/index.js
- app/assets/javascripts/user.js
This is in addition to #5872 where I wrote `{ position }` instead of a longer `{ position: position }`.
> Shorten options of map controls

- app/assets/javascripts/osm.js.erb
- app/views/site/fixthemap.html.erb
- test/system/fixthemap_test.rb
Embed pages have links to the *fixthemap* page that have lat/lon/zoom params:
[Example link](https://www.openstreetmap.org/fixthemap?lat=53.25688279713156&lon=-1.4329004287719729&zoom=13)
*fixthemap* has an *Add a Note* section with a new note icon that is supposed to be a link:
But it's not a link because javascript writing it is broken. `zoom` is used as a string with `+` operator, concatenation happens instead of addition, and link generation fails.
This PR forces zoom to be a number inside `OSM.formatHash` which is used to generate a link.
Actually we don't need javascript to write new note links because lat/lon/zoom are available server-side, but I'm not changing that yet.
> Fix fixthemap note link

- app/assets/javascripts/index/history.js
- app/assets/stylesheets/common.scss
- app/views/changesets/index.html.erb
- config/locales/en.yml
- test/system/history_test.rb
Changes *Load more* buttons into links similar to those used for pagination.
Changes their text to *Newer/Older Changesets*, see https://github.com/openstreetmap/openstreetmap-website/pull/5812#issuecomment-2735280265.
Now these links can be copied and opened like any other links.
For example, you can middle-click a link to open the next page in a new tab.
> History page links

- app/assets/javascripts/index.js
- app/assets/javascripts/leaflet.locate.js
- app/assets/javascripts/user.js
There's a claim in #5752 that "Due to the nature of the leaflet locate plugin, that icon is done with ..." and then various approaches are used such as clip path and polygon in css instead of a regular svg. While true, this is easily fixable inside our `L.OSM.locate` control. But turns out that we don't use our own `L.OSM.locate` in `user.js`. That's because I wasn't paying attention to this file when doing https://github.com/openstreetmap/openstreetmap-website/commit/12a7c9d023bcca01657e357b2ed28cc6bcd20e06.
This PR makes `user.js` use `L.OSM.locate`.
> Use L.OSM.locate control in user.js

- app/assets/javascripts/index/history.js
- test/system/history_test.rb
The regular `/history` page shows changesets intersecting with the map view. To get them, the current map view bounds are sent as the `bbox` parameter. But the bound can be outside of [-180..180] longitude range, therefore also a `.wrap()` fix is applied. The fix itself is broken, see #5473 which removes it and implements support for longitudes outside of [-180..180].
Still, we don't need to send the `bbox` parameter with huge longitude values when the entire planet is visible.[^1] If there's no `bbox`, no filtering by `bbox` happens and all changesets are visible. This is what this PR does.
This is a partial fix for #3423 when the entire planet is visible. #5473 is still required for map views with the antimeridian that don't include the entire planet. But even without #5473 you'll be …
> Don't set bbox history param when the entire world is visible

- app/assets/javascripts/welcome.js
Go to `/welcome` and click *start mapping*:
What's going to happen is that if you didn't give the geolocation permission yet:
1. the permission dialog pops up
2. if you fail to react to it in four seconds, you get redirected to the map view
Four seconds is probably too short. And why do you need any timeout here? Supposedly this was a workaround for [a Firefox bug](https://bugzilla.mozilla.org/show_bug.cgi?id=675533) but it was fixed years ago.
This PR removes the timeout.
> Remove manual edit after 4-second timeout on welcome page

- app/views/site/welcome.html.erb
`/welcome` page has this section at the bottom:
Notice *the map* link. Now look at it in dark mode:
You can't see the link because this is a *primary alert*, the primary color is blue and the links are also blue.
Why is it primary-blue? It was made blue during a Bootstrap refactor in https://github.com/openstreetmap/openstreetmap-website/commit/f0ee117cffb37d36cc2fc0be198832358a451025. Previously it was *offwhite*. Dark mode didn't exist during that time.
This PR changes the color to secondary:
> Change "add a note" background to secondary on welcome page

- app/views/dashboards/_contact.html.erb
- app/views/dashboards/show.html.erb
- app/views/diary_entries/_diary_entry.html.erb
- app/views/diary_entries/index.html.erb
- app/views/issues/show.html.erb
- app/views/users/show.html.erb
We don't need [Bootstrap's clearfix class](https://getbootstrap.com/docs/5.3/helpers/clearfix/) because we're not using css floats anywhere.[^1] That includes user-provided richtext because we're removing `style` and `class` attributes.
[^1]: except on the *Export* page, see the next PR.
> Remove .clearfix from places without floats

- app/assets/stylesheets/common.scss
- app/views/site/export.html.erb
In the export box on the `/export` page we're positioning inputs using floats. Then we have to guard them with `/*rtl:ignore*/` in css. But actually we don't need any custom css here because we set `dir='ltr'` on the entire box. If we don't use any styles that mention left/right/start/end, `dir` will work as expected. Instead of left/right floats, I'm using flex with justify-content-between to push the inputs to the edges of the box.
> Use flex+justify instead of floats on export page

- app/assets/javascripts/index/layers/data.js
Look at data layer. Notice that everything is blue:
Now look at the `setStyle` call that I remove in this PR. Notice that the colors are supposed to be black, red, green. It's broken since https://github.com/openstreetmap/openstreetmap-website/commit/5e9ab5bc5edb63b7ab7719fa989a18f52e3637a2, but I'm not fixing it because those colors don't look very well over the tiles and everyone probably got used to blue.
The argument to `setStyle` is invalid; and when used on feature group layer, `setStyle` should be called after adding the geometry.
https://leafletjs.com/reference.html#featuregroup-setstyle
> Remove invalid setStyle from data layer

- app/assets/javascripts/leaflet.map.js
Full discussion here: https://github.com/openstreetmap/openstreetmap-website/pull/5009#issuecomment-2722980833 But I'll duplicate the comment here.
https://github.com/openstreetmap/openstreetmap-website/pull/5009 brought two problems:
1. When moving the map, a white flash occurs and all objects on the map are redrawn:
https://github.com/user-attachments/assets/3c87c769-174c-4513-a5be-115eb9517bb8
2. Rendering slowed down. What used to occupy ~400ms now occupies ~1.3s. Hiding a data layer was previously performed on ~100ms, now ~1.5s (!)
Both problems arise due to the fact that before that the redrawing of the map was performed only once, after the completion of the removal/adding of objects to the SVG-element of the map.
--
This PR only removes asynchronous rendering. The loader that …
> Disabling asynchronous Map data layer rendering

- app/assets/javascripts/index/layers/data.js
We have this bug in various places where AbortController is used. It happens like this:
1. you enable data layer and `getData()` is called
2. `getData()` checks if `dataLoader` is defined and it's not defined
3. `getData()` initializes `dataLoader` with a new `AbortController` and passes its signal to `fetch`
4. before the loading is finished you move the map and `getData()` is called again
5. `getData()` checks if `dataLoader` is defined, now it is
6. `getData()` calls `dataLoader.abort()` which schedules the abort event
7. `getData()` overwrites `dataLoader` with the second `AbortController` and passes its signal to the second `fetch`; the first `fetch` is still running
8. after the execution returns to the event loop, abort event happens and the first `fetch` is cancelled
9. `.finally` …
> Keep reference to AbortController on AbortError in data layer

- app/views/layouts/_header.html.erb
- test/system/account_rename_test.rb
When trying to rename a user account to an invalid name, the invalid name is shown in the upper right corner as if the rename already happened:
This PR shows the name before the invalid change:
> Show valid username in header when renaming

- Dockerfile
Updates the Dockerfile to use `COPY` instead of `ADD`. From [Docker's best practices doc](https://docs.docker.com/build/building/best-practices/#add-or-copy):
> You'll mostly want to use COPY for copying files from one stage to another in a multi-stage build.
and:
> The ADD instruction is best for when you need to download a remote artifact as part of your build.
Since we're just copying files, let's prefer `COPY`.
I rebuilt my docker container with these new changes and was able to successfully navigate the app locally.
> Prefer COPY to ADD in Dockerfile

- app/assets/javascripts/index/search.js
- app/controllers/geocoder_controller.rb
- app/views/geocoder/search.html.erb
- test/system/search_test.rb
Fixes #5859.
Also includes zoom value in reverse geocoding Nominatim link.
> Add viewbox param to Nominatim link in search results

- app/assets/javascripts/index/directions.js
- app/assets/javascripts/index/directions/fossgis_osrm.js
- app/assets/javascripts/index/directions/fossgis_valhalla.js
- app/assets/javascripts/index/directions/graphhopper.js
Writing step numbers is currently the responsibility of each routing engine:
But that shouldn't be the case. Writing the numbers outside would later help to stop constructing html by concatenation.
> Move directions step numbering out of engine-specific code

- app/assets/javascripts/index.js
The workaround was added in https://github.com/openstreetmap/openstreetmap-website/commit/9cc9a0098840363b6497337951b53aa583f4aa44. It uses [deprecated .focus() jQuery function](https://api.jquery.com/focus-shorthand/).
It's also not necessary because [browsers supported autofocus on input for a long time](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/autofocus#browser_compatibility). Except maybe on iOS but we may not want anything to happen on mobile devices. In fact I'm going to do another pull request that prevents virtual keyboard from popping up on certain focus operations.
> Remove search input autofocus workaround for old browsers

- app/assets/javascripts/index/new_note.js
Another autofocus-related change in addition to #5899.
Normally on map view pages we have the search input autofocused. But on the *Add a note* page it makes sense to focus on the note description input. Since it may be loaded in the sidebar after the regular page load, we're focusing with javascript instead of a html attribute.
Now try adding a note on a phone with a small screen. What's normally a sidebar now takes up the upper half of the screen. You get the lower half to see the map and to place the note marker. Except not really because the virtual keyboard shows up as soon as the description input gains focus, that is right away:
This PR adds [a workaround](https://gist.github.com/supertanuki/1f73f9aa33d5010bf07205804596e042) to suppress the initial focus from triggering the virtual …
> Avoid virtual keyboard when visiting new note page

- app/assets/javascripts/index/history.js
- app/controllers/changesets_controller.rb
- test/controllers/api/changesets_controller_test.rb
- test/controllers/changesets_controller_test.rb
- test/factories/changesets.rb
- test/system/browse_comment_links_test.rb
- test/system/history_test.rb
Fixes #3423.
> Issue: Only changesets from that very narrow gap are shown.
How narrow this area is depends on zoom and map view width. It's an area between wrapped left and (independently) wrapped right longitude bounds because:
> The bug is caused by Leaflet's method .wrap()
It's not Leaflet's method. Maybe it existed previously in Leaflet and was removed, but we added it again in https://github.com/openstreetmap/openstreetmap-website/commit/f612f573f92c524bbcf4b913e71c9f288383a845. Implementing wrap on `L.LatLngBounds` by wrapping its corners independently is not going to give correct results in a general case.
> Bit more sophisticated fix is to add client-side bbox validation where too large bboxes would be clipped from -180/180 meridian.
It's not difficult to write the logic without …
> Support unwrapped bbox values in changeset history queries

- app/assets/javascripts/index/directions-route-output.js
- app/assets/javascripts/index/directions.js
Previously I moved endpoints code out of `directions.js`, but there's still too much code.
This PR creates a module for valid route output which includes:
- total time/distance
- directions table
- download link
- link to the routing engine
- route geometry drawn on the map with hovers/popups
> Directions route output module

- app/assets/javascripts/index/history-changesets-layer.js
- app/assets/javascripts/index/history.js
Continues #5473 by fixing the rendering.
When anything is added to the map, its longitude could be as well (the original longitude) + n * 360. n is an integer and usually it's 0 but that doesn't work when looking at the map near the antimeridian. Here I'm picking such n for each changeset bbox that it's going to be at the closest location to the map view center.
> Render changesets on both sides of the antimeridian

- app/assets/javascripts/index/directions-route-output.js
- app/assets/javascripts/index/directions.js
- app/assets/javascripts/index/directions/fossgis_osrm.js
- app/assets/javascripts/index/directions/fossgis_valhalla.js
- app/assets/javascripts/index/directions/graphhopper.js
Much like in the API responses from GraphHopper or Overpass Turbo, this PR adds the credit information to the returned routes, removing the need to pass the `chosenEngine` to the `DirectionsRouteOutput`.
> Attach routing credit to route

- app/assets/javascripts/leaflet.key.js
- app/assets/javascripts/osm.js.erb
- lib/map_layers.rb
Links _key.yml_ to _layers.yml_ in the `MapLayers` module by putting a `hasKey` flag into the `LAYER_DEFINITIONS`.
This removes the need for `LAYERS_WITH_MAP_KEY` as the key button can now directly check `layer.options.hasKey`.
> Put map key presence in js layer definitions

- test/system/history_test.rb
The test from #5921 might have a timing issue when the map is clicked before the chagesets are loaded. This PR fixes it by asserting that there's a link to the changeset in the sidebar, which should wait for things to load and the link to appear.
> Wait for changeset link before clicking the map

- app/assets/javascripts/index/search.js
- app/assets/stylesheets/common.scss
- app/views/geocoder/results.html.erb
For spinners that appear after clicking this button in search results:
Removes a little bit of custom css.
> Change 'search more' spinner hiding css to hidden attribute

- app/assets/stylesheets/common.scss
- app/views/layouts/_content.html.erb
Removes some *Rules for non-map content pages*
> Remove custom position and margin css from .content-inner

- app/assets/javascripts/index/history-changesets-layer.js
- app/assets/javascripts/index/history.js
- app/assets/stylesheets/common.scss
On history pages, if you load many changesets and look at the map, it's difficult to find the corresponding changesets in the sidebar. The idea here is to color changesets differently, depending on whether they are above/in/below the sidebar viewport.
- The orange color that was previously used for all changesets is now used only for the ones in the viewport.
- The bluish ("colder") color is for older changesets below the viewport. If you see this color on the map, you know you have to scroll down to find the changeset in the sidebar.
- The reddish ("hotter") is for newer changesets. Actually the color became more brownish as I desaturated it because it has to beless saturated than the usual orange.
https://github.com/user-attachments/assets/0f6eb2d8-3b66-4890-ae23-9f160aadb50b
> Change colors of changeset bboxes when they enter/exit the viewport

- Gemfile
- Gemfile.lock
- app/controllers/application_controller.rb
- config/initializers/cors.rb
- test/integration/compressed_requests_test.rb
- test/integration/cors_test.rb
- test/integration/page_locale_test.rb
- test/teaspoon_env.rb
This updates to rack 3 which was blocked by omniauth being locked to 2.0 so this updates omniauth to 2.1 which unlocks the rack 3 update which in turn requires a puma update.
> Update to rack 3

- app/views/diary_entries/_diary_entry.html.erb
- app/views/diary_entries/_page.html.erb
- app/views/diary_entries/show.html.erb
- config/locales/en.yml
- lib/rich_text.rb
- test/system/diary_entry_test.rb
This PR is alternative to the https://github.com/openstreetmap/openstreetmap-website/pull/5103.
This PR addresses "Provide a summary view of recent diaries" issue mentioned in the https://github.com/openstreetmap/openstreetmap-website/issues/3887
Diary entries will be truncated after 1000 characters on the list pages. To avoid long diaries with pictures on the list page, every picture is handled as 500 characters. View of the diary entry details (show) page remains the same. "See full entry" button was added to the entry to explicitly mention that full entry is no more visible in the list and enhance UX. Fixes https://github.com/openstreetmap/openstreetmap-website/issues/3887
Screenshots:
> Provide a truncated view of recent diaries

- app/models/trace.rb
This refactors our trace file format detection so that we only do it in one and then adjusts that code to work around https://bugs.astron.com/view.php?id=643 which otherwise means that we fail to identify zip files on systems using version 5.46 of the file command.
> Workaround a bug in file 5.46

- app/assets/javascripts/index/history-changesets-layer.js
- app/assets/javascripts/index/history.js
A fix for ["Also, sometimes the hover fails and the bbox ends up not on top of other bboxes"](https://community.openstreetmap.org/t/better-osm-org-a-script-that-adds-useful-little-things-to-osm-org/121670/105), look at the animation of the lower bbox in the second image.
Sometimes there's a bunch of changesets on the same place. When one of them is highlighted, the orange bbox is visible as intended if it happens to be rendered above others:
If it's below, the highlight is less visible:
This PR moves the highlight to another layer rendered on top of normal bboxes. The highlight is non-interactve to avoid interfering with hover events on bboxes below.
> Changeset highlights in a layer on top of normal bboxes

- test/javascripts/osm_test.js
The teaspoon UI at localhost:3000/teaspoon currently gets broken because the entire DOM is discarded in tests.
This alters the tests to make the UI usable (although a leftover _osm_location cookie can cause tests to fail in there).
> Make teaspoon UI usable

- app/assets/javascripts/home_location_name-endpoint.js
- app/assets/javascripts/user.js
- app/controllers/profiles_controller.rb
- app/controllers/searches/nominatim_reverse_queries_controller.rb
- app/models/user.rb
- app/views/profiles/edit.html.erb
- app/views/users/show.html.erb
- config/locales/en.yml
- db/migrate/20241030090336_add_user_location_name.rb
- db/structure.sql
- test/controllers/searches_controller_test.rb
- test/system/user_location_change_test.rb
PR adds location name info on the user profile page. Location name can be changed from "Edit Profile" page either by manual typing or auto-filling according to the home location.
One column was added to the user table to save user's location.
JS logics are responsible for handling:
1) Delete-Undelete buttons interactions
2) Nominatim calls to locate home locations country name
3) Warning logic of the location name
> Add profile location

- app/assets/stylesheets/common.scss
Fixes #5947 by removing the broken reference to `--bs-btn-close-white-filter` and also the `filter: none` because both are already taken care of by Bootstrap's definition of `--bs-btn-close-filter`.
dev tools
> Remove unneeded and broken bootstrap close button theme overrides

- app/assets/favicons/manifest.json.erb
- app/assets/javascripts/index.js
- app/assets/javascripts/osm.js.erb
- test/javascripts/osm_test.js
This PR adds a geo protocol handler in the web manifest and the functionality for parsing in mapParams.
We can't directly parse it as it arrives wrapped in `encodeURIComponent`,
`geo:48.410,12.060?z=9` would be handled as https://www.openstreetmap.org/?geouri=geo%3A48.410%2C12.060%3Fz%3D9
~~This also includes a heuristic zoom fallback based on the precision.~~
With `navigator.registerProtocolHandler`, which can be included later to settle #1123 (I don't know where to put it).
> Add PWA geo protocol handler

- app/assets/stylesheets/common.scss
Update the close button light/dark theme fix from #4761 after Bootstrap v5.3.4 broke it. #5951 removed the fix as "unneeded".
Currently the fix is needed for *auto site theme in osm preferences* + *no system dark theme preference* + *dark banner theme*.
Black close button that should be white without the fix:
White close button with the fix:
Possible Bootstrap issue: https://github.com/twbs/bootstrap/issues/39481
> Update fix for close button inside themed elements

- app/assets/favicons/manifest.json.erb
I don't think the svg icon added in #5735 ever worked.
Before:
See that the path is wrong.
After:
> Fix svg icon path in manifest.json

- test/system/user_location_change_test.rb
The system test from #5302 sometimes fails:
```
Failure:
UserLocationChangeTest#test_User_can_change_their_location [test/system/user_location_change_test.rb:20]:
expected to find text "Test Location" in "OpenStreetMap\nEdit\nHistory\nExport\nGPS Traces\nUser Diaries\nCommunities\nCopyright\nHelp\nAbout\nUser 597\nUser 597\nMy Edits 0\nMy Notes 0\nMy Traces 0\nMy Diary 0\nMy Comments 0\nMy Account\nMapper since: April 26, 2025 Last map edit: No activity yet\nEdit Profile"
bin/rails test test/system/user_location_change_test.rb:8
```
It could be because it leaves the edit profile page before sending the update request, or because arriving at the view profile page before the changes propagate. But `visit user_path(user)` is unnecessary because clicking *Update Profile* redirects you to that …
> Don't visit profile page after tested profile location update

- app/assets/javascripts/login.js
- app/controllers/sessions_controller.rb
- app/views/sessions/new.html.erb
- config/locales/en.yml
- test/integration/login_test.rb
- test/system/user_login_test.rb
- test/system/user_signup_test.rb
Fixes #5441 by showing a warning as described in https://github.com/openstreetmap/openstreetmap-website/issues/5441#issuecomment-2563121432.
This is what you'll see if you visit the login page while already logged in:
Additionally there's going to be a link (styled as button) if there's a referer parameter and it's a "safe" referer (according to the `safe_referer` method of `ApplicationController`; the check looks a bit silly because it has to satisfy both RuboCop and Brakeman):
In the scenario described in https://github.com/openstreetmap/openstreetmap-website/issues/5441#issue-2758188137 that link should open the editor.
> Show warning when visiting login page while already logged in

- app/assets/javascripts/index/directions.js
Fixes #5959.
To reproduce the bug:
1. Add `sleep 5` or something similar to directions search action: https://github.com/openstreetmap/openstreetmap-website/blob/d54310c0dbf0c69ddbaeabfc93e415129dad6f66/app/controllers/directions_controller.rb#L7-L9 The goal is to make it take longer than the route request.
2. Do steps from #5959.
The fix here delays the route request to be performed after the sidebar finishes loading.
> Fix outputting route before directions sidebar is loaded

- app/assets/javascripts/index/directions-endpoint.js
Geocoding for route endpoints requests the default number of results, which is 10, but only uses the first one.
> Limit number of directions endpoint geocoding results to 1

- app/abilities/api_ability.rb
- app/controllers/api/changesets/closes_controller.rb
- app/controllers/api/changesets_controller.rb
- config/routes.rb
- test/controllers/api/changesets/closes_controller_test.rb
- test/controllers/api/changesets_controller_test.rb
Continues #5801.
Creates changeset close resource that responds to `PUT /api/0.6/changeset/:changeset_id/close`, which doesn't change the API.
I think `PUT` is wrong here because it should be idempotent. If executed twice, the result should be the same. And it's the same, changeset is closed, except for the response status. The second response is `Conflict`, but shouldn't it be `OK`? I'm not changing this yet, if this needs fixing, the backwards-compatible fix is to make the route respond to `POST`.
> API changeset close resource

- app/assets/javascripts/edit/id.js.erb
- app/assets/javascripts/osm.js.erb
The destructuring of parseHash.center makes using parseHash more unwieldy. Adding these parameters separately allows for easier integration elsewhere.
> Reorganize parseHash to avoid needing to destructure parseHash.center

- app/assets/javascripts/index/directions-route-output.js
- app/assets/javascripts/index/directions.js
- app/views/directions/search.html.erb
- app/views/layouts/_search.html.erb
- config/locales/en.yml
Previous attempt was in #1747. This PR is a complete rewrite.
The main difference is that #1747 tried to store in locale strings what kind of "imperial" units are in use, along with conversion factors. I don't think that was a good idea and I don't do that in this PR.
I also moved most of html writing from javascript to the erb template because it's easier to deal with flex containers and button groups this way. This is probably what @gravitystorm wants for all javascript page controllers.
> Add kilometers/miles switch to directions

- app/assets/javascripts/dashboard.js
- app/assets/javascripts/user.js
- app/views/dashboards/show.html.erb
- app/views/profiles/edit.html.erb
- test/system/dashboard_test.rb
Fixes #5971.
`user.js` does too many different things. It's better to take it apart and have smaller scripts included from all of the pages that currently include it.
This PR takes out dashboard-specific code from `user.js` and puth it into `dashboard.js`. This code doesn't include `OSM.HomeLocationNameGeocoder` which would fail on dashboard pages breaking the map:
> Move dashboard-specific javascript to dashboard.js

- app/assets/javascripts/index/history-changesets-layer.js
- app/assets/stylesheets/common.scss
This PR adds outlines on history pages for:
- bboxes of changesets inside the sidebar viewport
- highlighted bboxes
This attempts to address [the *hard to find the edit* / *color noise* problem](https://community.openstreetmap.org/t/better-osm-org-a-script-that-adds-useful-little-things-to-osm-org/121670/106).
I tried different colors for outlines. For example, I tried [black](https://community.openstreetmap.org/t/better-osm-org-a-script-that-adds-useful-little-things-to-osm-org/121670/108) for hover highlights. That makes them more noticeable, but the color itself looks too out of place. So temporarily I'm keeping all of them white.
When there's a lot of bboxes shown on the map, the in-viewport bboxes don't stand out enough from the rest:
With outlines they are more visible:
This is how …
> Add outlines for in-viewport changeset bboxes

- app/controllers/users_controller.rb
- app/views/users/show.html.erb
- config/locales/en.yml
- test/controllers/users_controller_test.rb
Adds dynamic headline to heatmap. Addresses https://github.com/openstreetmap/openstreetmap-website/issues/5810.
On my local machine I've verified that the header works as expected in the case that a user has 0, 1, and >1 contributions.
> Add headline to heatmap

- config/routes.rb
- test/controllers/api/capabilities_controller_test.rb
- test/controllers/api/permissions_controller_test.rb
Converts to resources everything in `routes.rb` that comes before changesets, except for the deprecated `/api/capabilities`.
> API versions, capabilities and permissions resources

- app/assets/stylesheets/common.scss
- Make newer changeset colors redder. The blue color of older changesets was [more noticeable](https://community.openstreetmap.org/t/blaue-bounding-boxes/128904) than the red of newer. It wasn't very red because I didn't want it to grab too much attention. But looks like it's better to make it slightly more red to increase the distance between it and the in-viewport orange.
- Make fill colors lighter. The highlight fill colors for out-of-viewport changesets are significantly darker than the color for in-viewport changesets. That's because I left there a temporary gray color before I decided on older/newer colors. Now after changing the newer color I can adjust the fill colors to be both lighter and closer to the newer/older colors.
Newer changeset before:
Newer changeset after:
Older …
> Adjust colors of out-of-viewport bboxes on history pages

- .rubocop.yml
- .rubocop_todo.yml
- config/initializers/wrap_parameters.rb
Going through the Rubocop config, I found a few exclusions that weren't necessary anymore.
> Remove a few exclusions from RuboCop configuration

- app/assets/javascripts/index/history-changesets-layer.js
- app/assets/javascripts/index/history.js
Let's suppose there's a large enough changeset:
You can zoom in and this changeset is going to cover the view completely:
If you click anywhere on the map you'll open this changeset, unless you click some other changeset. But that's not a good way to pick this changeset because you can even see it. Seeing it requires some part of its border to be in view and there isn't any. It also fills the entire view with its hover color, which even though transparent makes things more difficult to see.
This PR checks whether any part of a changeset border is visible and if none is, removes the area layer of the changeset. This disables hover on area for this changeset, making it easier to see and select other changesets that fit on the screen:
If you look at the edit history of some place and do …
> Remove area layers for changesets completely covering map view

- app/views/site/_add_a_note.html.erb
- app/views/site/fixthemap.html.erb
- app/views/site/welcome.html.erb
- config/locales/en.yml
We have two versions of the guide to notes: one with the link as an icon and one with the link as plaintext in a barely different color. I dropped the second version.
> Deduplicate note adding instructions

- app/assets/javascripts/fixthemap.js
- app/assets/javascripts/index/history.js
- app/assets/javascripts/welcome.js
- app/helpers/geocoder_helper.rb
- app/views/site/fixthemap.html.erb
- app/views/site/welcome.html.erb
There is not just a `formatHash` call in `fixthemap` but also one in `welcome` that can be written in the template.
Looked through all `formatHash` calls and cleaned up another call.
Builds on the commit from #5752 that fixes gravitystorm#257.
See also #5869.
> Clean OSM.formatHash calls

- app/assets/javascripts/index/history-changesets-layer.js
- app/assets/stylesheets/common.scss
Currently highlighted in-viewport bboxes change their color to more reddish. Changing their color made sense previously when only one orange color was in use. However now we have different colors, with red being for newer changesets. The problem is that if the highlighted changeset is located on a pile of newer changesets, it's made less noticeable by this color change. I think it's better to do highlights by other means without color changes. In this PR I'm making highlighted outlines bolder fo in-viewport changesets.
This should especially helpful for valious cases of color blindness.
Before / after for completely colorblind users:
But I had to do one more thing. Changing the color still made highlighted changesets stand out more among other in-viewport changesets, …
> Remove reddish color and add shadows to history changeset highlights

- app/assets/javascripts/index/history-changesets-layer.js
Previously strokes were suppressed using weight: 0 which made them have zero width. That produced some unnecessary svg attributes for strokes.
> Suppress strokes on bbox area layers using stroke: false

- app/assets/stylesheets/common.scss
Two `background-color` rules one after another is a [fallback for browsers not supporting rgba](https://css-tricks.com/rgba-browser-support/#aa-declaring-a-fallback-color) which you might want to use 15 years ago. It was added in https://github.com/openstreetmap/openstreetmap-website/commit/b9a19ab23a8dc63bc7c7f867e2ece6924319f0f2 and https://github.com/openstreetmap/openstreetmap-website/commit/dcbc42b1a485fdf39f5f11e37a628b383843e69b.
> Remove background-color rgba fallback from Leaflet controls

- script/deliver-message
- script/statistics
- script/update-spam-blocks
I tried running the statistics script because of #5994:
```
ruby script/statistics
```
and it didn't work until I made this change. `config/environment.rb` already uses `require_relative`.
> Use require_relative in scripts

- app/assets/stylesheets/print.scss
I merged #5752 which started to use svg `<defs>` more widely. They are in `<svg>` elements that still take space on the page unless hidden. We hide these images with `d-none` class. The problem is this is a Bootstrap class and we don't load Bootstrap for print styles. This is how the map looks in print view:
Notice the empty space above the map. I also did that hiding before with routing icons but it wasn't as noticeable because I set width/height on the svg defs image to small enought values.
This PR adds `d-none` class to the print stylesheet:
Another option could have been using `hidden` attribute, but it works slightly differently (looks like it prevents margin folding, so the svg still takes some space, even if used together with width=0 + height=0). And I'm not sure if it's …
> Add Bootstrap .d-none class to print styles to hide svg defs

- app/assets/stylesheets/leaflet-all.scss
Was added in https://github.com/openstreetmap/openstreetmap-website/commit/0d35a10a503f466f5cb7fe41fcb9e0c5167d9ee1, the commit message doesn't say why. There's a number of other Leaflet popup paragraph margin overrides. This one doesn't seem to be active in dashboard/directions/diary popups.
> Remove unused Leaflet popup paragraph margins css

- app/assets/stylesheets/common.scss
This min-height only affects dashboard popups of users with small avatars.
Before:
After:
It doesn't seem to make look anything better. It could have been useful in the past if floated images were used, but I don't thinnk they were when this css rule was introduced. It was first added in https://github.com/openstreetmap/openstreetmap-website/commit/a36f3558dd43dd5a598e36dd21fd5f7d2b4a94f5 and then changed to 50px in https://github.com/openstreetmap/openstreetmap-website/commit/40012189cb311510e545202d688294b9a8490ab1.
> Remove min height from dashboard map popups

- app/assets/stylesheets/common.scss
Works fine without this css rule:
because `.caret` is not used anymore. It was used explicitly before #2524, after that maybe it was in Bootstrap, but currently it isn't.
> Remove unused dropdown caret css

- app/assets/stylesheets/common.scss
- app/assets/stylesheets/leaflet-all.scss
Part of the css is in `leaflet-all.scss` where it partially overrides another part of the css from `common.scss`. This PR puts everything into `common.scss`.
The comment in `leaflet-all.scss` with https://github.com/openstreetmap/openstreetmap-website/pull/121#issuecomment-10206946 was about rules for images. It was added in https://github.com/openstreetmap/openstreetmap-website/commit/ed84516db2ccf634c8639d15fc39b1896f66cd18 where paragraphs had large left margins to make space for avatar images. That css was removed in https://github.com/openstreetmap/openstreetmap-website/commit/dc67e54958c50301cd0b8b0ada72936a4ae0b0f2 which switched to Bootstrap grid.
> Combine dashboard user popup custom css

- lib/locale.rb
The method that checks if a locale exists currently does it by accessing the translation and checking if exception is (not) thrown. It could use `I18n.exists?` instead.
> Use I18n.exists? to filter available locales

- app/assets/javascripts/index/directions/graphhopper.js
There are some minor updates to the latest GraphHopper API e.g. `vehicle` was deprecated a few years ago.
Also there is no longer a need for the parameter `turn_costs` (related #2695).
> minor changes to graphhopper routing

- .rubocop_todo.yml
- app/controllers/confirmations_controller.rb
- app/models/user.rb
The `gravatar_enable` method configures a gravatar for the user. Since this is business logic let's put it on the model instead of in the controller. This also opens the door to testing this method outside of the request/response lifecycle.
The existing test coverage in `ConfirmationsController` continues to pass.
> Move `gravatar_enable` method to User model

- app/assets/javascripts/leaflet.key.js
- app/assets/stylesheets/common.scss
- app/controllers/map_keys_controller.rb
- app/views/map_keys/show.html.erb
- config/key.yml
- config/locales/en.yml
Add links to map legends on external sites:
The key on osm.org may not be complete and maybe it doesn't even make sense to complete it, in case there's a lot of icons. This PR adds links to pages like https://www.cyclosm.org/legend.html.
I don't add `noreferrer` etc because we're already linking to these sites without these properties in map attributions, except for `:rel => "noopener"`.
> Add links to external map legends

- app/controllers/diary_entries_controller.rb
- test/controllers/diary_entries_controller_test.rb
It's possible to open the new diary entry link with parameters to initialize the form values like this:  
https://www.openstreetmap.org/diary/new?diary_entry[title]=Subject&diary_entry[body]=texttexttext
The only value that is not supported is entry language because it's overwritten by user preferences. But the prefences are supposed to set only the default language value judging by `diary.default_language` name, not to override explicitly specified values.
This PR allows to use the `diary_entry[language_code]` parameter to specify the language of a new diary entry.
> Allow new diary entry language to be specified in params

- app/controllers/diary_comments_controller.rb
- app/controllers/diary_entries_controller.rb
- app/views/diary_comments/new.html.erb
- app/views/diary_entries/_navigation.html.erb
- app/views/diary_entries/index.html.erb
- app/views/diary_entries/show.html.erb
- config/locales/en.yml
- test/system/diary_entry_test.rb
You open your diary, look at the top of the page and see something like this:
You click *New Diary Entry*, write an entry and publish it. Now you look at the top of the page again and see:
Where's the *New Diary Entry* link? The answer is, you're on a different page. Previously you were on your *index* page with several entries, but right after publishing you ended up on the *show* page of your new entry. And for whatever reason we don't show *New Diary Entry* on *show* pages. But I don't think there's a good reason, after all the RSS link for your entire diary is still there.
This PR adds *New Diary Entry* links on *show* pages of your own diary entries.
- includes *Rename entry to diary_entry* commit which turned out to be unnecessary for implementing this, but I think is a good idea …
> Add new diary entry links to user's own diary entry pages

- app/assets/config/manifest.js
- app/assets/javascripts/heatmap.js
- app/assets/stylesheets/common.scss
- app/controllers/users_controller.rb
- app/views/users/_heatmap.html.erb
- app/views/users/show.html.erb
- config/routes.rb
- package.json
- test/controllers/users_controller_test.rb
- yarn.lock
Ditching the ever-increasing amount of code required to accommodate CalHeatmap like in #5906 and going for a custom responsive solution.
Fixes #5905 and closes #5906. Also fixes #5810.
This also makes the history links of the heatmap tab-navigatable, even before hovering over each link.
> Prerender heatmap in partial

- app/assets/javascripts/index/directions-route-output.js
- app/views/directions/show.html.erb
- config/locales/en.yml
- Group unit translations by sending the scope with `translateDistanceUnits`
- Regroup `writeSummary` and `writeSteps` into `writeContent` and `writeStep`
- Unify unit toggling into `writeContent` with `data-unit` to simplify event binding.
locally
> Refactor directions output rendering and unit handling

- app/assets/javascripts/heatmap.js
- config/locales/en.yml
This uses a custom date format to drop the year from the heatmap tooltips, which doesn't really seem necessary when it only covers a single year - certainly GitHub doesn't show a year.
It also suppresses the leading zero from the day number, so overall "04 January, 2025" becomes "January 4" which seems nicer to me.
> Improve dates in heatmap tooltips

- app/views/dashboards/_contact.html.erb
- app/views/users/show.html.erb
- test/controllers/users_controller_test.rb
- test/system/report_diary_comment_test.rb
- test/system/report_diary_entry_test.rb
Replaces
```
user_path(user.display_name)
```
and likes with
```
user_path(user)
```
They mostly were replaced already but heatmap and friends-follows brought some back.
> Remove .display_name from user path helper calls

- app/assets/javascripts/heatmap.js
- app/assets/stylesheets/common.scss
- app/views/users/_heatmap.html.erb
I don't think that the goal of #5998 was changing colors. Color changes led to issues like https://github.com/openstreetmap/openstreetmap-website/pull/5998#issuecomment-2888521983 that make it impossible to see the days with edits for some editing patterns.
Before:
After:
---
To address this comment https://github.com/openstreetmap/openstreetmap-website/pull/5998#issuecomment-2887816546:
> And anything involving different light and dark color palletes requires watching the color scheme media query again, which I really want to avoid.
Most of watching was made necessary by cal-heatmap controlling the colors. Now that cal-heatmap is gone, `@include color-mode(dark) { ... }` css is enough to redefine colors for dark mode.
> Restore the original heatmap cell colors

- app/assets/stylesheets/common.scss
- app/views/browse/_common_details.html.erb
- app/views/changesets/_changeset.html.erb
Not part of #3429.
Fixes bidi bugs illustrated by images in https://github.com/openstreetmap/openstreetmap-website/pull/3429#issuecomment-2828944354.
Before:
After:
> Use <bdi> for comments in changeset history lists

- app/views/diary_entries/_profile_diaries.html.erb
- app/views/users/show.html.erb
- config/locales/en.yml
- test/controllers/users_controller_test.rb
Closes #6009.
Adds recent diary entries partial and displays it on the user profiles pages by implementing a responsive card layout. It takes 4 most recent diary entries by default. Each diary entry is now shown in a Bootstrap card that displays the title, truncated content, comment count, and creation date. The layout is responsive - showing as a single column on mobile and two columns on larger screens
Both testing manually to make sure it works along different screen sizes and adding tests to `users_controller_test.rb`.
> Add latest diaries partial to profile page

- app/assets/javascripts/user.js
When a new social link is added presumably the user is about to fill it in, so focus on it.
> Focus on newly added social link fields

- app/assets/stylesheets/common.scss
- app/views/social_links/_show.html.erb
> Invert social link icons in dark mode

- app/assets/javascripts/index/layers/data.js
This pull request adds human readable HTTP 509 rate limiting error messages.
Before:
After:
> Data layer: display text for http 509 rate limiting errors

- app/assets/javascripts/user.js
- app/views/profiles/show.html.erb
- config/locales/en.yml
- test/system/user_social_links_test.rb
Fixes https://github.com/openstreetmap/openstreetmap-website/pull/5439#issuecomment-2904227124
Here's how tabbing through social link inputs looks like:
https://github.com/user-attachments/assets/0bb01428-9b4c-4a27-9093-6d563c912d45
Notice that only the newly added *Remove* buttons are reachable. That's because *Remove* buttons for already existing links are not actually buttons. They are labels for hidden checkboxes styled as buttons.
This PR makes *Remove* buttons actual `<button>` elements. It also adds placeholders for link inputs, mainly because it's easier to test:
Also removes interpolation of strings from Translatewiki into html like this:
```html
<button type="button" class="btn btn-outline-primary col-sm-2 align-self-start">${OSM.i18n.t("javascripts.social_links.remove")}</button …
```
> Always use button elements for Remove social link buttons

- app/controllers/api/maps_controller.rb
Related to this issue: https://github.com/openstreetmap/openstreetmap-website/issues/6057
The exact details in the issue above. 
As changeset is required while rendering [here](https://github.com/openstreetmap/openstreetmap-website/blob/812557147870c02d5dadc22e42b1cf805006292f/app/views/api/nodes/_node.xml.builder#L7)
> Include changeset with node instead of loading it while rendering

- app/assets/images/social_link_icons/ogf.svg
- app/assets/images/social_link_icons/ohm.svg
- app/assets/images/social_link_icons/osm_forum.svg
- app/assets/images/social_link_icons/osm_wiki.svg
This is how some social link icons look on profile pages in Firefox:
For comparison in Chrome they look like this:
The icons are supposed to be grayscale, which is achieved by applying `<feColorMatrix>` filter to the entire `<svg>`. Firefox doesn't like that, maybe because `filter="url(#grayscale)"` references something inside the svg. Anyway there's a simpler way to define this filter without using `url`.
If icons are kept with colors, the dark mode filter would have to be changed because currently the icons look like this:
This PR replaces filter attributes with `filter="grayscale(100%) brightness(65%)"` and removes `<feColorMatrix>`. For OpenGeoFiction icon it sets colors directly.
After in Firefox:
> Social link icon filter

- .github/workflows/tests.yml
This implements the suggestion from #6022 to upload any screenshots from failing system tests as an artefact.
> Save any screenshots when tests fail in CI

- app/assets/javascripts/index/query.js
- app/helpers/browse_helper.rb
JS and Ruby side feature naming has been a bit different. Using a similar structure and logic, these parts can become nearly identical to read.
I also moved the standard address to i18n as some languages have it the other way round.
Closes #3447
> Use same logic for feature names

- app/assets/javascripts/index/query.js
- test/system/query_features_test.rb
When using *Query features*, enclosing features are sorted by their bounding box size. But the sorting is broken if the bounding boxes cross the antimeridian. This is noticeable in Russia. The entire Russia should be larger than some place inside Russia, therefore Russia should be at the end of the list. Instead Russia is at the start, because the bbox area is calculated as negative.
This is what Overpass returns as bounds for Russia. `maxlon` is smaller than `minlon`, going up to [this place](https://www.openstreetmap.org/#map=10/65.7679/-168.9787) and wrapping to a negative value:
```json
"bounds": {
"minlat": 41.1850968,
"minlon": 19.4041722,
"maxlat": 82.0586232,
"maxlon": -168.9769440
},
```
Same for Fiji:
Before:
After:
> Fix sorting of enclosing features with bounds including antimeridian

- app/assets/images/social_link_icons/ogf.svg
#6072 tried to change the color of the ogf icon to match the colors of other social icons. Except that wouldn't work as intended because the lines in the ogf icon are narrower than 1px. It already looks bleak, and with that color change it's going to be bleaker. There's not much to be done about it other than redrawing the entire icon. That's what this PR does.
Here's the ogf icon changes compared to the generic website icon.
Before (100% / 200%):
After (100% / 200%):
> Redraw OpenGeofiction social icon

- test/controllers/preferences/advanced_preferences_controller_test.rb
- test/controllers/preferences/basic_preferences_controller_test.rb
Avoid accidental changes to `I18n.locale` when a request is made as a logged in user with a different language preference.
Fixes #6075.
> Protect I18n.locale around tests which may change it

- app/controllers/profiles_controller.rb
- test/controllers/profiles_controller_test.rb
Go to `/profile`, add an empty social link, click *Update Profile*. You should see this:
But actually you'll get error 500.
When doing #6060 I forgot to update the template that's rendered when `current_user.save` fails from `:edit` to `:show`. Turned out we didn't have a test for profile update failures.
> Fix template rendered on profile update failure

- app/views/profiles/show.html.erb
According to https://github.com/openstreetmap/openstreetmap-website/pull/5987#issuecomment-2858925494, as @mmd-osm mentioned, it will be good if `Home Location Name` has maximum field length.
Changes length of the `Home Location Name` field to be stretched to the maximum length.
Manually. Tests are not affected.
> Maximum field length for Home Location

- app/assets/javascripts/index/query.js
Keeps the width of the antimeridian at 0.
> Fix antimeridian bounds size

- app/views/layouts/_flash.html.erb
I was redoing the language selector. I made it always update the language, even when the user is logged in, which means updating the preferences when a new language is picked. But updating the preferences generates a flash message which may overlap with map controls on small screens.
If the alert can be closed, the overlap is not a big problem.
> Make flash alerts dismissable

- app/assets/javascripts/user.js
- app/assets/javascripts/user_list.js
- app/views/users/lists/show.html.erb
Continues #5972 by moving things out of `user.js`.
> Move user list javascript to its own file

- app/controllers/concerns/pagination_methods.rb
- app/controllers/old_elements_controller.rb
- app/controllers/old_nodes_controller.rb
- app/controllers/old_relations_controller.rb
- app/controllers/old_ways_controller.rb
- app/views/old_elements/index.html.erb
- app/views/old_elements/index.turbo_stream.erb
- config/locales/en.yml
- test/system/element_history_test.rb
Paginates element history like changesets history, with *Older/Newer* buttons and 20 versions per page. Should help with history pages of elements with hundreds of versions.
Uses Turbo streams, no javascript required.
> Newer/Older Version buttons in element history

- app/controllers/layers_panes_controller.rb
- app/controllers/share_panes_controller.rb
- app/views/layers_panes/show.html.erb
- app/views/share_panes/show.html.erb
Closes #5616 as a partial spiritual successor of #4335
> Move layer definitions to pane controllers

- test/controllers/diary_comments_controller_test.rb
- test/controllers/diary_entries_controller_test.rb
You don't need to write comments about following the redirect if you actually `follow_redirect!`.
> Follow redirects to suspended page in spammy tests

- app/controllers/concerns/pagination_methods.rb
- app/helpers/pagination_helper.rb
- app/views/shared/_pagination.html.erb
- config/locales/en.yml
- test/controllers/diary_entries_controller_test.rb
- test/controllers/traces_controller_test.rb
- test/controllers/user_blocks_controller_test.rb
- test/controllers/users/diary_comments_controller_test.rb
- test/controllers/users/issued_blocks_controller_test.rb
- test/controllers/users/lists_controller_test.rb
- test/controllers/users/received_blocks_controller_test.rb
#4733 without "oldest"/"newest" button text on any screen width and with `title` tooltips.
Partly addresses #2387 ("No way to jump to the last page").
> Add oldest/newest links to shared pagination - with gaps around "newer" and "older" v2

- app/controllers/confirmations_controller.rb
- app/views/confirmations/confirm.html.erb
Closes https://github.com/openstreetmap/openstreetmap-website/issues/6130
Someone helped me debug https://github.com/openstreetmap/openstreetmap-website/issues/6130 and this change fixes the issue.
The OAuth process starts as a GET and becomes a POST by submitting the form below in JS automatically.
We lost the `referer` during this submit which means `confirmation_controller#confirm` never received the referrer to pass it through to the `/welcome` page so the button on that page could never change.
<details><summary>Some debug logging that shows that the referer is there at first and then disapears…</summary>
<p>
```log
2025-06-27 17:03:33 Started GET "/user/test23/confirm?confirm_string=eyJfcmFpbHMiOnsiZGF0YSI6WzMsIjA2MWU3YWNjZjIxYjI3MzVlYmY0MDUwMjk3ZmE1YzJmNjJiZWY4YTc3ZGEyNmMwYTYwMjlkNz …
```
> Preserve `referer` during oauth JS confirmation

- app/assets/stylesheets/common.scss
- app/views/browse/_node.html.erb
- app/views/browse/_relation.html.erb
- app/views/browse/_way.html.erb
- app/views/changesets/show.html.erb
`.browse-section` has some custom css associated with it but it's now outdated, including one issue mentioned in #6142, "the footer divider".
`.browse-node`, `.browse-way` and `.browse-relation` are not necessary after #6129 because they were only used in tests. `.browse-redacted` is already removed in #6129.
> Remove .browse-section and other css classes previously used for testing

- app/helpers/numbered_pagination_helper.rb
Mentioned in #6142, "Non-functional scrollbar".
This is for browsers that display scrollbars not only during scrolling. On Linux this is currently Chrome, but not Firefox.
If the version list is long enough to have the potentially scrollable part (currently >= 5 versions) but it fits in the sidebar entirely without scrolling, the scrollbar may still be visible.
This PR sets the horizontal overflow to `auto` instead of `scroll`, which hides the scrollbar when there's nothing to scroll.
> Make element version scrollbar appear only when necessary

- app/views/elements/show.html.erb
- app/views/old_elements/index.html.erb
- config/locales/en.yml
Adds a *Versions:* label above the versions navigeation list on element pages.
Fixes #6146.
Before for most of the users:
After:
Before for moderators:
After:
> Add versions label to breadcrumbs

- config/eslint.config.mjs
The arrow syntax should be equally as checked as the regular function syntax.
> Enable arrow-spacing ESLint rule

- app/views/users/new.html.erb
- config/locales/en.yml
Currently `layouts.tou` message (link label) is reused in two different sentences, i.e. in messages `accounts.terms.show.tou explain html` and `users.new.by_signing_up.html`. In some languages however the link label needs different declension in these sentences.
Here `users.new.by_signing_up.tou` message is added for use in the latter sentence in signup form. In English it's identical to previous `layouts.tou` message.
Similarly in #4936 two other link labels in the same sentence were already adjusted like this.
It also appears that at some point the terms of use link label already existed for this particular sentence, as still documented in translatewiki, but no one remembered to actually use it, and then it got removed as an unused message in b0ad96e.
> Fix message reuse for Terms of Use link in signup form

- app/controllers/accounts/terms_controller.rb
- app/views/accounts/show.html.erb
- config/locales/en.yml
- test/controllers/accounts/terms_controller_test.rb
- test/system/account_terms_test.rb
In case *Contributor Terms* or *Terms of Use* were updated since last agreeing to them, which is supposedly the case for many people, it's impossible to accept the new terms.
This PR makes it possible by
- telling when the terms were accepted in *My Account*
- linking to the *Terms* page
- disabling the checks if terms were previously accepted on the *Terms* page, which made it do nothing or redirect back to *My Account*
> Allow to agree to new terms if already agreed to old terms

- app/assets/stylesheets/print.scss
Fixes https://github.com/openstreetmap/openstreetmap-website/pull/6119#issuecomment-3059447787 by making Bootstrap modals hidden by default.
Similar to #5999.
> Add Bootstrap .modal class to print styles to hide language select dialog

- app/assets/stylesheets/.browserslistrc
While reviewing #6184 I discovered a problem with Firefox causing by autoprefixer adding a `-moz-placeholder` rule alongside the `placeholder-shown` rule.
The details are discussed in https://github.com/postcss/autoprefixer/issues/1533 but basically Firefox has supported `placeholder-shown` since version 50 but before that used `-moz-placeholder` and some other browsers based on old Firefox versions still do. The problem is that newer Firefox versions still recognise `-moz-placeholder` but at some point started treating it as `placeholder` and always matching whether or not the text is shown.
The solution is to drop support for one specific browser (KaiOS 2.5) which is the only thing in the default set actually triggering this. Newer versions (3.0, 3.1) of KaiOS remain supported.
> Drop KaiOS 2.5 support to fix placeholder styling in Firefox

- app/assets/javascripts/index/directions.js
- app/assets/javascripts/index/search.js
- app/assets/stylesheets/common.scss
Use the input state to toggle the describe_location button's visibility with CSS instead of manually updating.
> Lock describe_location button to query placeholder

- app/views/diary_entries/_diary_entry.html.erb
- test/system/diary_entry_test.rb
If a diary entry has floated contents, its controls and discussion may be displayed to the side of floated elements.
This PR clears floats in diary entry texts.
Example entry text to trigger the bug:
```
```
Before:
After:
Fixes #6186.
> Clear floats in diary entries

- app/assets/javascripts/index/element.js
- app/assets/javascripts/osm.js.erb
- app/assets/stylesheets/common.scss
- app/controllers/application_controller.rb
- app/helpers/browse_tags_helper.rb
- config/locales/en.yml
- config/settings.yml
- test/helpers/browse_tags_helper_test.rb
See original plugin [announcement](https://community.openstreetmap.org/t/announcing-human-readable-wikidata-browser-plugins-for-openstreetmap-org/108180/9) and [codebase](https://github.com/ZeLonewolf/osm-wikidata-greasemonkey) from @ZeLonewolf.
Updates the CSP and sets the requested paths from the settings.
Changes to the plugin are requesting more of the user's languages, getting the images more directly and replacing flexbox with float to accommodate longer descriptions better.
DevTools to test on real data.
> Integrate human-readable wikidata browser plugin

- app/assets/images/icons/comment.svg
- app/assets/images/icons/pencil.svg
- app/views/changesets/_changeset_line.html.erb
- config/initializers/inline_svg.rb
Makes the changeset icon definitions a bit more compact and doesn't redefine them in every single history entry.
> Simplify changeset icon definitions

- app/controllers/concerns/pagination_methods.rb
- config/routes.rb
- test/controllers/diary_entries_controller_test.rb
1. Go to the diary of someone who has a lot of entries written, for example https://www.openstreetmap.org/user/SomeoneElse/diary
2. Press the [*>>* button](https://www.openstreetmap.org/user/SomeoneElse/diary?after=0) to get to the earliest entries
3. Notice that it doesn't work
The actual bug existed before *>>* was added. *>>* here is just the easiest way to notice it.
The reason is that the `diary_entries` association of the user model has an order defined as `order(:created_at => :desc)`. When the pagination method sorts user diary entries by id, that order gets added after the existing order. The entries are still going to be sorted by `:created_at => :desc` first and by id next. The added order by id doesn't do anything, therefore ascending order by id doesn't work, therefore pages …
> Reorder paginated items

- app/views/dashboards/show.html.erb
When you don't have your home location set, this link in your dashboard leads to *Profile Description*:
It makes more sense to link to *Profile Location* instead.
> Change edit link to profile location in dashboard

- app/assets/images/about/community.svg
- app/assets/images/about/legal.svg
- app/assets/images/about/local.svg
- app/assets/images/about/open.svg
- app/assets/images/about/partners.svg
- app/views/site/_about_section.html.erb
- app/views/site/about.html.erb
- config/locales/en.yml
`_about_section.html.erb` was removed in #4868 due to the incompatibility with manually inlined icons.
With the icons inlined with the new gem, we can re-add the layout partial.
This slims #5938. See also the changed files in [this diff](https://github.com/openstreetmap/openstreetmap-website/compare/c36f09b28db7244066df53b9e52c7ab32a1693da..4f163a434f5b15c3ce4d602d87ed6119e3b3b221#diff-20b1b4068a14bbb692bf60b143f2cd17d495893dbd397e41eadeb732056341d7).
> Restore about section partial

- app/assets/javascripts/index/element.js
This avoids breaking page load in legacy browsers like Pale Moon by delaying the instanciation of Intl.DisplayNames until it's needed.
Closes #6207.
Sandboxed Pale Moon with a locally served site.
> Move Intl.DisplayNames inside renderWikidataResponse

- app/assets/javascripts/index.js
- app/assets/javascripts/leaflet.share.js
Fixes #6225 by passing the SVG marker for the `L.marker` that didn't have one already.
> Fix missing raster marker

- app/assets/javascripts/leaflet.maptiler.js
- config/layers.yml
In contrast to raster tile layers, the maxZoom for vector tile layers isn't determined by the served tiles (up to zoom level 14).
Hence, the maxZoom for vector tile layers is more of an integration decision than an inherent property of the tile layer itself.
Therefore, I argue, the maxZoom for vector tile layers should be set in the layers.yml instead.
Also resolves #6222.
> Bundle vector layer maxZoom definitions in layers.yml

- app/models/social_link.rb
`?` character needs to be escaped.
Before: 
After:
> Fix HDYC social link

- app/assets/javascripts/embed.js.erb
- app/assets/javascripts/leaflet.map.js
The marker is currently described as follows:
https://github.com/openstreetmap/openstreetmap-website/blob/9c8467e7ed9d38260077eaf64bb270b2acf18679/app/assets/javascripts/leaflet.map.js#L369-L373
Instead of 12 in `iconAnchor` it should be 12.5 because the marker is symmetrical. This is, of course, a small thing, but on Retina displays it can be noticed if, for example, the marker is set at the end node of the way.
The following screenshots can be reproduced using the following snippet for the browser console (more precisely, in the place of the code where the object of the current map is available):
```javascript
L.marker(([42, 42]), ({ draggable: false, icon: OSM.getMarker({ color: "var(--marker-blue)" }) })).addTo(map);
L.circleMarker(L.latLng(42, 42), { weight: 2.5, radius: 3, …
```
> More precise marker position

- app/assets/javascripts/leaflet.map.js
Since Leaflet's divIcon doesn't support putting elements in the shadow pane, all `OSM.getMarker` shadows are currently interactive.
This PR overwrites this behaviour.
> Overwrite marker shadow interactability

- app/assets/config/manifest.js
- app/assets/javascripts/embed.js.erb
- app/assets/stylesheets/embed.scss
- app/views/export/embed.html.erb
Since #6249 mentioned retina displays on the embed page, I changed my decision on whether to put the SVG marker there too.
This also already overwrites the interactivity for the marker, which is tackled by #6250 for the main page.
> Use SVG marker in embed

- app/assets/javascripts/download_util.js
- app/assets/javascripts/index/export.js
- app/assets/javascripts/leaflet.share.js
- app/views/site/export.html.erb
- config/locales/en.yml
Map XML download currently has a few issues, such as a button staying in disabled state after a download, or error messages that are shown on a blank page.
Applying the same concepts as in #6192, this PR aims at making the download a bit more robust and user friendly.
We have a bit of code duplication here, and it would probably make sense to move downloadBlob, handleExportError and  turbo:submit-end handler to a common file. Any ideas?
> Map XML download with Turbo

- app/assets/javascripts/leaflet.map.js
- app/assets/javascripts/leaflet.share.js
- config/eslint.config.mjs
- test/javascripts/osm_test.js
Only very few affected gaps, none of which looked like it was needed for contextual separation.
> Lower max allowed blank line count

- app/assets/javascripts/index/search.js
- app/assets/stylesheets/common.scss
This PR improves the visualization and interactivity of search results in the sidebar and map.
- Search result entries now have permanent map markers (instead of hover-only).
- Each marker is assigned a unique color based on the golden angle[^1], improving distinction even with many results.
- List entries visually match their corresponding markers via a colored border (`--marker-color`).
- Hovering over a list entry highlights the marker, and vice versa.
- Clicking a marker forwards that to the associated list entry.
- Refactored fetch logic into a reusable `fetchReplace()` function.
This touches a multitude of issues, see the list at https://github.com/openstreetmap/openstreetmap-website/issues/872#issuecomment-2588598803.
[^1]: Why this way? This approach scales better for arbitrary …
> Make search show multiple markers

- app/assets/javascripts/index.js
SVG anchors don't have the URL properties, which forces a page reload. This can be avoided by getting the properties from the href.
> Make handler able to handle SVG links

- app/assets/stylesheets/common.scss
- app/views/layouts/_header.html.erb
- app/views/layouts/_select_language_button.html.erb
Aligning the buttons with flexbox means they move up a pixel or two.
The locale selector button adapts its height to the available space, now 35px high instead of 36.5px.
Setting the menu item stroke and width with the Bootstrap colors (after inlining it) removes the need to invert it.
Closes #6052.
> Remove hard-coded stuff in header

- app/assets/javascripts/download_util.js
- app/views/layouts/_header.html.erb
- config/locales/en.yml
For better UX consistency, this PR replaces alert() by a centered Bootstrap modal window. It's currently used for map export messages only.
Before:
After:
> Bootstrap modal instead of alert()

- app/views/site/_id.html.erb
Pressing the down arrow key will sometimes scroll the parent element of the iframe, since it generates an inline box with some whitespace below. This parent element having overflow: hidden meant that it was impossible to scroll deliberately and I would be stuck with a white gutter on the bottom of the viewport for the remainder of my editing session.
Instead of overflow: hidden, give the iframe display: block to avoid generating an inline block.
Manually in Firefox and Chrome.
> Add display:block to the editor iframe

- docker-compose.yml
Configures the `web` service in `docker-compose.yml` file to allow for interactive debugging. `tty` allocates a pseudo terminal while `stdin_open` runs the container with stdin. Running `docker attach WEB_CONTAINER_ID` connects to the running container where the debugger can be interacted with.
One alternative is to run `docker-compose run --rm --service-ports -it web bash` and then `bundle exec rails s -p 3000 -b '0.0.0.0'` inside the container. However, I think leaning into `docker-compose.yml` makes sense here — we get consistent terminal behavior as a default when running `docker compose up` and `docker attach`. 
I ran `docker-compose up` and then in a separate terminal ran `docker attach WEB_CONTAINER_ID`.  When I hit a `debugger` I can then step through the code.
> Support interactive debugger with docker-compose

- app/assets/javascripts/index/history-changesets-layer.js
- app/assets/javascripts/index/layers/data.js
- app/assets/javascripts/index/layers/notes.js
- app/assets/javascripts/index/search.js
- app/assets/javascripts/router.js
Yet another PR for click handling.
This fixes #6264 and probably solves #6276 too, but due to the nature of that issue, I haven't been able to test that.
In contrast to #6267, this approach does not make assumptions about what modifiers do.
It also doesn't make assumptions about the event type. Perhaps it should.
> Rework map element click handling

- config/ui_languages.yml
This language arrived from Translatewiki in https://github.com/openstreetmap/openstreetmap-website/commit/bae910cf844ede7c23d20c6b51e2f844be9b10dc and broke tests.
> Add Arpitan to ui languages list

- app/views/layouts/_header.html.erb
- config/locales/en.yml
This string doesn't need to be in javascripts because we're not placing it in javascript. We don't need to send it again along with other js i18n strings.
> Move Bootstrap modal ok string out of javascripts

- app/assets/stylesheets/common.scss
Closes #6301 by restoring the behaviour prior to #6271.
> Fix erroneously collapsed CSS rule

- app/models/changeset.rb
- test/models/changeset_test.rb
Optional part of https://github.com/openstreetmap/openstreetmap-website/pull/6299.
That PR deals with pages of elements changed in a given changeset. We need to know the total number of elements and derive the total number of pages. Currently we're just counting them all with sql `COUNT(*)`. But we don't need to do it for new changesets because we have per element statistics. See https://github.com/openstreetmap/openstreetmap-website/issues/5758#issuecomment-2781054236.
This PR adds some changeset model methods for easier access to number of changed nodes/ways/relations.
> Changeset num_changed_(element type) methods

- config/eslint.config.mjs
- package.json
- yarn.lock
Previously we [picked javascript-only package of stylistic plugin](https://github.com/openstreetmap/openstreetmap-website/pull/5557#discussion_r1941580714) but now they [deprecated it](https://eslint.style/guide/getting-started#plugin).
> Migrate from @stylistic/eslint-plugin-js to @stylistic/eslint-plugin

- app/assets/javascripts/index/layers/data.js
This PR enables map data display across the antimeridian. It splits up the /map request into two requests if needed.
Depending on the current map center,  cloned nodes and ways with +/- 360 offset are added to the list of features. This is described in more detail here: https://stackoverflow.com/a/54709437/3501889 + https://stackoverflow.com/a/38824652 by one of the main Leaflet contributors.
Before:
After:
> Antimeridian map data display

- Gemfile
- Gemfile.lock
The file_exists gem [was originally added](https://github.com/til/openstreetmap-website/commit/c68fa8f8f5a89213aa22920edc72170093c5abbe) to support `File.exists?`, which was deprecated in Ruby 3.2 but still used by version 0.4.7 of the oauth gem. Since `File.exists?` was removed in version [0.5.0](https://github.com/oauth-xx/oauth-ruby/releases/tag/v0.5.0) of the oauth gem (see commit [here](https://github.com/ruby-oauth/oauth/pull/106/files)) and we are on 1.1.0, the dependency is no longer needed and can now be removed.
The tests pass. I was also able to navigate the app after this change.
> Remove `file_exists` gem

- .github/workflows/danger.yml
- .github/workflows/docker.yml
- .github/workflows/lint.yml
- .github/workflows/tests.yml
Lock GitHub Actions dependencies to specific version SHAs for security and predictability. Doing so is a best practice as we then know exactly which version of a given dependency is being used. Without locking to SHAs, Actions will simply use whatever latest version is available for the given specified version, usually a major such as "v4", leading to "silent bumps" at the GitHub Action runtime level.
Locking to SHAs will also allow us to receive patch and minor level dependency upgrade PRs as opposed to, in most cases, just bumps for major versions.
CI and Danger runs will prove if these changes are proper or not as they only affect GitHub Actions.
For reference here are the GitHub Actions dependencies releases so we can check the SHAs.
- …
> Lock GitHub Actions dependencies to SHAs for security and predictability

- INSTALL.md
In INSTALL.md, within the Manual Installation Guide section:
```
- export PATH=/Applications/Postgres.app/Contents/MacOS/bin:$PATH
+ export PATH=/Applications/Postgres.app/Contents/Versions/latest/bin:$PATH
```
…/Contents/MacOS/bin was the path before Postgres.app 9.2. The CLI tools now live under Contents/Versions/[version]/bin with a stable Versions/latest/bin symlink. The current path in INSTALL.md can lead to psql not being found.
Docs change only. I verified locally on macOS by trying both paths and confirming psql only resolves from …/Versions/latest/bin.
> Fix Postgres.app PATH on macOS

- Gemfile
- Gemfile.lock
Ruby has shipped with the default JSON gem since 1.9, so there's no need to require this in the Gemfile unless we want to pin a version (which I don't think we do). 
I don't think `multi_json` requires us to explicitly require the gem either. They mention in their docs [the JSON gem that ships with Ruby is supported](https://github.com/sferik/multi_json?tab=readme-ov-file#supported-json-engines). I also don't see anything concerning in the `multi_json` [adapter](https://github.com/sferik/multi_json/blob/main/lib/multi_json/adapters/json_gem.rb#L7).  
The tests pass and I was able to navigate the app locally.
> Remove json dependency

- Gemfile
- Gemfile.lock
- config/initializers/omniauth.rb
Removes the `multi_json` gem. `multi_json` was originally [added as a dependency for the omniauth-windowslive plugin](https://github.com/openstreetmap/openstreetmap-website/commit/5a28ff2901fd0387805240732a31194d198d1071). However, that plugin was replaced with `omniauth-microsoft_graph` in https://github.com/openstreetmap/openstreetmap-website/pull/4169. Since `omniauth-microsoft_graph` does not need `multi_json` we can remove it from the Gemfile.
The tests pass and I was able to run the app locally. I've also looked through the other omniauth plugins and confirmed they do not rely on `multi_json` gem either:
- [omniauth](https://github.com/search?q=repo%3Aomniauth%2Fomniauth+MultiJson&type=code)
- [omniauth-apple](https://github.com/search?q=repo%3Anhosoya%2Fomniauth-apple%20MultiJson&ty …
> Remove `multi_json` library

- app/helpers/user_helper.rb
- test/helpers/user_helper_test.rb
The translation noise in the #6351 failures was hiding a real failure, which this fixes.
> Fix test failures from #6351

- app/helpers/user_helper.rb
- app/views/application/_auth_button.html.erb
- app/views/application/_auth_providers.html.erb
- test/helpers/user_helper_test.rb
After #6351 and #6352 I don't think we need a helper for auth buttons.
I think a template is easier to read. Unlike the helper, it doesn't have html string concatenation.
> Replace auth_button helper with template

- app/controllers/api/old_elements_controller.rb
- app/views/api/old_nodes/index.json.jbuilder
- app/views/api/old_nodes/index.xml.builder
- app/views/api/old_relations/index.json.jbuilder
- app/views/api/old_relations/index.xml.builder
- app/views/api/old_ways/index.json.jbuilder
- app/views/api/old_ways/index.xml.builder
Eliminates `@elems` instance variable. Otherwise there are both `@elements` and `@elems` and the difference is that one is filtered by redactions and the other is not, which you can't guess from their names.
> Use @elements instead of @elems in api element history

- app/assets/javascripts/index/layers/data.js
- app/assets/javascripts/leaflet.map.js
In this PR, we're adding a Bearer token for Map API requests, if available.
Benefits:
- Users behind a shared IP address are less likely to hit rate limiting.
- Higher rate limits for moderators are taken into account.
Tested with anonymous / known user for "Map Data" and single object map display. Map requests were  served by a cgimap backend.
> Map API requests with Bearer token

- app/assets/stylesheets/common.scss
- app/views/layouts/_select_language_list.html.erb
- config/locales/en.yml
- config/ui_languages.yml
- test/lib/i18n_test.rb
With this PR the language names in *Select Language* dialog can be translated, that would fix #6319.
Using CLDR or anything derived from it is not going to work because it's not complete enough. If you try, you'll have to "fall back to ... the raw language code" as #6319 says and why would you want that when we already have English names.
The problem this PR may introduce is that we won't be able to control how wide the names are. Some of them will likely won't fit on one line which will make the list look worse.
> Move English language names to en.yml

- app/controllers/api/nodes_controller.rb
- app/controllers/api/relations_controller.rb
- app/controllers/api/ways_controller.rb
- test/controllers/api/nodes_controller_test.rb
- test/controllers/api/relations_controller_test.rb
- test/controllers/api/ways_controller_test.rb
See https://github.com/openstreetmap/openstreetmap-website/pull/6361#issuecomment-3232959610.
I was easily able to trigger race conditions when creating nodes and ways but not when creating relations, modifying nodes and ways. That's why there are race condition tests only for create actions.
I assume we're locking the changeset first and the elements later, that's what cgimap seems to do.
> Lock changeset in api single element changes

- app/views/layouts/_header.html.erb
- config/locales/en.yml
The avoids using "OK" as a button label, and aligns with the labelling of the cross in the corner of the modal.
I considered alternative labels (like "dismiss") but since we have two ways to close the dialog, the cross is already labelled as "Close", so let's use "Close" for the button too.
Before:
After:
> Use Close as the button label to close modal alerts

- app/assets/javascripts/index.js
- app/assets/javascripts/index/directions.js
- app/assets/javascripts/index/new_note.js
- app/assets/javascripts/language_selector.js
- app/assets/javascripts/osm.js.erb
Two changes:
- DRY up the code handling JS cookies.
- It's very repetitive as every single instance repeats the arguments `{ secure: true, path: "/", samesite: "lax" }`.
- We can avoid this using `Cookies.withAttributes`, creating a preset that I have placed at `OSM.cookies`.
- Argument `expires` left in place as it does change in each instance.
- Change `secure: true` to only apply when HTTPS is expected. This is, when `Settings.server_protocol == "https"`.
This change is extracted from https://github.com/openstreetmap/openstreetmap-website/pull/6424. Over there it was done so that system tests work with remote Selenium.
> Use secure cookies only when HTTPS is expected

- test/application_system_test_case.rb
- test/controllers/sessions_controller_test.rb
- test/factories/user.rb
- test/integration/login_test.rb
- test/integration/oauth2_test.rb
- test/integration/page_locale_test.rb
- test/integration/user_blocks_test.rb
- test/integration/user_diaries_test.rb
- test/integration/user_terms_seen_test.rb
- test/system/user_login_test.rb
- test/test_helper.rb
Extracted from https://github.com/openstreetmap/openstreetmap-website/pull/6424.
This is a workaround for Selenium/Webdriver throwing an error `You are trying to upload something that isn't a file`, despite not trying to upload anything.
In some circumstances, Selenium interprets the value `test` in a form field as a placeholder for a fake file upload. No idea why. Hat tip to https://blog.konoson.com/webdrivererror-you-are-trying-to-upload-something-that-isnt-a-file for the info.
This was discovered when trying to run a remote Selenium instance (in a separate Docker container). So I guess that's one such circumstance where this can happen.
> Workaround for strange Selenium behaviour
