openstreetmap/openstreetmap-website

- Vagrantfile
Add vagrant cachier (apt repo caching) plugin support (if available) to speed up re-provisioning.
> Add Vagrant cachier plugin support if available

- Gemfile
- Gemfile.lock
- app/controllers/user_controller.rb
- app/helpers/user_helper.rb
- app/views/user/account.html.erb
- app/views/user/login.html.erb
- app/views/user/new.html.erb
- config/example.application.yml
- config/initializers/omniauth.rb
- lib/auth.rb
- test/controllers/user_controller_test.rb
- test/fixtures/users.yml
- test/integration/user_creation_test.rb
- test/integration/user_login_test.rb
- test/models/user_test.rb
This replaces our existing OpenID based support for logging in with Google with an OAuth based approach, which will resolve #897 and deal with the forthcoming remove of OpenID support by Google.
It's not ready for merging quite yet because it requires a small patch to the `omniauth-google-oauth2` gem to support transparent upgrading of OpenID logins to OAuth logins.
> Google OAuth support

- app/assets/javascripts/index/new_note.js
This removes a tweak added in 40b3c82, which we believe is no longer relevant now the new-note dialogue is sidebar rather than bubble.
I've tested this with various screen sizes (inc mobile-sized) on my laptop with Firefox and Chromium. It looks good and doesn't incur scrolling (as the comment on 40b3c82 might suggest).
Fixes #1028
> Simplify new-note marker placement - always in the centre

- config/locales/en.yml
Found by me in 
https://github.com/openstreetmap/openstreetmap-website/issues/1031#issuecomment-130560940
Probably a missing string even in the fallback language should get tested somehow.
> added missing wording for note "not found" and "timeout"

- config/locales/en.yml
Changed hundreds to thousands in the about text. 
It is safe to say osm maps and data are used on more than a thousand website app etc. hundreds make it seem like a small project.
> Updated about text

- app/views/layouts/_flash.html.erb
- app/views/layouts/_header.html.erb
Apparently this unclosed tag didn't break anything but judging from the
fact that this was the only unclosed tag and was introduced recently,
it probably wasn't intended.  The unit tests did expect the tag to be
closed.
> Close html <source> tags

- app/assets/stylesheets/common.scss
Is there any particular reason for secondary links being inline? They are on next line if location is long enough anyway. This PR changes this:
to this:
> Remove inline property of secondary links on diary page

- app/views/site/id.html.erb
This should cut down on the errant edits in Three Rivers, MI.
Users getting stuck in walkthrough are probably refreshing their browser and
returning to the location in the walkthrough where they got stuck.
> Don't update urlhash while in iD intro

- app/views/browse/timeout.html.erb
This adds an `X` to the sidebar, in order to allow the user to close the sidebar after a timeout occured (happens e.g. for objects with long history).
Before/after-comparison:
> Allow closing the sidebar when a timeout occured

- INSTALL.md
PostgreSQL 9.0 is end of life, and having both extension install methods in documentation is often a source of confusion.
> Remove 9.0 extension install instructions

- public/robots.txt
Add a Host: which is an extension to the robots.txt standard. https://en.wikipedia.org/wiki/Robots_exclusion_standard#Host
Googlebot particularly seems to be incorrectly indexing the spike-0x host urls.
> Add Host: to robots.txt

- app/helpers/changeset_helper.rb
- app/helpers/note_helper.rb
- config/locales/en.yml
- test/controllers/changeset_controller_test.rb
- test/fixtures/changesets.yml
- test/helpers/changeset_helper_test.rb
- test/helpers/note_helper_test.rb
- test/models/changeset_test.rb
`anonymous` is closest thing I could find in yml files for internationalization, should I create a new tag named 'DELETED' like #579 suggests?
Related: #1069
> Do not hyperlink profiles of deleted users

- script/vagrant/setup/provision.sh
`bundle install` was failing because of missing ruby2.0.
And `rake db:migrate` was also failing subsequently.
The only locale related error remaining is:
```
==> default: Generating locales...
==> default:   en_GB.UTF-8... 
==> default: done
==> default: Generation complete.
==> default: /tmp/vagrant-shell: line 7: warning: setlocale: LC_ALL: cannot change locale (en_GB.utf8)
```
It seems to be `update-locale LANG=en_GB.utf8 LC_ALL=en_GB.utf8`
> Vagrant fix provision script + fix locale errors

- Vagrantfile
Because some tests were crashing by lack to RAM.
Once, even a part of the provisioning failed with an out of memory error.
And a second core speeds up the provisioning and the tests.
I can't test for lxc and libvirt so I only edited virtualbox config.
> Vagrant: Virtualbox: increase RAM and put 2 CPUs

- INSTALL.md
Added inline code markdown in MacOSX install instructions, making it look like command line code.
> INSTALL.md: Added inline code markdown

- app/helpers/browse_helper.rb
- test/helpers/browse_helper_test.rb
This is a follow-up to #786, in which I've linked the basic wikidata-tags to [wikidata.org](https://wikidata.org)
With this pull-request, also the other wikidata-tags (see [the proposal's wiki-page](https://wiki.openstreetmap.org/wiki/Proposed_features/Wikidata)) get linked.
I decided against a catch-all to discourage misspelled keys. If other prefixes will get popular, one could add them easily in the future.
So tags with the following keys are the only ones that get linked:
* architect:wikidata
* artist:wikidata
* brand:wikidata
* ~~name:etymology:wikidata~~
* ~~old_name:etymology:wikidata~~
* operator:wikidata
* subject:wikidata
The reason that it took longer than expected to implement it, was the following:
The basic tag allows only exactly one value, because both OSM and WikiData …
> Link prefixed Wikidata-tags to wikidata.org

- README.md
The EWG is inactive and doesn't have weekly meetings.
> Remove references to EWG meetings

- Gemfile
- Gemfile.lock
- test/factories/diary_comments.rb
- test/factories/diary_entries.rb
- test/models/diary_comment_test.rb
- test/models/diary_entry_test.rb
- test/test_helper.rb
FactoryGirl is a widely used alternative to fixtures in tests. The fixtures are annoying since every time you want to test something slightly different (for example, a diary entry with an apostrophe in its title), you need to add a whole new fixture and rework the tests. Fixtures are also a pain when the model attributes change.
This PR adds FactoryGirl, and reworks two model tests (DiaryEntry and DiaryComment) to use them.
> Add Factorygirl as an alternative to fixtures

- app/helpers/banner_helper.rb
(closes #1284)
This PR makes it so that if multiple banners are tied for queue position (e.g. if user is in incognito mode or just hasn't seen _any_ banners yet), we pick the banner with the soonest end date.
> Prioritize next upcoming event in banner rotation

- config/locales/en.yml
Pro memoria: while we only have one (old) translation of the privacy policy, it is conceivable that down the road we would want more and then we would potentially need to revisit where we actually store the policy.
> Add links to new approved OSMF privacy policy and some rewording.

- test/controllers/browse_controller_test.rb
- test/controllers/notes_controller_test.rb
- test/controllers/site_controller_test.rb
- test/factories/notes.rb
Add a note_with_comments factory and migrate tests to use it, and blocks, to create notes and their associated comments in one action.
Partly I was playing with factory girl, but I also think I prefer creating the object in one go rather than creating it and then adding things to it. Maybe @gravitystorm will have some thoughts on whether we should merge this?
> Add a note_with_comments factory

- app/controllers/diary_entry_controller.rb
- app/controllers/message_controller.rb
- app/controllers/trace_controller.rb
- app/controllers/user_controller.rb
Rails redirect_to uses the current controller by default, so there
is no need to re-iterate this in the code when the redirect targets
the current controller.
The short-form is already used elsewhere, this just tidies up those
which were still using the long-form.
> Remove unnecessary controller references from the redirect hashes.

- test/controllers/diary_entry_controller_test.rb
- test/controllers/notes_controller_test.rb
- test/controllers/user_controller_test.rb
- test/models/note_test.rb
- test/models/user_test.rb
Rather than passing around record ids explicitly, we can use the model relations and pass around the models. This makes reading the tests slightly simpler to read.
> Use model relations when creating objects from factories

- app/controllers/changeset_controller.rb
- app/controllers/user_preference_controller.rb
- app/models/node.rb
- app/models/relation.rb
- app/models/trace.rb
- app/models/way.rb
This technique was already used in app/models/changeset.rb
This suppresses the error messages when parsing invalid XML, but
the exceptions are still raised, as tested in test_from_xml_double_lat
in test/models/node_test.rb
> Suppress XML parsing errors.

- app/assets/javascripts/index/directions.js
Use the DataTransfer interface properly, using the `text` format, as IE/Edge does not support much more. We can JSON-serialize anything there, even though right now, only a single string would be enough. (This might be unnecessarily complicated right now, and in the spirit of KISS, we might use just `dt.setData('text', $(this).data('type')` and `type = oe.dataTransfer.getData('text')`. Your call.)
Also, IE does not support .setDragImage, so check for support prior to calling.
Fixes #1343
> Ensure IE/Edge compatibility for routing drag&drop

- app/views/diary_entry/rss.rss.builder
- test/controllers/diary_entry_controller_test.rb
The XML builder takes care of the escaping, and adding h() lead to
double-escaped titles in the RSS feed.
> Avoid double-escaping diary entry titles

- Gemfile
- Gemfile.lock
- lib/osm.rb
- test/controllers/site_controller_test.rb
- test/controllers/user_controller_test.rb
- test/http/geocoder_ca.yml
- test/http/gravatar.yml
- test/http/nominatim.yml
- test/http/npemap.yml
- test/integration/oauth_test.rb
- test/integration/page_locale_test.rb
- test/integration/user_creation_test.rb
- test/integration/user_roles_test.rb
- test/integration/user_terms_seen_test.rb
- test/test_helper.rb
I found while offline that many of the tests make real http requests. Using [webmock](https://github.com/bblimke/webmock) means these are disabled by default, and need to be explicitly stubbed - this ensures that http requests aren't accidentally overlooked when they are written while online.
Later I found that some http requests were being mocked out using the stub_http_requests method, so I've refactored that to use webmock too. I also refactored some gravatar tests to improve their clarity, and removed their http fixture since it was just dummy responses anyway.
> Use Webmock to intercept http requests in tests

- app/views/changeset/list.atom.builder
- app/views/diary_entry/rss.rss.builder
- app/views/notes/index.rss.builder
This PR fixes a couple of missing xmlns declarations, and makes the remaining feeds use the assets path for their images.
> Feed validation

- app/models/node.rb
- app/models/relation.rb
- app/models/way.rb
If a deadlock occurs then the transaction will be retried so we need to make sure that the object will still be dirty so that it will be saved again during the retry but that the version won't be incremented a second time.
> Clone objects before saving in case of a retry

- config/locales/en.yml
We can't provide a free unlimited API for any third-party, not just developers. The change should further make translations less bumpy.
> Fix misleading wording

- config/locales/en.yml
This updates the OWG policy links to point at the operations.osmfoundation.org website.
> Update OWG policy links

- INSTALL.md
change dependancies. nokogiri requires a later ruby now as pointed out here: https://github.com/openstreetmap/openstreetmap-website/issues/1402 ruby2.0->ruby 2.3 ...which then entails a later ubuntu if we're installing from packages.
> change described dependancies ruby2.0->ruby 2.3

- test/models/user_token_test.rb
The fixture is a 0-byte file, and the test is only checking that no fixtures have been loaded from that 0-byte file.
> Remove unused user_tokens fixture and pointless test

- app/models/user_role.rb
- test/factories/user.rb
- test/factories/user_role.rb
- test/models/user_test.rb
This pull request starts the process of replacing the users.yml fixtures with a user factory. Given the size of the change by the end of the process, I plan to submit several individual pull requests.
This PR creates the user and user_role factories, and refactors only the test/models/user_test.rb file. 
Given the number of tests involved even just with this one file, I've broken it down further into separate commits, so the `git blame` etc can have specific comments. If this PR is still too big, or something is controversial, I'm happy to split this PR into the ~11 separate PRs - but then each PR is a bit trivial.
Future work will involve refactoring other places where the user fixtures are used.
> Initial user_factory refactoring

- app/views/notifier/note_comment_notification.html.erb
- app/views/notifier/note_comment_notification.text.erb
This fixes the bug reported in [this comment on PR #1401](https://github.com/openstreetmap/openstreetmap-website/pull/1401#issuecomment-278389580)
> Don't display a box at all if the note event doesn't include a comment

- app/assets/javascripts/index/directions/graphhopper.js
latLng is an array and not a latLng object
Here is a minor fix for GraphHopper engine
> Fix latLng from GraphHopper engine

- app/views/layouts/map.html.erb
- app/views/site/about.html.erb
- config/locales/en.yml
See [the policy](https://operations.osmfoundation.org/policies/hosting/) for the details, but basically means a swap in the order that we list credits (which might take some time to percolate through translations), plus a paragraph in the welcome box. It looks like this (until dismissed as usual):
Note that, since I'm using `en_GB`, the order hasn't changed - I'll have to wait for translatewiki for that.
> Implement the OWG credit policy for hosting partners.

- app/controllers/application_controller.rb
- app/models/user_block.rb
- config/locales/en.yml
This PR adds a specific message for zero hour blocks that is a bit friendlier than the rather technical default message.
While this improves the messaging special support at least in iD would be good as the user is asked to login to the OSM website and it may not be clear to the user how to do this without losing their edits.
Tests to come.
> Add functionality to return a specific message for zero hour blocks

- app/assets/javascripts/index/contextmenu.js
At least in Google Chrome `e.shiftKey` is not defined in `mousedown` event here, so the desired effect (skipping contextmenu) is not working. Using `e.originalEvent.shiftKey` now.
I really love TypeScript :-)
> Fix shift key handling in contextmenu

- app/helpers/user_blocks_helper.rb
- config/locales/en.yml
- test/helpers/user_blocks_helper_test.rb
This fixes a tiny issue with the block display: previously if the need_view flag was set, the status only displayed that the user has to login even if the block hadn't expired yet, this PR makes the remaining block time visible too.
> Small improvement to block status display

- test/controllers/diary_entry_controller_test.rb
- test/factories/user.rb
- test/models/diary_comment_test.rb
- test/models/diary_entry_test.rb
This PR refactors the diary_entry tests to use the User factory instead of the fixtures. To simplify them I've created a "normal user" factory, which can log in without being redirected to view contributor terms etc.
I've tried to keep consistent naming for the tests, in most cases there are 'user' and 'other_user' objects replacing the 'normal_user' and 'public_user' fixtures.
> Refactor diary entry tests to use User factory

- test/controllers/amf_controller_test.rb
In all honesty I wouldn't be surprised if there are some semi-hidden
dependencies on the user fixtures here, given the number of magic numbers
all over the place. But this commit takes care of the explicit
dependencies for now.
> Refactor amf_controller tests to avoid users fixtures

- test/controllers/amf_controller_test.rb
- test/controllers/api_controller_test.rb
- test/controllers/diary_entry_controller_test.rb
- test/controllers/notes_controller_test.rb
- test/factories/user.rb
The use of create(:normal_user) makes the tests needlessly harder to understand and reason about, particularly when we start using associations in the factories.
> Make all factory-generated users 'normal'

- test/controllers/user_controller_test.rb
- test/factories/changeset_comments.rb
- test/factories/diary_comments.rb
- test/factories/diary_entries.rb
- test/factories/friends.rb
- test/factories/messages.rb
- test/factories/traces.rb
- test/factories/user_blocks.rb
- test/factories/user_preferences.rb
- test/models/user_preference_test.rb
We have a User factory now, might as well use it!
There were two tests that made assumptions about the user_id of objects generated by factories. For the `test_api_details` the assumption was that the message was sender was also user_id 1. I think the test is clearer by having two messages, since having a message sent to yourself is a bit curious.
> User factory associations for all factories

- app/helpers/notifier_helper.rb
- app/views/layouts/notifier.html.erb
- app/views/notifier/_message_body.html.erb
- app/views/notifier/changeset_comment_notification.html.erb
- app/views/notifier/email_confirm.html.erb
- app/views/notifier/signup_confirm.html.erb
A few tweaks to the HTML/CSS code of the email notifications to make messages more responsive on narrow displays, which should improve the viewing experience on mobile. Also a handful of minor tweaks to fonts.
There are no changes to content, only implementation.
https://wiki.openstreetmap.org/wiki/Dressed-up_Notification_Mails is up to date with screenshots of what this PR produces.
> Responsive HTML mails

- app/controllers/application_controller.rb
- config/locales/en.yml
I've tried to make the message slightly less technical, but betterwording suggestions are welcome.
> Externalize message about missing OAuth capabilities/permissions

- app/models/notifier.rb
- app/views/notifier/changeset_comment_notification.html.erb
- app/views/notifier/changeset_comment_notification.text.erb
- config/locales/en.yml
In PR #1401 we added a new I18N string, `notifier.changeset_comment_notification.hi`, whose value is `"Hi %{to_user},"`. It's now been translated to 32 languages (if I'm grepping right).
The only other email that doesn't already open with a greeting is `friend_notification`.
This PR does two things:
1. start using the new string in the changeset comment notification template
2. add a a new string, `notifier.friend_notification.hi`, which is a copy of the `changeset_comment_notification.hi` (IIUC there's no way around the translatewiki pipeline, even for strings that are identical to previous ones?) Once translated this can be added to the friend_notification templates.
> Add greeting to changeset comment notification

- .rubocop_todo.yml
- test/controllers/user_roles_controller_test.rb
- test/factories/user.rb
- test/helpers/user_roles_helper_test.rb
I couldn't figure out a neat way to shorten these monster lines. The %() notation is a useful way to avoid the nested double-quotes, but the ruby parser then had problems splitting that over multiple lines, e.g.
```
expected = %(<a href=....)\
%(<picture><....)
^ruby got confused by the left bracket here
```
If anyone has a suggestion for breaking these lines then I'm all ears, otherwise I just extended the rubocop limit to the largest of the new strings.
> User factories for user_roles_helper tests

- test/integration/user_login_test.rb
I've split this one out separately from the others since there's more refactoring here to consider.
The display_name logins were reworked to use downcase since the factories supply users with an already-title-cased display_name.
The tests were also renamed to align better with the purpose of the test rather than the name of the fixture used.
> Use user factories for user_login integration tests

- app/controllers/api_controller.rb
- test/controllers/api_controller_test.rb
Trivial patch so that we return the maximum bounding box size for notes retrieval in the capabilities.
> Return maximum size of bounding box for note retrieval

- test/controllers/user_controller_test.rb
This replaces the fixtures in the user_controller tests with factories.
Note that two of the tests still have explicit dependencies on the fixtures, where they are counting the total number of users in the database. But we can't remove the fixtures yet since there's still more refactoring to do.
> User factory for user_controller tests

- test/controllers/old_node_controller_test.rb
- test/controllers/old_relation_controller_test.rb
- test/controllers/old_way_controller_test.rb
- test/controllers/redactions_controller_test.rb
- test/factories/old_node.rb
- test/factories/redaction.rb
- test/models/redaction_test.rb
This PR creates a redaction factory and uses it wherever the redactions fixtures were used explicitly. The redactions fixture is still used indirectly by various other fixtures so needs to wait for them to be refactored before it can be removed.
> Redaction factory

- test/controllers/browse_controller_test.rb
- test/factories/node.rb
- test/helpers/browse_helper_test.rb
- test/models/redaction_test.rb
This PR contains more conversions to use the node factories. I've also added the `with_history` option to the node factory to create the correct number of old_nodes, for when a realistic history is required.
> More node factories

- app/models/node.rb
- test/controllers/api_controller_test.rb
- test/controllers/way_controller_test.rb
- test/models/node_test.rb
This matches the double formatting in XML from cgimap. Fixes #341.
> Format latitudes and longitudes as %7f in XML output

- test/controllers/node_controller_test.rb
- test/controllers/site_controller_test.rb
- test/factories/changesets.rb
- test/factories/relation.rb
- test/factories/relation_member.rb
- test/factories/way.rb
- test/factories/way_node.rb
This converts more tests to node factories. To replace the `:used_node_1` and `:node_used_by_relationship` fixtures, various new factories are introduced.
The test_delete section of node_controller_test alternated between using nodes() and current_nodes() fixtures, but I've stuck with using the Node factory consistently since it is testing other things.
> Node factories 3

- app/views/layouts/map.html.erb
- app/views/site/about.html.erb
- config/locales/en.yml
Since we're now hosted at a main ISD data centre, makes sense to credit the whole of UCL for hosting rather than just the Bartlett / VR Centre.
> Credit the whole of UCL, rather than just the Bartlett / VR centre.

- app/models/node.rb
- app/views/notes/_note.json.jsonify
- lib/bounding_box.rb
- lib/geo_record.rb
- lib/potlatch.rb
- test/controllers/api_controller_test.rb
- test/controllers/changeset_controller_test.rb
- test/controllers/relation_controller_test.rb
- test/lib/bounding_box_test.rb
- test/models/note_test.rb
- test/models/old_node_test.rb
- test/models/tracepoint_test.rb
This turned out to be slightly more complex than I expected, but it does work using the delegate method. Fixes #1509 
In the json builder, an explicit `.to_f` is required since the builder calls `to_s` on objects that it doesn't recognise, and we would end up with strings instead of floats in the json.
In lib/potlatch, again we need to be explicit, since there's a hardcoded shortcut for built-in types when running `[n].pack("G")`, but adding `.to_f` sorts it out too.
The rest of the changes are in the tests, where testing coordinates as strings needs the corresponding changes.
> Rework coordinates to avoid scientific formatting of small numbers

- app/views/user/view.html.erb
- test/controllers/user_controller_test.rb
It's no longer important to show when users agreed to the contributor terms.
For users that haven't agreed, we still show their status on their profile.
Logic was also re-written to avoid lots of `if not` things, and tests added.
Replaces #97
> Hide contributor terms details, unless the user hasn't agreed

- Vendorfile
- vendor/assets/leaflet/leaflet.locate.js
Leaflet.Locate 0.54.0 is incompatible with Leaflet 1.1.0.
This causes the following error when clicking _Show my location_:
> Uncaught TypeError: t.DomUtil.removeClasses is not a function
Leaflet.Locate 0.62.0 and later includes [the fix](https://github.com/domoritz/leaflet-locatecontrol/commit/690891f93f161653cd6897704f00b16bd5aa7040) for this incompatibility.
> Update to Leaflet.Locate 0.62.0

- Gemfile
- Gemfile.lock
- app/assets/stylesheets/common.scss
OSM uses the R2 gem to "flip" CSS for right-to-left languages.  In #1585 I explained how this is causing all but one icon to go missing on these languages' pages on OpenStreetMap.
The issue got back to the R2 gem developer and he released a new version of the gem (0.2.7) where you can place a ```/* no-r2 */``` comment inside a CSS block and have sprites and other items not be modified. Due to how we use SASS, I believe that the comment needs to be inside each block.
> Update gem, fix icons on RTL/Arabic pages

- app/controllers/trace_controller.rb
- app/models/trace.rb
- test/controllers/trace_controller_test.rb
This PR refactors the trace api_update method to work on existing trace objects, rather than creating temporary 'shadow' trace objects. In doing so it refactors the `from_xml` and `from_xml_node` model methods to be instance methods instead of class methods.
Advantages:
* No longer duplicate tags (i.e. fixes #1600)
* makes updating a trace via xml more similar to updating via forms (which don't use shadow objects)
Concerns:
* Doesn't avoid deleting and recreating tag objects when the tags are the same (but neither does the `tagstring=` method, afaict)
* Other classes (Node, Changeset etc) all use the class method approach for `from_xml`, rather than instance methods. I don't know whether they should be refactored too, or whether there's some advantage of the class method approach that I …
> Refactor trace api_update to avoid duplicating tags

- app/assets/javascripts/index.js
- app/assets/javascripts/user.js
With this the cursor should render identical to the other buttons. 
It is a proper `a` element where the browser default style is a pointer.
closes #1653
> Add missing href=# in location button

- app/controllers/changeset_controller.rb
- app/controllers/message_controller.rb
- app/controllers/user_blocks_controller.rb
- app/controllers/user_controller.rb
- app/controllers/user_roles_controller.rb
The code is easier to read using higher-level concepts. This PR isn't comprehensive but it fixes a few obvious cases in the controllers.
> Avoid using or comparing explicit model ids

- config/locales/en.yml
This removes the repeated `add` 
`Hosting is supported by UCL, Bytemark Hosting and Imperial College London, and other partners.` to 
`Hosting is supported by UCL, Bytemark Hosting, Imperial College London, and other partners.`
> Change wording for hosting partners

- app/assets/javascripts/application.js
I did't realise that jquery-rails offers all three major versions of jQuery and you have to choose which one you want, so we've been sat on 1.x for a long time...
I've tried to test as much as I can but it wouldn't hurt if other people played with it before we merge it - there's a test site deploying now at https://tomh.apis.dev.openstreetmap.org/.
> Update site to use jQuery 3

- config/locales/en.yml
In particular translations of the web site point to translated version of the wiki page that are even worse.
> Remove link to wiki legal FAQ as confusing and unmaintained

- config/locales/en.yml
Related to #373
"Where am I?" is short for "Where am I looking at?" but prone to be interpreted as "Where am I located right now?"
This pull request changes it to "Where is this?" I considered "Where am I looking at?" but the at? is pushed onto the next line, consuming vertical sidebar space.
It does not make the side text any longer and should be a clearer description of what the feature does.
Current:
Where am I looking at?:
Where is this?:
> Change Where am I to Where is this on left sidebar

- app/controllers/api_controller.rb
- app/controllers/relation_controller.rb
- app/controllers/search_controller.rb
- app/models/relation.rb
What's going on [here](https://github.com/openstreetmap/openstreetmap-website/blob/e64bcf335a95f7cc35cd19c190b8111c2d7b275f/app/models/relation.rb#L150)? `p` is either 0 or 1, both of which are truthy in Ruby, so the `if` block is always executed.
Do we need this check?
> non-functional visibility check in `Relation#to_xml_node`

- app/helpers/title_helper.rb
- test/helpers/title_helper_test.rb
Discussed in #835 - might be better to put the more specific part of the page title at the start rather than the end, so that the different pages are easier to distinguish when you have lots of tabs.
(This doesn't solve all of #835. Independent PRs may come later...)
> Page titles: put specific page title at the start not the end

- config/locales/en.yml
Although the content is currently duplicated into the blog aggregator, it's still worth having an explicit link, and making it the first one, since it contains entries of more significant interest to the community.
Refs #260 and #1042 and I think is a reasonable compromise.
> Add the OpenStreetMap Blog to the list of community links

- CONTRIBUTING.md
As mentioned in https://github.com/openstreetmap/openstreetmap-website/pull/1290#issuecomment-346368540 cruise.openstreetmap.org no longer exists. Travis shows the output from running the tests, so link to that instead.
> Update CONTRIBUTING to remove reference to cruise and use link to Travis

- app/assets/javascripts/index.js
- app/controllers/application_controller.rb
Fixes #1703.
This should actually be merged as soon as we're happy with browser support. It makes setting up the JOSM remote a lot easier, and supports calling merkaator from https (how many people still use merkaator?)
[Chrome 53+ works](https://chromium.googlesource.com/chromium/src.git/+/130ee686fa00b617bfc001ceb3bb49782da2cb4e).
[Firefox 55+ works](https://bugzilla.mozilla.org/show_bug.cgi?id=903966) but not ESR.
[Safari wontfix](https://bugs.webkit.org/show_bug.cgi?id=171934).
[MS Edge](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/11963735/) is fixed, release coming.
[No plans for IE 11](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/11963735/#comment-0) ?
> Remove support for soon discontinued josm remote https endpoint

- config/locales/en.yml
The trademark policy has now been approved by the OSMF board, link to it 
- point to the TM policy instead of the LWG on the Copyright page
- add short text on TMs to the About page
> Add links to the trademark policy

- .rubocop_todo.yml
- app/controllers/changeset_controller.rb
- test/controllers/changeset_controller_test.rb
Fixes #1627 
There’s one rubocop max class length message left in the Travis CI build, which i have no idea how to address properly. Supposedly, I need to run `rubocop --auto-gen-config`, but this creates a new file with many unrelated "fixes".
> Allow (un)subscribing discussions also when changeset still open

- test/application_system_test_case.rb
This comes via https://github.com/rails/rails/pull/29561
> Silence puma startup messages when running tests

- config/application.rb
- config/image_optim/test.yml
There's two parts to this - firstly, removing the forced loading of the config file, and letting image_optim load the config itself. Secondly, this then enables per-environment image_optim config files, and so we can disable the various workers in the test environment.
> Silence image_optim missing worker warnings during tests

- config/locales/en.yml
This keeps bugging me when doing work in the translations file, since my editor strips the trailing white space automatically on save.
> Strip trailing whitespace from multiline html translations

- app/controllers/trace_controller.rb
- app/views/trace/list.html.erb
- app/views/user/view.html.erb
- config/locales/en.yml
...for objects that belong to the user. We use 'my' almost everywhere, and this PR takes care of a few that use 'your' inconsistently.
I'm not making any comment on whether 'my' or 'your' or 'neither' is the best (see #1163), just trying to be consistent.
> Be more consistent with 'my' vs 'your'

- app/assets/javascripts/index/directions.js
- app/assets/stylesheets/common.scss
- config/locales/en.yml
Fixes #1790 
Added a new locale translation where you can specify a specific location in the 'not found' error message
Made it so that the textbox containing the error-ed value gets highlighted in red
> Unlocateable place now highlighted in red and specified in error message

- config/locales/en.yml
If you go to https://www.openstreetmap.org/directions?engine=osrm_car&route=52.4680%2C-1.7135%3B52.4601%2C-1.7042#map=15/52.4612/-1.7058 you'll notice that there is a missing locale instruction in the directions list, which this PR fixes
> Add missing onramp instructions to locale file

- app/views/diary_entry/_diary_entry.html.erb
- app/views/message/new.html.erb
- config/routes.rb
- test/system/diary_entry_test.rb
- test/test_helper.rb
I noticed that the link "Reply to this entry" includes the title for the message, but this wasn't being shown in the new message form. This PR includes a test to ensure that the form field is filled in correctly, and includes some extras to make the tests easier to write (taken from the moderation branch).
> Fix handling of title when replying to diary entries

- app/models/notifier.rb
- app/views/notifier/_message_body.html.erb
- config/application.rb
- config/initializers/action_mailer.rb
This saves having to repeat the same host and protocol options throughout the notifiers.
> Set default_url_options for action_mailer

- .rubocop_todo.yml
- app/controllers/user_preferences_controller.rb
- config/routes.rb
- test/controllers/user_preferences_controller_test.rb
This is the rails convention for controllers and can make route generation easier.
http://guides.rubyonrails.org/action_controller_overview.html#controller-naming-convention
There's plenty more renaming that can be done, but most need some refactoring around named paths. This one is completely stand-alone!
> Pluralise user_preferences_controller

- app/views/user_blocks/_block.html.erb
- app/views/user_blocks/_blocks.html.erb
- config/locales/en.yml
Lazy translations are easier to read, to write, and easier to deal with when refactoring things like partial names, controller methods and controller names. 
This is just a first gentle step in a wider project.
@Nikerabbit as per https://github.com/openstreetmap/openstreetmap-website/issues/1289 this PR will involve changing translation keys on Translatewiki, if it is merged.
> Use lazy translation lookups for the user_blocks partials

- app/controllers/user_blocks_controller.rb
- app/helpers/user_blocks_helper.rb
- app/views/user_blocks/blocks_by.html.erb
- app/views/user_blocks/blocks_on.html.erb
- app/views/user_blocks/edit.html.erb
- app/views/user_blocks/index.html.erb
- app/views/user_blocks/new.html.erb
- app/views/user_blocks/not_found.html.erb
- app/views/user_blocks/revoke.html.erb
- app/views/user_blocks/show.html.erb
- config/locales/en.yml
This PR converts the user_blocks views to use lazy translation lookups, and involves renaming all the remaining `user_block.*` i18n keys to `user_blocks.*`.
cc @Nikerabbit
> Use lazy lookups for user_blocks translations

- app/controllers/redactions_controller.rb
- app/views/redactions/edit.html.erb
- app/views/redactions/index.html.erb
- app/views/redactions/new.html.erb
- app/views/redactions/show.html.erb
- config/locales/en.yml
cc @Nikerabbit 
The following translations are renamed in this PR
* `redation.*` to `redactions.*`
> Use lazy translation lookups for redactions

- app/views/notes/_comment.html.erb
- app/views/notes/_entry.html.erb
- app/views/notes/_note.rss.builder
- app/views/notes/feed.rss.builder
- app/views/notes/index.rss.builder
- app/views/notes/mine.html.erb
- app/views/notes/show.rss.builder
- config/locales/en.yml
Enables lazy translation lookups for most cases. 
cc @Nikerabbit this PR contains the following renames:
* `note.*` to `notes.*`
* then in addition, `notes.description.*` to `notes.comment.*`
> Rename note to notes in i18n lookups

- app/controllers/oauth_controller.rb
- app/views/oauth/authorize.html.erb
- app/views/oauth/authorize_failure.html.erb
- app/views/oauth/authorize_success.html.erb
- config/locales/en.yml
cc @Nikerabbit 
This PR renames the following keys:
* `oauth.oauthorize.*` to `oauth.authorize.*`
* `oauth.oauthorize_success.*` to `oauth.authorize_success.*`
* `oauth.oauthorize_failure.*` to `oauth.authorize_failure.*`
> Use lazy translation lookups for the oauth controller

- app/views/site/_markdown_help.html.erb
- app/views/site/about.html.erb
- app/views/site/copyright.html.erb
- app/views/site/edit.html.erb
- app/views/site/export.html.erb
- app/views/site/fixthemap.html.erb
- app/views/site/help.html.erb
- app/views/site/key.html.erb
- app/views/site/welcome.html.erb
- config/locales/en.yml
Some of the site pages had their own top-level i18n keys, so I've renamed them to fit with their view names. In addition, I've removed the 'start' prefix from the export keys since there was no other prefix and it seems unnecessary.
cc @Nikerabbit the following keys have been renamed in this PR:
* `export.title` to `site.export.title`
* `export.start.*` to `site.export.*`
* `license_page.*` to `site.copyright.*`
* `welcome_page.*` to `site.welcome.*`
* `fixthemap.*` to `site.fixthemap.*`
* `help_page.*` to `site.help.*`
* `about_page.*` to `site.about.*`
> Use lazy lookups and rename keys for site pages

- config/locales/en.yml
I've cut back all the complicated refactoring from the PR I've just closed, and just left in the roundabout wording changes.
Basically I've just reworded the instructions to be the same as whats used on OSRM..
See: https://www.openstreetmap.org/directions?engine=osrm_car&route=53.7320%2C-1.5165%3B53.7254%2C-1.5161
vs: http://map.project-osrm.org/?z=17&center=53.730483%2C-1.512321&loc=53.731819%2C-1.514997&loc=53.728976%2C-1.512133&hl=en&alt=0
> Reworded roundabout exit text

- app/controllers/trace_controller.rb
- app/views/trace/create.html.erb
- app/views/trace/list.html.erb
- config/locales/en.yml
A few more lazy translations, to make future refactoring easier.
@Nikerabbit  This PR contains translation key renaming as follows:
* `trace.trace_form.*` is combined into the existing `trace.create.*`
* `trace.trace_header.traces_waiting.*` becomes `trace.create.traces_waiting.*`
* Other `trace.trace_header.*` is combined into the existing `trace.list.*`
> More lazy translation lookups for traces

- config/locales/en.yml
This updates the LINZ attribution at https://www.openstreetmap.org/copyright to be in line with the current recommendation for attribution provided in the LINZ data metadata:
> Following Attribution:
> If you publish, distribute or otherwise disseminate this work to the public without adapting it, the following attribution to Land Information New Zealand should be used:
> 'CC BY 4.0 Land Information New Zealand.
> 
> If you adapt this work in any way or include it in a collection, and publish, distribute or otherwise disseminate that adaptation or collection to the public, the following attribution to Land Information New Zealand should be used:
> 'Contains data sourced from the LINZ Data Service and licensed for reuse under CC BY 4.0'
> 
> If 'attribution stacking' problems exist then …
> Update New Zealand copyright based on current attribution instructions from LINZ

- app/views/oauth/authorize.html.erb
Gives the user a larger target to toggle a permission.
> Wrap the permission label with a <label> tag

- .rubocop_todo.yml
- app/controllers/messages_controller.rb
- app/views/layouts/_header.html.erb
- app/views/messages/inbox.html.erb
- app/views/messages/new.html.erb
- app/views/messages/outbox.html.erb
- app/views/messages/show.html.erb
- config/routes.rb
- test/controllers/messages_controller_test.rb
This PR refactors the inbox and outbox paths to avoid using the display names in their urls. It does this by creating resourceful routes, but I've kept redirects for the old urls. This PR also refactors the url for showing messages (since that was easy to add) and fixes some broken translation strings that I noticed while doing so.
More refactoring of other messages methods will happen in followup PRs
> Refactor some messages urls

- app/controllers/diary_entry_controller.rb
- app/views/browse/not_found.html.erb
- app/views/browse/timeout.html.erb
This fixes #1877 which is a bug that I introduced when converting to lazy lookups. It also simplifies the lookup of the key, and refactors remaining uses of I18n.t to avoid any similar bugs in the future.
> Fix i18n lookup for browse errors

- test/controllers/changeset_controller_test.rb
- test/controllers/old_node_controller_test.rb
The old_node_controller#test_version in particular was slow, since it saves a huge number of tags when adding a tag 30 times over. Since the tests are random and not based on the number of iterations, this
reduces the iteration counts.
> Speed up tests by making fewer random changes

- app/controllers/notes_controller.rb
- test/controllers/notes_controller_test.rb
If you are logged in to the web site with a moderator account, you get to see hidden notes; however the XML API will just return "Gone" when trying to access a hidden note. This pull request enables read access to hidden notes through the API with moderator authentication, and doesn't change anything else.
> allow moderators to read hidden notes through API

- app/controllers/geocoder_controller.rb
- test/controllers/geocoder_controller_test.rb
The website allows for searching by a coordinate in "lat, lon" format. Quite often the order is opposite, with longitude coming first. GeoJSON, WKT, OpenLayers and many other formats and services use "lon, lat". To search by such coordinate on the OSM website, one needs to manually swap the numbers.
This pull request modifies the `search_latlon` function so that it adds not one, but two lines to its results: both "lat, lon" and "lon, lat" coordinates.
> Add parsing coordinates in lon, lat format

- app/controllers/traces_controller.rb
- config/locales/en.yml
- test/controllers/traces_controller_test.rb
At the moment if you try and upload a trace without setting a `description`, then the page just hangs.
Now it renders `traces/new` with full validation errors.
> Fixes "new trace" validation error

- Vagrantfile
The ubuntu image by default creates a logfile during each boot, but this is uninteresting for our workflow. This switch suppresses the log.
> Suppress the creation of boot logs from the ubuntu vagrant image

- db/functions/Makefile
In bundle < 2.0, warnings are printed to stdout, along with the path information that we need. This takes the final line of the output and assumes it's the path.
Fixes #1930
> Alter the Makefile to be robust against bundler warnings

- app/controllers/messages_controller.rb
- app/views/messages/new.html.erb
- config/locales/en.yml
- config/routes.rb
- test/controllers/messages_controller_test.rb
This makes it more conventional, rather than handling posts to the new action. The posting of the form was also reworked to use a hidden field for the displayname, rather than in the url, again for convention.
@Nikerabbit this PR contains some translation key changes:
* `messages.new.message_sent` => `messages.create.message_sent`
* `messages.new.limit_exceeded` => `messages.create.limit_exceeded`
> Refactor message creation to use a create action

- config/locales/en.yml
Otherwise it drives me nuts using an editor that fixes it on unrelated saves! Introduced in 2aca6920dc3488a381b275d21a31344da02029e6
> Fix unwanted trailing whitespace in locale file

- config/routes.rb
These were preserved to avoid users hitting errors, if we deployed while they were filling in the related forms.
> Remove temporary routes

- test/controllers/traces_controller_test.rb
The same approach is used elsewhere in the test suite.
> Use full url escaping when required in trace tests

- app/helpers/changeset_helper.rb
- app/views/changeset/_changeset.html.erb
- app/views/issues/_comments.html.erb
- app/views/issues/_reports.html.erb
- app/views/issues/index.html.erb
- app/views/layouts/_header.html.erb
- test/controllers/reports_controller_test.rb
- test/controllers/user_blocks_controller_test.rb
- test/controllers/user_controller_test.rb
- test/controllers/user_roles_controller_test.rb
- test/system/report_user_test.rb
The various `_path` methods (e.g. `user_path`) can take a wide variety of arguments, but passing just the relevant object (e.g. `user_path(user)`) is the most concise and preferred way to do so in most cases.
This PR refactors a few `_path` methods accordingly.
> Pass objects instead of strings/numbers to _path methods

- .rubocop_todo.yml
- app/helpers/notifier_helper.rb
- test/controllers/amf_controller_test.rb
- test/controllers/changeset_controller_test.rb
- test/controllers/diary_entry_controller_test.rb
- test/controllers/messages_controller_test.rb
- test/controllers/old_node_controller_test.rb
- test/controllers/redactions_controller_test.rb
- test/controllers/swf_controller_test.rb
- test/controllers/traces_controller_test.rb
- test/controllers/user_controller_test.rb
- test/integration/user_creation_test.rb
- test/lib/bounding_box_test.rb
- test/lib/country_test.rb
- test/models/changeset_test.rb
- test/models/message_test.rb
- test/models/node_test.rb
- test/models/old_node_test.rb
- test/models/relation_test.rb
- test/models/tracepoint_test.rb
- test/models/way_test.rb
This PR pulls in three of the rubocop-related changes from the Ruby For Good refactoring PR (#1918). One of them was already fixed in the meantime.
> Selected rubocop changes (ruby for good)

- app/assets/stylesheets/common.scss
This patch sets a default width and height for the _search_form_ and _directions_form_ image button, matching directions.png dimensions of 20x20px. `.icon ` already uses the same hint to avoid content jumping in the browser.
> Set img.button dimensions to 20x20px

- INSTALL.md
I realise that the OSMF servers have since been updated, but that can wait for later!
> Fix incorrect reference to 12.04 in installation notes

- .rubocop.yml
> Remove rubocop reference to quad_tile code

- app/assets/javascripts/index/history.js
Changed the minimum changeset width to be in pixels rather than degrees.
When zooming out, the minimum pixel width is maintained, so even when max-zoomed out, the pixel width will be 40px (width could be easily edited)
> Set minimum changeset size in pixels

- app/views/site/copyright.html.erb
- config/locales/en.yml
The [Australian community wants to import](https://lists.openstreetmap.org/pipermail/talk-au/2018-October/012085.html) suburb, locality and municipality admin boundaries into OSM from a government CC BY 4.0 source, as [documented](https://wiki.openstreetmap.org/wiki/Import/Catalogue/PSMA_Admin_Boundaries), and we'll need this notice in place before the import can happen.
The source did agree to and complete the the OSMF's CC BY waiver, unfortunately it was the first revision which mentioned openstreetmap.org/copyright instead of the wiki contributors page. It took 6 months passing through multiple bureaucrats, so I'd rather not try to re-negotiate this to the wiki contributors page.
Hopefully it's okay to add a new contributor to this page for this substantial contribution, until we can …
> add australia copyright notice for PSMA Australia

- Gemfile
- Gemfile.lock
- config/application.rb
- db/migrate/20181031113522_create_delayed_jobs.rb
- db/structure.sql
This persists jobs into the database, and uses locking to ensure that workers from multiple machines avoid treading on each other.
Jobs can be run by using `bundle exec rake jobs:work`
Fixes #2015
> Set up Delayed Job as the backend for Active Job

- .rubocop_todo.yml
- app/controllers/changeset_controller.rb
- app/controllers/diary_entry_controller.rb
- app/controllers/messages_controller.rb
- app/controllers/notes_controller.rb
- app/controllers/users_controller.rb
- config/environments/test.rb
- test/controllers/changeset_controller_test.rb
- test/controllers/diary_entry_controller_test.rb
- test/controllers/messages_controller_test.rb
- test/controllers/notes_controller_test.rb
- test/controllers/users_controller_test.rb
- test/integration/user_creation_test.rb
- test/test_helper.rb
This PR builds on #2037 and configures email sending as a background task.
Note that this depends on having the setup for delayed_job (#2037) already merged, along with having workers running in production (https://github.com/openstreetmap/chef/issues/201), before this can be deployed - so I'm marking it as WIP until those prerequisites are met.
> Use deliver_later for email sending

- app/models/note_comment.rb
- app/views/browse/new_note.html.erb
- app/views/browse/note.html.erb
Follow up for #1543 
There's essentially no upper limit to notes comments, leaving the upload more or less unprotected to nonsense stuff like https://upload.apis.dev.openstreetmap.org/note/3
PR attempts to set the limit to 2000 characters both in the model, as well in the textarea (to avoid dealing with an unhappy backend). I'm not sure if anything else needs to be done to deal with existing (too long) comments.
> Limit note comment size to 2000 characters

- test/controllers/api_controller_test.rb
- test/controllers/browse_controller_test.rb
- test/controllers/geocoder_controller_test.rb
- test/controllers/redactions_controller_test.rb
- test/models/redaction_test.rb
I think these were first introduced around 2007, but they aren't needed currently.
> Remove unnecessary require statements from tests

- app/abilities/ability.rb
- app/controllers/redactions_controller.rb
- app/controllers/user_blocks_controller.rb
- test/controllers/redactions_controller_test.rb
- test/controllers/user_blocks_controller_test.rb
This PR refactors user blocks and redactions to use CanCanCan. 
This does change the response slightly for forbidden actions, rather than redirecting to :index with a flash message. But I'm happy with the simplification and I doubt anyone will notice the difference.
> CanCanCan for user blocks and redactions

- app/controllers/diary_entries_controller.rb
- app/controllers/issue_comments_controller.rb
- app/controllers/issues_controller.rb
- test/controllers/diary_entries_controller_test.rb
- test/controllers/issue_comments_controller_test.rb
- test/controllers/issues_controller_test.rb
- test/system/issues_test.rb
Since these pages are not accessed by normal users, except for url fiddling, it's fine to respond with a generic access denied.
> Remove custom deny_access handlers

- app/abilities/ability.rb
- app/abilities/capability.rb
- app/controllers/application_controller.rb
- app/controllers/changeset_comments_controller.rb
- test/abilities/capability_test.rb
- test/factories/access_tokens.rb
This introduces different deny_access handlers for web and api requests, since we want to avoid sending redirects as API responses. See #2064 for discussion.
I think in the long term, we'll have separate deny_access handlers for web and api requests using controller inheritance, but I think this works as an intermediate stage while we're refactoring.
> Use CanCanCan for changeset comments

- app/controllers/application_controller.rb
- test/controllers/user_preferences_controller_test.rb
The Authenticate#allow? method (from oauth-plugin) sets `current_user` as a side effect of checking the token. But this allowed a valid token to access all actions that are available to that user, beyond the capabilities for that token.
This PR changes that, so that if there is a token, only the permissions from the Capability class are used. I've added a couple of tests that illustrate the change, to show that with the new approach you definitely need the allow_read_prefs permission on a token.
I went for the @request.env fiddling to make the request, since creating a fully signed request (as used in test/integration/oauth_test) is a bit more complex than I would like. But I'm open to other suggestions.
> Use only token capabilities when a token is provided

- app/abilities/ability.rb
- app/abilities/capability.rb
- app/controllers/application_controller.rb
- app/controllers/users_controller.rb
- config/locales/en.yml
- test/controllers/user_preferences_controller_test.rb
- test/controllers/users_controller_test.rb
This PR builds on #2083 , so it should wait until that is approved before reviewing.
> Refactor users_controller to use CanCanCan for authorisation 

- app/abilities/ability.rb
- app/abilities/capability.rb
- app/controllers/changesets_controller.rb
The expand_bbox method now needs `require_write_api` capability on tokens. 
I'm not sure whether this omission was intended previously, but I think it makes sense to require it from now on. I think it's quite unlikely that anyone has been creating changesets with one token and expanding the bbox with another, less privileged token.
> Use CanCanCan for changesets controller

- app/abilities/ability.rb
- app/controllers/amf_controller.rb
- app/controllers/browse_controller.rb
- app/controllers/directions_controller.rb
- app/controllers/export_controller.rb
- app/controllers/geocoder_controller.rb
- app/controllers/search_controller.rb
- app/controllers/swf_controller.rb
This PR brings our authorization framework to search, export, browse, directions and swf controller, and ignores authorization for amf_controller since that handles both authorization and authentication itself.
> More authorization refactoring

- app/controllers/api_controller.rb
- app/views/api/capabilities.builder
- app/views/api/permissions.builder
- app/views/notes/index.xml.builder
- app/views/notes/show.xml.builder
- app/views/users/api_read.builder
- app/views/users/api_users.builder
- lib/osm.rb
This PR uses an xml builder template to create the API capabilities response, rather than building the xml response 'by hand' in the controller. This makes the code easier to read, as well as more closely following the MVC conventions.
It also refactors the other builder-based XML responses to use the same set of root attributes (i.e. adding copyright, attribution and license attributes) as the other XML responses.
> Use an xml builder to generate the capabilities response

- Gemfile
- Gemfile.lock
- app/assets/stylesheets/common.scss
- config/initializers/sanitize.rb
- config/locales/en.yml
- lib/rich_text.rb
- test/lib/rich_text_test.rb
As suggested by @gravitystorm in #2103 this switches our markdown formatting to use kramdown instead of redcarpet.
As kramdown doesn't have the builtin sanitisation features of redcarpet I have passed the resulting HTML through the sanitiser used for other formats and have also added a few extra restrictions to links in user generated content.
Note that this doesn't fix all the issues in #2103 as bullet lists nested in numbered lists still don't seem to work as the reporter there is expecting.
Also I noticed that redcarpet was turning thinks which look like links but have no link markup into links which kramdown doesn't - we could fix that by running our autolinker if we wanted.
> Switch to using kramdown for markdown formatting

- app/controllers/application_controller.rb
- app/controllers/errors_controller.rb
This PR enforces the use of cancancan authorization checks on all actions, and cleans up some no-longer-required authorization methods.
https://github.com/CanCanCommunity/cancancan/wiki/Ensure-Authorization
> Enforce cancancan on all actions

- CONFIGURE.md
When setting up a development-Server, ` i18n:js:export` is, according to [The i18n-js docs](https://www.rubydoc.info/gems/i18n-js/2.1.2) run automatically.
When setting up a production-Server it is required to run it manually before precompiling the assets.
> Advise to run i18n:js:export before assets:precompile

- config/locales/en.yml
This allows our translators to work in languages not yet supported by the upstream plugin. Fixes #2128
> Copy i18n strings from validates_email_format_of plugin

- CONTRIBUTING.md
- test/test_helper.rb
This enables the simplecov output, in case a developer wants to investigate the coverage locally. The instructions on how to do this from coveralls are incorrect, so this approach is slightly different. I've also chosen to silence the output message since it's not usually interesting or actionable.
> Enable simplecov output

- app/controllers/api/amf_controller.rb
- app/controllers/api/capabilities_controller.rb
- app/controllers/api/changes_controller.rb
- app/controllers/api/changeset_comments_controller.rb
- app/controllers/api/changesets_controller.rb
- app/controllers/api/map_controller.rb
- app/controllers/api/nodes_controller.rb
- app/controllers/api/notes_controller.rb
- app/controllers/api/old_controller.rb
- app/controllers/api/permissions_controller.rb
- app/controllers/api/relations_controller.rb
- app/controllers/api/search_controller.rb
- app/controllers/api/swf_controller.rb
- app/controllers/api/tracepoints_controller.rb
- app/controllers/api/traces_controller.rb
- app/controllers/api/user_preferences_controller.rb
- app/controllers/api/users_controller.rb
- app/controllers/api/ways_controller.rb
- app/controllers/api_controller.rb
- app/controllers/application_controller.rb
- app/controllers/browse_controller.rb
- app/controllers/changeset_comments_controller.rb
- app/controllers/changesets_controller.rb
Follows on from #2160 and #2161 
This PR refactors the API controllers to inherit from a common ApiController. This allows us to move some methods out of ApplicationController, and simplify other things like the deny_access handler.
I've also taken the opportunity to mark all these methods as private, to avoid surprises if there's ever controller actions with the same name, and adjusted some before_actions appropriately.
There's more work to be done on this topic, but this makes a good start.
> Create a common ApiController for API controllers

- Gemfile
- Gemfile.lock
- app/models/trace.rb
- lib/gpx.rb
- test/models/trace_test.rb
Non-rigourous testing shows a significant speedup, even on ssds.
> Use activerecord-import for bulk importing tracepoint records

- app/controllers/changesets_controller.rb
It makes no difference today, but prevents problems in future if methods accepting post requests are added to this controller in future.
I didn't pick this up as being unnecessary during earlier refactorings, since it currently applies to one of the methods in this controller, but there's no need for it to do so.
> Check validity token in changesets controller

- app/controllers/api/traces_controller.rb
I spotted that this was only implemented for the non-api methods in https://github.com/gravitystorm/openstreetmap-website/commit/e59f1b610817ad8442bc639d479cebe0a851c05a and https://github.com/gravitystorm/openstreetmap-website/commit/581eca3bbe3f2e8a657d5f72afe6cbe261d4d8bf
> Use the trace jobs for creating and destroy traces via the API

- app/abilities/api_ability.rb
- app/abilities/api_capability.rb
- app/controllers/api_controller.rb
- app/controllers/application_controller.rb
- test/abilities/abilities_test.rb
- test/abilities/api_abilities_test.rb
- test/abilities/api_capability_test.rb
This will allow us to rename actions without causing permissions headaches. The choice of abilities files is made by inheriting from either `api_controller` or `application_controller`.
Also rename `capabilities` to `api_capabilites`, for consistency.
> Disentangle the api abilities from the web abilities

- config/settings.yml
I think it's a good idea to use the trace jobs queue by default now, even while we wait on #2132.
> Enable trace jobs by default

- .rubocop_todo.yml
- app/assets/javascripts/leaflet.map.js
- app/assets/javascripts/user.js
- app/controllers/users_controller.rb
- app/models/user.rb
- app/views/layouts/map.html.erb
- app/views/users/terms.html.erb
- config/locales/en.yml
- db/migrate/20181020114000_add_user_tou_agreed.rb
- test/controllers/users_controller_test.rb
- test/integration/user_creation_test.rb
- add links to the ToU in the Welcome box and on the About page
- add tou_agreed to users table
- require checking a checkbox that the ToU have been read for signup
Missing:
~~- [ ] tests~~
> Add links to the ToU and include them in signup

- .rubocop_todo.yml
- app/abilities/ability.rb
- app/controllers/diary_entries_controller.rb
- app/views/diary_entries/_form.html.erb
- app/views/diary_entries/edit.html.erb
- app/views/diary_entries/index.html.erb
- app/views/diary_entries/new.html.erb
- app/views/layouts/_header.html.erb
- app/views/site/about.html.erb
- app/views/users/show.html.erb
- config/locales/en.yml
- config/routes.rb
- test/controllers/diary_entries_controller_test.rb
- test/controllers/users_controller_test.rb
- test/integration/user_diaries_test.rb
- test/system/diary_entry_test.rb
This PR contains some refactoring of diary entries, to use `:create` and `:update` methods separate from the `:new` and `:edit` methods. The routes are also partially refactored to use resources, and various path names are therefore adjusted.
@Nikerabbit this PR contains some i18n key renames:
* diary_entries.new.publish_button -> helpers.submit.diary_entry.create
* diary_entries.edit.subject -> diary_entries.form.subject
* diary_entries.edit.body -> diary_entries.form.body
* diary_entries.edit.language -> diary_entries.form.language
* diary_entries.edit.location -> diary_entries.form.location
* diary_entries.edit.latitude -> diary_entries.form.latitude
* diary_entries.edit.longitude -> diary_entries.form.longitude
* diary_entries.edit.use_map_link -> diary_entries.form.use_map_link
> Diary refactoring

- app/controllers/diary_entries_controller.rb
- config/settings.yml
- config/settings/test.yml
- test/controllers/diary_entries_controller_test.rb
* This is to provide another tool to help spam fighting. It is, of course, not a panacea.
* The configuration value is set to zero hours in order to be 'least surprising' for anyone else deploying the code.
* You can change the setting without interfering with your test suite.
If this is merged, then it will be up to the sysadmins what value they want to set for osm.org. I would suggest 6 hours as a reasonable compromise between unnecessary delays and allowing enough time to allow admins (and/or moderators, see #2226) to take action. Of course, it's a setting that can be adjusted, and can be set back to 0 hours in the future.
> Allow a configurable delay for diary entry feeds

- Gemfile
- Gemfile.lock
- config/initializers/strong_migrations.rb
… to help developers avoid problems in production database schema changes.
I've used this gem in other projects and I find it really useful. For many developers it's not clear which migrations can be done near-instantly (e.g. adding a new column) and which migrations will lock a table, potentially for hours (e.g. adding a new column with a default value).
This gem highlights bad migrations during development, so that the developers can learn what the problems might be before the sysadmins find out in production. I've set it to ignore all existing migrations since some of them won't have been safe, but that no longer matters.
> Use strong_migrations 

- app/helpers/user_blocks_helper.rb
- app/views/user_blocks/edit.html.erb
- app/views/user_blocks/new.html.erb
- config/locales/en.yml
- config/settings.yml
This avoids admins from having to manually change end periods in the database.
Most of this diff is the helper to display durations in the dropdown menu in more friendly terms than e.g. "8766 hours". The hours are carefully picked to show up as rounded durations. It's possible to pick particular hours that don't fit the pattern, e.g. 36 hours, but handling those situations was becoming an exercise in over-engineering.
I also wanted to preserve the "0 hours" label since that's how those blocks are referred to in common parlance, and to avoid e.g. "about 1 month" and similar vagueness, so that precluded using the standard rails time_to_words helpers.
> Allow user_blocks to be created for longer periods

- .rubocop.yml
- .rubocop_todo.yml
Since the routes are more of a dsl than code, we've been happy to repeatedly bump up this number. But then that hides other code which has over-long block lengths hiding behind.
So instead let's exclude the routes from this metric.
Also, I keep getting failed travis builds due to this, so it's self-interested :-)
> Ignore the block length of the routes

- app/abilities/ability.rb
- app/controllers/diary_entries_controller.rb
- app/views/diary_entries/_diary_comment.html.erb
- app/views/diary_entries/_diary_entry.html.erb
- app/views/diary_entries/show.html.erb
- config/locales/en.yml
- config/routes.rb
- test/controllers/diary_entries_controller_test.rb
- test/system/diary_entry_test.rb
In https://github.com/openstreetmap/openstreetmap-website/pull/2226 @tomhuges wrote:
> I do really need an easy way to be able to see the user's diary posts or comments with deleted entries included. 
So here we go! This PR shows deleted diary entries to administrators, so long as the user hasn't also been deleted. It also shows deleted diary comments to administrators. It shows these deleted things deemphasized, and allows admins to restore them if desired.
There's a small difference in functionality between entries and comments, because comments are always shown (i.e. not filtered by user status). However, that was more complexity and we're already getting into some deep hypothetical weeds here.
> Show deleted diaries and diary comments to admins

- Gemfile
- Gemfile.lock
- lib/gpx.rb
Here's a pull request based on @mmd-osm's work with a few minor changes from me. It produces animated gifs that look identical to those generated by the external importer.
This PR contains two notable caveats:
* We uncovered [a bug](https://github.com/libgd/libgd/issues/499) in libgd itself. This PR works around the bug, and I wouldn't propose waiting for that bug to be fixed and the fix to work its way into distribution packages since that could take a while.
* We are using a forked version of the gd2-ffij gem, until the animation code is available in the upstream gem. I'm fine with that from a bundler point of view, but of course there's the risk that the animation code is either not upstreamed, or upstream ends up with a different implementation.
> Animated images for traces

- app/views/diary_entries/show.html.erb
- app/views/issues/_comments.html.erb
- app/views/messages/new.html.erb
- app/views/oauth_clients/edit.html.erb
- app/views/oauth_clients/new.html.erb
- app/views/redactions/edit.html.erb
- app/views/redactions/new.html.erb
- app/views/traces/edit.html.erb
- app/views/traces/new.html.erb
- app/views/user_blocks/edit.html.erb
- app/views/user_blocks/new.html.erb
- config/locales/en.yml
- test/application_system_test_case.rb
- test/system/issues_test.rb
I noticed this while working on the diary entries, so now I'm rolling it out more widely. In many cases we've been avoiding using the built-in translation keys for submit buttons, and hard-coding translations based on the file the form is in (rather than based on the model for the form). This has made some form refactoring harder than it needs to be, as well as just being a bit of a waste of time. Sometimes this has been done just because of copying other places where it was done first.
There's ample opportunity to improve these labels in the future - too many saves and not enough updates in my opinion! But I'll leave the strings mostly unchanged for now.
@nikerabbit this PR contains a few translation key renames:
* `diary_entries.show.save_button` -> `helpers.submit.diary_comment.create` …
> Adjust submit labels to use built-in i18n handling

- app/controllers/changesets_controller.rb
- app/controllers/diary_entries_controller.rb
- app/controllers/users_controller.rb
- app/models/friendship.rb
- app/models/user.rb
- app/views/users/show.html.erb
- test/controllers/changesets_controller_test.rb
- test/controllers/diary_entries_controller_test.rb
- test/controllers/users_controller_test.rb
- test/factories/friendships.rb
- test/models/user_test.rb
This PR refactors the Friend model and related code, primarily by renaming it to Friendship to more accurately describe the model. 
This also allows us to remove some naming gymnastics, so that user.friends is now a list of user objects.
I haven't actually renamed the database table, since that's a ton more work :smile:
> Refactor Friend into Friendships

- config/locales/en.yml
This allows translators to accurately translate times when they need to modify the distance_in_time beyond just adding 'ago'.
This PR represents the first step of the action plan in #2255
@Nikerabbit I wanted to check with you that all these translations will show up as "count" translations in Translatewiki? For example, so that 'x_seconds' will allow translators to use the normal "one/few/many/other" style count translations. Do we need to do anything special for that?
> Add translations for distance_in_time_ago

- app/views/api/changesets/changeset.builder
- app/views/api/changesets/changesets.builder
- app/views/api/notes/index.gpx.builder
- app/views/api/notes/index.json.jsonify
- app/views/api/notes/index.rss.builder
- app/views/api/notes/index.xml.builder
- app/views/api/notes/show.gpx.builder
- app/views/api/notes/show.json.jsonify
- app/views/api/notes/show.rss.builder
- app/views/api/notes/show.xml.builder
- app/views/api/users/index.builder
- app/views/api/users/show.builder
- app/views/diary_entries/_diary_index_entry.html.erb
- app/views/diary_entries/index.html.erb
- app/views/diary_entries/show.html.erb
- app/views/redactions/_redactions.html.erb
- app/views/redactions/index.html.erb
- app/views/traces/index.html.erb
- app/views/users/index.html.erb
During review of #2207 I realised that we can simplify a bunch of our partial calls. For example, if @trace is a `Trace` model, then instead of:
```
<%= render :partial => "trace", :object => @trace %>
```
... you can instead call...
```
<%= render @trace %>
```
... and Rails will find the partial named after the model, and pass the object into the partial automatically. It also works with collections.
> Simplify partial rendering when the partial is named after the model

- app/controllers/api/users_controller.rb
- app/controllers/site_controller.rb
Similar to #2278 , this simplifies render calls from within controllers when the action isn't being overridden.
> Avoid stating the action to render when it just matches the current action

- app/controllers/api/traces_controller.rb
- app/controllers/api/users_controller.rb
- app/models/trace.rb
- app/views/api/traces/_trace.builder
- app/views/api/traces/show.builder
- app/views/api/traces/trace.builder
- app/views/api/users/gpx_files.builder
- test/controllers/api/traces_controller_test.rb
This continues the work from #2164 for the "trace" class.
> Move gpx_file (trace) xml generation out of model and into view

- app/abilities/api_ability.rb
- app/controllers/api/versions_controller.rb
- app/views/api/versions/show.builder
- config/routes.rb
- test/controllers/api/versions_controller_test.rb
This will eventually replace the unversioned 'capabilities' call.
Client applications can use this versions call to find out what versions are available, if they support multiple versions. The capabilities of each version, and the format of the capabilities call, is then
able to change between versions. If a client only supports one version they can jump straight to the versioned capabilities call.
Additionally, supported versions are now a list of version identifiers, without any implications surrounding min/max values (e.g. guesswork for supported intermediate versions).
Fixes #2162
> Add support for an unversioned 'versions' API call

- .rubocop.yml
- .rubocop_todo.yml
There's no sensible way to refactor a controller test into multiple classes, so lets exclude them from the class length metrics to reveal other over-length classes.
Similar reasoning to #2250
> Ignore the class length of test files

- app/jobs/trace_importer_job.rb
- test/jobs/trace_importer_job_test.rb
If we delay sending failure notifications then they will fail because the trace will no longer exist.
As trace imports are running in the background anyway there doesn't seem to be any good reason to defer the emails.
Fixes #2312
> Send trace import result notification immediately

- db/migrate/005_tile_tracepoints.rb
- db/migrate/006_tile_nodes.rb
- db/migrate/013_add_email_valid.rb
- db/migrate/039_add_more_controls_to_gpx_files.rb
- db/migrate/044_create_user_roles.rb
- db/migrate/046_alter_user_roles_and_blocks.rb
- db/migrate/051_add_status_to_user.rb
- db/migrate/20110322001319_add_terms_seen_to_user.rb
- db/migrate/20120208122334_merge_acl_address_and_mask.rb
- db/migrate/20120219161649_add_user_image_fingerprint.rb
- db/migrate/20120808231205_add_counter_caches.rb
- db/migrate/20121005195010_add_diary_entry_counter_caches.rb
- db/migrate/20121012044047_add_image_use_gravatar_to_users.rb
- db/migrate/20150111192335_subscribe_old_changesets.rb
- db/migrate/20150222101847_rename_openid_url.rb
- db/migrate/20161011010929_subscribe_authors_to_diary_entries.rb
- db/migrate/20180204153242_tile_users.rb
A recent change to the user model triggered breakages in the database migrations. This is because the migrations have, until now, been using the live model in old migrations. When there is a table name change, or certain column changes, in the live model, this can blow up the old migration.
Instead, it's best practise that if a model is needed during the migration, the model is defined within the migration. This ensures that the model picks up the table name, columns etc that match what's in the database at that stage.
> Models in migrations

- config/locales/en.yml
This avoids using the OSM acronym, and uses better titles than urls for the help forum and the wiki. Both titles are based on the title of the linked sites.
Extracted from work on #2321
> Rework help page text

- app/views/diary_entries/_diary_entry.html.erb
This adds a class containing the user ID to the div element enclosing a diary entry.
So, for example, a diary entry I write would get the class `user_165`.
This enables a site viewer to add basic killfile-like functionality with Firefox's usercontent.css or extensions like Stylus.
> Add user_<uid> class to diary entry div

- app/views/layouts/error.html.erb
When reviewing #1550 I realised that the logo isn't clickable, whereas elsewhere on this site the logo in the top left links to the front page.
It's a reasonable convention so one I that I feel is worth implementing. I've used the same srcset/picture code as in the main header.
> Make the logo on the error pages clickable

- INSTALL.md
There seems to be an easy solution that does not have negative side effects. So I suggest to add it to the installation instructions until https://github.com/openstreetmap/openstreetmap-website/issues/2185 has a more permanent solution. 
Once https://github.com/openstreetmap/openstreetmap-website/issues/2185 is solved, this commit should be reverted.
The same issue came up in https://github.com/openstreetmap/openstreetmap-website/issues/2372, https://github.com/openstreetmap/openstreetmap-website/issues/2292#issuecomment-508531378, https://github.com/openstreetmap/openstreetmap-website/issues/2345#issue-478341245
> Add reference to settings.local.yml-file in installation.md

- config/locales/en.yml
…is for the comment
Refs https://trac.openstreetmap.org/ticket/5307
There's still an unfortunate double use of "comment" to mean both the
ChangesetComment and also the changeset's `comment` tag, but I can't see a
simple way to fix that.
> Rephrase changeset comment notifications to clarify the time

- .travis.yml
- CONFIGURE.md
- INSTALL.md
- db/functions/functions.sql
- db/structure.sql
- script/vagrant/setup/provision.sh
This repo contains code for three functions to be loaded into PostgreSQL as a shared library:
1. `maptile_for_point`, which is used only by the `/changes` API call. This API call is little-used and IMHO should be deprecated and removed. However, even now it's hardly on the hot path for most development activities.
2. `tile_for_point`, which is used only in migrations. At this point, it seems unlikely that anyone will be doing a migration on existing data which would call this function (most developers will be running migrations on an empty database, to set it up).
3. `xid_to_int4`, which is only used for replication using Osmosis and isn't used in the Rails code at all. Hopefully this will be replaced Real Soon Now, but until then it's a quite advanced feature that most developers won't …
> Remove need for shared library PostgreSQL functions

- VAGRANT.md
This is a reworking of #2367 since we do support multiple providers in the Vagrantfile, and we obviously don't need the note about xenial boxes any more.
For more info, see the discussion in #2367
> Rephrase note on vagrant providers

- CONFIGURE.md
- db/functions/functions.sql
- db/structure.sql
Thanks to @mmd-osm and @timwaters for [pointing out](https://github.com/openstreetmap/openstreetmap-website/pull/2383#discussion_r333039034) [there's a pure SQL version of `xid_to_int4`](https://github.com/openstreetmap/openstreetmap-website/pull/2383#commitcomment-35582035), so we might as well include that. I wasn't aware that anyone was using this, but @gravitystorm [knows of some (perhaps former) users](https://github.com/openstreetmap/openstreetmap-website/pull/2383#commitcomment-35587159). So it looks like perhaps this is worth including for completeness / parity?
:crossed_fingers: we get to replace all this soon with something compatible with PostgreSQL 10+.
> Add pure SQL version of xid_to_int4.

- app/assets/javascripts/index/query.js
15 decimal places for bbox lat/lon values seemed a bit excessive.
> Overpass query bbox to use map precision

- .travis.yml
These were removed from the structure file in 098e73479b466902cf48a07627f050dadd2fd73e
> Remove references to libpgosm during travis runs

- app/controllers/diary_entries_controller.rb
- app/views/layouts/_header.html.erb
- app/views/redactions/show.html.erb
- app/views/user_blocks/blocks_by.html.erb
- app/views/user_blocks/blocks_on.html.erb
- app/views/user_blocks/index.html.erb
- app/views/user_blocks/show.html.erb
- app/views/users/show.html.erb
This replaces various (but not all) uses of `current_user.administrator?` and `current_user.moderator?` to use the permissions system. This is what we would like to see new code follow, as it allows more flexibility for changing abilities in the future.
> Convert various user attribute tests to use permissions system

- app/models/node.rb
- test/controllers/api/changesets_controller_test.rb
- test/controllers/api/nodes_controller_test.rb
- test/controllers/api/old_nodes_controller_test.rb
- test/models/node_test.rb
- test/test_helper.rb
The `.to_xml` and `.to_xml_node` methods are only used in the tests, for creating 'fixture'-style payloads, and aren't used by the application code. This PR moves those methods into the tests as helper methods. 
It also changes the lat/lon formatting test, to test the rendered response from the controller. This should probably have been done when the output was refactored to use the xml builders, but I overlooked this during that review.
Followup work involves doing similar work for the other elements with .to_xml methods.
> Remove Node.to_xml

- app/models/user.rb
This is the first step of removing the column, see #2417. It needs to be deployed before a migration to remove it, since the columns are cached in ActiveRecord and things break if objects exist in memory
that expect the database column to be there.
Thanks to `strong_migrations` for pointing this out when I tried creating the migration first!
> Ignore the users.nearby column

- app/models/relation.rb
- app/models/way.rb
- test/controllers/api/changesets_controller_test.rb
- test/controllers/api/relations_controller_test.rb
- test/controllers/api/ways_controller_test.rb
- test/test_helper.rb
This is a followup to #2433, and makes the same change for ways and relations.
> Move to_xml methods from ways and relations into the tests

- app/abilities/api_ability.rb
- app/abilities/api_capability.rb
- app/controllers/api/user_preferences_controller.rb
- app/models/user_preference.rb
- app/views/api/user_preferences/_user_preference.xml.builder
- app/views/api/user_preferences/index.xml.builder
- config/routes.rb
- test/abilities/api_capability_test.rb
- test/controllers/api/user_preferences_controller_test.rb
This PR refactors two aspects of the user preferences:
* Renames the controller methods to follow rails conventions more closely
* Uses a view to build the xml responses
I really only wanted to do the second part, but I couldn't bring myself to do that without giving it a better method name first.
> Refactor user preferences

- app/abilities/ability.rb
- app/controllers/traces_controller.rb
- app/views/traces/show.html.erb
- config/routes.rb
- test/controllers/traces_controller_test.rb
This PR changes the action for destroying traces from 'delete' to 'destroy'. It brings it in line with rails conventions. The api/traces_controller already uses destroy.
> Use the conventional 'destroy' action name for destroying traces

- app/abilities/api_ability.rb
- app/abilities/api_capability.rb
- app/controllers/api/changesets_controller.rb
- config/routes.rb
- test/controllers/api/changesets_controller_test.rb
This pull request removes the `expand_bbox` call, see discussion in #2316 for details. I removed more test cases than I originally anticipated, so a bit of extra scrutiny would be advisable.
Note: Analysis of current production log files to spot potential (non-mainstream) users of this endpoint is still pending at this time.
Closes #2316
> Remove expand_bbox endpoint

- app/views/messages/show.html.erb
I noticed this while working on #2386. Previously, the "back" button always linked to the outbox, even if you were reading a received message. Now the "back" button links to the inbox or the outbox, depending on whether it's a received or sent message.
> Make the back button link to the inbox when reading received messages

- test/controllers/api/changesets_controller_test.rb
- test/controllers/api/relations_controller_test.rb
- test/integration/compressed_requests_test.rb
Squiggly heredocs were introduced in ruby 2.3 and I prefer the ability to indent the closing heredoc marker.
> Use squiggly heredocs instead of rails strip_heredoc

- app/assets/stylesheets/common.scss
- app/assets/stylesheets/parameters.scss
While working on some bootstrap-related stuff I noticed that we have multiple similar colours for off-white backgrounds, and then I noticed we have a lot of places where grey colours are hard-coded and either match or are slightly different from the grey colour parameters.
This PR refactors many of the explicit colours to use the colour parameters instead. Both off-whites have been unified and the lighter is now used. For the greens, I chickened out and kept the more vibrant ones separate from the standard ones, for now at least. Perhaps they can be unified with some colour functions like lighten. Also the greys have been combined into the three different greys from the palette, which cuts down on the number of different `1px solid X` variations.
> Use parameters for various colours

- app/views/diary_entries/comments.html.erb
- app/views/notes/mine.html.erb
- app/views/oauth_clients/index.html.erb
- app/views/user_blocks/_blocks.html.erb
- app/views/users/index.html.erb
While working on replacing our stripy table logic with an out-of-the-box bootstrap solution, I ran into a problem with table header rows getting the stripes applied to them. This is because we're missing `<thead>` wrappers on some tables.
This PR adds those wrappers, which currently do nothing much, but will make the future bootstrap work easier and those future commits much smaller.
> Wrap table header rows in thead

- app/models/user.rb
This is the final stage in the process. Now that the migrations are run, and apps restarted, it is safe to remove the ignore_column declaration.
Refs #2417 #2432 #2439
> Remove ignoring of nearby column

- .rubocop.yml
- .rubocop_todo.yml
- test/integration/user_creation_test.rb
Just two rubocop fixes while I was doing other stuff, namely:
* We're unlikely to ever document every method of our ruby code, so move the config out of the todo list
* Refactor some params hashes in the tests to reduce the maximum line length
> Rubocop fixes

- app/assets/stylesheets/common.scss
This PR adds the `resize: vertical` CSS property to comment textareas to fix a problem, where they could be dragged beyond the sidebar.
Furthermore, I've added a `min-height` to all textareas to not let them be too small to enable the display of a scrolling bar.
I've also added a `border-radius` to form fields, to make them more consistent with what we do with buttons and tables.
> Improve textarea behaviour

- app/assets/javascripts/index.js
- app/assets/javascripts/user.js
- config/locales/en.yml
This fixes the rather awkward strings "Du bist innerhalb von 2080 meters um diesen Punkt" (de), or "Вы находитесь в 2080 meters от этой точки" (ru).
> Translate units used by leaflet-locatecontrol

- .travis.yml
- db/structure.sql
We're using bionic in production, so I figured it would be good to do so in CI, too.
> travis: change dist to bionic

- app/assets/stylesheets/common.scss
This fixes a number of issues with the headings, by removing some reset rules (that are acting after the bootstrap reset + defaults and so are messing things up) and by removing some custom heading font sizes and allowing the bootstrap values to be used.
I've overridden the heading sizes for the sidebar temporarily (roughly making h2 the same as bootstrap h3, and h3/h4 the same as bootstrap h5) since there's a bunch of specific style rules preventing me from changing e.g. h2 -> h3. For example, the h2 in sidebar gets extra left padding, since it isn't included in the sidebar browse-section. Fixing all that will come in a future PR.
> CSS fixes for headings

- app/assets/stylesheets/_bootstrap-custom.scss
- app/assets/stylesheets/common.scss
- app/views/reports/new.html.erb
This removes custom colouring for the alert. The list overrides need to stay until we unpick more of our custom styling.
> Use a warning alert for reporting new issues

- app/assets/stylesheets/_bootstrap-custom.scss
- app/assets/stylesheets/common.scss
- app/views/traces/_trace.html.erb
- app/views/traces/show.html.erb
This PR makes a few minor changes to the traces display. It replaces some custom CSS with a combination of bootstrap badges, text-styles and inline display for the geo microformat.
> Trace CSS badges

- app/mailers/notifier.rb
Closes https://github.com/openstreetmap/openstreetmap-website/issues/2430
Context: _I'm subscribed to a blog post/changeset discussion/note and receive lots of emails by users replying to that post. As those emails don't include an In-Reply-To & References header, my inbox fills up with pages and pages of unrelated messages, rather than producing a nice threaded view of all emails._
> Add In-Reply-To, References headers to email

- app/assets/stylesheets/common.scss
No other headings are underlined, and the underlines look more like a section separator (e.g. dashed hr) and so visually separated the heading from its content.
> Remove the dashed underline from prose headings

- app/assets/stylesheets/common.scss
This is required when the sidebar overlaps the map, for example whenit is not full height on the welcome message.
> Reinstate background colour for sidebars

- app/assets/javascripts/index/query.js
- app/assets/stylesheets/_bootstrap-custom.scss
- app/assets/stylesheets/common.scss
- app/views/browse/changeset.html.erb
- app/views/browse/query.html.erb
- app/views/changesets/_changeset.html.erb
- app/views/changesets/index.html.erb
This PR fixes a few CSS issues that were highlighted in #2492 and others that I noticed while working on that. In summary:
* Uses bootstrap's list-group-flush to replace custom css, for sidebars with lists-with-lines-between
* Uses h6 for the changeset comment tag text
* Removes some unnecessary custom css rules
* Tweaks the rss icon to line it up with other icons
> Various CSS fixes

- app/controllers/users_controller.rb
- app/views/layouts/_header.html.erb
- app/views/users/logout.html.erb
- test/controllers/users_controller_test.rb
- test/system/user_logout_test.rb
This avoids needing to access the session id, which is currently only working with the memcache store.
The fallback page is preserved for anyone who wants to logout without using javascript.
Refs #2488
> Use a post link to logout

- app/assets/stylesheets/_bootstrap-custom.scss
- app/assets/stylesheets/common.scss
- app/assets/stylesheets/small.scss
- app/views/site/fixthemap.html.erb
- app/views/site/welcome.html.erb
- app/views/users/new.html.erb
- app/views/users/terms.html.erb
This refactors various pages in order to remove our custom layout grid, and to use the bootstrap grid instead. Since the bootstrap grid is responsive, it means that some pages (e.g. the fixthemap page) now look much better on small screens.
I changed very little on the /user/new page, but adding a wrapper div caused the diff to blow up. 
The commit messages contain further details on each change.
> Replace custom grid CSS with bootstrap grid

- app/assets/stylesheets/common.scss
- app/views/site/about.html.erb
- config/locales/en.yml
This is a minor refactoring of the about page. It splits one of the translation strings into two paragraphs, rather than having a <br> tag in the translation. And it removes some unused and some unnecessary custom CSS rules.
> Refactor layout for the about page

- app/views/diary_entries/show.html.erb
- app/views/messages/new.html.erb
- app/views/user_blocks/blocks_by.html.erb
- app/views/user_blocks/edit.html.erb
- app/views/user_blocks/new.html.erb
- app/views/users/no_such_user.html.erb
They are escaped properly without the h() call, and doing that just double-escapes them.
As part of #2494 I set my local users to have all kinds of weird usernames, and today I spotted some places where they are being double-escaped. I suspect that almost all our uses of h() have been redundant since rails 3.x, but I haven't checked the rest.
> Avoid double-escaping display names through the translation system

- lib/osm.rb
- test/application_system_test_case.rb
- test/controllers/api/users_controller_test.rb
- test/controllers/site_controller_test.rb
- test/controllers/users_controller_test.rb
- test/integration/oauth_test.rb
- test/integration/page_locale_test.rb
- test/integration/user_creation_test.rb
- test/integration/user_terms_seen_test.rb
- test/test_helper.rb
We haven't used hostip.info in production for years, except for when we did so by accident, leading to a two hour partial outage when it went down.
> Remove fallback to hostip.info

- app/assets/stylesheets/common.scss
The makes the tag tables more consistent with other tables, like messages, gps traces, user_blocks etc that use an offwhite background colour.
> Use offwhite instead of grey for browse pages tag tables

- app/views/diary_entries/index.html.erb
These are unnecessary, and also prevent the secondary-actions vertical border from appearing.
> Remove extra div wrappings from list items

- app/assets/stylesheets/common.scss
- app/views/issues/_comments.html.erb
- app/views/issues/_reports.html.erb
- app/views/issues/show.html.erb
- config/locales/en.yml
This change uses the bootstrap grid to make the issues page responsive, and avoids having lots of custom widths of divs specified via CSS.
It also changes the display of the reports and comments to be more like diary entry comments, by having all metadata on one line and shown before the comment / report text.
> Rework issues display page to be responsive

- app/views/site/copyright.html.erb
This fixes a small bug where the hr was shown even when not required, by ensuring the test is run before creating the content.
Also fixes where an h1 tag was used instead of a div.
> Minor tweaks to copyright heading

- app/assets/javascripts/leaflet.share.js
- app/assets/stylesheets/common.scss
- app/views/browse/changeset.html.erb
- app/views/diary_entries/_form.html.erb
- app/views/issues/show.html.erb
- app/views/messages/new.html.erb
- app/views/oauth_clients/_form.html.erb
- app/views/reports/new.html.erb
- app/views/traces/edit.html.erb
- app/views/traces/new.html.erb
- app/views/users/account.html.erb
- app/views/users/login.html.erb
- app/views/users/new.html.erb
- app/views/users/terms.html.erb
- test/controllers/users_controller_test.rb
- test/integration/user_creation_test.rb
This PR contains some changes that clean up our custom CSS rules.
* Rename form-row to standard-form-row, since form-row clashes with a class in the bootstrap forms component (and so things go badly awry when enabling the forms component).
* Rework lists to assume that they have margin+discs by default. It's easier to override them in the few cases that we don't want that to happen (e.g. forms, nav links) and the number of overrides is likely to decrease anyway as we use more bootstrap components
* Remove the custom reset code. Bootstrap contains its own reset, so there's nothing to be gained by resetting things again.
> Cleanup custom CSS

- app/assets/javascripts/index/query.js
- app/assets/javascripts/index/search.js
- app/assets/stylesheets/common.scss
- app/views/geocoder/results.html.erb
- test/controllers/geocoder_controller_test.rb
As requested in #2497 , this PR changes the search results to use list-groups, which sorts out the extra margins on that page. I also spotted some fallback text in the query tool that needed the new list item classes, so I've added them too.
> Use a list group for search results

- config/initializers/sanitize.rb
- lib/rich_text.rb
- test/lib/rich_text_test.rb
as the correct rel attribute in external links.
> Fix typo: change 'noreferer' to 'noreferrer'

- app/assets/javascripts/index/directions.js
When reversing a route with full or partial empty `to` and `from` inputs, we get an exception.
Steps to reproduce.
- open directions, 
- enter something in `to` input.
- hit reverse directions
- the variable `to` is undefined, but the properties `lat` and `lng` are accessed.
> Prevent exceptions while reversing directions

- app/assets/stylesheets/common.scss
- app/views/browse/_node.html.erb
- app/views/browse/_relation.html.erb
- app/views/browse/_way.html.erb
- app/views/browse/changeset.html.erb
- app/views/browse/note.html.erb
Here's a few styling fixes for parts of the sidebar. Thanks go to @mmd-osm for pointing some out!
* Re-add table border spacing rules for the tables where we use border-collapse: separate
* Remove list styling from various lists in the sidebar, like nodes in the browse way page
> Sidebar styling fixes

- app/views/site/help.html.erb
> Fix help page, grid card layout on mobile

- INSTALL.md
Removed an extra ')' that caused the last link for macosx-bundle-config to render incorrectly.
> Fix macosx-bundle-config link typo in INSTALL.md

- app/controllers/api/notes_controller.rb
Adds two new parameters to the notes search API to be able to
- specify the value the notes should be sorted by (either `created_at` or `updated_at`, `updated_at` remains the default value)
- specify the order of the returned notes (either `ASC` or `DESC`, `DESC` remains the default)
A new call to the notes search API may look like this:
[/api/0.6/notes/search?**sort_by=created_at&order_by=ASC**](https://api.openstreetmap.org/api/0.6/notes/search?sort_by=created_at&order_by=ASC)
See also #2380 for the reason of this pull request.
> Sort and order notes

- .rubocop.yml
- app/helpers/browse_tags_helper.rb
- test/helpers/browse_tags_helper_test.rb
Resolves #1689.
This will recognize most, but not all, valid email values and create mailto: links for them.
First used a regex suggested by the [W3C HTML spec](https://html.spec.whatwg.org/multipage/input.html#valid-e-mail-address) directly,  but changed to using the built-in `URI::MailTo::EMAIL_REGEXP` in 5d7b09e3bd0a072835d992abc4a5229c3fcb10f1.
A subset of valid emails containing comments, whitespace characters, and quoted strings may not be recognized.
> Show mailto: links for email values in browse

- app/assets/stylesheets/common.scss
With this PR, I fixed a minor visual bug with the search query input field. The border-radius caused the field to not touch the neighbouring button at its corners, which looked weird in my opinion.
**Before**
**After**
> Fix border-radius for search query input field

- app/views/browse/_common_details.html.erb
- app/views/browse/_containing_relation.html.erb
- app/views/browse/_relation_member.html.erb
- app/views/browse/changeset.html.erb
- app/views/changesets/index.atom.builder
- app/views/diary_entries/_diary_comment.html.erb
- app/views/diary_entries/_diary_entry.html.erb
- app/views/diary_entries/index.html.erb
- app/views/messages/_message_summary.html.erb
- app/views/messages/_sent_message_summary.html.erb
- app/views/messages/show.html.erb
- app/views/traces/_trace.html.erb
- app/views/traces/edit.html.erb
- app/views/traces/index.html.erb
- app/views/traces/show.html.erb
- app/views/user_blocks/_block.html.erb
- app/views/user_blocks/blocks_on.html.erb
- app/views/user_blocks/revoke.html.erb
- app/views/user_blocks/show.html.erb
- app/views/users/_contact.html.erb
- app/views/users/_user.html.erb
These were necessary in the rails 2.x era, but not now. Expands on the situations fixed by #2500
> Remove unnecessary h() calls on model attributes

- Gemfile
- Gemfile.lock
- test/controllers/api/traces_controller_test.rb
- test/controllers/traces_controller_test.rb
- test/factories/traces.rb
- test/models/trace_test.rb
- test/test_helper.rb
I spent some time trying to get the parallel tests to work. The main problem is surrounding the trace tests, since they make assumptions about removing files during the teardown stage. Since all the tests share the same directory, this causes test failures when one test is tearing down while the other is still using the dir.
I've reworked it so that the tests each get their own unique directory, using Dir.mktmpdir.
However, this appears to introduce some flakeyness to the test suite, and I'm not sure why. I'm sharing this WIP to see if other people also see the flakey tests, see what Travis says, and see if anyone has any better ideas!
> Parallel tests

- app/assets/javascripts/index/directions.js
The rename is only a refactoring preventing confusion like in https://github.com/openstreetmap/openstreetmap-website/pull/2521#discussion_r370989660
The variables `to` and `from` are not the same as the properties a few lines below.
> Rename internal variable to avoid confusion

- app/assets/stylesheets/common.scss
- app/views/issues/index.html.erb
- app/views/messages/inbox.html.erb
- app/views/messages/outbox.html.erb
- app/views/notes/mine.html.erb
- app/views/oauth_clients/index.html.erb
- app/views/site/key.html.erb
- app/views/traces/_trace.html.erb
- app/views/traces/show.html.erb
- test/controllers/messages_controller_test.rb
- test/controllers/traces_controller_test.rb
This removes the custom table styling code, and move to using bootstrap table styling for almost all remaining tables.
> Remove custom table styling

- .rubocop.yml
- .rubocop_todo.yml
- Gemfile
- Gemfile.lock
I found this gem recently while investigating other things, and I think it makes sense to add it. I've updated the `rubocop_todo.yml` file with the currently failing tests, so this PR is just to add the gem. Changes to the test suite will be added in future PRs.
> Add rubocop-minitest

- app/models/client_application.rb
- test/models/client_application_test.rb
Replacement PR for #2570 and #2578 
This replaces our homegrown regexps (that didn't quite work) with ruby built-in regexps, and uses the termination anchor to ensure that the entire string, not just the first part, is validated.
> Ensure that urls are only valid if the entire string is a url

- app/views/notifier/gpx_success.html.erb
- config/locales/en.yml
Correctly pluralize the word point in the notification message based on the given possible points.
The `count` parameter is needed in order to provide the necessary information to i18n choose the right message.
Solves #2397
> Notifier message pluralization

- app/models/trace.rb
In this situation, `trace_name` can be trivially checked as legitimate, but this removes any lingering risks from interpolating into a command line instead of passing parameters explicitly.
Refs #2229
> Use Open3.capture2 instead of backticks, to avoid command line injection risks

- config/routes.rb
- test/controllers/site_controller_test.rb
- test/test_helper.rb
This is the modern way of writing controller tests, since it uses the rails middleware (among other things) and leads to more realistic tests.
Refs #2563
If we're all happy with this, then I can refactor all the remaining controller tests in order to unblock #2563
> Refactor site controller tests to inherit from ActionDispatch::IntegrationTest

- app/models/trace.rb
- config/initializers/tempfile.rb
Effectively reverts c0d2ad40c30e5a0837b6012d7b9067d69ce41dd0
This patch is no longer required, since we only use send_data in combination with Tempfile.read and that all works fine. 
And going by the original commit message, it might not have been needed after we upgraded from ruby 1.8.4
> Remove tempfile patch for trace data

- .travis.yml
- Gemfile
- Gemfile.lock
- INSTALL.md
- test/application_system_test_case.rb
This switches to using selenium with a headless firefox to run system tests. I would have preferred to use chrome (possibly running firefox as well in travis at least) but https://bugs.chromium.org/p/chromium/issues/detail?id=775911 means that headless chrome is a pain as we can't control `Accept-Language` fully.
> Switch to using selenium for system tests

- config/routes.rb
- test/controllers/api/capabilities_controller_test.rb
- test/controllers/api/changes_controller_test.rb
- test/controllers/api/changesets_controller_test.rb
- test/test_helper.rb
For the changesets_controller_test, I introduced a few more route aliases. I'm not super keen on some of them (like api_node) but that's to distinguish them from the non-api method that already has the name. Refactoring the routes is left for the future.
The two new helper methods will replace the existing ones, we only need both sets during the transition.
> Refactor more controller tests

- config/routes.rb
- test/controllers/api/traces_controller_test.rb
- test/controllers/users_controller_test.rb
- test/test_helper.rb
This refactors api/traces_controller_test and user_controller_test. The latter was a bit tough, since a lot of the tests involved somewhat artificial setup involving direct access to the session. In many cases around the testing of the terms and confirmation pages, the approach I've taken is to work through the first half of the signup process, to get the session into the expected state.
I found a bunch of tests were misnamed, since they were called 'test_new_something' but were testing the save method. Some things like duplicate emails are tested both during the submission of the signup form, and again during the creation of the user record in the save method. So I've renamed the tests and kept them testing the second stage, since it's more important. I added one test for the first step …
> Final controller test refactorings

- app/views/diary_entries/index.html.erb
- config/locales/en.yml
The link is only displayed when we don't display a user diary. Affected views are the global, localized ones, friends and nearby ones.
Fix #2620
> Add link to my diary in the diary index

- config/initializers/query_cache.rb
I don't know why the query cache was originally intended to be disabled, since the [original commit](0d8e4b4337e9b94b6a9ed85095005a779f69583c) doesn't give any reason or links to tickets.
However, this initializer seems to be ineffective, since queries are being successfully cached on my local machine, and as far as I can tell, there's no middleware with that name any longer. Perhaps this is all just historical stuff?
So this PR just removes the initializer.
> Remove ineffective query cache disable initializer

- app/abilities/ability.rb
- app/controllers/users_controller.rb
- app/views/users/show.html.erb
- config/routes.rb
- test/controllers/users_controller_test.rb
This renames the delete action to destroy, and starts using resourceful routing for user actions.
> Rework user#set_status and #delete to avoid GET requests

- app/views/site/copyright.html.erb
- config/locales/en.yml
This changes the text describing the tile licence as per decision of the OSMF board starting July 1st 2020. 
There might be a bit of fine tuning before this is finalised, in any case it should not go live before July 1st.
> Change tile licence (pls merge 2020.7.1)

- app/assets/stylesheets/common.scss
- app/views/messages/show.html.erb
This switches the message buttons to use bootstrap, so that we can have a back button that looks clickable.
Alternative implementation of #2386
> Make the back button not look disabled

- app/views/site/_markdown_help.html.erb
I missed this ban in January during https://github.com/openstreetmap/openstreetmap-website/pull/2508
> Avoid list markers for the richtext help text

- config/locales/en.yml
In an effort to resolve the long-outstanding #1632, I'm proposing this slight change to the about text. This is based on [my suggestion](https://github.com/openstreetmap/openstreetmap-website/pull/1632#issuecomment-367891236) adapted with [the feedback to stick with the word 'map'](https://github.com/openstreetmap/openstreetmap-website/pull/1632#issuecomment-368039431). 
Thanks to @klumbumbus for the original suggestion.
> Rephrase the 'used_by' text on the about page.

- app/abilities/ability.rb
- app/controllers/notes_controller.rb
- app/views/notes/index.html.erb
- app/views/users/show.html.erb
- config/locales/en.yml
- config/routes.rb
- test/abilities/abilities_test.rb
- test/controllers/notes_controller_test.rb
This is a simple renaming to use a more resourceful action name. The "user" part of "user_notes_path" is what it would be if we refactored the routes to use nested resources, so it's a bit of future proofing.
> Rename the notes#mine action to index

- app/controllers/api/changesets_controller.rb
- app/controllers/api/notes_controller.rb
- app/controllers/api/traces_controller.rb
- app/controllers/api/users_controller.rb
These were left over from the refactoring of the controllers into api and non-api versions.
I'm pretty sure that none of the API calls output html, but I wouldn't bet on it!
> Remove unnecessary layout calls from api controllers

- app/assets/stylesheets/common.scss
- app/assets/stylesheets/small.scss
- app/views/users/account.html.erb
- app/views/users/show.html.erb
This uses bootstrap instead, ensuring the map shows before the text on small screens, but to the right of it on md+ widths. The height of the map also changes at this breakpoint instead of being based on the menu width (body.small).
The account edit page was also changed to match the content_map changes, and a full width map is now used. This can be changed, if required, using bootstrap breakpoints but I like it as it is.
> Rework the users#show page to avoid custom column css

- app/assets/javascripts/embed.js.erb
- app/assets/javascripts/leaflet.map.js
- config/locales/en.yml
- vendor/assets/leaflet/leaflet.osm.js
The layer has been approved by the OWG, I just took longer than expected to add it.
There was some discussion with @gravitystorm about naming in IRC a few weeks back. I think this naming is consistent with what we've done with other layers, using the layer name rather than a description. We've used that for MapQuest, HOT, Transport, and close to that to OpenCycleMap.
> Add OPNVKarte

- app/assets/javascripts/application.js
- app/assets/stylesheets/common.scss
- app/assets/stylesheets/small.scss
- app/views/issues/show.html.erb
This PR contains several CSS cleanups. 
The main theme is continuing the work of disentangling the small screen stuff (which should be done with media breakpoints or builtin bootstrap functionality) from the navigation bar changes (which is based on the length of the text in the menus, not on the screen size).
Various other changes were found during this work too.
> More CSS cleanups

- app/assets/javascripts/index/browse.js
- app/assets/stylesheets/common.scss
- app/views/browse/new_note.html.erb
- app/views/browse/note.html.erb
- app/views/site/export.html.erb
This work is based on the ideas from #1773 but with bootstrap alerts.
Pictures tell a thousand words:
The last of these took some rearranging of the jquery-crafted html, so I can rework that bit if necessary. But other than that I think they are much better than the merely indented paragraphs that we had before.
> Rework various warnings

- app/assets/javascripts/index/directions/graphhopper.js
No way of actually testing if this works, but it is based on https://docs.graphhopper.com/#operation/getRoute/parameters/point and https://www.graphhopper.com/blog/2020/07/08/turn-restriction-support-for-graphhoppers-directions-api/
> Turn on turn restriction support for graphhopper

- app/views/browse/_common_details.html.erb
- app/views/browse/note.html.erb
This matches the one for nodes. Fixes #1355. Replacement for #1773.
An unstyled list works better for the details section, particularly when all three are shown.
The change to the named path in the nodes template is based on a review I gave in #1773.
> Add a browse map link to notes

- .travis.yml
- CONTRIBUTING.md
- Gemfile
- Gemfile.lock
- config/brakeman.yml
This is my preferred version of #2229 
I've also reviewed the currently ignored warnings. Many of them are in code that will soon be either removed (amf_controller) or refactored (trace file handling) so I'm not prioritising fixing them at the moment. But at least having Brakeman included will prevent other errors from being accidentally introduced.
> Use Brakeman for static code analysis

- app/assets/javascripts/index.js
This means that if you pan to a 'copy' of the world, the overlays reappear on that copy.
https://leafletjs.com/reference-1.6.0.html#map-worldcopyjump
Fixes #2040
> Use the worldCopyJump option for leaflet overlays

- test/controllers/api/ways_controller_test.rb
- test/controllers/changesets_controller_test.rb
This PR fixes #2614. Minor refactoring of tests to create relevant objects, and test against them. Previously these tests were asserting against empty database queries, since the fixtures were removed a few years ago.
> Avoid testing against empty db queries

- app/assets/javascripts/index/directions/graphhopper.js
I know there was a bit forth and back in #2695 and my last recommendation was to use turn_costs=true. This was not intended for bike and foot - they are currently broken :( ... which this PR fixes.
Sorry for this.
> turn_costs=true only for car

- config/settings.yml
Sorry that this is necessary but as iD is currently dead in the water this seems to be the only expedient way of stopping people to use these two layers, which are not available on OSM compatible terms. Hopefully in the long term this can be removed again. 
PS: tested locally with iD.
> Black list 2010 and 2016 imagery for the Canton Schaffhauen

- config/settings.yml
Sorry, didn't realize that the GL imagery was still available in iD too.
> Block Canton Glarus imagery too

- app/views/browse/_common_details.html.erb
- app/views/browse/note.html.erb
- app/views/diary_entries/_location.html.erb
- app/views/traces/show.html.erb
- config/locales/en.yml
Use the i18n system for joining coordinate values together, while avoiding making any changes or standardisation involving the exact symbol used in each situation.
Refs #2732
This was mentioned in passing in the linked issue, so I thought I could at least fix that minor point. It doesn't change anything wrt decimal separators, and it's worth noting that we've been inconsistent in the past with `,` vs `;` within pairs of coordinates and this PR deliberately doesn't change either option, just moves them into the i18n files.
> Avoid lego translations for coordinates

- app/helpers/reports_helper.rb
- app/views/issues/index.html.erb
- app/views/oauth_clients/_form.html.erb
- app/views/oauth_clients/edit.html.erb
- app/views/oauth_clients/new.html.erb
- app/views/oauth_clients/show.html.erb
- app/views/reports/new.html.erb
- config/locales/en.yml
This refactors the reports, issues and client_application forms to use Bootstrap form components.
The bootstrap_form `collection_radio_buttons` helper expects a group of objects that respond to methods, so we can't use the array of report category strings directly. I think the helper method is the best approach to this, since it leaves the form itself easy to read.
> Bootstrap forms

- app/assets/stylesheets/common.scss
- app/views/changesets/index.html.erb
- app/views/geocoder/results.html.erb
- app/views/layouts/map.html.erb
- app/views/site/fixthemap.html.erb
Fixes #2774 
I also found one more unstyled button on the fixthemap page. 
The preferred option is to use bootstrap buttons, but in one case I used the `standard-form` class as a temporary workaround. After refactoring, the `load_more` class was no longer necessary.
> Fix buttons

- app/views/browse/_node.html.erb
- app/views/browse/_relation.html.erb
- app/views/browse/_way.html.erb
- config/locales/en.yml
Fixes #2823
The panels are collapsed by default, when there is a long list of features, but open on short lists to save on clicks. 10 items is arbitrary but seemed reasonable.
This is one of those "how hard can it be", "oh wait that took longer than expected" kinds of thing. Thanks to @tordans for the pure-html suggestion, I think it looks reasonable. But I think a proper designer could do better. I'm not 100% happy with the duplication between the `<h4>` section titles and the `<summary>` labels, but putting titles in the summaries breaks the layout and I think this PR is at least a little better than the previous situation. Similarly, I went back and forth on whether small lists should be handled differently, whether small lists should even have the summaries, and trying to balance …
> Show linked features as collapsable detail panels on feature browse pages

- app/views/browse/_common_details.html.erb
- app/views/browse/changeset.html.erb
- app/views/changesets/_changeset.html.erb
- app/views/users/_contact.html.erb
Alternative to #580
This reworks changeset descriptions to use italics instead of header elements, in order to make them look more like quotes.
I've always found it strange that they were headers, particularly on the node/way/relation pages, since they are more similar to a text paragraph or a quote than a description of the element being viewed. But it turns out to be quite tricky to refactor, since the descriptions appear in multiple contexts, and the partials are repeated in history pages and look strange unless the first item is a header.
So this is my proposed solution, feedback welcome.
> Style changeset descriptions with italics on browse pages

- .rubocop.yml
- db/seeds.rb
- script/locale/reload-languages
This is seed data that should reasonably be loaded into every database, even those that are otherwise empty (e.g. no geo data). Using the seeds process means that it will often be loaded by default (depending on exactly which db tasks are run), and is easier to find for existing rails developers.
Replaces #309
> Use the db:seed task to load languages

- config/locales/en.yml
I believe these translations are currently unused, unless the keys are generated using some kind of programmatic trickery. Each commit shows where the usage was removed from the codebase.
> Remove some unused translations

- .rubocop_todo.yml
- app/controllers/users_controller.rb
- app/helpers/note_helper.rb
- app/helpers/open_graph_helper.rb
- app/views/browse/changeset.html.erb
- config/locales/en.yml
We can avoid using `html_safe` in various circumstances, through alternative approaches like i18n keys ending in `_html` or using `safe_join` to avoid converting via unsafe string types.
The `_html` keys approach only work for ActionView helper version of `t`, not the base `I18n.t` method.
> Avoid various uses of html_safe

- FAQ.md
- Link to the official Banner Policy page on the OWG website instead of a GitHub ticket discussion
- Reformat Markdown lists so that the rendered HTML results in properly nested lists
> Link to official OWG Banner Policy page

- app/views/application/_sidebar_header.html.erb
- app/views/browse/changeset.html.erb
- app/views/browse/feature.html.erb
- app/views/browse/history.html.erb
- app/views/browse/new_note.html.erb
- app/views/browse/not_found.html.erb
- app/views/browse/note.html.erb
- app/views/browse/query.html.erb
- app/views/browse/timeout.html.erb
- app/views/changesets/history.html.erb
- app/views/geocoder/search.html.erb
- app/views/layouts/map.html.erb
- app/views/site/export.html.erb
- config/locales/en.yml
This ensures that the text and the close icon don't overlap, regardless of the length of the title. The title div grows to use all available space, while ensuring the text breaks if necessary to prevent it from pushing the close icon offscreen.
* Fixes #2530 
* Fixes #2850 
* Alternative to #2537
* Alternative to #2872
> Use flexbox to position the close icon on the sidebars

- .rubocop_todo.yml
- app/helpers/changesets_helper.rb
- app/helpers/geocoder_helper.rb
- app/helpers/user_blocks_helper.rb
- config/locales/en.yml
We can use `html_safe` on non-interpolated strings, since that's trusted content.
> Avoid some (more) uses of html_safe

- .rubocop_todo.yml
- test/abilities/api_capability_test.rb
- test/controllers/api/nodes_controller_test.rb
- test/controllers/api/old_nodes_controller_test.rb
- test/controllers/api/relations_controller_test.rb
- test/controllers/api/ways_controller_test.rb
- test/helpers/browse_helper_test.rb
- test/integration/client_applications_test.rb
- test/integration/short_links_test.rb
- test/integration/user_blocks_test.rb
- test/integration/user_creation_test.rb
This PR includes a small refactoring, and marking many utility methods in the test suite as `private`, in order that we can enable the `Minitest/TestMethodName` cop.
> Enable minitest test name cop

- .rubocop_todo.yml
- app/controllers/api/notes_controller.rb
- app/controllers/application_controller.rb
- app/controllers/browse_controller.rb
- app/controllers/changeset_comments_controller.rb
- app/controllers/changesets_controller.rb
- app/controllers/users_controller.rb
- app/helpers/browse_helper.rb
- app/views/browse/changeset.html.erb
- test/helpers/browse_helper_test.rb
- test/models/diary_entry_test.rb
- test/models/trace_test.rb
- test/models/tracetag_test.rb
This PR fixes some cases where we are using optional boolean parameters, to use keyword arguments instead.
I think this is particularly useful where the method definition lies elsewhere, since it's not obvious what an isolated 'true' or 'false' means.
https://docs.rubocop.org/rubocop/1.0/cops_style.html#styleoptionalbooleanparameter
> Prefer keyword arguments when method has optional boolean arguments

- config/initializers/sanitize.rb
This is an alternative implementation of #2959 that overrides the kramdown converter to add the classes instead of trying edit the generated HTML with a search and replace.
> Add bootstrap classes to markdown tables

- app/mailers/user_mailer.rb
- app/views/user_mailer/_gpx_description.html.erb
- app/views/user_mailer/gpx_failure.html.erb
- app/views/user_mailer/gpx_success.html.erb
- config/locales/en.yml
- test/mailers/user_mailer_test.rb
Fixes #2268.
Unfortunately there's still a lego translation when both halves of the sentence are joined together, but this at least reduces the number of combinations to translate.
> Refactor trace notifications to reduce lego translations

- config/initializers/action_mailer.rb
- config/settings.yml
This allows easier configuration using the settings.local.yml files
Fixes #2571
> Allow smtp settings to be configured through the settings system

- app/controllers/geocoder_controller.rb
- config/locales/en.yml
This adapts to two changes in place handling by Nominatim:
* Place links that are computed by Nominatim are now found in extratags['linked_places']. Keep the check for extratags['place']
as this may contain an explicitly mapped place label.
* Use address rank for guessing the boundary type. This gets normalised by Nominatim with respect to country-specific use of admin_level.
Also adds additional labels for admin levels, so that we now have complete coverage for all levels that are in use in OSM.
I would have liked to avoid the long line but rubocop insisted on using a modifier if.
> Improve guessing of labels for Nominatim results

- app/mailers/user_mailer.rb
- app/views/user_mailer/changeset_comment_notification.html.erb
- app/views/user_mailer/diary_comment_notification.html.erb
- app/views/user_mailer/diary_comment_notification.text.erb
- app/views/user_mailer/email_confirm.html.erb
- app/views/user_mailer/email_confirm.text.erb
- app/views/user_mailer/friendship_notification.html.erb
- app/views/user_mailer/lost_password.html.erb
- app/views/user_mailer/lost_password.text.erb
- app/views/user_mailer/message_notification.html.erb
- app/views/user_mailer/message_notification.text.erb
- app/views/user_mailer/note_comment_notification.html.erb
- config/locales/en.yml
- test/mailers/user_mailer_test.rb
This PR contains some translation-related refactoring for the user_mailer.
It took me two attempts to get this right, since there's some subtleties about how the `_html` translations interact with plain text mail templates, and so I had to revisit and refactor some (unsubmitted) work that was done last week when I realised what was going on. But I've added a test that would have caught my mistake earlier.
In short, `_html` translations take the translation options (e.g. something like `t(".foo", :username => "Jack & Jill")`, html_escapes the options, interpolates them into the translation, and returns the whole thing as a SafeBuffer to avoid further html_escaping in the template. Putting that straight into an html template is fine, since it a) is already a safebuffer and b) is already …
> Mailer refactoring

- app/views/user_mailer/message_notification.html.erb
The new key was added to the translations config file in #2993 
Thanks to @woodpeck for reporting at https://github.com/openstreetmap/openstreetmap-website/pull/2993#issuecomment-740623075
> Add missing html suffix to translation key

- app/controllers/api/tracepoints_controller.rb
- app/models/user.rb
- test/models/user_test.rb
This was originally going to involve getting rid of the to_xml for tracepoints, and move to a builder view for that, but I got bogged down in the gpx file building stuff and had to abandon that.
So this PR is some stand-alone work that was going to be in that PR but may as well be used separately.
> Refactoring for to_xml

- Vagrantfile
Fixes #2972
Like others, I found that the previous setting caused OOM failures, and 4096 was sufficient. I suspect lower values will also work, but I don't have time or inclination to bisect a smaller value.
> Increase memory given to the virtualbox vm

- .rubocop_todo.yml
- Gemfile
- Gemfile.lock
- app/controllers/api/amf_controller.rb
- app/controllers/application_controller.rb
- lib/nominatim.rb
- lib/osm.rb
SystemTimer was only needed on ruby 1.8, and we dropped support for that a long time ago.
https://web.archive.org/web/20110820091021/http://ph7spot.com/musings/system-timer shows the creator of SystemTimer saying not to use it on other versions of ruby.
> Remove SystemTimer and use stdlib Timeout directly

- lib/osm.rb
- test/lib/osm_test.rb
Fixes #3007. 
If all the provided points in the gpx file have the same lat/lon, then an image where they are all at the centre seems plausible.
> Return the centre of the image if the bbox has no extent

- app/assets/stylesheets/common.scss
- app/views/diary_entries/_form.html.erb
- app/views/diary_entries/edit.html.erb
- app/views/diary_entries/new.html.erb
- app/views/shared/_markdown_help.html.erb
- app/views/shared/_richtext_field.html.erb
- config/locales/en.yml
- lib/richtext_form_builder.rb
This PR refactors the Diary Entry forms to use bootstrap, including using a custom form builder to create a `f.richtext_field` form component that does everything we need it to.
I've kept all the javascript the same, and the relevant ids the same, and the previews etc worked for me. The new form fields are built on the bootstrap form layout, so it's responsive as the screen width changes.
I did consider making a form component for the latitude/longitude/use_map stuff, since we also have lat/lon inputs elsewhere (e.g. user home location). But I left that aside for now, since having a form control related to two fields is a bit tricky, and the javascript and exact behaviour differs between diary entries and user home locations anyway.
This should unlock the conversion of most of our forms …
> Refactor Diary Entry forms to use a custom form builder

- app/helpers/application_helper.rb
- app/views/diary_entries/_diary_comment.html.erb
- app/views/diary_entries/_diary_entry.html.erb
- app/views/diary_entries/comments.html.erb
- app/views/messages/show.html.erb
- app/views/redactions/show.html.erb
- app/views/shared/_richtext_field.html.erb
- app/views/user_blocks/show.html.erb
- app/views/users/_user.html.erb
- app/views/users/show.html.erb
This uses https://getbootstrap.com/docs/4.4/utilities/text/#word-break to break long URLs on the blog post show view.
Example case: https://www.openstreetmap.org/user/tordans/diary/395215
Screenshot before:
Screenshot after:
An alternativ solution would be this custom CSS:
```
.diary_post .richtext {
margin-top: $lineheight;
// Prevent long URLs from breaking out of the container
// https://css-tricks.com/snippets/css/prevent-long-urls-from-breaking-out-of-container/
overflow-wrap: break-word;
word-wrap: break-word;
word-break: break-word;  
}
```
> Break long URLs in blog post show

- app/views/diary_entries/index.html.erb
Use https://getbootstrap.com/docs/4.5/components/pagination/ for the pagination.
Side note: I tried using link_to_if but this does not work well in this case since multiple changes need to happen for the disabled state.
The pagination css class cannot be removed, yet, since there is quite a bit more custom pagination in the codebase that will be a lot harder to migrate. Maybe for those, using a pagination gem that also uses bootstrap would be the better approach.
Before
After
> Diary entries #index: Migrate to bootstrap pagination

- app/views/traces/_trace_paging_nav.html.erb
- app/views/traces/index.html.erb
- Change pagination to use bootstrap default styles
- … but with empty span-tags instead of non-active a-tags
- refactor partial to not use @-variables but get the variables via
the render-call, simplify render-call-syntax
- remove the additional `if @traces.size > 1` inside the pagination
partial since that caused the pagination to disappear on the last page.
The partial will be visible with inactive links.
- Add bootstrap spacer-classes to overwrite commons-css so removing. Eg.
commons also has a pagination class same as bootstrap.
> Traces: Migrate pagination to bootstrap

- config/locales/en.yml
- test/system/report_diary_comment_test.rb
- test/system/report_diary_entry_test.rb
- test/system/report_note_test.rb
- test/system/report_user_test.rb
"successfully" was accidentally written with a single "c" on report creation, and then a couple tests expect that misspelled message.
> Fix a small typo and tests that depend on it.

- app/assets/stylesheets/common.scss
- app/views/diary_entries/show.html.erb
- app/views/messages/new.html.erb
- app/views/users/new.html.erb
- test/controllers/users_controller_test.rb
- test/integration/user_creation_test.rb
This PR converts the message, user registration, and diary comment forms to use bootstrap.
The user registration third-party-auth section was a little fiddly, due to the appearing and disappearing form fields, but I wanted to keep the current behaviour for now.
> More bootstrap forms

- INSTALL.md
Due to a problem with namespacing and vendoring, the Ubuntu package leads to namespace conflicts with Thor 1+
Fixes #3013
> Avoid recommending installation of the Ubuntu bundler package

- .rubocop_todo.yml
- Gemfile
- Gemfile.lock
- app/controllers/users_controller.rb
- app/helpers/user_helper.rb
- config/routes.rb
- test/helpers/user_helper_test.rb
- test/integration/user_creation_test.rb
- test/integration/user_login_test.rb
This requires converting all use of the /auth endpoints to use the POST method as GET is no longer supported.
Unfortunately I had to change all the `follow_redirect!` calls in the tests as in rails 6.0 that always uses GET regardless of the response status - in rails 6.1 that has actually been fixed but we can't move to that yet.
> Update to Omniauth 2.x

- app/assets/stylesheets/common.scss
- app/views/browse/changeset.html.erb
- app/views/browse/new_note.html.erb
- app/views/users/login.html.erb
- app/views/users/terms.html.erb
This pull request refactors four more forms to use bootstrap, specifically changeset comments, new notes, user terms and the third-party login form.
After this, there are only three more forms remaining, and then we can remove all the custom standard-form CSS. I tried refactoring the search form / directions form today, but it's a bit of a nightmare!
> Even more bootstrap forms

- DOCKER.md
- Dockerfile
- config/boot.rb
- docker-compose.yml
- docker/postgres/Dockerfile
- docker/postgres/openstreetmap-postgres-init.sh
Follow up to Tom’s review comments in https://github.com/openstreetmap/openstreetmap-website/pull/2409#pullrequestreview-582662631:
- Checkout was updated to v2 upstream, so no need to do that in this PR
- After testing under a variety of platforms, we haven’t been able to reproduce last year’s bug so ENABLE_BOOTSTRAP is now gone.
- Moved DB functions to `/usr/local/share/` since they’re still necessary per https://github.com/openstreetmap/openstreetmap-website/pull/2409#discussion_r570115583
- DB password and superuser privilege are both still needed when even when using trust auth because the database is needed for setup, migrations, normal usage, and data imports
- `yarnpkg install` is still required since `bundle exec` will not work without additional app code present during Docker …
> Post-merge Docker Compose cleanup issues

- app/assets/javascripts/leaflet.layers.js
- app/assets/javascripts/leaflet.share.js
This PR refactors two leaflet panels - the overlay selection and the share panel - to use bootstrap form styling.
> Refactor leaflet panel forms

- app/assets/stylesheets/common.scss
- app/views/browse/note.html.erb
Resolves #3075
Depending on the current language, the buttons for closing and commenting on notes may overflow resulting in no spacing between the buttons. This change improves accessibility as it allows the user to easily distinguish between the two buttons and reduces accidental presses on the wrong button.
Example of the issue:
Example after the fix:
May require additional testing.
> Fix unexpected spacing on note buttons when overflowed

- app/assets/stylesheets/small.scss
Some of these selectors no longer apply, and the one that did just made the behaviour worse, so they are all no longer required.
> Remove CSS overrides for the login page at small screen sizes

- config/settings.yml
The previously restrictively licensed material is now available on relatively open terms directly from swisstopo per 1. March 2021, so these entries can be removed.
> Remove GL and SH cantonal WMS servers from black list

- app/views/messages/inbox.html.erb
- app/views/messages/outbox.html.erb
- config/locales/en.yml
Per https://github.com/openstreetmap/openstreetmap-website/issues/2962#issuecomment-768985393, improve visual appearance of inbox/outbox headers.
Closes #2962
> Use Bootstrap nav tabs for inbox/outbox header navigation

- config/locales/en.yml
It turns out that neither `natural=peninsula` or `natural=coastline` are available for translation using [Translatewiki](https://translatewiki.net/wiki/Translating:OpenStreetMap).
https://wiki.openstreetmap.org/wiki/Tag:natural%3Dpeninsula
https://wiki.openstreetmap.org/wiki/Coastline
Let me know if this is the way to add it so that it will be available in Translatewiki.
> Added natural=coastline and natural=peninsula to i18n file

- app/views/traces/_trace.html.erb
- test/controllers/traces_controller_test.rb
This is a better solution than spans and margins. Additionally, rework to use `mb-*` instead of `my-*` (bootstrap advises against using margin-top) and get rid of `<br>`s by using paragraphs instead.
My apologies for two PRs on the same topic in quick succession, but I discovered the `list-inline` while reviewing another PR and so I thought I should go back and improve this.
> Use list-inline to achieve spacing between elements on a line

- config/locales/en.yml
Added key-value pairs to allow TranslateWiki translation of labels in Nominatum (a follow-up to #3124 )
https://wiki.openstreetmap.org/wiki/Tag:natural%3Datoll
https://wiki.openstreetmap.org/wiki/Tag:place%3Darchipelago
> Added natural=atoll and place=archipelago to en.yml

- Gemfile.lock
mimemagic 0.3.5 was yanked earlier today, so this updates to 0.3.6
> Bundle update for mimemagic yankage

- config/initializers/sanitize.rb
- test/lib/rich_text_test.rb
There are an endless amount of shenanigans that you can get up to using CSS classes. Examples are available privately on request.
This PR makes a few related changes:
* Adds tests for adding classes to table elements
* Refactors the configuration setup for the sanitize gem (although it turned out not to be necessary for this particular task)
* Strip away all class attributes from the output, by extending our custom transformer, to prevent shenanigans.
> Sanitize classes from outputs

- app/views/api/users/index.json.jbuilder
- app/views/api/users/show.json.jbuilder
During review for another PR, I released that the root attributes (copyright, generator etc) were missing from the User json responses.
> Add missing root attributes to User#show and User#index json responses

- app/assets/favicons/manifest.json.erb
I made the necessary changes to turn OSM.org into fullscreen web app on iOS and android
Sources : 
https://developer.apple.com/library/content/documentation/AppleApplications/Reference/SafariHTMLRef/Articles/MetaTags.html
https://developer.chrome.com/multidevice/android/installtohomescreen
Issue from https://trac.openstreetmap.org/ticket/5218
> Transform the web site into a fullscreen web app

- app/controllers/api/user_preferences_controller.rb
- app/views/api/user_preferences/_user_preference.json.jbuilder
- app/views/api/user_preferences/index.json.jbuilder
- test/controllers/api/user_preferences_controller_test.rb
I’m unsure about this, because I haven’t seen an example with more than one preference.
Test plan:
```
GET /api/0.6/user/preferences?format=json
{"preference":{"k":"diary.default_language","v":"en"}}
```
```
GET /api/0.6/user/preferences?format=xml
<osm version="0.6" generator="OpenStreetMap server" copyright="OpenStreetMap and contributors" attribution="http://www.openstreetmap.org/copyright"license="http://opendatacommons.org/licenses/odbl/1-0/">
<preferences>
<preference k="diary.default_language" v="en"/>
</preferences>
</osm>
```
Closes https://github.com/openstreetmap/openstreetmap-website/issues/3160
> Added JSON support to user preferences

- app/views/diary_entries/comments.html.erb
- app/views/notes/index.html.erb
- config/locales/en.yml
- test/controllers/diary_entries_controller_test.rb
- test/controllers/notes_controller_test.rb
Display more specific/friendly message when the there are no notes/comments to display, rather than empty tables.
> Display message when the there are no notes/comments to display

- script/statistics
It would be nice to be able to link to specific sections on the stats page on osm.org. 
If the headings would have the IDs proposed here one could link to them like `
```
https://www.openstreetmap.org/stats/data_stats.html#number-of-editors
```
I also 
- changed the topmost heading to be h1 instead of h2 since each page should have a h1
- Put `OpenStreetMap stats`on its own and on the next line `report run at 2021-02-16 23:00:05 +0000`
The final result looks like this
> Format openstreetmap.org/stats/data_stats

- app/views/user_blocks/show.html.erb
Fixes #3143.
Not tested by myself. Treat like pseudocode, I don't speak Ruby.
Intends to append the "Created" line with the difference ```duration = (ends_at - created_at)```, so it would read e.g.
```Created: over 1 year ago (4 hours)``` avoiding a new text string
> Show the crafted duration of a block independent of the reading time

- app/views/user_blocks/show.html.erb
- config/locales/en.yml
This also standardises the labels to have the colon, in common with oauth_clients#show.
It's just a minor change, but the higgledy-piggledy list of attributes, along with the fact that some colons were in bold and some colons were, was getting to me.
> Refactor user blocks information to use a dl

- app/views/diary_entries/index.html.erb
Google (and other search engines) should follow all links on this page, but only index the actual diary_entry#show and not the #index. This meta tag tells google to do just that (https://developers.google.com/search/docs/advanced/crawling/block-indexing?hl=en).
Part of https://github.com/openstreetmap/openstreetmap-website/issues/2851
> Add noindex meta tag to diary index pages

- .rubocop.yml
- .rubocop_todo.yml
- Gemfile
- Gemfile.lock
This checks the coding standards in our rake files. I haven't fixed any of the current warnings, but at least it will avoid any more problems in the future.
> Add rubocop-rake

- INSTALL.md
There is no "js" package, so this is probably a typo and should be "nodejs" (https://nodejs.org/en/download/package-manager/#centos-fedora-and-red-hat-enterprise-linux)
> fixed nodejs package name for fedora

- INSTALL.md
libpq-dev is required for `gem install pg` (this is also included in the ubuntu install guide). Note that on fedora the package is named libpq-devel
> Added missing dependency for fedora installation

- test/models/changeset_tag_test.rb
- test/models/message_test.rb
- test/models/node_tag_test.rb
- test/models/old_node_tag_test.rb
- test/models/old_relation_tag_test.rb
- test/models/old_way_tag_test.rb
- test/models/relation_tag_test.rb
- test/models/user_preference_test.rb
- test/models/way_tag_test.rb
It's really the upper and lower boundaries that we want to check, and it's reasonable to assume all the intermediate values will work fine if the boundary values are tested.
This also saves about 75% of the time taken and almost 85% of the assertions when running all the model tests.
Rough notes from my laptop when running `bundle exec rails test test/models/`:
Before:
```
Finished in 21.187886s, 11.1384 runs/s, 314.2362 assertions/s.
236 runs, 6658 assertions, 0 failures, 0 errors, 0 skips
```
After:
```
Finished in 6.723931s, 35.0985 runs/s, 160.3229 assertions/s.
236 runs, 1078 assertions, 0 failures, 0 errors, 0 skips
```
> Skip intermediate lengths when testing tag validity

- app/assets/javascripts/index/browse.js
- app/assets/javascripts/index/directions.js
- app/assets/stylesheets/common.scss
- app/assets/stylesheets/small.scss
- app/views/application/_sidebar_header.html.erb
- app/views/browse/changeset.html.erb
- app/views/browse/new_note.html.erb
- app/views/browse/not_found.html.erb
- app/views/browse/note.html.erb
- app/views/browse/query.html.erb
- app/views/browse/timeout.html.erb
- app/views/changesets/history.html.erb
- app/views/changesets/index.html.erb
- app/views/geocoder/search.html.erb
- app/views/layouts/map.html.erb
- app/views/site/export.html.erb
- test/integration/user_changeset_comments_test.rb
This PR was going to be a series of small CSS fixes, but is dominated by one in particular which is reworking the sidebar padding.
Until now, there's been no padding on the sidebar, so every piece of content has to sort out their own padding. For example, the header h2 normally have their own padding, and then either the sidebar content gets div-by-div padding or a class like browse-section was used all over the place.
Since there's only one or two places that we don't want the padding (namely in some lists) it's much easier to apply the padding globally and make exceptions for these cases. This should make the layout of the sidebar much easier to deal with in future, since it will work nicely by default if/when we add more sidebars.
The other changes in this PR are mostly …
> Rework sidebar to use padding on the sidebar_content div

- app/assets/stylesheets/common.scss
- app/assets/stylesheets/small.scss
- app/controllers/confirmations_controller.rb
- app/controllers/users_controller.rb
- app/helpers/application_helper.rb
- app/views/confirmations/_resend_success_flash.html.erb
- app/views/layouts/_flash.html.erb
- app/views/layouts/_header.html.erb
- app/views/users/_terms_declined_flash.html.erb
- config/locales/en.yml
- test/controllers/confirmations_controller_test.rb
- test/system/confirmation_resend.rb
This PR addresses #3215. I did a bunch of research to see what alternative approaches people were using - mostly, it seems, just opening themselves up to security errors by using .html_safe everywhere, going by the blogs and stackoverflow comments that I found. 
However, an approach I saw mentioned a couple of times and in particular used by a mysociety application is to use the ability of flash messages to store Hashes. Then you can use this Hash to render a template, either to include html or just to use the translation features. Since the only things we pass to the flash object is some strings that will need escaping (and we don't store any html anywhere in the flash object) everything works nicely. I'm quite pleased with this approach.
I also took the opportunity to move the flash …
> Use partials to support complex flash messages

- app/assets/stylesheets/common.scss
This PR removes some of our overrides of basic CSS, which is handled through bootstrap. This reduces our custom CSS without having much impact on the rendered results. For example:
* color: `#222` -> `#212529`
* line-height: `1.6666` -> `1.5`;
* font-family: `'Helvetica Neue',Arial,sans-serif;` -> `-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, "Noto Sans", "Liberation Sans", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji" !default;`
My plan with the body `font-size` is to tackle all of our font-size settings in one go as a separate PR.
> Use bootstrap defaults for body CSS

- app/assets/stylesheets/common.scss
- app/views/site/about.html.erb
This reduces the amount of custom CSS required for the layout, and makes it responsive on small screen sizes.
> Refactor About header to use bootstrap and flex

- FAQ.md
This adds a contrast requirement for the upper-right corner so the 'X' can be seen. It also adds a requirement that PRs be created before the banner needs to be shown, in order to allow for proper review.
> Update banner FAQ.

- app/views/messages/inbox.html.erb
- app/views/messages/outbox.html.erb
- app/views/messages/show.html.erb
This PR contains a few minor improvements to the messages pages, namely
* Converting the inbox and outbox lines to tabs, in line with the tabs on the traces pages
* Adding a title to the header, since tabs alone looked a bit weird
* Putting the message title into the heading for sent messages, for consistency
* Making the delete message button red when viewing messages (for consistency with the similar buttons on inbox/outbox) and adding the button to the sent message view page (already shown on the outbox page)
> Minor improvements to messages

- config/locales/en.yml
Added key-value pair to allow TranslateWiki translation of labels in Nominatim.
https://wiki.openstreetmap.org/wiki/Tag:historic%3Drune_stone
See #3124 and #3142.
> Added historic=rune_stone to en.yml

- app/assets/stylesheets/common.scss
- app/views/confirmations/confirm.html.erb
- app/views/users/blocked.html.erb
- app/views/users/new.html.erb
- app/views/users/terms.html.erb
Fixes #3259 
The first problem was that there was a missing class there, since the CSS rule applied only to a certain list of classes and those class names are based on the controller. So this was inadvertantly broken in #3165.
The main problem is that the text appeared behind the background illustration. This predates any of our recent CSS work, but was probably less noticed back then since the titles were in a much smaller font. Here's a screenshot from early 2019 codebase. The titles need to be very long before being overlapped by the illustration.
So in this PR I've refactored the heading, so that the titles are a child of the div that has the background illustration, and this means the text naturally appears over the top.
I've also tweaked the div to be `min-height` instead of …
> Ensure heading text appears above the header illustration

- app/controllers/application_controller.rb
The spelling of language is wrong here, and the correct version is already there further down at the preferred_language method definition itself.
> Remove incorrectly spelled helper_method

- test/system/preferences_test.rb
Now that the translations have been updated, we can enable this test. 
Followup from #3257.
> Enable test for showing flash message in the new language

- Dockerfile
Refs #3275
See also 102f3a6668665774f069a8116a251a28c3c5c0cc
This at least fixes the docker CI build while we discuss the best long-term approach in #3275
> Add --ignore-engines for yarn in the Dockerfile

- config/locales/en.yml
- test/controllers/diary_entries_controller_test.rb
- test/system/user_logout_test.rb
As discussed in the #3257 review our page titles are somewhat inconsistent in their use of capitalisation and this is an attempt to improve that situation.
That said, some of our headings are quite long sentences and I'm not sure how well they work in full titlecase...
> Improve capitalisation of page titles

- app/assets/stylesheets/parameters.scss
Our blue is less saturated and lighter than the bootstrap-default blue, and so the bootstrap-default secondary colour is too dark and too saturated when beside our primary buttons.
I'd noticed this a while ago with the terms page (the only place we currently use a secondary-link with default bootstrap colours) but this was much more apparent when reviewing #3267 
Before:
After:
> Use our darkgrey for bootstrap secondary colour

- app/helpers/browse_tags_helper.rb
- test/helpers/browse_tags_helper_test.rb
Fixes #3269
In the HTML4 days, fragments weren't allowed to have `%` signs, so mediawiki generated fragments with `%` replaced with a `.`
In HTML5, fragments can have % encoded characters, and so in 2017 wikipedia switched over to this for their automatically generated fragments, while keeping the "dot" versions available as a fallback.
However, we have been automatically converting all fragments, including manually specified anchors that do not have "dot"-encoded versions available. So we can now simplify everything by just using the HTML5 percent-encoded fragments.
> Switch to html5-compatible fragment encoding for wikipedia URLs

- app/controllers/users_controller.rb
- test/controllers/users_controller_test.rb
This was missed during #3147 since it wasn't covered by a test.
> Fix redirect to terms path when not logged in

- app/views/users/show.html.erb
- config/locales/en.yml
This is a followup to 26698d6 which introduced the html. It's better to use interpolation for links, since this avoids the translations introducing any html syntax errors.
I had to change the translation key, since changing the interpolation variables alone would lead to breakages.
> Avoid using raw html in translations for links.

- app/views/site/_potlatch.html.erb
- config/locales/en.yml
I've left the internal name of the link the same, to avoid having to change the translation key and retranslate everything.
> Update the link for changing your editor preferences

- app/controllers/confirmations_controller.rb
- app/controllers/users_controller.rb
- app/views/layouts/_header.html.erb
- app/views/site/edit.html.erb
- app/views/user_blocks/_block.html.erb
- app/views/user_blocks/show.html.erb
- app/views/users/show.html.erb
This PR refactors various links to use named paths, rather than the `controller => ... action => ...` alternative. This makes them easier to read, particularly when dealing with `display_name` parameters.
> Use more named paths

- app/views/application/_settings_menu.html.erb
- app/views/oauth2_applications/edit.html.erb
- app/views/oauth2_applications/index.html.erb
- app/views/oauth2_applications/new.html.erb
- app/views/oauth2_applications/show.html.erb
- app/views/oauth2_authorized_applications/index.html.erb
- app/views/oauth_clients/edit.html.erb
- app/views/oauth_clients/index.html.erb
- app/views/oauth_clients/new.html.erb
- app/views/oauth_clients/show.html.erb
- app/views/users/account.html.erb
- config/locales/en.yml
- test/integration/client_applications_test.rb
This makes it easier to navigate around these pages. Since each tab corresponds to a given controller, this makes the selection of active tabs straightforward.
The tabs, like on the traces pages, also switch to a vertical list on small screen widths.
> Convert account setting menu to tabs, and include on other pages

- app/views/layouts/map.html.erb
- app/views/site/about.html.erb
- config/locales/en.yml
As discussed in the ops meeting, they meet the criteria for listing as a top three donor.
> Add Fastly as top three donor

- Gemfile
- Gemfile.lock
There is a bug in the Rails/ContentTag cop that causes rubocop to crash. The bug has already been fixed and so should be available in the next release.
See https://github.com/rubocop/rubocop-rails/issues/543
> Temporary pin on rubocop-rails until next bugfix release

- app/controllers/api/tracepoints_controller.rb
- app/models/tracepoint.rb
- app/views/api/tracepoints/index.gpx.builder
- test/controllers/api/tracepoints_controller_test.rb
- test/models/tracepoint_test.rb
This PR moves the rendering of the tracepoints#index call to use a builder view, rather than creating the xml within the controller method. It then allows us to remove the `to_xml_node` method from the model.
I've had to refactor the code slightly, since the original involved going back to previously added XML nodes and adding more details to them (e.g. adding more points to the anon_trackseg). I couldn't find a way to do this "revisiting" approach with the xml builder, so instead I sort all the tracepoints into the tracksegs using hashes and arrays, and then iterate over those structures when writing out the end result as xml. The decisions on what goes where should (hopefully) be the same though, since that logic hasn't been changed.
> Use a view to render tracepoints

- README.md
We no longer use or refer to trac, which has in the meantime been archived anyway.
> Remove mention of trac in README

- app/assets/stylesheets/common.scss
- app/views/browse/_common_details.html.erb
- app/views/browse/changeset.html.erb
- app/views/dashboards/_contact.html.erb
- app/views/dashboards/show.html.erb
- app/views/users/index.html.erb
- test/controllers/dashboards_controller_test.rb
- test/integration/user_changeset_comments_test.rb
This PR reduces the usage of margin-top for controlling layouts. Bootstrap [tries to avoid margin-top](https://getbootstrap.com/docs/4.0/content/reboot/) since they collapse into preceding margin-bottoms, so it's easier to be consistent and just use margin-bottoms instead. Since they are applied to most elements (like tables, lists, paragraphs) by default, some refactoring of plain text-in-div to text-in-paragraph solved the spacing problems, otherwise I used the bootstrap margin utilities.
> Reduce usage of margin-top for layout

- app/assets/stylesheets/common.scss
- app/assets/stylesheets/leaflet-all.scss
- app/views/dashboards/_contact.html.erb
- app/views/dashboards/_popup.html.erb
- app/views/diary_entries/_diary_comment.html.erb
- app/views/diary_entries/_diary_entry.html.erb
- app/views/diary_entries/index.html.erb
- app/views/diary_entries/show.html.erb
- app/views/issues/_comments.html.erb
- app/views/issues/_reports.html.erb
- app/views/users/show.html.erb
This PR continues work started in 9aa17258fcccf5b1f292e1190bd9a2968822274e and 31e247c1e223145a6ac8ce9012fe5eb586f1aaea to refactor the `user_image` and `user_thumbnail` css rules. Instead of using floats and margins, we now prefer to use the flex grid to control the layout.
The commits in this PR refactor each use of these helpers to use the temporary `_no_margins` rules, before refactoring the old rules and removing the class overrides at the end.
> Rework user images and thumbnails to use flex grid

- app/views/diary_entries/no_such_entry.html.erb
- app/views/diary_entries/show.html.erb
- app/views/issues/show.html.erb
- app/views/messages/new.html.erb
- app/views/messages/show.html.erb
- app/views/notes/index.html.erb
- app/views/traces/edit.html.erb
- app/views/traces/offline.html.erb
- app/views/traces/show.html.erb
- test/controllers/diary_entries_controller_test.rb
This makes them consistent with all the other pages that use `h1` in the `content_for :heading` sections
> Convert remaining heading titles to use h1

- app/views/diary_entries/index.html.erb
- app/views/diary_entries/show.html.erb
- app/views/users/show.html.erb
- test/controllers/users_controller_test.rb
The style rule was removed in 3f8cf322723750aa4c8d062d4a727f9107ceccb4 and they were otherwise only used in the tests.
> Remove the userinformation ids from headings

- Gemfile
- Gemfile.lock
- lib/password_hash.rb
- test/lib/password_hash_test.rb
It's been five years since we last updated our password hashing and things have moved on - the [current OWASP recommendation](https://cheatsheetseries.owasp.org/cheatsheets/Password_Storage_Cheat_Sheet.html) is to use Argon2.
Argon2 takes care of recording the salt and hash parameters as part of the password so the separate salt is no longer needed except for legacy passwords.
We're using the default parameters (64Mb memory, 2 iterations, 1 degree of parallelism) which exceeds the OWASP recommended values and upgrading will be automatic as the defaults change over time.
There is also support for an optional "pepper" which means that a leak of hashed passwords would be useless without the pepper (a shared secret included in the hashes) which is not present in the database or on the …
> Switch to Argon2 for password hashing

- app/assets/stylesheets/common.scss
- app/assets/stylesheets/parameters.scss
- app/helpers/user_helper.rb
- app/views/browse/_paging_nav.html.erb
- app/views/browse/_tag_details.html.erb
- app/views/browse/changeset.html.erb
- app/views/dashboards/show.html.erb
- app/views/diary_entries/_diary_entry.html.erb
- app/views/diary_entries/_form.html.erb
- app/views/layouts/_header.html.erb
- app/views/profiles/edit.html.erb
- app/views/site/export.html.erb
- app/views/users/terms.html.erb
- test/controllers/diary_entries_controller_test.rb
- test/helpers/user_helper_test.rb
This PR contains various changes and simplifications to the CSS, mainly focussed on reducing the number of floating elements (by using flexbox for layout) and using border utility classes instead of selector-specific rules.
> CSS Simplification for floats and borders

- app/controllers/diary_entries_controller.rb
- app/views/diary_entries/comments.html.erb
- config/locales/en.yml
Fixes #3369
This makes the heading match the layout of the user's Notes page,
which also has a short heading and a subheading with a link.
Additionally, add a page title, again for consistency
> Add a user link to the heading of the diary comments page

- .github/ISSUE_TEMPLATE/bug.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature.yml
This should help new users find the right place to go with their issue, while also letting people continue to use the blank template if they prefer.
The templates are heavily inspired by similar templates in the iD repo.
Fixes #3358
As an aside, I did think about adding more links (e.g. other map layers, each of the routing engines etc) or more templates (e.g. installation support) but I want to strike a balance between having too few links and on the other hand having an overwhelming page full of too many choices. In the original issue there was a suggestion to add a link to operations, but I found it really hard to write useful guidance for a regular mapper to be able to figure out whether it's a code or operations problem, so I've left that out for now.
> Add some issue templates and links to other repositories

- app/assets/stylesheets/common.scss
- app/views/layouts/_flash.html.erb
Because we are using an edge-to-edge layout for the flash messages, the negative margins on the row were expanding the element offscreen.
Bootstrap provides a "no-gutter" class for removing these margins, but that also drops the spacing between columns which we want to preserve. So instead we use a margin override on the row only.
Additionally, drop some padding css in favour of a utility class
Fixes #3351
Bug was introduced in 3dd639c8d02677b773935aa982ba0c9f3cc209e5
> Prevent flash messages from expanding offscreen

- config/locales/en.yml
This leads to confusion on features otherwise tagged (e.g. roads) while not being necessary for nominatim results.
Fixes #3170
> Remove emergency=yes fallback description

- app/controllers/api/traces_controller.rb
- app/controllers/traces_controller.rb
- config/settings.yml
This has been set as true by default, and in production, for many years. I don't think there's much use in keeping the setting around any longer.
> Drop the trace_use_job_queue option

- package.json
- yarn.lock
Refs #3387
This temporarily gets the site working again for IE11 while we discuss longer term options
> Revert to the last es5-compatible version of locatecontrol

- config/locales/en.yml
Added `highway=turning_circle` to en.yml - value was not available in TranslateWiki for translation.
A precedent has already been set that labels found through the "Find objects" tool should be made available for translation too (see discussion on topic in #3124)
> Added `highway=turning_circle` to en.yml

- .rubocop_todo.yml
- app/abilities/ability.rb
- app/controllers/accounts_controller.rb
- app/controllers/concerns/user_methods.rb
- app/controllers/confirmations_controller.rb
- app/controllers/users_controller.rb
- app/views/accounts/edit.html.erb
- app/views/application/_settings_menu.html.erb
- app/views/layouts/_header.html.erb
- app/views/sessions/new.html.erb
- app/views/site/edit.html.erb
- app/views/users/show.html.erb
- config/locales/en.yml
- config/routes.rb
- test/controllers/accounts_controller_test.rb
- test/controllers/confirmations_controller_test.rb
- test/controllers/users_controller_test.rb
- test/integration/client_applications_test.rb
This PR refactors the account edit/update pages out into a separate "accounts" controller. This continues the process of refactoring users_controller into separate controllers, aligned with the controllers found in Devise, along with this being some foundational work for account self-deletion.
I thought long and hard about the naming for this controller, since there are various possibilities. Devise uses "registrations" as the name for the corresponding controller, but I find that a mouthful and I think that having a controller match what we want to have in the URL is more straightforward. Throughout the site we refer to this functionality as "account" and it also matches the previous method name, so I went for that. I also think this is worth moving out of the users controller since …
> Refactor the account edit/update pages 

- app/models/user.rb
- app/views/api/users/_user.json.jbuilder
- app/views/api/users/_user.xml.builder
- app/views/users/_user.html.erb
- app/views/users/show.html.erb
This allows rails to set the created_at automatically, and so avoids us from having to do so in a callback. It also hides the unusual db column name from the rest of the app.
> Alias the user creation_time column

- app/controllers/users_controller.rb
- app/models/user.rb
- test/controllers/browse_controller_test.rb
- test/models/user_test.rb
"delete" is generally used for immediate SQL deletion without running any callbacks or other ruby code, whereas "destroy" will trigger callbacks.
Although we don't currently use any callbacks, let's rename this method to align better with the convention.
> Rename User#delete to User#destroy

- app/abilities/ability.rb
- test/system/user_suspension_test.rb
Without the ability defined, the user is still logged out, but then the `deny_access` check redirects to the login page. The re-login attempt would then fail anyway, with an error message, but let's fix the abilities and use the intended page.
I think this has been broken since the abilities were introduced, since there's no `suspended` action defined in the controller. I was a bit surprised that actions without definitions worked, but it seems that's a legitimate way to do things in Rails!
> Fix display of suspension message when a user is suspended mid-session 

- test/models/issue_test.rb
- test/models/message_test.rb
- test/models/node_test.rb
- test/models/relation_test.rb
- test/models/user_preference_test.rb
- test/models/user_test.rb
This PR changes various uses of `Model.new` in the tests to use FactoryBot via `build(:model)`. It's partly for consistency, but also partly because I ran into problems with those User model tests while doing some unrelated work.
> Use factories instead of new objects

- test/system/confirmation_resend_test.rb
- test/system/diary_entry_test.rb
- test/system/issues_test.rb
- test/system/preferences_test.rb
- test/system/report_diary_comment_test.rb
- test/system/report_diary_entry_test.rb
- test/system/report_note_test.rb
- test/system/report_user_test.rb
- test/system/user_logout_test.rb
- test/system/user_signup_test.rb
This PR switches to using `assert_content` (and `assert_link`) from Capybara's list of assertions, instead of using a plain assert on the Capybara node matchers (e.g. assert page.has_content?). 
This makes little difference when the tests are working, but the error messages are much more helpful when the tests fail (e.g. during development or refactoring). The previous approach led to "Expected false to be truthy" which is not super helpful to debug!
Example for `assert_content`:
```diff
Failure:
DiaryEntrySystemTest#test_reply_to_diary_entry_should_prefill_the_message_subject [/test/system/diary_entry_test.rb:15]:
- Expected false to be truthy.
+ expected to find text "Receive a new message" in "OpenStreetMap\nEdit\nHistory\nExport\nGPS Traces\nUser Diaries\nCopyright\nHelp\nAbout\nUser …
```
> Use `assert_content` instead of `assert page.has_content?`

- test/controllers/users_controller_test.rb
They have no effect, and are likely a copy-paste error from when the test was first written in 39a54f8c14d739c95495e0d2c0ca56826eddfe52
> Remove params from user deletion test

- app/views/layouts/_search.html.erb
Improve right-to-left language search experience by adding HTML attribute `dir="auto"` to the input. Browsers will align left or right based on the input text.
No effect for left-to-right language input.
I am open to reordering the tag, or limiting this to just the primary search input.
> Add dir="auto" to search to improve right-to-left language support

- .github/ISSUE_TEMPLATE/config.yml
This was originally intended in #3397 and I'm not sure why I set this to false.
> Allow blank issue templates

- app/controllers/confirmations_controller.rb
- app/controllers/passwords_controller.rb
- app/controllers/users_controller.rb
- app/models/user.rb
- app/views/users/show.html.erb
- config/locales/en.yml
- test/controllers/browse_controller_test.rb
- test/controllers/confirmations_controller_test.rb
- test/controllers/users_controller_test.rb
- test/factories/user.rb
- test/models/user_test.rb
- test/system/diary_entry_test.rb
- test/system/user_status_change_test.rb
- test/system/user_suspension_test.rb
This came up during work on #3398 when considering all the ways state can be changed, and there being nowhere really to document what the states means and what it means to change them (e.g. confirmed isn't related to confirming the email, difference between an admin hiding and deleting an account, etc, which are a bit unintuitive). 
That made me think about AASM since you can define the states, the transitions, and also easily restrict which transitions between states are permitted. I think this will also come in useful when we think about removing "still pending" accounts and other things like that.
If this is approved, then I'll rework #3398 to be based on top of this.
> Use a state machine for user status

- config/locales/en.yml
These labels turn up in the 'Find objects' tool. 
They should be made available for translation - hence this PR.
See discussion in the following PRs:
- Original: #3124
- Supplemental: #3391
> Added some key-value pairs under `railway=`

- app/abilities/ability.rb
- app/controllers/account/deletions_controller.rb
- app/controllers/accounts_controller.rb
- app/controllers/application_controller.rb
- app/views/account/deletions/show.html.erb
- app/views/accounts/edit.html.erb
- app/views/application/_settings_menu.html.erb
- config/locales/en.yml
- config/routes.rb
- test/system/account_deletion_test.rb
Account deletion is something that administrators currently do manually, when emailed with a request, but there's no reason to prevent users from being able to delete their own accounts.
I'm opening this as a draft PR in order to get early feedback on the UI. Obviously tests need to be written, and to help with development, it doesn't actually delete the account yet :smile:
The idea is to have a button on the account editing page:
Which then leads to a description of what exactly will happen when you delete your account:
Please let me know what you think. If you want to see exactly what happens when you delete an account currently, have a look at the reasonably straightforward [`User#destroy`](https://github.com/openstreetmap/openstreetmap-website/blob/8adb486130d867070504c2c2c705fdfe74e5d …
> Allow users to delete their own accounts

- app/assets/javascripts/embed.js.erb
- app/assets/javascripts/index/query.js
- app/assets/javascripts/osm.js.erb
[String.prototype.substr()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substr) is deprecated so we replace it with [String.prototype.slice()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/slice) which works similarily but isn't deprecated.
.substr() probably isn't going away anytime soon but the change is trivial so it doesn't hurt to do it.
> Replace deprecated String.prototype.substr()

- db/migrate/20220223140543_remove_id_defaults.rb
- db/structure.sql
In both the case of primary keys, and also foreign key references, there's no need to set a default value.
This doesn't have a big impact in routine situations, but can be very confusing when debugging corner cases.
> Remove default values from id columns

- app/models/access_token.rb
- app/models/client_application.rb
- app/models/issue.rb
- app/models/note_comment.rb
- app/models/oauth_token.rb
- app/models/old_node.rb
- app/models/old_relation.rb
- app/models/old_way.rb
- app/models/trace.rb
- app/models/user_block.rb
- config/application.rb
This switches the logic so that `belongs_to` parent objects must exist by default, and marks the optional ones explicitly. This is reflected in the null/not_null status on the relevant db columns.
Doing this exposed a small corner case where we were relying on the previous default (of everything being optional) in order for trace objects to pass validation. When the `belongs_to` was made required by default, rails couldn't autodetect the inverse relationship, and so thought that all tracetags for new traces were invalid. Adding inverse_of fixed this. See also https://guides.rubyonrails.org/association_basics.html#bi-directional-associations for a better explanation.
> Enable active_record.belongs_to_required_by_default

- config/locales/en.yml
Fix some links to osmfoundation.org pages which are redirecting (not broken links but this is just avoiding a slightly messy redirection)
> Fix redirecting links to osmfoundation.org

- CONFIGURE.md
- app/views/oauth_clients/index.html.erb
- test/controllers/oauth_clients_controller_test.rb
- test/integration/client_applications_test.rb
Update the instructions in CONFIGURE.md on how to set-up the built-in apps OAuth settings.
Also a small cosmetic tweak in OAuth 1 settings button:
before & after:
> OAuth updates to CONFIGURE doc + cosmetic tweak

- .github/workflows/tests.yml
- Dockerfile
- INSTALL.md
- config/initializers/new_framework_defaults_7_0.rb
- script/vagrant/setup/provision.sh
This switches to using vips (the rails 7 default) for image processing.
It also drops Ubuntu 18.04 support as the libvips it has is too old - we're coming up on the next LTS release anyway so it's probably time to let one go.
> Switch to using vips for image processing

- app/assets/images/sprite.svg
The question mark on the query icon is using a font that does not exist and is defaulting to serif. This fix uses the built-in web safe Helvetica with sans-serif fallback. This should match the PNG version of the icon.
Issue:
> Fix SVG query icon font

- config/locales/en.yml
Removed redundant space in "web site".
> Make spelling for "website" consistent

- config/locales/en.yml
"sportsclub" is an uncommon spelling of "sports club".
**Wikidata**
https://www.wikidata.org/wiki/Q847017
(See also Wikipedia)
**Wiktionary** (missing from Wikidata)
- https://en.wiktionary.org/wiki/sports_club
- https://en.wiktionary.org/wiki/Sportclub
(See also "club" for related terms)
**Dictionaries, articles**
Found no dedicated articles / dictionary pages for this spelling, but dictionary examples (almost) always use "sports club".
(i.e. (British English dictionaries); Encyclopaedia Britannica, Cambridge (Cambridge University), Oxford Learners (Oxford University))
**Google Trends**
```
"sports club", "sportsclub"
"sport club", "sportclub"
"sporting club"
```
https://trends.google.nl/trends/explore?date=all&q=sports%20club,sportsclub,sport%20club,sportclub,sporting%20club
(left out); …
> Change spelling for club=sport

- test/models/changeset_tag_test.rb
- test/models/node_tag_test.rb
- test/models/old_node_tag_test.rb
- test/models/old_relation_tag_test.rb
- test/models/old_way_tag_test.rb
- test/models/relation_tag_test.rb
- test/models/way_tag_test.rb
This PR reworks some model tests to use factories, instead of creating new objects. This tends to simplify the tests, since there's often less boilerplate in setting up the new object to be valid.
It also reworks the "empty" tag tests, since it wasn't clear from the naming and code exactly what was being tested. So I've refactored these to show that they are testing that the parent object is set.
> Rework some tests to use factories instead of new objects

- app/views/browse/_common_details.html.erb
Fixes #3435
Also brings the location information into the list, which avoids a
lack of padding before the next header.
Before:
After:
> Rework common details to avoid awkward line breaks

- app/models/report.rb
- app/views/issues/_reports.html.erb
- app/views/reports/new.html.erb
- test/models/report_test.rb
- test/system/issues_test.rb
Pass the text of reports ('details' field) through the RichText formatter to give us kramdown formatting support.
Users don't generally get to see their reports. Only a few admins ever see them displayed, but DWG folks working with reports have complained of a **"wall of text"** problem when looking at some longer reports. This solves it, particularly with basic paragraphs rendered from double-newlines. Other kramdown tricks are a bonus:
We don't need to do support of alternative HTML formatting as we did for legacy diary entries. I don't think we need any special treatment for old reports in the database. We can bung them all through the kramdown formatter and it will either make no difference or will improve the display.
> Kramdown formatting on reports text

- app/controllers/reports_controller.rb
- test/controllers/reports_controller_test.rb
Fix an issue with the report verification, causing it to lose the text of a report if the user fails to fill in a category. In the absence of the required field 'category' it redirects to the new report form. This redirect should retain the value of the 'details' field.
> Fix verification redirect on missing report category

- app/models/issue_comment.rb
- app/views/issues/_comments.html.erb
- test/factories/issue_comment.rb
- test/models/issue_comment_test.rb
On issue comments (which only admins can create or see), put the body text through kramdown formatting.
We actually show the info box with kramdown syntax and preview button, but it looks like we forgot to render the formatting!
This wasn't on DWG's list of requested fixes. Nobody noticed or complained about it, but I thought I'd fix it while I'm looking at these things.
> Put issue comments through kramdown formatter 

- app/views/issues/show.html.erb
This fits with actions on other pages, avoids using pipe characters, and resolves an issue with empty paragraphs.
> Use a secondary-actions nav for issue actions

- config/locales/en.yml
Make map key list "common, meadow, garden" instead of just "common, meadow".
This is in response to a DWG ticket ( #2022051810000111) where a resident complained that their private garden was "listed as 'common, meadow' " in OSM because they consulted the map key. Listing "garden" along these should clear up that misunderstanding.
> Add "garden" to map key

- config/locales/en.yml
The entry is syntactically wrong. The description terms expect a list of values for each key.
Given that 'crossing' is not a main tag, the key shouldn't be featured in the list at all. I've added highway=crossing instead.
> Fix highway crossing in nominatim description terms

- app/views/issues/_comments.html.erb
- app/views/issues/_reports.html.erb
Don't remove margins with `mb-0` class on reported-by lines.
After enabling markdown in issue reports/comments, they can consist of several paragraphs. There's spacing between paragraphs provided by their bottom margins. But then there's a reported-by line above and it doesn't have margins. This line is displayed next to the report text without any spacing which looks strange for multi-paragraph reports.
Before merging #3566 there was a kind-of margin provided by an empty paragraph resulting from invalid html. Now that paragraph is gone.
> Margins for 'comment from' / 'reported by' lines on issues page

- app/assets/javascripts/edit/id.js.erb
Presumably this was an oversight in the original implementation: `OSM.params` falls back to the page's `query` string if the function's parameter (here: the page's `hash`) is an empty string.
This fixes the following inconsistent behaviour of the website: In the example below, the first URL sets the `background` to `none` while in the second example it doesn't.
* https://www.openstreetmap.org/edit.html?background=none
* https://www.openstreetmap.org/edit.html?background=none#map=…
With this PR, the `background` query parameter is ignored in both examples. Btw, the correct way to supply the `background` (and [related parameters](https://github.com/openstreetmap/openstreetmap-website/blob/c55d346/app/assets/javascripts/edit/id.js.erb#L23-L39)) is via a hash parameter:
* …
> [iD] only parse hashParams if there actually is a hash

- app/views/layouts/_header.html.erb
P.S. I've noticed that all `<li>`s from [line 47 to line 61](https://github.com/openstreetmap/openstreetmap-website/blob/master/app/views/layouts/_header.html.erb#L47-L61) have `<%= current_page_class(traces_path) %>` which seems to return nothing. It's the same on [lines 73 to 77](https://github.com/openstreetmap/openstreetmap-website/blob/master/app/views/layouts/_header.html.erb#L73-L77). It may be worth removing it all together if it's not working and if it's not needed any more.
> Fix small error in _header.html.erb

- app/assets/javascripts/application.js
The dropdown and tooltip of the map edit controls should behave similar when zooming in and out. This is fixed by disabling the button-group and the buttons. Fixes  #3456
> Fix map edit controls min-zoom behaviour

- config/locales/en.yml
It's invalid YAML to have duplicate keys. Some parsers may refuse to read the file.
(I had to scan block page heading locale strings once to find out whether they are "User A blocked by User B" or "User B blocked User A" in all possible languages. The parser threw an exception on en.yml.)
> Remove duplicate keys from en locale data

- app/models/trace.rb
- test/models/trace_test.rb
Space-separated "do as before for backwards compatibility" tags were already stripped when assigning to tagstring, do the same for comma separated tags.
Fixes #3596.
> Strip leading/trailing whitespace from comma-separated trace tags

- app/views/traces/index.html.erb
The border between items is familiar UI, so we can keep it, but lets use the secondary-actions approach instead.
This avoids using left-right specific border, margin and padding classes.
> Rework trace index to use secondary-actions

- app/views/api/notes/show.rss.builder
Was going to write tests for rss case in #3607 and I can't use `assert_select` to get `<dc:creator>` element without this namespace declared. `<dc:creator>` is where the user's name is revealed.
> Add xmlns:dc namespace to note show rss actions

- test/controllers/api/notes_controller_test.rb
They were commented out probably because they weren't working. They weren't working because `:` had to be replaced by `|` in element name selectors.
> Uncomment asserts for namespaced elements in note rss test

- app/helpers/user_helper.rb
Changes unused `rounded-lg` to respective `rounded-3`.
> Fix Bootstrap 5 rounded authentication buttons

- app/assets/stylesheets/common.scss
- app/views/site/about.html.erb
- app/views/site/fixthemap.html.erb
- app/views/site/welcome.html.erb
- app/views/traces/show.html.erb
Now that we're on Bootstrap 5 we are using RFS, which implements responsive font sizes. Therefore it's worth refactoring places where we have font-sizes declared in our common.scss, particularly for headers, because these custom definitions are not responsive.
I've also refactored the about, welcome and fixthemap pages slightly, to change the headers used, use the bootstrap '[lead](https://getbootstrap.com/docs/5.1/content/typography/#lead)' paragraph styling, and move some more CSS into bootstrap utils.
> Various font size changes

- script/statistics
Use absolute links instead of relative links which are incorrect since: https://github.com/openstreetmap/chef/commit/0eb2a2b70464e53cd52edcee3b2fa96ac8bc416b
Fixes: https://github.com/openstreetmap/openstreetmap-website/issues/3593
> Fix statistics script to use absolute links

- app/assets/stylesheets/common.scss
- app/views/browse/note.html.erb
- config/locales/en.yml
Add some wording wrapped around the 'Report this note' link to explain to users to resolve the note instead.
Also re-arrange to place this down at the bottom with less prominence than the comment/resolve form.
Tackling the issue reported by DWG, that too many note reports are coming to them, where the users could deal with it themselves: https://github.com/openstreetmap/openstreetmap-website/issues/3071
> Wording to discourage note reporting

- app/assets/stylesheets/common.scss
- app/views/layouts/_search.html.erb
This makes it keyboard selectable, and also preserves the event handler.
I had originally looked at using `tabindex="0"` to make the link itself selectable, but then the onclick event doesn't fire, so I went with using a button instead.
Refs #3637
> Switch reverse_directions link to use a button

- .github/ISSUE_TEMPLATE/feature.yml
When writing https://github.com/openstreetmap/openstreetmap-website/issues/3551 I noticed that your template is somewhat problematic.
What users really should write is how/why they have the feature request they want, i.e. what (problem) is “behind” a feature request. Similar to how user stories should always go like ”I as a [who] want [what], because [why]”, here the “why” aspect was missing.
The “Description” does not really tangle that, it only tangles _what_ the user wants.
Screenshots may also be better inline inside of a text description, but I see you want to nudge the user to add screenshots or mockups, so that's fine IMHO.
> Add cause to feature request issue template

- app/assets/stylesheets/common.scss
This restores the outline effect when the user menu button is focussed (e.g. using keyboard navigation).
Refs #3633
Personally I think the outline is a bit ugly when the user menu is expanded, but I can understand the concerns about accessibility - and those outweigh my aesthetic preferences.
> Remove the user menu focus overrides

- app/assets/javascripts/index/directions/graphhopper.js
When using directions, the footer says "Directions courtesy of Graphhopper", it should instead say _GraphHopper_.
> Correct name in graphhopper.js

- app/assets/javascripts/index.js
- app/assets/javascripts/index/browse.js
- app/assets/javascripts/index/directions.js
- app/assets/javascripts/leaflet.key.js
- app/assets/javascripts/leaflet.layers.js
- app/assets/javascripts/leaflet.share.js
- app/assets/javascripts/leaflet.sidebar-pane.js
- app/views/application/_sidebar_header.html.erb
- app/views/layouts/_search.html.erb
Implemented this:
> https://github.com/openstreetmap/openstreetmap-website/pull/3631#issuecomment-1203797930
> Many of the close buttons https://github.com/openstreetmap/openstreetmap-website/pull/2901 recently to use flexbox for layout, rather than floating, but there's still some (as found in this PR) where the icons are floating around. These could be refactored to follow the convention used in the sidebar.
Also refactored common code in Leaflet sidebars that wrote close buttons among other things.
> Position close buttons with flexbox

- app/views/site/help.html.erb
- config/locales/en.yml
Add link to the new [community forum](https://community.openstreetmap.org), replacing the link to the original "legacy" forum.
Intentionally replaced the translation keys to ensure replacement in the translated text.
> Add Link and text for the new community forum

- app/assets/javascripts/index/directions.js
- app/views/application/_sidebar_header.html.erb
Fixes buttons within geolinks issue: https://github.com/openstreetmap/openstreetmap-website/pull/3631#issuecomment-1203797930
For the directions sidebar I removed the geolink because its close button had its own click handler that prevented default actions.
> Remove geolink and close button nesting

- app/assets/javascripts/index/history.js
- app/assets/stylesheets/common.scss
- app/views/changesets/_changeset.html.erb
Use Bootstrap's stretched link instead of simulating clicking a normal link on [history](https://www.openstreetmap.org/history) pages.
Fixes https://github.com/openstreetmap/openstreetmap-website/issues/1020
> Stretch changeset links in history lists

- app/assets/stylesheets/common.scss
- app/views/changesets/_changeset.html.erb
There's one problem after merging #3675.
Let's suppose you're on a history page and you want to select the text of a changeset comment. It's a link so normally you'll hold Alt in addition to holding a button and moving your mouse. Except with Bootstrap stretched link it won't work because they implemented it with an ::after pseudo element inside the link that covers the link itself. Now you can only reach the pseudo element and not the text content.
But that's easily fixable by wrapping the text inside the link and lifting it above ::after.
I also made links for changeset ids so they can also be lifted above the pseudo element and be selectable while working as before when clicked.
> Text selection improvement for stretched links on history pages.

- app/assets/javascripts/index/history.js
- test/system/history_test.rb
There are different kinds of history (changeset list) pages:
- [*friends*](https://www.openstreetmap.org/history/friends) and [*nearby*](https://www.openstreetmap.org/history/nearby) history don't have feeds and don't have links to feeds; trying to modify the link results in javascript error
- *user* history has the feed link but it doesn't use the bbox parameter
- only [*place* history](https://www.openstreetmap.org/history) feed link needs bbox updates
> Rewrite bbox only in place history atom links

- app/assets/javascripts/index/browse.js
- app/assets/javascripts/index/directions.js
- app/assets/javascripts/leaflet.sidebar-pane.js
- app/views/application/_sidebar_header.html.erb
The margins mentioned in https://github.com/openstreetmap/openstreetmap-website/pull/3631#issuecomment-1203797930 are likely no longer necessary. They were leftovers from floated buttons put inside headers, probably to align the buttons with the text baseline. And they only affect the button position in the left sidebar.
| With margin-top | Without margin-top |
| --- | --- |
| ![b0](https://user-images.githubusercontent.com/4158490/188168631-ba9a6ff0-e236-4395-b1cf-961cd6c1cc11.png) | ![b1](https://user-images.githubusercontent.com/4158490/188168690-983a3aaa-c64b-44cc-ae6f-2a86f4e816c9.png)
> Remove top margins from close buttons

- app/assets/stylesheets/common.scss
I don't see it being used anywhere.
`pager` class was introduced in https://github.com/openstreetmap/openstreetmap-website/commit/a36f3558dd43dd5a598e36dd21fd5f7d2b4a94f5 for views that no longer exist. Last time that part of css was updated in https://github.com/openstreetmap/openstreetmap-website/commit/29e98571454a450f0af1e2649d1688c6f2afffdb and there weren't any `pager` classes in use.
> Remove unused pager secondary nav css

- app/assets/stylesheets/common.scss
- app/views/browse/new_note.html.erb
[New note page](https://www.openstreetmap.org/note/new) is the only place where was still in use. Replaced by `btn-wrapper` like it was done on /note/:id pages before.
`buttons` class was originally introduced in https://github.com/openstreetmap/openstreetmap-website/commit/597fb5d27f092f956235c04d77cf74cab2012b1a for rich text edit/preview buttons and was mostly removed during Bootstrap conversions like https://github.com/openstreetmap/openstreetmap-website/commit/c0adab7abaae779d2600aeb098f4d4fce07caba4 .
> Remove "buttons" css class used only on new note page

- app/assets/stylesheets/common.scss
Background images are no longer used on the about page so these properties are not required.
> Remove background image-related css from about page

- app/assets/stylesheets/common.scss
This is a pre-pre-bootstrap close button from 2013: https://github.com/openstreetmap/openstreetmap-website/commit/ded28617c7. It wasn't in use when I was replacing close buttons couple of months ago.
> Remove old map sidebar close button css

- app/assets/stylesheets/common.scss
- app/views/site/_about_section.html.erb
- app/views/site/about.html.erb
Icons on [the about page](https://www.openstreetmap.org/about) were shifted down too much because they were centered relative to headings with bottom margins. Also they were inside the headings which they shouldn't be, at least not as `<div>`s inside `<h2>`s.
Before:
After:
> Vertically center about page icons with flex align-items

- app/assets/stylesheets/common.scss
Currently tooltips are appended directly to `<body>`. Styles defined inside `#map-ui` can't affect them.
(originally added in https://github.com/openstreetmap/openstreetmap-website/commit/439ad373ec5ee364003625e56159b1dce5fb186e, https://github.com/openstreetmap/openstreetmap-website/commit/eda8b00fec)
> Remove unused tooltips css

- app/assets/stylesheets/common.scss
No longer in use since https://github.com/openstreetmap/openstreetmap-website/commit/1bf671f6847c0c5c6561520ef4970689a0977e55 and https://github.com/openstreetmap/openstreetmap-website/commit/0b1aafb7015c7ab1986407870d048b3a3dcefda6.
> Remove unused icon list css from welcome pages

- app/assets/stylesheets/common.scss
There was a fix #2547 for some bugs that set `height: 50%;` for the `#map` container but not for `#map-ui` sidebar. But `#map-ui` should be the same height as the map itself, right?
Fixes #3053
> Change map ui sidebar height together with map height

- app/assets/javascripts/index/browse.js
- app/assets/javascripts/index/directions.js
- app/assets/javascripts/leaflet.sidebar-pane.js
- app/views/application/_sidebar_header.html.erb
Mostly it's `<h*>` elements wrapped in `<div>`, which is not necessary because `<h*>` are already block-level elements.
> Remove unnecessary wrapper divs

- app/views/browse/feature.html.erb
- test/controllers/browse_controller_test.rb
Fixes https://github.com/openstreetmap/openstreetmap-website/issues/3325. I'm not displaying the link instead of greying it out because pages of elements that never existed don't have download links.
> Don't show 'Download XML' link for deleted elements

- app/controllers/api/notes_controller.rb
- config/routes.rb
- test/controllers/api/notes_controller_test.rb
Currently the notes API json return type can only be specified by appending the .json file extension at the end of the URL path. This is inconsistent to other JSON API entry points which also allow specifying the return type via the HTTP ACCEPT header.
I guess the routing tests (see example below) do not catch these cases because they do not allow to specify headers.
```
assert_routing(
{ :path => "/api/0.6/notes/1.json", :method => :get },
{ :controller => "api/notes", :action => "show", :id => "1", :format => "json" }
)
```
> Allow setting JSON return type by HTTP ACCEPT header for notes API

- app/views/browse/note.html.erb
"Hide" button doesn't work if the note is already hidden.
> Remove 'Hide' button from hidden note page

- app/assets/javascripts/index/note.js
- app/assets/javascripts/leaflet.map.js
"Current object" change from https://github.com/openstreetmap/openstreetmap-website/pull/3718.
Notes become "current objects" in `L.OSM.Map`. No user-visible changes.
> Make notes to be map current objects

- app/assets/javascripts/leaflet.map.js
- test/system/index_test.rb
An alternative to displaying some other icon instead of the missing "hidden" icon. Don't display any icon for hidden and other unknown note states, only show a "halo" circle marker.
Previous version with "closed" icon: https://github.com/openstreetmap/openstreetmap-website/pull/3718#discussion_r981484149
Fixes https://github.com/openstreetmap/openstreetmap-website/issues/1215 - when you have note layer enabled you can click on other notes after hiding a note.
Fixes https://github.com/openstreetmap/openstreetmap-website/issues/546 - although this bug doesn't fully manifests itself in current website versions. Before the fix clicking "history" works, but it's a full page reload. What is supposed to happen is a partial reload of the sidebar.
> Display icon for current note only if this icon is defined

- app/assets/javascripts/index/note.js
Another js bugfix.
Fixes things similar to https://github.com/openstreetmap/openstreetmap-website/pull/3746, but this time for hidden notes when you don't have permissions to see them (thus the details with coordinates are not written and it's impossible to get `latLng`) or for notes that never existed.
> Don't scroll to or show markers of notes with no data

- app/views/site/about.html.erb
This `<h5>` creates an [incorrect document outline](https://validator.w3.org/nu/?showoutline=yes&doc=https%3A%2F%2Fwww.openstreetmap.org%2Fabout).
> Replace <h5> used to set the font size with Bootstrap class h5

- DOCKER.md
Adds documentation to tell Windows users to enable symlinks before cloning the repo so that they don't run into #3422.
Also gives alternatives for a few UNIX commands that aren't supported on Windows.
> Add further Docker installation instructions for Windows users

- config/locales/en.yml
My editor does this any time the file is saved, so let's fix this.
Was introduced recently in #3565
> Strip trailing whitespace from copyright notice

- lib/nominatim.rb
get_text("reversegeocode/result") returns an XML text node.  We want to get the value of that node.
This will un-escape &#039; into an apostrophe.
All callers of this function will later re-encode it depending out output whether it be HTML in an email, or XML in an RSS feed.
* app/mailers/user_mail.rb
* app/helpers/geocode_helper.rb
* app/views/api/notes/feed.rss.builder
* app/views/api/notes/_note.rss.builder
Fixes openstreetmap/openstreetmap-website#3761
> Get the value of the text node to unescape it

- app/assets/javascripts/index/history.js
- test/system/history_test.rb
Since the pull request https://github.com/openstreetmap/openstreetmap-website/pull/3682 is not going anywhere I'll start taking it apart. Here are the changes in https://github.com/openstreetmap/openstreetmap-website/pull/3682/commits/10319cac0d54ddb9e8f1f467cf16928646474730.
On any history page that displays a list of changesets the "Load more" button loads more changesets. This button creates another list element for those changesets. You get as many lists as the number of times you pressed the button plus the original list. There's a line between list items but no line between lists. To the user it looks like some dividing lines are missing. Here you can see that there's no line between the second and the third changesets:
This PR makes "Load more" to merge the changesets it loads into …
> Merge changeset <ol>s on Load more

- CONTRIBUTING.md
We've got a lot of open PRs. In recent months there's been a few things I've noticed that make PRs harder to review. I think it's worth expanding the guidance in CONTRIBUTING.md, to document things that contributors can do to help.
I've also changed some of the phrasing of the existing guidance, since we don't tend to use the terms 'hacking' or 'patches'. In all honesty I can't remember the last time anyone wanted to send a `git format-patch` style email to the mailing list, so I've removed that paragraph too.
> Add guidance on making pull requests easier to review

- app/assets/javascripts/index.js
- app/views/application/_sidebar_header.html.erb
This is https://github.com/openstreetmap/openstreetmap-website/pull/3682/commits/cc9bcce5f0531243c34ffab8d43bc2885ff106ef + https://github.com/openstreetmap/openstreetmap-website/pull/3682/commits/b9f05806dbda4c33fcad5c1d68cb59623c432989
When I was changing close buttons to Bootstrap's `class="btn-close"`, I kept the one in the left sidebar as a link. It was a "geolink" and I didn't want to remove it because "geolinks" are updated when map view changes and I didn't know exactly how it was happening. Later in https://github.com/openstreetmap/openstreetmap-website/pull/3682 I finally replaced it with a button. I think I did it so I could cache the entire sidebar without worrying about map view updates.
> Use close button instead of geolink in sidebar content

- app/assets/javascripts/index/query.js
This is for "Query features" map tool. What was supposed to happen [here](https://github.com/openstreetmap/openstreetmap-website/commit/078059b76b8304368fd7ddac2dd563470e83472e#diff-8275a6df0995b2af17f0b52a0dfe5a00f8b09d9d51b89516e2612a3faa9d8c0fR127) is this I guess:
- the spinner is initially hidden
- when the query runs it's still hidden
- if the query runs longer than a second, the spinner is shown
The problem is that the spinner was never hidden. Therefore there's no point in having this delay timer.
> Remove query spinner show delay because the spinner is not hidden

- app/assets/javascripts/index/browse.js
- app/assets/javascripts/index/directions.js
- app/views/application/_sidebar_header.html.erb
- app/views/layouts/_banner.html.erb
- app/views/layouts/_search.html.erb
See https://github.com/openstreetmap/openstreetmap-website/pull/3631#issuecomment-1203797930. Now that all close buttons are actually button html elements, I can finish adding aria labels.
> Add aria-label to close buttons

- app/assets/javascripts/index/query.js
Fixes this:
1. use "query features" tool to get nearby/enclosing features lists in the sidebar
2. type some search query in search box above the sidebar but don't press enter yet
3. hover the pointer over one of nearby/enclosing features list items to see it appear on the map
4. press enter to run the search
5. notice that the hovered feature stays on the map
Possibly related to https://github.com/openstreetmap/openstreetmap-website/issues/2082.
> Remove query result geometry when unloading the page

- app/assets/javascripts/id.js
This is a small additional integration adjustment needed for iD v2.23: After https://github.com/openstreetmap/iD/commit/c8a3cf154b43469d643b034f47d4e48d449582a1 the configuration of API connections is not done in the "boot-up" routine anymore. But as the integrated iD uses the pre-authentication, it is now necessary to clear the default api (_live_ / _dev_) connections such that the "api" switcher (<img src="https://user-images.githubusercontent.com/1927298/201652584-c2a4b729-6235-4bb1-a0c1-1d96df04497d.png" height=24>) on the bottom right doesn't shown up (it is only supposed to show up on the stand-alone instances of iD such as the one on https://ideditor-release.netlify.app/).
PS: this should have been part of #3789 already.
> [iD] hide live/dev server switcher on integrated iD editor 

- .github/ISSUE_TEMPLATE/feature.yml
The syntax for the feature request GitHub issue template yaml file was wrong because two elements had the same ids and thus the feature request issue form did not work. This changes one that was the same.
> Fix feature request GitHub issue template

- CONFIGURE.md
- CONTRIBUTING.md
- DOCKER.md
- INSTALL.md
- README.md
- db/functions/quadtile.c
As discussed in #3796 , the "rails port" terminology is confusing. This PR standardises on "openstreetmap-website" throughout.
This also picks up 3 minor documentation fixes that I found at the same time, which I've put in a separate commit.
> Remove references to "The Rails Port"

- Gemfile
- Gemfile.lock
This lets us receive 7.0.x patch releases without having to edit the Gemfile.
I considered making this `~> 7.0` since point releases are usually safe (in particular, if you run `bundle update` and the tests pass, then all good) but there's often a "new framework defaults" file that needs to be generated. So there's an argument that minor 7.x releases should still be treated differently.
> Relax strict version constraint on rails gem

- app/controllers/sessions_controller.rb
- app/controllers/users_controller.rb
- app/views/changesets/history.html.erb
- app/views/sessions/_suspended_flash.html.erb
- config/locales/en.yml
Following on from #2898 and #2919, and using the flash technique from #3232 we can get rid of more uses of `html_safe` in our views. This takes care of the user suspended flash message, and a link in the browse sidebar.
> Remove more usage of html_safe

- config/brakeman.yml
These have been refactored already, so no longer need to be skipped.
> Enable more brakeman checks

- app/controllers/api/notes_controller.rb
- app/helpers/note_helper.rb
- app/models/note.rb
- app/views/browse/note.html.erb
- config/locales/en.yml
- test/helpers/note_helper_test.rb
Modify the message displayed at the bottom of the notes sidepanel. For already resolved notes we don't want to say "please resolve it". Fixes https://github.com/openstreetmap/openstreetmap-website/issues/3663  .
Instead explain that it will disappear from the map (so reporting is probably not necessary) and display how long to go until that happens. Tackling https://github.com/openstreetmap/openstreetmap-website/issues/3071
_"For all other problems, resolving is sufficient. This resolved note will disappear from the map in X days"_
> Display how long until a note will disappear

- app/views/users/blocked.html.erb
- app/views/users/suspended.html.erb
- config/locales/en.yml
This also reworks the user suspended page to avoid having html in the translation strings.
> Use mail_to help to avoid handcrafting mailto links

- .github/workflows/tests.yml
- INSTALL.md
- db/migrate/028_add_more_changeset_indexes.rb
- docker/postgres/openstreetmap-postgres-init.sh
- script/vagrant/setup/provision.sh
This simplifies the install instructions. Loading from structure.sql is already handled.
The more I thought about what I wrote in #3110 the more I realised it was worth doing anyway.
> Automatically enable the btree_gist extension

- .github/workflows/tests.yml
This is more painful that it ought to be for a number of annoying reasons...
Firstly https://github.com/ruby/setup-ruby currently only supports ruby 3.1 on 22.04 even though 22.04 actually ships with 3.0 as the system ruby - apparently 3.1 is the first version that builds with openssl 3 out of the box so I guess Ubuntu must have patched 3.0 for the system build.
Secondly the forced move to a snap for Firefox means that geckodriver has (currently at least) gone away ([discussion here](https://bugs.launchpad.net/ubuntu/+source/firefox/+bug/1968266)) so we need to switch to Chrome and hope we won't have the same problem there once they force a move to snap for that!
Finally because chrome in headless mode doesn't support browser preferences ([discussion …
> Add testing on Ubuntu 22.04

- lib/osm_community_index.rb
- test/lib/osm_community_index_test.rb
- test/system/view_communities_test.rb
This uses the fallbacks for OCI translations. For example, if a local chapter doesn't have an explicitly translated name, it will use a template for osm-lc resources and fill in the appropriate translated community name.
Fixes #3814
> Use fallbacks for OCI resource names

- README.md
In #3653 and #3814 noticed that communities name listed in https://www.openstreetmap.org/communities can't found in TranslateWiki
> docs(README.md): add communities name translate guide

- app/controllers/users_controller.rb
- test/system/user_signup_test.rb
Adds missing test to pick this up.
Fixes #3826.
> Fix redirection to wiki when terms are declined

- test/controllers/api/changesets_controller_test.rb
- test/controllers/diary_entries_controller_test.rb
- test/controllers/users_controller_test.rb
- test/integration/user_diaries_test.rb
- test/models/way_test.rb
I came across these while working on something else - there's no need to keep them in the code.
> Remove some old debugging comments

- app/views/layouts/_header.html.erb
These elements don't link to another page, and so there's no need to use a link that leads to nowhere.
Refs #3679
> Use buttons for dropdown toggles

- .github/workflows/lint.yml
- .github/workflows/tests.yml
Without quotes these are parsed as numbers, which can cause subtle problems. For example, "ruby: 3.0" is interpreted by the ruby/setup-ruby action as "ruby: 3", meaning 3.x instead of the intended 3.0.x
The test suite started failing a couple of days ago, with an error installing nokogiri - this is because nokogiri doesn't support ruby 3.2 yet, we were inadvertently installing "ruby: 3" instead of "ruby: '3.0'", and then when setup/ruby was updated a couple of days ago to support 3.2 this bug was unveiled.
It also means we haven't actually been testing on ruby 3.0.x since ruby 3.1 was released - our tests were just running twice on ruby 3.1 :smile:
> Quote ruby versions in yaml

- config/locales/en.yml
This PR is to address #3650
For comment submit buttons we currently have:
"Comment" (Changeset Comments)
"Add Comment" (Issue Comments)
"Comment" (Note Comments)
"Save" (Diary Comments)
So, to make them consistent, I'd propose to change "Save" to "Comment"
> Change Save to Comment

- app/helpers/browse_tags_helper.rb
- test/helpers/browse_tags_helper_test.rb
If a tag value currently contains two URLs separated by a semicolon, the website creates a broken clickable link. 
[This example node](https://osm.org/node/9335292678) can be viewed on osm.org and in the Washington, D.C. example from [the installation guide](https://github.com/openstreetmap/openstreetmap-website/blob/master/DOCKER.md#loading-an-osm-extract).
<table>
<tr>
<td><strong>Before
<td><strong>After
<tr>
<td><img src="https://user-images.githubusercontent.com/16009897/210159559-222dab8d-6562-4e5b-9471-1ed0123ced86.jpg" />
<td><img src="https://user-images.githubusercontent.com/16009897/210159568-b5d9a27c-e801-4c46-afa5-f6afe3acd213.jpg" />
</table>
Closes openstreetmap/iD#9444 which was opened in the wrong issue tracker.
p.s. Please reconsider merging #3575, it's impossible for …
> fix formatting of tag values with semicolon-separated URLs

- app/views/errors/_contact.html.erb
- app/views/errors/forbidden.html.erb
- app/views/errors/internal_server_error.html.erb
- app/views/errors/not_found.html.erb
- config/locales/en.yml
> Make error pages translatable

- .github/workflows/lint.yml
- .github/workflows/tests.yml
- Dockerfile
- INSTALL.md
- script/vagrant/setup/provision.sh
Since rails 7, the `rails yarn:install` command no longer uses bin/yarn and so it
- doesn't detect yarn binaries named "yarnpkg" (e.g. Ubuntu), and
- doesn't allow us to pass any flags to yarn, (e.g. "--ignore-engines").
Since we want to avoid making the installation more difficult (by e.g. installing yarn from other sources, or requiring particular node versions) we can instead just use our existing bin/yarn script.
The reason Dockerfile did its own thing was to avoid pulling in big chunks of rails, but bin/yarn is a standalone ruby script.
Fixes #3579
> Use bin/yarn consistently for installations

- app/controllers/api_controller.rb
- app/controllers/application_controller.rb
- app/controllers/notes_controller.rb
I noticed this while I was looking at the (non-API) NotesController, which doesn't need to have any api-related error handling.
> Move some api call handlers to ApiController

- app/helpers/browse_tags_helper.rb
- test/helpers/browse_tags_helper_test.rb
Fixes #2184
Since I also updated the prefix list which is used for both `wikipedia` and `wikidata`, that reimplemented:
- #2812
> Link prefixed wikipedia tags

- config/locales/en.yml
This PR just changes the label for tag [leisure=horse_riding](https://wiki.openstreetmap.org/wiki/Tag:leisure%3Dhorse_riding)
**from "Horse Riding" to "Horse Riding Centre"** in en.yml and thus resolves https://github.com/openstreetmap/openstreetmap-website/issues/3189
The motivation is to make it clearer to the user what the object tagged in this way is. Simply "hoirse riding" is too generic and an activity rather than a location for that activity. Other tags with suboptimal names also have more descriptive labels, e.g.
leisure=dance : "Dance Hall"
leisure=fishing : "Fishing Area"
The presets for leisure=horse_riding in the main editors iD and JOSM are now also named "Horse Riding Centre" (or "Horseback Riding Center" in US English, see …
> Change label for leisure=horse_riding in en.yml

- app/views/accounts/_go_public.html.erb
- app/views/accounts/edit.html.erb
- app/views/site/_any_questions.html.erb
- app/views/site/export.html.erb
- app/views/site/fixthemap.html.erb
- app/views/site/welcome.html.erb
- app/views/traces/index.html.erb
- app/views/users/new.html.erb
- config/locales/en.yml
- test/controllers/traces_controller_test.rb
This is the first batch of changes to avoid using html in our translation strings. It reworks various views to make sure that all html (e.g. links, paragraphs, bold tags etc) are defined in the view, and that the translations only contain the words that need to be translated. The aim is, among other reasons, to make it easier to translate since it avoids having to get the brackets, quoting etc correct to ensure valid html.
The primary challenge with this refactoring is, as usual, to make sure that the translation keys change whenever there is a difference with interpolations, which leads to a little strain around picking new translation keys.
> Avoid using html in translations

- Gemfile
- Gemfile.lock
- config/i18n-tasks.yml
This can be used for checking our translations, for example to see if there are unused translations in en.yml, and various other tasks.
My aim is to have the `i18n-tasks unused` run as part of CI, but that's not possible yet since there's still some translations (and false-positives) being flagged up for attention. 
Meanwhile, I think it's worth including the gem and the configuration that I've been working on, so that other people can (potentially) contribute to the task.
Refs #3960
> Add the i18n-tasks gem

- config/locales/en.yml
Change the date range for Ordnance Survey Open Data licensed under the Open Government Licence (OGL) from "2010-19" to "2010-22" to comply with OGL terms.
Fixes #3845
> Update OSGB date range for copyright

- CONTRIBUTING.md
This comes up every now and then, and so let's have the existing procedure documented.
> Document the procedure to change the copyright attribution page

- app/views/diary_entries/_form.html.erb
It was missing some space between the form and the Publish button:
With this change:
> Add space between form and Publish diary button

- app/views/user_mailer/gpx_success.html.erb
- config/locales/en.yml
This fixes almost all the cases referred to in #3972.
I think the only remaining case is `users.index.showing` which is kind of weird and is only ever seen by administrators.
> Include count in messages for the "one" plural category

- app/views/site/copyright.html.erb
This PR removes two incorrect language blocks declarations from the copyright page. In both cases, the text is shown in the users native language that is used for the rest of the page (i.e. there are no `@locale` overrides) and so no additional language declarations are required for those parts of the page.
Although marking the language incorrectly in html doesn't have much of a user-visible impact, the dir attribute causes problems that are easier to see. If you set your language preference to `ar` and view the copyright page, then you will see Arabic written LTR due to these incorrect declarations.
The solution is to remove them, while keeping the language (and direction) overrides for the parts of the page that use the `@locale` override.
> Remove incorrect language blocks from copyright page

- app/views/site/_about_section.html.erb
- app/views/site/about.html.erb
- app/views/site/copyright.html.erb
- test/controllers/site_controller_test.rb
This PR changes the about and copyright pages to use `I18n.with_locale` blocks, instead of using `:locale` overrides on each translation.
This makes it slightly less verbose, and slightly easier to get right when adding additional translations to these sections. But more importantly, it makes it much less verbose when using interpolated translations, e.g. 
```erb
<%= t ".foo_html", :locale => @locale,
:first_link => link_to(t(".bar", :locale => @locale), t(".bar_url", :locale => @locale)),
:second_link => link_to(t(".baz", :locale => @locale), t(".baz_url", :locale => @locale)),
... etc ...
```
vs
```erb
<% I18n.with_locale @locale do %>
<%= t ".foo_html", :first_link => link_to(t(".bar"), t(".bar_url")),
:second_link => link_to(t(".baz", t(".baz_url"))
... etc ...
```
The `with_locale` …
> Use with_locale instead of individual locale overrides

- app/assets/stylesheets/ltr/small.scss
- app/assets/stylesheets/rtl/small.r2.scss
These should have been removed as part of 5ab682dbbdc0bc4034d1c93aae3d082dae09fa65
> Remove unused small.scss symlinks

- test/lib/i18n_test.rb
These only apply to the en.yml file for now, but can be expanded in due course.
I had a long search for any third-party utilities that could do this for us, but I didn't find anything appropriate. None of the generic yaml validators that I found allowed custom validations of values (most were just focussed on validating the type of the value, int/string/hash etc against a fixed schema). I also checked for any i18n-specific validators, but again I didn't find any that could validate the values.
I expect to expand these checks to cover the rest of the translations, but there are currently a bunch of translations in the output that contain html elements (that aren't included in en.yml, which is interesting). I also expect to expand these check to add more validations, perhaps validating urls …
> Add some validations for i18n values

- INSTALL.md
- script/vagrant/setup/provision.sh
These are unnecessary for development environments, and are not used in the Fedora instructions nor in the Dockerfile.
[It looks like it was me who added them back in 2013](c3d7cfd7ff90879511ff1c8b54a5d280e2e15057), but I don't know why!
> Remove apache packages from install instructions and vagrant config

- docker-compose.yml
Resolves https://github.com/OpenHistoricalMap/issues/issues/516 but not sure if it might cause other problems? Also not sure why no one upstream at OSM has ever had to deal with this issue, since it seems at least somewhat known in the Rails world, based on https://ieftimov.com/posts/docker-compose-stray-pids-rails-beyond/
> Update docker compose to solve stray PID problem

- .github/workflows/docker.yml
- .github/workflows/lint.yml
This PR changes the single-platform workflows to run on 22.04. Given that this is github-flavoured-ubuntu, it's not super important which version they run on since they all contain the same packages (node, geckodriver, etc are not from upstream Ubuntu).
Refs #4048
> Update workflows to run on Ubuntu 22.04

- INSTALL.md
- Vagrantfile
- script/vagrant/setup/provision.sh
Refs #4048
* geckodriver is now inside the firefox snap package
* the yarnpkg package is completely broken, see https://bugs.launchpad.net/ubuntu/+source/node-yarnpkg/+bug/2003697
> Update vagrant provisioning for 22.04

- Dockerfile
* Node 12 is sufficient for now, and aligns with INSTALL.md and vagrant
* Upstream yarnpkg is completely broken, see https://bugs.launchpad.net/ubuntu/+source/node-yarnpkg/+bug/2003697
Refs #4048
> Use default version of node, but use npm to install yarn

- Dockerfile
- INSTALL.md
- Vagrantfile
- script/vagrant/setup/provision.sh
Refs https://github.com/openstreetmap/openstreetmap-website/issues/4048
* We don't currently need a specific version suffix on the package names,
since ubuntu only ships with one ruby version (and newer versions on
e.g. 23.04 are fine).
* We don't need to explicitly install libruby, since it's pulled in by
other packages as required.
* Ubuntu again ships a decent enough version of bundler for our needs,
so we don't need to install it via rubygems.
Please note: This PR builds on top of #4050 , I thought it would be useful to put this up for review even though that PR isn't yet merged.
> Simplify ruby installations

- .gitignore
This can be created by passing flags to bundler, such as the ones used in our vagrant provisioning
> Ignore .bundle/config

- config/image_optim/development.yml
Lots of new developers see this during configuration (e.g. rails db:migrate) and then spend time trying to fix them, by figuring out what packages are missing (or just worrying that something is wrong). So let's silence the warnings entirely in the development environment.
An alterative would be to expand the installation instructions to add all the additional packages, but this just makes the (already lengthy) installation process take more time, for little gain.
I was surprised to find this topic mentioned in #4038 since it's been so long since I've seen the warnings. But then I found that I've created this file (and locally ignored it using .git/info/excludes) many years ago. So I think it's reasonable to have the same approach happen out-of-the-box for new developers.
The main …
> Silence image_optim warnings in development

- app/views/site/copyright.html.erb
- config/locales/en.yml
We are required to cite the source of open data in accordance with the Serbian Open License (Law on eGovernment, Article 26). This PR is adding proper copyright text for Serbia official sources
> Adding information about Serbia sources

- app/views/site/copyright.html.erb
When doing commit https://github.com/openstreetmap/openstreetmap-website/commit/d1fe40ac69719f4f835fbcd44a06368f9136d343, there were regression in ERB Lint which is failing now (aligning arguments). This PR tries to fix that
> Fix ERB Lint for copyright page

- app/assets/stylesheets/common.scss
- app/controllers/site_controller.rb
- app/views/layouts/_flash.html.erb
- app/views/site/edit.html.erb
- app/views/site/offline.html.erb
- test/controllers/accounts_controller_test.rb
- test/controllers/messages_controller_test.rb
- test/controllers/passwords_controller_test.rb
- test/controllers/preferences_controller_test.rb
- test/controllers/profiles_controller_test.rb
- test/controllers/site_controller_test.rb
- test/integration/user_login_test.rb
This PR makes the following changes:
- Notices, warnings and error messages which appear under the search bar will use Bootstrap's classes (instead of the custom `flash` classes)
- The `offline.html` page gets a facelift (red background around the message)
- The `edit.html` page also gets facelift although I wasn't able to test it since it redirects me to `/offline/`.
Note that `alert-success` uses `#D4EDDA` while `flash flash-notice` uses `#CBEEA7` for background colour. It w
> Facelift `offline.html` and use Bootstrap classes for "notifications" under the search bar

- test/helpers/application_helper_test.rb
- test/helpers/note_helper_test.rb
The test suit currently fails if your development environment (e.g. your own laptop) is set to a timezone outside of the UK. I encountered this earlier this year, at the Karlsruhe Hack Weekend, but I'm surprised more people haven't complained about it! The failing test is:
```
Failure:
ApplicationHelperTest#test_friendly_date [/home/andy/src/openstreetmap-website/test/helpers/application_helper_test.rb:62]:
Expected /^<span title=" *5 March 2014 at 18:58">.*<\/span>$/ to match "<span title=\" 5 March 2014 at 17:58\">over 9 years</span>".
```
This is because that test uses `Time.new(...).utc`, which is not the same thing as `Time.utc(...)`.
But why does it work - all year round - in the UK? 
`Time.new` takes an optional list of year, month, day etc (defaults to midnight first of January) …
> Fix test suite to work in non-UK timezones

- config/locales/en.yml
Fixes Issue #1828 
Changed title and alt text of the button.
No variables were renamed, so functioning of auth should stay unaffected.
Internally the identifier "windowslive" is being used (as it was), just the UI shows "Log in with Microsoft" instead.
> Title and alt text changed from Windows Live to Microsoft Account

- test/lib/i18n_test.rb
This closes a potential security issue, where unreviewed html could be added via translation files.
> Expand raw html checks to all translation files

- app/views/diary_entries/_diary_entry.html.erb
- app/views/issues/show.html.erb
- config/locales/en.yml
- test/lib/i18n_test.rb
This makes it impossible to translate to other languages that use the `zero:` key, e.g. for other numbers that end in zero.
An alternative approach would be possible in future, when ruby-i18n and rails and translatewiki all have full support for `0:` and `1:` keys.
Fixes #3997
> Avoid using the zero key for pluralisation in English

- vendor/assets/iD/iD.js
Hotfix to fix a crash when rendering `email` UI fields: https://github.com/openstreetmap/iD/issues/9752
> Update to iD v2.26.1

- config/locales/en.yml
Without this, translatewiki's validator shows an error for English.
> Consistent plural forms for browse.way.nodes_count

- app/controllers/api/changesets_controller.rb
- test/controllers/api/changesets_controller_test.rb
Similar to notes query limit parameter.
Defaults to 100 changesets, which was the only possible value before. Max value is also 100, feel free to change it.
Use example: I need to get the latest changeset of a user. Without the limit parameter I have to download hundred changesets, although I only need one.
> Add limit parameter to api changesets query

- app/assets/javascripts/leaflet.share.js
- app/assets/stylesheets/common.scss
`display` is already manipulated by jquery `.show()` and `.hide()`, makes sense to do it everywhere
> Remove display properties from share tabs

- app/assets/stylesheets/common.scss
This is already a bootstrap default: https://getbootstrap.com/docs/5.1/content/reboot/#forms
> Remove resize css property from textarea

- app/views/oauth2_authorized_applications/_application.html.erb
Addresses #4103 by removing the links, which is the simplest and safest thing to do.
> Remove links to apps from OAuth2 authorizations page

- app/assets/stylesheets/common.scss
- app/assets/stylesheets/print.scss
They weren't applied to print media (according to print media simulation in Firefox).
> Move map attribution print styles to print.scss

- app/assets/stylesheets/common.scss
Share panel doesn't have any lists.
Layers panel has two:
- The bottom one with checkboxes has zero margins anyway.
- The one with layer buttons overrides margins with its own values. Merging #3674 will remove this list.
> Remove unused 0 bottom margin from map ui css

- app/assets/stylesheets/common.scss
100% width + float is like stacking vertically. But this is the default behavior for block elements. And those divs are inside another floated element.
> Remove unnecessary full-width float css from sidebar

- app/views/layouts/_head.html.erb
Original version was introduced in 6674873478c9fe221d2fd78f76cabc6d4b03c0aa and has not been changed since.
Google's PageSpeed Insights tool also flagged this up as an accessibility issue, since it previously prohibited users zooming into the site.
> Switch to bootstrap recommended viewport definition

- app/controllers/application_controller.rb
- app/models/trace.rb
This is preferable to using SQL statements.
I double checked the output of the `.or()` formulation, and apart from extra table names and quoting, it's the same query.
```
> print Trace.visible.where("visibility IN ('public', 'identifiable') OR user_id = ?", u).to_sql
SELECT "gpx_files".* FROM "gpx_files" WHERE "gpx_files"."visible" = TRUE
AND (visibility IN ('public', 'identifiable') OR user_id = 1)=> nil
> print Trace.visible.where(:visibility => %w[public identifiable]).or(Trace.visible.where(:user => u)).to_sql
SELECT "gpx_files".* FROM "gpx_files" WHERE "gpx_files"."visible" = TRUE
AND ("gpx_files"."visibility" IN ('public', 'identifiable') OR "gpx_files"."user_id" = 1)=> nil
```
> Use hashes to define where..in sql queries

- app/assets/stylesheets/common.scss
`#errorExplanation` is the old rails [error message id](https://guides.rubyonrails.org/v2.3.11/activerecord_validations_callbacks.html#customizing-the-error-messages-css)
- was added in https://github.com/openstreetmap/openstreetmap-website/commit/37bd2971b49da9364fe5dd25415e97e38b34abd7
- was updated to `.formError` in https://github.com/openstreetmap/openstreetmap-website/commit/c5fc21e6a6615646b3fa443b6fd12a80b4fef331
- was updated to bootstrap in https://github.com/openstreetmap/openstreetmap-website/commit/cc8bb7c6a5730e9d7d0389e4efd4c896702f575f
> Remove old rails error css

- app/assets/javascripts/user.js
- app/assets/stylesheets/common.scss
- app/views/profiles/edit.html.erb
`#accountForm` selectors weren't in use because there's no such id on profile edit pages
> Remove custom css from user profile edit pages

- app/assets/stylesheets/common.scss
User menu (dropdown with username) is stretched horizontally in small navigation mode, but login menu isn't. Let's stretch it too.
Before:
After:
> Stretch login menu buttons in small nav mode

- app/controllers/issues_controller.rb
Sets `<title>` to the same value as `<h1>`,
otherwise it's inconvenient to have several browser tabs with issues.
> Add titles to issue pages

- app/assets/stylesheets/common.scss
Probably was there to remove double underline, one from border, other from text decoration. Nowadays there are no borders on abbrs/links, and Bootstrap does [its reset](https://getbootstrap.com/docs/5.1/content/reboot/#inline-elements).
Was added in https://github.com/openstreetmap/openstreetmap-website/commit/0b913efd0583570c5a9cd900189fc88085218d61 .
> Remove unnecessary css from diary entry locations

- app/assets/stylesheets/common.scss
- app/views/messages/show.html.erb
Also removed leftover `</td>`s from old table layout in de8a60a3e371e6289643dfb578b75458b856b07d.
> Use Bootstrap to format message headers

- app/assets/javascripts/user.js
- app/controllers/diary_entries_controller.rb
- app/helpers/application_helper.rb
- app/models/user.rb
- app/views/api/users/_user.json.jbuilder
- app/views/api/users/_user.xml.builder
- app/views/dashboards/_contact.html.erb
- app/views/dashboards/show.html.erb
- app/views/layouts/map.html.erb
- app/views/profiles/edit.html.erb
- config/locales/en.yml
- also undo delete button
- also show button to center map on currently entered coordinates
- also `has_home?` method in user models instead of doing home_lat && home_lon
Fixes #3725
> Delete button in Home location section of user profiles

- app/assets/javascripts/messages.js
- app/assets/stylesheets/common.scss
- app/views/messages/_message_summary.html.erb
- app/views/messages/_sent_message_summary.html.erb
- app/views/messages/inbox.html.erb
- app/views/messages/outbox.html.erb
- `width: 1%;` wasn't working correctly because `.inbox-delete` no longer existsted after rename in https://github.com/openstreetmap/openstreetmap-website/commit/73df8447e3918f08156dd69ddf631652d048f191
- Instead of showing/hiding cells with buttons I show/hide their wrapping forms.
- Many class names had `inbox` in them even if they were used in outbox. `.inbox-row-*` is still kept because it is used in tests and sets row colors which I don't want to change yet.
> Remove most of custom css in message inbox/outbox tables

- app/controllers/api/changesets_controller.rb
- test/controllers/api/changesets_controller_test.rb
When you want to get an unknown number of changesets matching some criteria, you use `/api/0.6/changesets` with the corresponding parameters. If you receive a number of changesets that is equal to the limit, you know there might be more matching changesets. To get the next page of changesets you set the upper limit of the `time` parameter to the last received changeset.* The lower limit is usually set to some date before osm existed. Then you run the query again and receive the next page of results. That next page should consist of changesets created earlier than the ones received previously.
But what if you want a previous page? You can't set the upper time limit to the first received changeset because you'll get the same result again.* You can set the lower limit, but then you'll still …
> Add order parameter to changeset query API call

- test/controllers/api/changesets_controller_test.rb
- test/controllers/api/relations_controller_test.rb
for forks that want to have something other than 'OpenStreetMap server' as a default generator
> Use Settings.generator string in tests

- .rubocop_todo.yml
- app/controllers/diary_entries_controller.rb
- app/controllers/issue_comments_controller.rb
- app/controllers/user_roles_controller.rb
- app/helpers/application_helper.rb
- app/helpers/user_roles_helper.rb
- app/models/user.rb
- app/views/api/users/_user.json.jbuilder
- app/views/api/users/_user.xml.builder
- app/views/dashboards/_contact.html.erb
- app/views/dashboards/show.html.erb
- app/views/layouts/map.html.erb
- app/views/profiles/edit.html.erb
- test/models/user_test.rb
This renames the two `has_xxx?` predicate methods in the user model and enables the rubocop warning that catches them.
> Fix predicate method names in the user model

- app/assets/stylesheets/common.scss
Later versions of Bootstrap don't have it.
See https://github.com/twbs/bootstrap/pull/35230
Fixes #4104
> Don't do direction override from Bootstrap reboot of <code>

- app/assets/stylesheets/common.scss
> Use multiple columns for map controls if they don't fit vertically

- app/controllers/api/changesets_controller.rb
- test/controllers/api/changesets_controller_test.rb
See https://github.com/openstreetmap/openstreetmap-website/pull/4164#issuecomment-1677667971
These parameters work exactly like they do with note searches when notes are sorted by `created_at`.
`time` parameter is left unchanged, but its use together with `order=oldest` is disallowed.
Sorting is restored to `created_at`.
Supersedes #4168
> Add 'from' and 'to' changeset query parameters

- app/controllers/issues_controller.rb
Reported users are either directly assigned to moderators or ofter reassigned to them.
> Add 'User' to selectable types in issues search for moderators

- app/controllers/api/notes_controller.rb
- app/views/api/capabilities/show.builder
- app/views/api/capabilities/show.json.jbuilder
- config/settings.yml
- test/controllers/api/capabilities_controller_test.rb
- test/controllers/api/notes_controller_test.rb
Same as #4142 but for notes.
Makes note and changeset query limit code the same.
> Add note limit settings, use them in capabilities and tests

- app/controllers/api/changesets_controller.rb
- test/controllers/api/changesets_controller_test.rb
The response used to be of type xml with empty body, which is not valid xml.
> Respond with plaintext when user not found in changeset query

- app/controllers/api/users_controller.rb
- app/views/api/users/index.xml.builder
- test/controllers/api/users_controller_test.rb
When using the Users API to find a set of specific users by their ids and including an id of a user that deleted their account in this set, the request will currently fail with a 404
For example requesting the details of the users with the ids `18597840` **and** `185978900` [fails with a 404](https://www.openstreetmap.org/api/0.6/users?users=18597840,185978900) whereas limiting the query to user `18597840` returns the [correct result](https://www.openstreetmap.org/api/0.6/users?users=18597840)
This happens because user `185978900` deleted their account and `find()` raises an `ActiveRecord::RecordNotFound` "If one or more records cannot be found for the requested ids". <sup><a href="https://api.rubyonrails.org/v7.0.7.2/classes/ActiveRecord/FinderMethods.html#method-i-find">1</a></sup> …
> Use `where()` instead of `find()` to prevent RecordNotFound

- app/controllers/users_controller.rb
- config/initializers/rate_limits.rb
- config/settings.yml
- lib/rate_limiter.rb
This PR attempts to add support for rate limiting signups from a given IP address and/or email address.
Obviously we only allow one account per email address but this works on the basis of a canonical address where any `+` extension is removed, and dots are stripped from the local part for gmail.
> Add support for rate limiting signup requests

- app/assets/javascripts/index/changeset.js
- app/controllers/api/changeset_comments_controller.rb
- app/models/user.rb
- app/views/browse/changeset.html.erb
- config/settings.yml
- db/migrate/20230825162137_restore_author_index_to_changeset_comments.rb
- db/structure.sql
- lib/osm.rb
- test/controllers/api/changeset_comments_controller_test.rb
This inspired by but not identical to the algorithm proposed in #4196.
It ramps up to a specified maximum rate (default 60 per hour or 1 per minute) over the first two hundred changesets, subject to a configured minimum that defaults to 1 every 10 minutes with each unresolved report of the user halving the limit.
By my calculations this algorithm, with these defaults, will take just under 12 hours to reach the maximum limit if you constantly post as soon as you can - so that would be two hundred posts in 12 hours after which you can do 60 per hour and all assuming nobody has reported you.
Moderators have an arbitrary high limit of ten per second.
The down rating for reports might be a bit harsh but we can adjust it if that turns out the be the case.
> Add rate limiting for changeset comments

- app/controllers/application_controller.rb
- app/controllers/changesets_controller.rb
- app/controllers/concerns/user_methods.rb
- app/controllers/confirmations_controller.rb
- app/controllers/diary_entries_controller.rb
- app/controllers/friendships_controller.rb
- app/controllers/messages_controller.rb
- app/controllers/notes_controller.rb
- app/controllers/traces_controller.rb
- app/controllers/user_blocks_controller.rb
- app/controllers/user_roles_controller.rb
For things that have username in their path like `https://www.openstreetmap.org/user/<username>/diary`. Later also for things with user id in their path.
The goal is to make `ApplicationController` smaller. <s>Code dealing with resolving user names/ids will go into the base class.</s> Adding anything to `ApplicationController` will cause Rubocop to complain.
> Move user lookup/error methods from app controller to concerns

- app/controllers/api/changesets_controller.rb
- app/controllers/api/notes_controller.rb
- app/controllers/changesets_controller.rb
- app/controllers/diary_entries_controller.rb
- app/controllers/issues_controller.rb
- app/controllers/user_roles_controller.rb
- app/models/changeset.rb
- app/models/trace.rb
- test/controllers/diary_entries_controller_test.rb
- test/models/trace_test.rb
This PR refactors some database queries, to avoid using `_id` and use the relation names instead. Generally this involves changing `.where(user_id => u.id)` to `.where(user => u)` or similar. Sometimes the relation name is quite different from the underlying column (e.g. `gpx_id` => `trace`).
Rails is pretty forgiving on whether you pass in an id or an object, so sometimes there's nothing to change on the right hand side.
> Avoid using _id in queries

- app/controllers/messages_controller.rb
That let's us use relation names (like `sender`) and avoid dealing directly with ids.
> Use Activerecord '#or' method for queries

- app/controllers/api/changeset_comments_controller.rb
- app/models/user.rb
- config/settings.yml
- config/settings/test.yml
- test/controllers/api/changeset_comments_controller_test.rb
- test/factories/issues.rb
This aims to address the review comments from #4202 which was already merged.
It mostly makes the request changes - one different is that I went with `initial` rather than `default` as the new name for the starting limit as default seemed confusing when it's only the default for a new user.
> Address review comments for changeset comment limiting

- app/assets/stylesheets/common.scss
- app/helpers/issues_helper.rb
- app/views/layouts/_header.html.erb
- app/views/layouts/_inbox.html.erb
- app/views/users/show.html.erb
This leaves bootstrap to take care of most aspects of the badge, while retaining the current colours and font weights.
This is the first PR in a wider project to remove our use of the Sass '/' division operator, which is deprecated and will be removed in future: https://sass-lang.com/documentation/breaking-changes/slash-div/ . All of our use of '/' division is in old custom CSS code, so my aim is to replace the code with bootstrap alternatives when possible.
> Use bootstrap badges to implement count-number badges

- app/views/api/notes/feed.rss.builder
- config/locales/en.yml
You can get a feed of notes unrestricted by any bounding box: https://api.openstreetmap.org/api/0.6/notes/feed
It's not entirely clear if this is planned. The query runs rather slow, the [wiki](https://wiki.openstreetmap.org/wiki/API_v0.6#RSS_Feed:_GET_/api/0.6/notes/feed) shows `bbox` as required, but the requirement was dropped more than ten years ago.
If it is supposed to work, the description element in the feed is going to look strange. It refers to an area and has slots for bounding box lat/lon, but since the area is undefined, the slots are empty:
<description>A list of notes, reported, commented on or closed in your area [(|) -- (|)]</description>
This PR adds another description string for feeds of all notes without area restrictions.
> Add notes feed description for unspecified area

- app/controllers/concerns/email_methods.rb
- app/controllers/users_controller.rb
The methods are not directly related to users.
Rubocop complains about users controller being too large.
> Move email-related methods to mixin

- app/controllers/api/map_controller.rb
- app/controllers/api/notes_controller.rb
- app/controllers/api/tracepoints_controller.rb
- lib/bounding_box.rb
- test/controllers/api/map_controller_test.rb
- test/controllers/api/notes_controller_test.rb
- test/controllers/api/tracepoints_controller_test.rb
- test/lib/bounding_box_test.rb
The `bbox` parameter is not always required when it can be used (#4214, api changesets query). But the error message inside BoundingBox reads that it is: "The parameter bbox is required, and must be of the form min_lon,min_lat,max_lon,max_lat".
We can check if `bbox` is present before calling a bbox constructor, and write a different error message when necessary.
> Check required bbox parameter presence outside of BoundingBox class

- app/controllers/api/notes_controller.rb
- test/controllers/api/notes_controller_test.rb
This is an alternative to #3605.
#3605 adds the time `from`/`to` parameters to the index endpoint that already supports the `bbox`, this PR adds `bbox` to the search that already supports `from`/`to`.
You may want this PR if:
- The index endpoint is to be kept as simple as possible. The index endpoint is probably used more frequently because of the notes layer. Maybe you want to optimize it further, for example, by implementing it in cgimap. In this case the fewer parameters it has, the better.
- Changesets search already supports `bbox`.
For the use case described in #3605 you can switch over from the index endpoint to search if you want to download more notes.
> Add bbox parameter to notes search api

- app/views/changesets/_user.atom.builder
Added in https://github.com/openstreetmap/openstreetmap-website/commit/e477f68a6c1da16b2b976ff97750a65bbd0e3dd9
Some partials from the same directory removed in https://github.com/openstreetmap/openstreetmap-website/commit/43f52daeaabd5bf5f1c43e181a1f4135364fd0e1
`_user.html.erb` removed in https://github.com/openstreetmap/openstreetmap-website/commit/68a3df4d53c84508bf443058040379c3a18eb1a7 but `_user.atom.builder` was kept
> Remove unused partial _user.atom.builder

- .rubocop.yml
- test/factories/changeset_comments.rb
- test/factories/friendships.rb
- test/factories/issues.rb
- test/factories/messages.rb
- test/factories/oauth_access_grant.rb
- test/factories/oauth_access_token.rb
- test/factories/oauth_applications.rb
- test/factories/old_node.rb
- test/factories/old_relation.rb
- test/factories/old_relation_member.rb
- test/factories/old_way.rb
- test/factories/relation_member.rb
- test/factories/user_blocks.rb
- test/factories/user_role.rb
This matches our usage of implicit style for associations generally, e.g. `user`.
This isn't currently picked up by rubocop-factory_bot, due to a bug with the [default include paths](https://github.com/rubocop/rubocop-factory_bot/issues/53). Until the fix is released we can use the rubocop configuration to include our factories in the cop.
While working with upstream [on a fix](https://github.com/rubocop/rubocop-factory_bot/pull/55), I realised I didn't like the output of the autocorrect. So since this change will need some manual input eventually, I thought I'd just do it sooner rather than later. 
(The autocorrect goes from `association :author, :factory => :user` to `author :factory => [:user]` but in our case there's no need for the array).
> Use implicit style for associations with factory overrides

- app/views/changesets/index.html.erb
The display area here uses negative margins to make the flush list work, so we need to add them back in for normal text.
> Fix lack of margin on changeset browsing messages

- app/views/diary_entries/index.html.erb
- test/controllers/diary_entries_controller_test.rb
https://www.openstreetmap.org/traces has "Newer Traces" button before "Older Traces"
https://www.openstreetmap.org/diary has "Older Entries" before "Newer Entries" - which is backwards because newer entries come first
> Swap older/newer diary entries buttons

- app/views/api/traces/_trace.builder
- test/controllers/api/traces_controller_test.rb
If you look at https://wiki.openstreetmap.org/wiki/API_v0.6#Download_Metadata:_GET_/api/0.6/gpx/#id/details
you'll notice that `<gpx_file>` has the `user` attribute but doesn't have the `uid`. Everywhere else in the api (changesets, elements, notes) `user` comes together with `uid`. `uid` was missing here from [the very beginning](https://github.com/openstreetmap/openstreetmap-website/commit/01cfcbd845c5d8d33f83bb22a24cf35932da2e29#diff-49ff8e13eb2bff9ffd834dad7421f568b40186cb58b28e7eac6b3e9168ec8759R58), but it doesn't make sense to try to conceal it when the name is shown.
> Add user id to api trace output

- app/views/diary_entries/_form.html.erb
- app/views/profiles/edit.html.erb
Some languages have labels that wrap on certain screen widths, breaking input alignment.
Before:
After:
> Fix alignment in profile and diary location forms

- app/controllers/api/traces_controller.rb
Traces api controller happens to be the only api controller that calls authorize_web.
This call was there since the traces api was added in https://github.com/openstreetmap/openstreetmap-website/commit/01cfcbd845c5d8d33f83bb22a24cf35932da2e29 and was copied over when web and api controllers were separated in https://github.com/openstreetmap/openstreetmap-website/commit/5f59845575ed313688eca669fd73f4f6a5993c23.
But it doesn't do anything. There's no session so no if branches with conditions on session are run https://github.com/openstreetmap/openstreetmap-website/blob/0e21afc56593eb9fce14d8cfe0984494e758c150/app/controllers/application_controller.rb#L24
There's no current_user at this point so the final line also doesn't do anything …
> Remove authorize_web call from traces api controller

- app/views/api/changesets/_changeset.json.jbuilder
- app/views/api/changesets/_changeset.xml.builder
- test/controllers/api/changesets_controller_test.rb
When anything in the api returns comments, they don't have ids. This is probably because the comment ids were considered unimportant. There used to be no way to do anything with them. If you know a changeset id, you can ask the api to show this changeset, same for elements, users, notes, but not for comments.
But later changeset comment hide/unhide endpoints [were added](https://wiki.openstreetmap.org/wiki/API_v0.6#Hide_changeset_comment:_POST_/api/0.6/changeset/comment/#comment_id/hide). To use them you need to know comment ids. However there's no way to get the ids purely through the api. Currently the ids are attached to hide/unhide buttons in the web interface, with the web interface being the only way to get them.
Knowing the ids may help with scripted comment processing. For …
> Add comment ids to changeset discussion api responses

- app/abilities/api_ability.rb
- app/controllers/api/user_blocks_controller.rb
- app/views/api/user_blocks/_user_block.json.jbuilder
- app/views/api/user_blocks/_user_block.xml.builder
- app/views/api/user_blocks/show.json.jbuilder
- app/views/api/user_blocks/show.xml.builder
- config/routes.rb
- test/controllers/api/user_blocks_controller_test.rb
Going through the DWG Wishlist, there was a blocks api.
Currently scripted blocks in [osmtools](https://github.com/woodpeck/osm-revert-scripts) are done by emulating the browser, loading webpages and filling out forms. That requires passing the password around. It would be better to be able to access block functionality with a proper api and an oauth token.
But before doing block creation, there need to be block read api endpoints. Here the xml block show method is added at `/api/0.6/user_blocks/:id` with an output like:
```
<osm version="0.6" ...>
<user_block id="6" created_at="2023-08-01T15:55:58Z" updated_at="2023-08-05T00:46:36Z" ends_at="2023-08-05T00:46:36Z" needs_view="false">
<user uid="1" user="fakeuser1"/>
<creator uid="2" user="fakemod1"/>
<revoker uid="2" user="fakemod1"/> …
```
> Add show user block api endpoint

- app/assets/javascripts/index/directions.js
- app/assets/stylesheets/common.scss
- app/views/browse/changeset.html.erb
- app/views/notes/show.html.erb
- app/views/sessions/new.html.erb
- app/views/site/export.html.erb
This PR removes the remaining usage of the Sass division operator in our stylesheets.
https://sass-lang.com/documentation/breaking-changes/slash-div/
Whereever practicable, I've done this by refactoring the way that our styles work in order to remove the need for the custom css rules. In a few situations I took the "easy option" and converted the division to a multiplication instead, for the sake of time.
This work is a pre-requisite for moving to dartsass for compiling our stylesheets (the `sassc` gem, and the libsass project it uses, are both abandoned at this point, in favour of dartsass). And moving to dartsass (using `dartsass-sprockets`) is a prerequisite for us upgrading to newer versions of Bootstrap, which are incompatible with libsass.
> Remove usage of Sass division operator

- app/assets/stylesheets/print.scss
Prints sidebar contents before the map.
No special formatting except for hiding controls.
Should be better than nothing because you can always close the sidebar before printing if you don't like how it looks.
Shows directions as requested in #1273, but without direction arrows and wastes paper by having only one column.
> Show sidebar in print media

- app/views/traces/index.html.erb
Changes for buttons on traces pages `/user/<username>/traces`.
Originally I just wanted to delete the empty list item `<li class="nav-item flex-sm-grow-1"></li>`, but I ended up doing more adjustments to align the buttons.
---
Before:
After:
---
Before:
After:
> Change traces feed and upload button alignment

- app/views/layouts/_search.html.erb
There is an attempt to use an [input group](https://getbootstrap.com/docs/5.1/forms/input-group/) to combine the search input and the *Go* button. It doesn't work however. You can see the controls being rounded where they touch each other and this shouldn't happen:
The problem is trying to combine an input group with one input being put into a container that is required to position the *Where this is?* link. You have to remove the container but then positioning the link becomes more difficult. I could come up only with positioning using javascript, which is an unnecessary complication.
The simpler way is not to use an input group and specify which corners are to be rounded by hand:
> Stick search input and Go button together with flex instead of input group

- Dockerfile
- Gemfile
- Gemfile.lock
- app/assets/stylesheets/parameters.scss
[`sassc-rails`](https://github.com/sass/sassc-rails) and the underlying C-library [libsass](https://github.com/sass/libsass), are deprecated. `libsass` has problems when compiling newer versions of Bootstrap (5.2+), where it cannot re-parse its own output, and that causes problems during our asset precompilation. After extensive investigations I cannot find a workaround to keep using sassc-rails with newer versions of Bootstrap.
This PR switches our sass stylesheet compiler to [`dartsass-sprockets`](https://github.com/tablecheck/dartsass-sprockets), which is designed to be a drop-in replacement for `sassc-rails`, and which uses the currently maintained [dart implementation of sass](https://sass-lang.com/dart-sass/). 
Unfortunately the bootstrap gem had, [until …
> Switch to dartsass-sprockets for stylesheets

- app/assets/stylesheets/common.scss
- app/views/layouts/_search.html.erb
https://github.com/openstreetmap/openstreetmap-website/pull/3690#issuecomment-1737780556
- color override problems are avoided by limiting the override to the direct button group child of the primary navigation ("edit", "history", "export" buttons)
- "where is this?" is turned into a button which makes is as tall as everything else in the search input group and "top: 6px;" is no longer required
> Use input group in search bar, but avoid positioning "where is this" in pixels

- app/assets/stylesheets/common.scss
The fix was added in #4156.
No longer necessary after updating Bootstrap.
> Remove rtl direction fix for <code>

- app/views/layouts/_header.html.erb
A `picture` element was added to show svg logo in https://github.com/openstreetmap/openstreetmap-website/commit/ecc4b64a23d0d27d5a1a2eb472082123cdf985cd. Then a `srcset` attribute was added in case `picture` is not supported in https://github.com/openstreetmap/openstreetmap-website/commit/37a4fc6dd14dfedc0c44a8d7bf6453df0db9e1b5. But why do you need both nowadays? Basic `<img src...>` is supported by anything, so if some browser doesn't understand `srcset`, there's a fallback.
(I know that picture+srcset is used similarly in several other places. I'm not removing picture everywhere in case I'm wrong.)
> Remove <picture> from logo in header

- app/helpers/user_roles_helper.rb
- app/views/account/deletions/show.html.erb
- app/views/layouts/_flash.html.erb
- app/views/layouts/error.html.erb
- test/helpers/user_roles_helper_test.rb
Continues #4269, removing `<picture>` from everything else.
> Remove <picture>s around <img srcset=...>

- .github/workflows/docker.yml
- DOCKER.md
- config/docker.database.yml
This PR change the `docker-compose` commands to the newer `docker compose`.
My understanding is, that `docker-compose` is deprecated and `docker compose` is more or less a drop in replacement.
https://docs.docker.com/compose/migrate/
> From July 2023 Compose V1 stopped receiving updates. It’s also no longer available in new releases of Docker Desktop.
I did a fresh setup on MacOS with this updated docs and it all worked out except for some failing tests which I suspect are unrelated.
This PR also extends the "Tests" section on how to prepare the tests db to make the copy-paste steps complete.
---
Open todos
> Docker: Use `docker compose`

- .rubocop.yml
- app/controllers/api/traces_controller.rb
- app/controllers/application_controller.rb
- app/controllers/diary_entries_controller.rb
- app/controllers/traces_controller.rb
- test/controllers/api/traces_controller_test.rb
- test/controllers/diary_entries_controller_test.rb
- test/controllers/friendships_controller_test.rb
- test/controllers/traces_controller_test.rb
- test/models/node_test.rb
- test/models/trace_test.rb
These are very similar, differing only if we would expect multiple results and the sorting is important. However, in all our cases we're only expecting one result to be returned, and so find_by is easier to read.
> Prefer find_by() instead of where().first

- app/assets/stylesheets/common.scss
- app/views/layouts/_header.html.erb
Currently there's no indication of keyboard focus on *More* button in compact-nav mode.
This adds a secondary button focus outline:
> Enable focus outline on More button

- app/assets/stylesheets/common.scss
No longer in use. The list was removed in https://github.com/openstreetmap/openstreetmap-website/commit/9e75b8472ff066ba98d5f2af07fa12f7c11df55f.
> Remove oauth list custom css

- app/assets/stylesheets/common.scss
Bootstrap tables have 100% width by default.
> Remove user list custom css

- app/assets/javascripts/index.js
- app/assets/stylesheets/common.scss
As mentioned in https://github.com/openstreetmap/openstreetmap-website/issues/2527#issuecomment-582127582 (but borders are still broken, however dropdown widths seem ok without changing anything).
> Fix tooltip left/right placement and arrows in rtl

- app/views/site/copyright.html.erb
- config/locales/en.yml
The Czech Local Chapter is in negotiation with State Administration of
Land Surveying and Cadastre about possibility to use their newly
opened data in OSM. We have the agreement with request to put them as
a source of data on the copyright web page:
https://www.openstreetmap.org/copyright/en
Czechia: Contains data from the State Administration of Land Surveying
and Cadastre licensed under Creative Commons Attribution 4.0
International license (CC BY 4.0).
and mainly czech version of this page:
Česko: Obsahuje data z produkce Zeměměřického úřadu licencovaná pro
opětovné použití pod licencí Creative Commons Attribution 4.0 (CC BY 4.0).
I expect this pull request to handle the EN main page and the CZ language version will be later prepared via https://translatewiki.net/.
> Add contributor info for Czechia for copyright web page

- app/models/old_relation_member.rb
- app/models/relation_member.rb
- db/migrate/20231010194809_correct_relation_members_primary_key.rb
- db/structure.sql
- test/controllers/api/relations_controller_test.rb
- test/factories/old_relation_member.rb
- test/factories/relation_member.rb
The two relation members tables have, for some reason that I don't really understand, a primary key that includes all the fields rather than just those needed to identify the member uniquely.
We then have to lie to rails about the primary key makeup in order for things to work properly.
I can't see any purpose to this - there don't seem to be any relationships or queries that would be helped by the extra fields, and having noise between `version` and `sequence_id` means postgres won't be able to assume ordering during an index read of members for a relation and will have to do a sort.
> Simplify primary key for relation members tables

- app/assets/stylesheets/common.scss
- app/views/layouts/_banner.html.erb
- app/views/layouts/map.html.erb
`.btn-close-white` added in https://github.com/openstreetmap/openstreetmap-website/commit/e6a8b400989802b0cc47ffac30103e4b10740fb4 is deprecated: https://getbootstrap.com/docs/5.3/components/close-button/#dark-variant
> Use dark theme to invert banner close button

- app/assets/javascripts/application.js
- app/assets/stylesheets/common.scss
Supposedly they were used in Potlatch:
https://github.com/openstreetmap/openstreetmap-website/blame/d62e8c43f3f404542dbdc310e31e4ed38cc2428b/app/views/site/edit.html.erb#L19
> Remove unused maximiseMap/minimiseMap functions

- app/assets/stylesheets/common.scss
- app/views/layouts/map.html.erb
Currently the message for disabled javascript has a large left margin. But what if the window is small? Also `z-index` doesn't do anything because it has static positioning.
Before:
After:
> Remove custom css and large left margin for map noscript message

- app/assets/javascripts/index/browse.js
- app/assets/stylesheets/common.scss
- app/views/layouts/map.html.erb
If you're negating it with a Bootstrap class (`mx-n3` on children, see https://github.com/openstreetmap/openstreetmap-website/commit/c8f0a81eb7043c297e050c1f3ff8a8cf7ff613bc), why not set it with a Bootstrap class?
> Replace padding: $spacer css with class="p-3"

- app/assets/stylesheets/common.scss
- app/helpers/browse_tags_helper.rb
- app/views/browse/_tag.html.erb
- app/views/browse/_tag_details.html.erb
- test/helpers/browse_tags_helper_test.rb
I think @gravitystorm used tags table as an example of what's to be converted to Bootstrap, like in https://github.com/openstreetmap/openstreetmap-website/pull/3535#issuecomment-1125113979. I don't think think it's a good example because Bootstrap doesn't have:
- `table-layout: fixed`
- `white-space: pre-wrap`
- `border-collapse: separate`, which is required for rounded corners directly on the table
- without `border-collapse: separate` you need a wrapper with a border and rounded corners, then you can't use Bootstrap's bordered table class because it will have an outer border which you don't need.
- actually you could use `box-shadow` instead of a wrapper to draw a border, but Bootstrap doesn't have that too
> Remove some tag table custom css

- app/assets/stylesheets/common.scss
These interfere with directions set in `dir` attributes, e.g. `dir='auto'`.
The corresponding text-align was removed in Bootstrap 5.
Fixes #3432.
> Remove global text-align declarations

- app/assets/javascripts/application.js
- app/assets/javascripts/index/query.js
- app/helpers/application_helper.rb
Pass the full expanded list of preferred languages to the client and use that when looking for the best name for an object.
Fixes #4310
> Improve name selection with the query tool

- app/views/browse/_tag.html.erb
The change fixes an issue where right-to-left language strings can be rendered incorrectly in the Tags table of Map Data or History views
I noticed this street label in Erbil with mismatched parentheses. This turned out to be an error in the name string:
When reviewing the name in the Map Data (or now, [History view](https://www.openstreetmap.org/way/195240072/history)), it looks like the name is wrapped in parentheses. With a wider box or shorter string, the parentheses appear to wrap one word (مشکۆ) . What we're really seeing is the 0th character of the name string , ( , displayed on the left end of this line. 
In an updated version with `dir="auto"`, the string renders like it did in the tiles. This makes the misplaced and unpaired parenthesis visible in the web view.
CSS has a …
> Format right-to-left and bi-di text in OSM tag values

- app/assets/stylesheets/common.scss
- app/helpers/application_helper.rb
- app/helpers/changesets_helper.rb
- app/helpers/note_helper.rb
- app/views/browse/_common_details.html.erb
- app/views/browse/changeset.html.erb
- app/views/dashboards/_contact.html.erb
- app/views/diary_entries/comments.html.erb
- app/views/issues/index.html.erb
- app/views/notes/show.html.erb
- app/views/traces/_trace.html.erb
- app/views/user_blocks/revoke.html.erb
- config/locales/en.yml
- test/helpers/application_helper_test.rb
- test/helpers/changesets_helper_test.rb
- test/helpers/note_helper_test.rb
- test/helpers/user_blocks_helper_test.rb
Refs #631 (site-wide consistency) and #4313 (use of `time` element instead of `abbr` or `span`).
This PR refactors our friendly date displays to be consistent throughout the site. I've standardised on using the `time` element (with the machine-readable datetime attribute, for anything that might need it), and removed all the (mis-)use of `abbr` elements. The highlighting of time periods which have titles (using dotted underlines), previously a side effect of `abbr`, is reimplemented in CSS.
I've kept the changesets_helper#changeset_details as the only place that doesn't use the friendly_date helpers, since it does some funky stuff with the titles. But I would consider refactoring that in future too, since I'm not convinced those titles are a good idea.
> Use friendly_date helpers throughout the site

- CONFIGURE.md
I don't think it's used anywhere, especially given https://github.com/openstreetmap/openstreetmap-website/issues/3613, but it can't be left blank.
> Update oauth configuration url input label

- app/views/api/changesets/changeset.xml.builder
- app/views/api/changesets/changesets.xml.builder
This is the place where this comment makes sense: https://github.com/openstreetmap/openstreetmap-website/blob/26f12ef11a43a83ad08a59742f15027417b2c968/app/views/api/changesets/_changeset.xml.builder#L1
But it was probably copied by accident to `changeset.xml.builder` and `changesets.xml.builder` in https://github.com/openstreetmap/openstreetmap-website/commit/538bfed8a61a576e44d8cc71d7727c0310bcf238. Json versions don't have these comments.
> Remove 'basic attributes' comments from changeset api output builders

- app/controllers/api/changesets_controller.rb
- app/controllers/changesets_controller.rb
This comment was added in https://github.com/openstreetmap/openstreetmap-website/commit/95d899786a1bbabacc0cd12ef1c4814118d9d0de when the `conditions_bbox` method actually returned bbox. Bbox returning was removed in https://github.com/openstreetmap/openstreetmap-website/commit/9c28a626cbefd289d17556747979bd73ee3a77cd yet the comment stayed and got copypasted later to the api controller.
> Remove 'need to return bbox' comment on conditions_bbox

- .rubocop_todo.yml
- app/controllers/accounts_controller.rb
- app/models/changeset.rb
- app/models/user.rb
- app/views/account/deletions/show.html.erb
- config/initializers/config.rb
- config/locales/en.yml
- config/settings.yml
- db/migrate/20231117170422_add_closed_at_index_to_changesets.rb
- db/structure.sql
- test/controllers/accounts_controller_test.rb
- test/models/user_test.rb
- test/system/account_deletion_test.rb
- test/test_helper.rb
As I posted in the dwg chat:
- the delay is 1 day to make sure that there are no open changesets when users are deleted
- there's a setting, delays are disabled when set to 0
- I assumed that no possible law/regulation can exist that would require us to act faster than within a day
- no checks if the user is blocked, only the last changeset opening time
- I'd check the closing time, but there's no index together with uid
> Account deletion cool-down period

- app/assets/javascripts/application.js
- app/assets/stylesheets/common.scss
- app/views/layouts/_header.html.erb
This is a step towards [Bootstrap navbar](https://getbootstrap.com/docs/5.2/components/navbar/), which also uses flex.
You don't want floats there because https://github.com/openstreetmap/openstreetmap-website/issues/3433#issuecomment-1632814133 too and they don't make sense anyway when flex is widely available in browsers.
Fixes #2536 if it was caused by line breaks when measuring widths.
> Use flex container instead of floats in header

- app/assets/stylesheets/common.scss
That list inside the primary navigation doesn't exist anymore. The only list there is the edit button dropdown, but it's hidden in small-nav mode.
> Remove unused css for lists inside primary nav on narrow screens

- app/assets/javascripts/leaflet.key.js
- app/assets/javascripts/osm.js.erb
There's a bunch of map layer configuration specified directly in javascript files, and I added more in https://github.com/openstreetmap/openstreetmap-website/pull/4367, the check for a layer name that can't be embedded. But it would be more convenient to have this configuration outside.
Here the map key button checks if the layer is one of `["mapnik", "cyclemap"]` to enable/disable itself, with these layer names directly in js. But we can look into `key.yml`, see which layers have keys and enable the key button based on that.
> Read layers with available map key from config/key.yml

- app/controllers/users_controller.rb
- app/views/site/welcome.html.erb
- config/locales/en.yml
When user wants to authorize 3rd party app with OSM, and wants to create an OSM account during OAuth authorization, the welcome screen displays "Continue with authorization" instead of "Start mapping".
> Welcome screen shows "Continue with authorization" when OSM account created from authorization flow

- app/assets/javascripts/index/directions/fossgis_valhalla.js
This will search for road segments within 5 meter radius of the input location and choose the best path from/to whichever segment gives the cheapest cost. It should be preferable in most scenarios compared to simply snapping to the closest segment.
I'll do the same PR for our web app at https://github.com/gis-ops/valhalla-app.
> Use 5 meter radius for input locations in Valhalla

- db/structure.sql
- script/normalise-structure
This PR makes a minor change to the structure.sql file to align it with the output from running migrations, along with some changes to the normalisation script. These normalisations can be removed since they aren't actually doing anything in CI.
* Adds the btree_gist comment. All developers will have this in their generated output from running the migrations so we should have it here too, to avoid noise in `git diff` (and therefore to make it easier to submit PRs with migrations).
* Remove the timestamp normalisation - see https://github.com/openstreetmap/openstreetmap-website/issues/4298#issuecomment-1832194246 on how to update really old pre-rails-6 databases, if you have one.
* Remove sequence type normalisation - this is actually important, and [differences shouldn't be …
> Align structure with generated output

- db/migrate/20231206141457_alter_sequences_bigint.rb
- db/structure.sql
These primary keys were converted to bigints in migrations, but the sequences were left unmentioned. If the original migrations are run on postgresql 10.0+, then this leads to a mismatch in column types vs sequence types. This migration fixes these mismatches.
If the original migrations were run on postgresql < 10, all sequences were bigints anyway, and this migration is a no-op.
If the sequence is a bigint, then postgresql doesn't output that fact in the statement dump.
Refs #4298
> Migrate some sequences to use bigints

- app/assets/images/key/opnvkarte/bus_stop13.svg
- app/assets/images/key/opnvkarte/bus_stop15.svg
- app/assets/images/key/opnvkarte/rail11.svg
- app/assets/images/key/opnvkarte/rail15.svg
- app/assets/images/key/opnvkarte/rail17.svg
- app/assets/images/key/opnvkarte/stop13.svg
- app/assets/images/key/opnvkarte/stop15.svg
- app/assets/javascripts/leaflet.key.js
- app/views/site/key.html.erb
- config/key.yml
- config/locales/en.yml
I decided to check how adding a map key would work by adding one for opnvkarte.
At first I wanted to copy the images from the key at https://publictransportmap.org/. They were base64 data uris, <s>so I added the ability to specify image sources directly in `key.yml`</s>, otherwise they are composed as `key/<layer name>/<image name>`. But I ended up making my own images <s>because the already existing i18n strings want to combine light rail and tram</s>.
I only did the transportation section. Now it's possible to see if a line is a bus or a tram. Other things on that map are more obvious.
> Add transportation map key for opnvkarte

- app/assets/images/key/cyclemap/pedestrian.svg
- config/key.yml
- config/locales/en.yml
As requested [here](https://github.com/openstreetmap/openstreetmap-website/issues/982#issuecomment-1822663434). Map key is actually available but the "grey street" was missing. 
It makes sense to close #982.
- there are more layers in the map key now
- there are at least some area colors in the cyclemap key
- there are “the blue lines alone the road”
- requests for individual features exist: #2956
> Add pedestrian way to cyclemap map key

- config/key.yml
You can zoom up to 21 on cyclemap, yet the map key has `max_zoom: 19` statements and disappears on z20 and z21.
> Remove max zoom from cyclemap map key

- app/controllers/users_controller.rb
- app/models/acl.rb
- test/models/acl_test.rb
Allows mechanism to configure exceptions to rate limiting for account creation.
Uses ACL table with `allow_account_creation` key to allow bypassing account creation rate limiter from specific IP address/network range for users with specified email `domain` and email `mx` address.
> Implement allow list for account creation

- config/key.yml
After removing `max_zoom` from cyclemap in #4411, it makes sense to remove it from everywhere else.
`max_zoom` is necessary only for "Built-up area" in mapnik, before it splits into more specific area types.
> Remove unnecessary max_zoom from map key

- app/assets/stylesheets/common.scss
- app/helpers/svg_helper.rb
- app/views/site/key.html.erb
Instead of [optimizing svg data uris](https://github.com/openstreetmap/openstreetmap-website/pull/4419) we can use inline svgs here.
Now this:
becomes this:
<svg width="52" height="1" class="d-block mx-auto"><rect width="100%" height="100%" fill="#787878" /></svg>
> Use inline svgs in map key

- .rubocop_todo.yml
- app/abilities/ability.rb
- app/controllers/messages_controller.rb
- app/controllers/user_mutes_controller.rb
- app/models/message.rb
- app/models/user.rb
- app/models/user_mute.rb
- app/views/application/_settings_menu.html.erb
- app/views/messages/_heading.html.erb
- app/views/messages/_message_summary.html.erb
- app/views/messages/_messages_table.html.erb
- app/views/messages/inbox.html.erb
- app/views/messages/muted.html.erb
- app/views/messages/outbox.html.erb
- app/views/messages/show.html.erb
- app/views/user_mutes/index.html.erb
- app/views/users/show.html.erb
- config/application.rb
- config/locales/en.yml
- config/routes.rb
- db/migrate/20231010201451_create_user_mutes.rb
- db/migrate/20231010203028_add_muted_flag_to_messages.rb
- db/structure.sql
- script/deliver-message
- test/controllers/user_mutes_controller_test.rb
- test/factories/messages.rb
- test/factories/user_mute.rb
- test/models/message_test.rb
- test/models/user_mute_test.rb
- test/system/user_muting_test.rb
Implements the UserMute-Feature as described in https://github.com/osmfoundation/ewg_bidding/tree/main/projects/ability-to-mute-other-users/proposals/gregory_igelmund-08-09-2023
Addresses #3129
- Refactors `app/views/messages/*.html.erb` templates (extracting shared code)
- Adds `UserMute`-Model w/ CRUD operations to mute/unmute users
- Extends `Message`-Model with a `muted`-flag
- Adjusts `UserMailer.message_notification`-calls to respect the `Message#muted?`-flag
> Add UserMute to control message visibility

- config/settings/test.yml
- test/integration/user_creation_test.rb
This PR makes our test suite run several minutes quicker (single-thread timings). User creation tests drop on my machine from 200 seconds to 6 seconds.
Previously, several of the user creation tests were repeated 228 times, once in each available locale. This takes a lot of time and provides very little value.
After those were refactored, the next slowest tests were the changeset comment rate limit tests. A simple way to make them run 3-4 times faster is just to reduce the rate limits in the test settings, since this reduces the number of (uninteresting) post requests made.
Rails 7.1 ships with the `--profile` flag, which makes it easy to find the slowest tests, and these stood out when doing so.
> Faster tests

- INSTALL.md
We started requiring postgresql 12 after the migrations in #4319
> Update minimum postgresql version

- .rubocop_todo.yml
- app/abilities/api_capability.rb
- app/helpers/authorization_helper.rb
- app/views/oauth2_applications/_application.html.erb
- app/views/oauth2_authorizations/new.html.erb
- app/views/oauth2_authorized_applications/_application.html.erb
- config/locales/en.yml
- lib/oauth.rb
- test/controllers/api/old_nodes_controller_test.rb
- test/controllers/api/old_relations_controller_test.rb
- test/controllers/api/old_ways_controller_test.rb
Currently redactions are allowed if the `write_api` is granted. But `write_api` is a very common scope requested by many apps for things like adding changeset comments. Those apps have no business being able to redact anything.
Here a separate scope for redactions is introduced. `write_api` still allows redactions, this is to be disabled in a later pull request, after [osmtools](https://github.com/woodpeck/osm-revert-scripts) are updated to request the new `write_redactions` scope. There's also redaction bot written in ruby, possibly also needs to be updated.
> Add oauth scope for redactions

- app/controllers/site_controller.rb
- app/views/site/key.html.erb
- config/key.yml
- config/locales/en.yml
Fix #3816 by not constructing sentences and not having combined i18n strings.
I don't think sentences are expected in map key, so instead of this:
we can connect terms by dots, like we do with *secondary actions* ("Download XML ·View History" on element pages etc):
Don't group locale strings in site.key.table.entry. Instead of this:
cable:
- Cable car
- chair lift
have this:
cable_car: "Cable car"
chair_lift: "Chair lift"
Group them in `key.yml`, depending on layer. Instead of this:
- { min_zoom: 12, name: cable, image: cable.png }
have this:
- { min_zoom: 12, name: [cable_car, chair_lift], image: cable.png }
---
The advantage is that if features are grouped differently on various layers, their names can be translated independently. For example, mapnik has different colors for parks and …
> Allow arrays of names in map key entries

- config/locales/en.yml
- test/system/oauth2_test.rb
for this message when no no authorized apps:
> You have not yet authorized any [OAuth 2](https://oauth.net/2/) applications.
> Add missing locale string for /oauth2/authorized_applications

- app/controllers/user_blocks_controller.rb
- test/controllers/user_blocks_controller_test.rb
If you block a user for two weeks, you'll see this:
> Duration: 1 week
The block end date is computed before `created_at` and its duration ends up being slightly shorter. Everything is rounded down and you get an incorrect value.
> Set block ends_at to exactly created_at + duration

- test/system/messages_test.rb
The class names are expected to match the test file names.
Follow-Up for #4437
(btw. thanks @AntonKhorev for the fix!)
> test/system/messages_test.rb: Rename NoteCommentsTest -> MessagesTest

- app/views/notes/show.html.erb
- config/locales/en.yml
- test/system/note_comments_test.rb
Add "Log in to comment on this note" link as requested in the [original post](https://github.com/openstreetmap/openstreetmap-website/issues/2761#issue-675527428) in https://github.com/openstreetmap/openstreetmap-website/issues/2761.
There also was [another request](https://github.com/openstreetmap/openstreetmap-website/issues/2761#issuecomment-1225816994) which I **didn't do**: adding "Log in to resolve/reactivate". Some users close and reopen notes several times for no apparent reason and previously we added texts to discourage that. I don't want to write anything that will encourage these actions.
> Add login notice for note discussions

- app/models/language.rb
- test/models/language_test.rb
Languages have names in the format of "English name (native name)". These names are used in diary entry language links and inputs.
Sometimes *native name* is exactly the same as *English name*, so the same thing is displayed twice:
I think we don't need "(native name)" in this case:
> Don't show native language name if it's the same as English name

- test/lib/bounding_box_test.rb
- test/models/acl_test.rb
- test/models/changeset_comment_test.rb
- test/models/changeset_tag_test.rb
- test/models/client_application_test.rb
- test/models/issue_test.rb
- test/models/message_test.rb
- test/models/node_tag_test.rb
- test/models/note_comment_test.rb
- test/models/oauth_token_test.rb
- test/models/old_node_tag_test.rb
- test/models/old_relation_tag_test.rb
- test/models/old_way_tag_test.rb
- test/models/redaction_test.rb
- test/models/relation_member_test.rb
- test/models/relation_tag_test.rb
- test/models/report_test.rb
- test/models/request_token_test.rb
- test/models/trace_test.rb
- test/models/tracepoint_test.rb
- test/models/user_preference_test.rb
- test/models/user_test.rb
- test/models/way_tag_test.rb
- test/system/report_diary_entry_test.rb
- test/validators/characters_validator_test.rb
- test/validators/whitespace_validator_test.rb
You have a test that looks like this:
https://github.com/openstreetmap/openstreetmap-website/blob/04c697b468057d1a3604694e7ead9d2c6efd1dfa/test/models/note_test.rb#L40-L42
Then Rubocop starts complaining that you don't use `assert_predicate` and you change the test:
https://github.com/openstreetmap/openstreetmap-website/blob/6892ccd0155b431cc567b4744b1e2759df3e8c68/test/models/note_test.rb#L40-L42
Yet you keep negative assertions as `assert_not` and don't change then to `assert_not_predicate`. Are there any good reasons for that other than Rubocop no complaining?
```ruby
assert_not_predicate create(:note, :status => "hidden"), :visible?
```
> Use assert_not_predicate in tests that have assert_predicate

- app/controllers/diary_entries_controller.rb
- app/views/diary_entries/index.html.erb
- test/system/diary_entry_test.rb
Adds a link requested in #2657 to https://www.openstreetmap.org/diary
Actually adds links for all preferred languages, using candidates logic https://github.com/openstreetmap/openstreetmap-website/blob/c95e2870f3310a68f8287bddcec6d0117b5f8961/lib/locale.rb#L44-L53
---
#2657 also requested:
> users could tick a box to in their settings, which would make the diary page default to their preferred language url
I don't think this is necessary. You can always bookmark diary pages in any specific language or subscribe to that language feed.
> Add links to diaries in preferred languages

- test/controllers/api/notes_controller_test.rb
- test/controllers/notes_controller_test.rb
- test/factories/notes.rb
- test/models/note_test.rb
- test/system/note_comments_test.rb
Currently you create a closed note in tests like this:
```ruby
create(:note, :status => "closed", :closed_at => Time.now.utc)
```
You have to remember to set `:closed_at`. There's code that assumes that closed notes have this time set. If omitted, it's going to be unset.
Here I add the `:closed` trait to the note factory that will set `:closed_at` and also add a closing comment.
> Add :closed trait to note factory

- test/application_system_test_case.rb
- test/system/note_comments_test.rb
- test/system/oauth2_test.rb
Let's suppose you want to have a system test that checks if adding comments to notes work. This commenting is done via the api. For the api to work you have to [register the website oauth app](https://github.com/openstreetmap/openstreetmap-website/blob/master/CONFIGURE.md#oauth-consumer-keys). Here I'm adding a test superclass that does this registration in `before_setup`.
> Add system test with osm website oauth app registration

- app/abilities/ability.rb
- app/controllers/user_blocks_controller.rb
- app/views/user_blocks/revoke_all.html.erb
- app/views/users/show.html.erb
- config/locales/en.yml
- config/routes.rb
- test/controllers/user_blocks_controller_test.rb
- test/system/user_blocks_test.rb
User pages have "Revoke all blocks" link when users have active blocks. These links are only visible to moderators.
See here for reasons: https://github.com/openstreetmap/openstreetmap-website/pull/4301#discussion_r1367510802
> Add revoke all blocks moderator action

- app/views/issues/_comments.html.erb
- app/views/issues/_reports.html.erb
- app/views/issues/show.html.erb
- config/locales/en.yml
It was done with dates everywhere else.
Also link to a profile page of the user who updated the issue. Previously it was just a display name without a link.
> Show dates as <time> elements on issues pages

- app/models/user.rb
- app/validators/normalized_uniqueness_validator.rb
- db/migrate/20231213182102_add_canonical_user_index.rb
- db/structure.sql
- test/models/user_test.rb
As with the previous checks on case sensitivity this only affects new users, and changes to names of existing users.
Once this is merged and deployed we can drop the old lowercase index in a separate change.
> Require user names to be unique after unicode normalisation

- app/abilities/api_ability.rb
Similar to https://github.com/openstreetmap/openstreetmap-website/pull/4478 but now removing things from `api_ability.rb`. Some were copied from `ability.rb`, `:change` was removed in https://github.com/openstreetmap/openstreetmap-website/pull/2486.
> Remove unnecessary api abilities

- INSTALL.md
Refs #4405
* instructions are already written for 22.04 so otherwise don't need updating
* vagrant is 22.04
* [docker uses postgres 14 image already](https://github.com/openstreetmap/openstreetmap-website/blob/master/docker/postgres/Dockerfile)
* [github actions 20.04 image uses postgres 14](https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2004-Readme.md#postgresql)
... so I think that this is the only thing that needs changing.
> Update minimum PostgreSQL version to 13 in documentatation

- .rubocop_todo.yml
- app/models/user.rb
- config/locales/en.yml
- test/models/user_test.rb
In case you don't want #4215, there's already a defacto url scheme with user ids: `/user/user_id`. That's what deleted accounts get reset to. But it has a couple of problems. "user_12345" is a valid username for anyone, not just the user with id=12345. Depending on how many usernames with this pattern already exist, we may want to stop allowing new ones.
I know one active user with this kind of name, but it matches their id.
> Disallow username changes to user_n if n isn't their id

- app/models/user.rb
- db/migrate/20240117185445_drop_lowercase_user_index.rb
- db/structure.sql
It's no longer needed as we now use the new canonical index...
> Drop lowercase index on display names

- config/locales/en.yml
- (mostly) introduced in https://github.com/openstreetmap/openstreetmap-website/commit/1db6b392a6c9f255d74669d8ae6db67934a2ab54
- unused since https://github.com/openstreetmap/openstreetmap-website/commit/438e8be102a2ac4c0e92041da2866f1339715b40
> Remove unused export tab translations

- config/locales/en.yml
On the login page redesign PR there's a discussion about colons in input labels starting at https://github.com/openstreetmap/openstreetmap-website/pull/4455#issuecomment-1899984034. The colons are in translation strings, thus they can be dealt with outside of that PR.
Those colons are not needed because they are mostly not used in other places. One place that has a colon is an input on the "forgot password" page, let's remove it from there too.
Another place is the share panel. I'm not so sure about colons there and I'm not removing them in this PR.
> Remove ":" from login form input labels

- test/test_helper.rb
Currently logins in system tests work by going to the login page, filling in the username and password and clicking the first "Login" thing. You hope that this first "Login" thing is the login button of the login form, which it currently is. But if you change the website navigation, it may no longer be. #4455 makes such change, adding a "Login" tab above the form. Then it adds workarounds [1](https://github.com/openstreetmap/openstreetmap-website/pull/4455/files#diff-29beaabe278fd17493296745cecb67919f0906b47b8246ab770f5517615d9ef7R203-R205) [2](https://github.com/openstreetmap/openstreetmap-website/pull/4455/files#diff-ba37813ca277c227a74a372479b7b05b7f3ff085d890ab708f80d62573efdb7aR248).
How about we click the button below the inputs instead?
> Click login below inputs in system test sign in

- app/helpers/svg_helper.rb
- app/views/shared/_pagination.html.erb
For [traces](https://www.openstreetmap.org/traces), [diaries](https://www.openstreetmap.org/diary) and comments pages.
Arrows are not displayed on extra small screen sizes because they can make things worse.
> Add previous/next page arrows to newer/older pagination

- app/views/sessions/new.html.erb
If you press tab while in the OpenID input, you'll get to the login button _above it_, not below. Same thing happens in #4455. `:tabindex => 3` was there since at least 2010 while things around it changed.
> Set OpenID tabindex higher than username/password form tabindexes

- app/abilities/ability.rb
- app/assets/javascripts/index.js
- app/controllers/old_nodes_controller.rb
- app/controllers/old_relations_controller.rb
- app/controllers/old_ways_controller.rb
- app/views/browse/_common_details.html.erb
- app/views/browse/_node.html.erb
- app/views/browse/_relation.html.erb
- app/views/browse/_relation_member.html.erb
- app/views/browse/_tag_details.html.erb
- app/views/browse/_way.html.erb
- app/views/browse/feature.html.erb
- app/views/old_nodes/not_found.html.erb
- app/views/old_nodes/show.html.erb
- app/views/old_relations/not_found.html.erb
- app/views/old_relations/show.html.erb
- app/views/old_ways/not_found.html.erb
- app/views/old_ways/show.html.erb
- config/locales/en.yml
- config/routes.rb
- test/controllers/browse_controller_test.rb
- test/controllers/old_nodes_controller_test.rb
- test/controllers/old_relations_controller_test.rb
- test/controllers/old_ways_controller_test.rb
Basic support for https://github.com/openstreetmap/openstreetmap-website/issues/662. Doesn't try to show the old versions on the map.
The paths scheme is `/node/123/history/4` like it was in https://github.com/openstreetmap/openstreetmap-website/pull/720. This is because you'll probably want resourceful routes, with index pointed later to `/node/123/history`.
Not necessarily a replacement of https://github.com/openstreetmap/openstreetmap-website/pull/4468. You may still want links to specific versions within full history pages, especially if they'll get more version comparison functionality, for example like it was attempted in https://github.com/openstreetmap/openstreetmap-website/pull/3535.
> Element version pages

- app/helpers/browse_tags_helper.rb
- test/helpers/browse_tags_helper_test.rb
This pull request adds the buried wikipedia/wikidata/wikicommon tag to the allowed secondary wiki prefixes
> Add buried to list of secondary Wiki prefixes

- app/views/site/help.html.erb
- config/locales/en.yml
Move the community.openstreetmap.org tab up to replace it and rename it to mentaion help as well as community.
Fixes #4497
> Drop help.openstreetmap.org from the help page

- app/views/site/help.html.erb
Drop the redundant links in the footer and turn the title into a header and extend it to cover the whole card.
> Improve styling of help page

- Gemfile
- Gemfile.lock
- test/test_helper.rb
This PR adds the [minitest-focus](https://github.com/minitest/minitest-focus) gem, which I've been using a lot recently. It's particularly helpful if you are examining the test logs, or doing some other work which means the other tests in the file are just a distraction.
There's a small risk with focussing a test, that it might be committed as focussed. If nobody notices during review, that can cause the rest of the test suite to be skipped. To mitigate this (admittedly remote) risk, I've set it up to not be enabled on CI, so any use of the 'focus' keyword there will cause the entire suite to fail.
(My preferred mitigation would be a rubocop rule like https://docs.rubocop.org/rubocop-rspec/cops_rspec.html#rspecfocus which would have a similar effect, but that doesn't yet exist for …
> Add minitest-focus gem

- test/application_system_test_case.rb
- test/test_helper.rb
Test helper has two methods for login: `sign_in_as` and `session_for`. Which one do you use? The answer is `sign_in_as` in system test and `session_for` everywhere else. Why not then move `sign_in_as` to the system test base class? This class already has other methods and you won't be able to accidentally call `sign_in_as` from non-system tests.
> Move system test specific sign in to system test superclass

- app/helpers/svg_helper.rb
- app/views/browse/changeset.html.erb
- app/views/browse/feature.html.erb
- app/views/old_nodes/show.html.erb
- app/views/old_relations/show.html.erb
- app/views/old_ways/show.html.erb
Links to first/last versions on the current version page:
Now they look differently to previous/next version links, to avoid confusion #4506.
Links to previous/next versions on the old version page:
And also on user's changeset pages, that's where the initial "<<" / ">>" link style came from:
> SVG icons in element version and changeset links

- app/views/browse/changeset.html.erb
Links in the sidebar on /changeset/_id_ pages before:
After:
The idea is that "Changeset XML" and "osmChange XML" are related to the current changeset and should be closer to the changeset details than links for navigation between changesets.
A similar order is already in use on element version pages:
> Move previous/next user's changeset links to bottom

- app/assets/stylesheets/common.scss
- app/views/diary_entries/_diary_comment.html.erb
- app/views/diary_entries/show.html.erb
- config/locales/en.yml
Places (un)subscribe button on diary entry pages like it's on changeset pages. That requires adding a heading above the comments to make it clear to what you're subscribing.
Previously the button was right below the new comment box which is somewhat confusing, see #4491. You don't want to accidentally press it after typing in a comment.
> Add diary discussion heading and move subscribe button next to it

- config/locales/en.yml
Added in https://github.com/openstreetmap/openstreetmap-website/commit/14ac1babc2517320a2c90fa9b4ac36a5a6e68018 but never used. Probably was intended to be a heading for changeset comments but "Discussion" was used instead.
> Remove unused browse.changeset.comment locale string

- app/views/changesets/index.atom.builder
- test/controllers/changesets_controller_test.rb
Look at https://github.com/openstreetmap/openstreetmap-website/commit/fc9768f34c803f9a9746d1705af097655d55f3e2. It added `type="html"` to changeset feed entries for the reasons stated in the commit message. But is it actually correct? Let's check.
I created a couple of changesets. This is how their comments are shown on the `/history` page. I expect to see the same in a feed reader.
This is how their titles look in `/history/feed` output. They are always escaped once.
<title type="html">Changeset 58 - is it going to &lt;em&gt;emphasize&lt;/em&gt;?</title>
...
<title type="html">Changeset 57 - this is unescaped (&lt;); this is escaped (&amp;lt;)</title>
This is how they look in [Liferea](https://en.wikipedia.org/wiki/Liferea). Not what's expected.
This is how they look after `type="html"` …
> Remove html type from changeset feed entry titles

- app/assets/stylesheets/browse.scss
- app/helpers/browse_helper.rb
- app/views/browse/_containing_relation.html.erb
- app/views/browse/_node.html.erb
- app/views/browse/_relation_member.html.erb
- app/views/browse/_way.html.erb
- app/views/browse/changeset.html.erb
- app/views/browse/feature.html.erb
- app/views/browse/history.html.erb
- app/views/old_nodes/show.html.erb
- app/views/old_relations/show.html.erb
- app/views/old_ways/show.html.erb
- config/locales/en.yml
- test/controllers/browse_controller_test.rb
- test/helpers/browse_helper_test.rb
Changeset pages have links to changed elements. Previously elements only had current version and full history pages, so links were to current versions. Now there are pages for each element version too, and links on changeset pages have version number displayed. It makes sense to link that v-number part to that exact version.
> Link to current and old element versions from changeset pages

- app/views/changesets/index.atom.builder
- config/locales/en.yml
Changeset feeds are not handled by browse controller, and I want to remove more stuff from browse controller later, possibly everything.
> Move changeset feed locale strings from browse section to changesets

- app/controllers/diary_entries_controller.rb
- app/mailers/user_mailer.rb
- app/views/diary_entries/_diary_entry.html.erb
- app/views/diary_entries/_diary_entry_heading.html.erb
- app/views/diary_entries/subscribe.html.erb
- app/views/diary_entries/unsubscribe.html.erb
- app/views/user_mailer/diary_comment_notification.html.erb
- app/views/user_mailer/diary_comment_notification.text.erb
- config/locales/en.yml
- config/routes.rb
- test/controllers/diary_entries_controller_test.rb
- test/mailers/user_mailer_test.rb
as I propose in #4505:
- add diary subscribe/unsubscribe pages for GET requests that contain a button to make a POST request
- these pages redirect to login if required
- add an unsubscribe page link to comment notification emails
> Add unsubscribe link to diary comment notification email

- app/controllers/api/traces_controller.rb
- app/controllers/traces_controller.rb
- app/models/trace.rb
This sets the priority of the trace import job based on the number of pending traces the user has so the more they up load at once the lower the priority, thus allowing other users who only upload a few to jump in front of them.
> Use a reduced priority for batch trace uploads

- .rubocop_todo.yml
- app/controllers/concerns/session_methods.rb
- app/controllers/concerns/user_methods.rb
- app/controllers/confirmations_controller.rb
- app/controllers/passwords_controller.rb
- app/controllers/sessions_controller.rb
- app/controllers/users_controller.rb
- app/mailers/user_mailer.rb
- app/models/user.rb
- app/models/user_token.rb
- test/controllers/confirmations_controller_test.rb
- test/controllers/passwords_controller_test.rb
- test/controllers/sessions_controller_test.rb
- test/controllers/users_controller_test.rb
- test/integration/user_creation_test.rb
This replaces our `user_tokens` table with a modern system based on rails builtin token generation capabilities which generates signed tokens using a key derived from the installations base secret avoiding the need to persist the tokens on disk.
It also scopes the tokens so that each token can only be used for the intended purpose.
Currently this still allows old tokens to be used - once this has been live for a few weeks a second PR will remove that support and drop the old table.
> Use rails generated tokens for emails

- app/abilities/ability.rb
- app/controllers/api/changesets_controller.rb
- app/controllers/changesets_controller.rb
- app/mailers/user_mailer.rb
- app/models/changeset.rb
- app/views/browse/changeset.html.erb
- app/views/changesets/_heading.html.erb
- app/views/changesets/no_such_entry.html.erb
- app/views/changesets/subscribe.html.erb
- app/views/changesets/unsubscribe.html.erb
- app/views/user_mailer/changeset_comment_notification.html.erb
- app/views/user_mailer/changeset_comment_notification.text.erb
- config/locales/en.yml
- config/routes.rb
- test/controllers/api/changesets_controller_test.rb
- test/controllers/changesets_controller_test.rb
- test/models/changeset_test.rb
This adds a subscribe/unsubscribe for changeset comments that mirrors the recently added one for diary comments and adjusts the emails for changeset comments, diary comments and notes to add appropriate List-XXX headers to them.
> Add standard List-XXX headers to some notification mails

- app/assets/stylesheets/common.scss
- app/helpers/browse_helper.rb
- app/views/browse/_paging_nav.html.erb
- app/views/browse/changeset.html.erb
- lib/classic_pagination/pagination_helper.rb
for sidebars of `/changeset/<id>` pages
when narrow enough:
when wider:
when really wide, with decreased padding:
> Bootstrap pagination in changeset pages for nodes/ways/relations

- app/controllers/api/changesets_controller.rb
- app/views/api/changesets/_changeset.json.jbuilder
- app/views/api/changesets/_changeset.xml.builder
- test/controllers/api/changesets_controller_test.rb
Continuation of https://github.com/openstreetmap/openstreetmap-website/pull/4245.
With comment ids shown it's possible to hide specific comments. But the unhiding also requires comment ids. They are not known because the comments are hidden from the api calls.
Here a parameter is added to show hidden comments. It makes hidden comments visible to users who can unhide comments. The request looks like this:
```
/api/0.6/changeset/<id>?include_discussion=true&show_hidden_comments=true
```
I chose to add a parameter instead of showing the comments to anyone with permissions in case there are too many hidden comments. Maybe later some kind of limit will be added, making changeset with discussion requests to look like search requests. In this case `show_hidden_comments` would act similar to …
> Show hidden comments to moderators if requested

- app/controllers/browse_controller.rb
- app/controllers/old_nodes_controller.rb
- app/controllers/old_relations_controller.rb
- app/controllers/old_ways_controller.rb
- app/views/browse/_common_details.html.erb
- app/views/browse/_node.html.erb
- app/views/browse/_relation.html.erb
- app/views/browse/_version_actions.erb
- app/views/browse/_way.html.erb
- app/views/browse/feature.html.erb
- app/views/browse/history.html.erb
- app/views/old_nodes/show.html.erb
- app/views/old_relations/show.html.erb
- app/views/old_ways/show.html.erb
- config/locales/en.yml
- test/controllers/browse_controller_test.rb
- test/controllers/old_nodes_controller_test.rb
- test/controllers/old_relations_controller_test.rb
- test/controllers/old_ways_controller_test.rb
Currently there's no obvious way to view redacted versions. The website won't show them. API-using apps will skip them because redacted versions are missing from element history request results unless a parameter that few people know about is added.
---
History page if logged in as a moderator:
After clicking the "View Unredacted History":
> Show unredacted element history to moderators

- app/controllers/passwords_controller.rb
- config/locales/en.yml
- test/controllers/passwords_controller_test.rb
This implements what is known as "paranoid" password reset flash messages ([using the terminology from Devise](https://github.com/heartcombo/devise/blob/bb18f4d3805be0bf5f45e21be39625c7cfd9c1d6/config/locales/en.yml#L36)). It avoids revealing whether the supplied email address is already registered.
Added an explicit test for this situation, so that the test for email non-existance is separate from the duplicate-case tests.
(I originally planned to move the entire passwords_controller to use `Devise::Recoverable`, but that was more challenging than I first thought.)
> Be paranoid when sending password reset emails

- test/controllers/accounts_controller_test.rb
- test/controllers/changesets_controller_test.rb
- test/controllers/confirmations_controller_test.rb
- test/controllers/diary_entries_controller_test.rb
- test/controllers/export_controller_test.rb
- test/controllers/issue_comments_controller_test.rb
- test/controllers/issues_controller_test.rb
- test/controllers/messages_controller_test.rb
- test/controllers/oauth2_applications_controller_test.rb
- test/controllers/oauth2_authorizations_controller_test.rb
- test/controllers/oauth2_authorized_applications_controller_test.rb
- test/controllers/oauth_clients_controller_test.rb
- test/controllers/passwords_controller_test.rb
- test/controllers/preferences_controller_test.rb
- test/controllers/profiles_controller_test.rb
- test/controllers/redactions_controller_test.rb
- test/controllers/reports_controller_test.rb
- test/controllers/sessions_controller_test.rb
- test/controllers/site_controller_test.rb
- test/controllers/traces_controller_test.rb
- test/controllers/user_blocks_controller_test.rb
- test/controllers/users_controller_test.rb
- test/integration/client_applications_test.rb
- test/integration/oauth2_test.rb
- test/integration/oauth_test.rb
- test/integration/redirect_test.rb
- test/integration/user_creation_test.rb
- test/integration/user_login_test.rb
- test/integration/user_terms_seen_test.rb
`assert_redirected_to` does `assert_response` anyway:
https://github.com/rails/rails/blob/6f0d1ad14b92b9f5906e44740fce8b4f1c7075dc/actionpack/lib/action_dispatch/testing/assertions/response.rb#L61
> Remove assert_response when followed by assert_redirected_to

- app/assets/javascripts/login.js
Fixes this:
Open a window with small height, go to the login page, scroll down to the OpenId button.
Press the button. The view scrolls to the top, away from the revealed OpenId form.
The same is happening in #4455.
> Prevent default event when clicking OpenID button

- app/views/changesets/show.html.erb
Whitespace at the start of a list item becomes significant when element icons are added using `::before` pseudoelement. You can see the extra space when elements with/without icons are next to each other. I'm removing unnecessary whitespace inside `<li>` here.
Before:
After:
> Fix whitespace in changeset element lists

- app/abilities/ability.rb
- app/abilities/api_ability.rb
- app/abilities/api_capability.rb
Different element types usually have the same actions with three very similar lines in ability files. It's possible to turn them into one line, also decreasing the complexity Rubocop complains about. I still have PRs where I need to increase complexity limits like #4301. After this change I won't have to do it.
> Collect node/way/relation CanCanCan subjects into arrays

- app/abilities/ability.rb
- app/controllers/browse_controller.rb
- app/controllers/old_nodes_controller.rb
- app/controllers/old_relations_controller.rb
- app/controllers/old_ways_controller.rb
- app/views/browse/_version_actions.erb
- app/views/browse/feature.html.erb
- app/views/browse/history.html.erb
- config/routes.rb
- test/controllers/browse_controller_test.rb
- test/controllers/old_nodes_controller_test.rb
- test/controllers/old_relations_controller_test.rb
- test/controllers/old_ways_controller_test.rb
Now they are in `index` actions to match `show` actions from #4480.
Views and path helpers are not changed in this PR.
> Move element history actions to old element controllers

- config/locales/en.yml
- test/application_system_test_case.rb
- test/controllers/messages_controller_test.rb
- test/helpers/user_helper_test.rb
Initiated by the following thread https://github.com/openstreetmap/openstreetmap-website/pull/4455#discussion_r1512725362
Split a separate PR from PR #4455.
> Replace "Login" labels with "Log in" when used as a verb

- app/views/users/blocked.html.erb
Split away from #4455, result of discussion https://github.com/openstreetmap/openstreetmap-website/pull/4455#discussion_r1519599220:
- Remove hanging arm
- Remove `<h1>` and `<h2>` tags for main text.
- Emphasize1st paragraph with `<strong>`
> Fix "blocked" user signup page layout

- app/abilities/ability.rb
- app/controllers/browse_controller.rb
- app/controllers/nodes_controller.rb
- app/controllers/relations_controller.rb
- app/controllers/ways_controller.rb
- app/helpers/geocoder_helper.rb
- app/views/browse/_relation_member.html.erb
- app/views/browse/_version_actions.erb
- app/views/browse/feature.html.erb
- app/views/browse/history.html.erb
- config/routes.rb
- test/controllers/browse_controller_test.rb
- test/controllers/nodes_controller_test.rb
- test/controllers/relations_controller_test.rb
- test/controllers/site_controller_test.rb
- test/controllers/ways_controller_test.rb
Continuing #4576, now moving `show` actions from Browse controller to Nodes/Ways/RelationsController.
> Move current element actions to their own controllers

- app/helpers/browse_helper.rb
- app/views/browse/_node.html.erb
- app/views/browse/_way.html.erb
`link_to` can often be simplified by passing to it just an object instead of a path or a controller name. This may help with refactoring. The simplification can be done in many other places in addition to what's in this PR, but just in case I'll do it in small steps, at least until #4581 is merged.
> Don't pass paths to element_single_current_link helper

- app/mailers/user_mailer.rb
- config/routes.rb
- test/controllers/changesets_controller_test.rb
- test/mailers/user_mailer_test.rb
Since changesets are already declared as resources, I moved subscribe/unsubscribe routes under their resources definition. The only problem is that rails named their path helpers differently, `subscribe_changeset_path` etc instead of previous `changeset_subscribe_path`.
> Move changeset subscribe/unsubscribe to resourceful routes

- app/views/messages/inbox.html.erb
- app/views/messages/outbox.html.erb
If your inbox or outbox is empty, you'll see this message
> You have no messages yet. Why not get in touch with some of the _people mapping nearby_?
with a link to your profile page. But you won't find anything about _people mapping nearby_ in your profile, this information was moved to the dashboard page in https://github.com/openstreetmap/openstreetmap-website/commit/cb7b79a58f0337ab28b41ed5105215de302d3f73.
> Change "people mapping nearby" empty inbox link to dashboard

- test/controllers/diary_entries_controller_test.rb
- test/controllers/friendships_controller_test.rb
- test/controllers/messages_controller_test.rb
- test/controllers/notes_controller_test.rb
- test/controllers/oauth_clients_controller_test.rb
- test/controllers/traces_controller_test.rb
- test/controllers/user_blocks_controller_test.rb
- test/controllers/user_roles_controller_test.rb
- test/controllers/users_controller_test.rb
for helpers with `:display_name` argument
> Shorten user path helper calls in tests

- app/views/traces/_description.html.erb
- app/views/traces/_trace.html.erb
- app/views/traces/edit.html.erb
- app/views/traces/georss.rss.builder
- app/views/traces/show.html.erb
- test/controllers/traces_controller_test.rb
for `link_to`, `url_for`, `image_tag` pointing to traces, users, map locations, edit locations
> Simplify links on trace pages

- app/helpers/browse_tags_helper.rb
Both cases are documented on OSM wiki. See:
- https://wiki.openstreetmap.org/wiki/Key:manufacturer:wikidata
- https://wiki.openstreetmap.org/wiki/Key:manufacturer:wikipedia
- https://wiki.openstreetmap.org/wiki/Key:model:wikidata
- https://wiki.openstreetmap.org/wiki/Key:model:wikipedia
> Add more wiki prefixes

- test/system/user_email_change_test.rb
```bash
$ bundle exec rails test test/system/user_email_change_test.rb 
/home/andy/src/openstreetmap-website/test/system/user_email_change_test.rb:24: warning: character class has '-' without escape: /\/user\/confirm-email\?confirm_string=[A-Za-z0-9-_%]+\s/
/home/andy/src/openstreetmap-website/test/system/user_email_change_test.rb:26: warning: character class has '-' without escape
/home/andy/.rbenv/versions/3.0.6/lib/ruby/gems/3.0.0/gems/bootsnap-1.18.3/lib/bootsnap/compile_cache/iseq.rb:53: warning: character class has '-' without escape: /\/user\/confirm-email\?confirm_string=[A-Za-z0-9-_%]+\s/
/home/andy/.rbenv/versions/3.0.6/lib/ruby/gems/3.0.0/gems/bootsnap-1.18.3/lib/bootsnap/compile_cache/iseq.rb:53: warning: character class has '-' without escape
```
> Fix warning on unescaped hyphen in regexp

- test/factories/user_blocks.rb
While testing you can create a revoked block with `create(:user_block, :revoked)`. However it's going to be active because its expiration date is not set. This can't happen when you normally use the osm website because block model's `revoke!` method expires the block.
Here I make all factory-created revoked blocks also expired. And just in case I also set the creation date earlier than the expiration date.
> Make factory-created revoked blocks inactive

- app/views/layouts/_head.html.erb
Unblocks the PR #4562
The `csp_meta_tag` does not generate a `csp-nonce`-tag since currently the `secure_headers`-gem is responsible to manage the `Content-Security-Policy` directives.
Once `secure_headers`-logic is moved/delegated back to Rails the usage of `csp_meta_tag` is useful again. Otherwise it is a bit confusing.
Once this PR is merged the CSP violation in #4562 will be solved. See more here https://github.com/openstreetmap/openstreetmap-website/pull/4562#discussion_r1532380754
> Replace csp_meta_tag with `secure_headers` nonce

- app/views/traces/_trace.html.erb
- config/locales/en.yml
Fixes #4597, but tags are still joined by `,` which might be a problem for some languages.
> Avoid lego translation in trace time/user/tags string

- Gemfile
- Gemfile.lock
- app/assets/javascripts/application.js
- app/assets/javascripts/messages.js
- app/controllers/messages_controller.rb
- app/views/layouts/_head.html.erb
- app/views/layouts/_meta.html.erb
- app/views/messages/_inbox_count.html.erb
- app/views/messages/_message_summary.html.erb
- app/views/messages/_messages_table.html.erb
- app/views/messages/_muted_count.html.erb
- app/views/messages/_outbox_count.html.erb
- app/views/messages/_sent_message_summary.html.erb
- app/views/messages/destroy.json.jbuilder
- app/views/messages/inbox.html.erb
- app/views/messages/mark.json.jbuilder
- app/views/messages/muted.html.erb
- app/views/messages/outbox.html.erb
- config/eslint.json
- test/controllers/messages_controller_test.rb
- test/system/messages_test.rb
This PR is part of a conversation with @gravitystorm and @tordans on the recent OSM Hackweekend in Karlsruhe and following conversations. The goal is to show how to integrate Rails Trubo to the project and what a migration path would look like.
Navigating the OSM website should be smooth. [Rails UJS](https://github.com/rails/rails/tree/main/actionview/app/assets/javascripts) and custom JavaScript enables users to manage their Messages in a SPA-like fashion without adding too much complexity to the codebase.
[Turbo](https://turbo.hotwired.dev) is the successor of Rails UJS. It provides SPA-like behaviour to Rails applications similar to Rails UJS but works a bit differently and allows to write even less JavaScript.
With the latest changes to [Turbo](https://turbo.hotwired.dev) (see …
> Add Turbo to replace custom JS

- app/controllers/api/changesets_controller.rb
- test/controllers/api/changesets_controller_test.rb
To find out which element order makes sense for #4571, I looked at how elements are sorted in changeset downloads. They are sorted by timestamp, then by version. Then I decided to simplify the code by replacing `sort`+ifs with `sort_by`, and I noticed that there are no tests for sort order.
Cgimap actually sorts further by type and id too: https://github.com/zerebubuth/openstreetmap-cgimap/blob/ea3e59543116fa97fd68e6d97813b1ee46e54290/src/osmchange_responder.cpp#L32. With `sort_by` it's easy to add this to osm-website if required.
> Simplify and test downloaded changeset element sorting

- app/controllers/api/users_controller.rb
`.find(params[:id])` is exactly what CanCanCan's `load_resource` does:
https://github.com/CanCanCommunity/cancancan/blob/develop/docs/controller_helpers.md#authorize_resource-load_resource-load_and_authorize_resource
> Replace lookup_user_by_id with load_resource

- app/controllers/api/changesets_controller.rb
- app/controllers/api/nodes_controller.rb
- app/controllers/api/relations_controller.rb
- app/controllers/api/ways_controller.rb
- app/controllers/api_controller.rb
- The name is confusing. It looks like a test assertion, but it's not.
- This check is unnecessary. You're only routed to actions if you use correct http verbs. If you reached the action method, you know that the verb is correct.
When `assert_method` was added in https://github.com/openstreetmap/openstreetmap-website/commit/3d0ca940d26bdc23aa791178b01b816185c5a086, [most of routes didn't check http methods](https://github.com/openstreetmap/openstreetmap-website/blob/3d0ca940d26bdc23aa791178b01b816185c5a086/config/routes.rb). That's why this check was necessary.
> Remove assert_method from api controllers

- app/controllers/concerns/pagination_methods.rb
- app/controllers/diary_entries_controller.rb
- app/controllers/traces_controller.rb
- app/controllers/users_controller.rb
- app/views/traces/index.html.erb
- app/views/users/index.html.erb
- config/locales/en.yml
- test/controllers/users_controller_test.rb
This gets rid of classic pagination on this page. There's going to be only two pages with classic pagination after that: user blocks and changeset elements.
Differences to the previous version:
- Users are listed in the opposite order.
- Of course now there's no page numbers and it's impossible to switch to the nth page, but I don't know if this was ever used.
- Normally with before/after pagination there's no total count. Classic pagination had it, which might be useful when combined with some filter like ip address. I added the count here because there won't be any large traffic to this page.
> Use newer/older pagination on admin users page

- app/controllers/api/changesets_controller.rb
- app/controllers/api/nodes_controller.rb
- app/controllers/api/old_controller.rb
- app/controllers/api/relations_controller.rb
- app/controllers/api/ways_controller.rb
- app/controllers/changesets_controller.rb
They don't even use it, and it's included in `lib/osm.rb` anyway.
> Remove require "xml/libxml" from controllers

- app/controllers/changesets_controller.rb
- app/models/old_node.rb
- app/models/old_relation.rb
- app/models/old_way.rb
- lib/diff_reader.rb
Why is ConsistencyValidations a model concern? It raises API exceptions.
> Remove unused includes of ConsistencyValidations

- app/views/diary_entries/subscribe.html.erb
- app/views/diary_entries/unsubscribe.html.erb
I was experimenting with subscribe/unsubscribe to diary entry page headings. I decided not to put username there but forgot to remove it from translation arguments.
> Remove unused user parameter for subscribe/unsubscribe headings

- config/routes.rb
- test/controllers/diary_entries_controller_test.rb
Like was done in https://github.com/openstreetmap/openstreetmap-website/commit/c909b29c35b32be6f918f4393692033b40c303ea for trace pagination.
`/user/username/diary/comments/123` -> `/user/username/diary/comments` because page numbers no longer exist
> Redirect from old diary comments pagination

- app/models/concerns/consistency_validations.rb
- app/models/node.rb
- app/models/relation.rb
- app/models/way.rb
- test/models/node_test.rb
- test/models/relation_test.rb
- test/models/way_test.rb
There are two sets of checks:
- old-new element consistency
- changeset-user consistency
Either one of them or both of them are performed in different situations.
> Refactor element consistency checks

- app/controllers/user_blocks_controller.rb
- app/views/user_blocks/_blocks.html.erb
- config/locales/en.yml
- test/controllers/user_blocks_controller_test.rb
This changes the order of blocks in the table, but:
- The current order (by end date desc) is not very useful, because the beginning of the list is dominated by long-term blocks. You'll have to page through a lot of "Ends in almost 10 years" blocks for throwaway vandalism accounts before you reach "real" blocks for people to pay attention to, those are not 10 years right away.
- There are plans to let the table be reordered, see #4200.
> Use before/after pagination on user blocks page

- test/controllers/api/changesets_controller_test.rb
- test/controllers/api/nodes_controller_test.rb
- test/controllers/api/old_nodes_controller_test.rb
- test/controllers/api/old_relations_controller_test.rb
- test/controllers/api/old_ways_controller_test.rb
- test/controllers/api/relations_controller_test.rb
- test/controllers/api/ways_controller_test.rb
Like #4591 etc.
One goal was to get rid of explicit `id` parameters because if I make old elements subresources of current elements, rails would want `node_id`/`way_id`/`relation_id` instead of `id`. Old element models already have these fields.
> Simplify api element paths in tests

- app/views/user_blocks/revoke.html.erb
- app/views/user_blocks/revoke_all.html.erb
- app/views/user_blocks/show.html.erb
Currently it's difficult to go between all blocks, blocks on, blocks by pages. For example, it's not obvious where's the link to the *all blocks* page. I want to make some kind of navigation for it. Something like tabs similar to how they are used on gpx traces pages will probably do:
But first I need to make room for tabs. Block pages have *Edit* and *Revoke* links in the heading where the tabs are supposed to be:
But why these links are there? If they are supposed to work on a currently shown block, they should be below the block, again similar to how *Edit*/*Delete* buttons are located on traces pages.
This PR moves the links and styles them similarly to traces buttons:
Later I'll turn *View all blocks* into a tab and add other tabs.
> Move edit/revoke block buttons to the bottom of the block page

- app/controllers/api/old_elements_controller.rb
- app/controllers/api/old_nodes_controller.rb
- app/controllers/api/old_relations_controller.rb
- app/controllers/api/old_ways_controller.rb
#3715 adds `ElementsController`. When I originally did it, I didn't notice that a similar superclass already exists for old elements because it's not named after elements.
The name "OldController" is not specific enough because there are other "old" things besides old elements like old tags or old relation members.
> Rename api OldController to OldElementsController

- app/views/user_blocks/_navigation.html.erb
- app/views/user_blocks/blocks_by.html.erb
- app/views/user_blocks/blocks_on.html.erb
- app/views/user_blocks/index.html.erb
- app/views/user_blocks/show.html.erb
- config/locales/en.yml
There's a potential problem though. Checks if a user has created any blocks are going to be made more often with this navigation, but there's no `creator_id` index on the blocks table. The options are:
- Do nothing because blocks pages are not the most visited and the blocks table is not the most populated.
- Remove `.blocks_created.exists?` checks. That would show more unnecessary and unexpected tabs: blocks by regular users but they can't make any blocks.
- Check if a user can create blocks instead of checking if they have created any. That would remove tabs for blocks by former moderators.
- Add a `creator_id` index on the blocks table.
- Add a `(creator_id, id)` index on the blocks table that will also help with sorting.
> Add navigation tabs to block list/show pages

- app/models/user_block.rb
- db/migrate/20240405083825_add_creator_index_to_user_blocks.rb
- db/structure.sql
For #4644 and existing `/user/.../blocks_by` pages.
> Add (creator_id, id) index to blocks table

- app/assets/stylesheets/common.scss
- app/assets/stylesheets/parameters.scss
- app/views/layouts/_content.html.erb
- app/views/traces/index.html.erb
Have to make these changes at the same time to see if they work together:
- `bg-body-secondary` in heading sections instead of #4651
- darker tab borders when they are inside `bg-body-secondary`
- default striped tables instead of #4652
This is how it looks in dark mode:
> Update heading, stripes and tab border colors

- app/views/user_blocks/_navigation.html.erb
- config/locales/en.yml
To have an active tab on a block page - see https://github.com/openstreetmap/openstreetmap-website/pull/4644#issuecomment-2041438566
> Add block tab to show block pages

- app/assets/stylesheets/common.scss
- app/helpers/application_helper.rb
- app/views/layouts/_header.html.erb
- test/helpers/application_helper_test.rb
Uses `text-secondary` or `text-secondary-emphasis` if it's a current page.
Replaces: 
- `$darkgrey`: `text-secondary` matches it
- `darken($darkgrey, 25%)`: in dark mode it shouldn't be darkened
Before:
After:
I also removed the current page color change in the "more" dropdown because it worked in the opposite direction, making the text lighter. Also there's no similar color change in the user menu dropdown.
Before, with "Communities" as the current page:
> Use secondary text color in header menu

- app/assets/stylesheets/common.scss
- app/views/site/export.html.erb
> Use secondary body color for export inputs background

- app/assets/javascripts/leaflet.layers.js
- app/assets/stylesheets/common.scss
Rewrite of #3674 - layer buttons as [Bootstrap radio toggle buttons](https://getbootstrap.com/docs/5.3/forms/checks-radios/#radio-toggle-buttons)
Enables keyboard navigation for layer buttons which is missing now.
The only custom css is to:
- set button heights
- override borders to have hover effects because Bootstrap toggle buttons don't have any hover effect (they'd need another color to tell hover states apart from selected states, they solved it by removing hover states)
> Use Bootstrap toggle buttons for layers menu

- app/assets/stylesheets/common.scss
- app/views/site/about.html.erb
I made the "OpenStreetMap provides map data" section lighter in light mode and darker in dark mode. The previous color, `bg-dark`, is exactly `bg-body` in dark mode. If kept, there would be no visible separation with the next section.
> Adapt About page backgrounds to dark mode

- app/views/layouts/map.html.erb
Fixes this:
I thought it wouldn't happen because sidebars are become full-width only in small layouts. But the right sidebar has its own logic when to go full width. It's possible to have an intermediate screen width which is both wide enough to have a floating search panel and narrow enough to have full-width right sidebar.
> Fix right sidebar background

- app/views/layouts/_header.html.erb
Not sure when the header background got broken:
It was working when I made #4667 with screenshots.
Testing again:
> Fix header background

- app/assets/javascripts/leaflet.key.js
- app/assets/javascripts/leaflet.layers.js
- app/assets/javascripts/leaflet.share.js
- app/assets/stylesheets/common.scss
Uses `border-secondary-subtle` if there's a border between section, like in #4654.
Dark mode before, the border is too bright:
Dark mode after:
> Remove custom right sidebar section class

- app/assets/stylesheets/common.scss
- app/views/traces/_trace.html.erb
- app/views/traces/edit.html.erb
- app/views/traces/show.html.erb
An alternative to #4679 which also changes light mode.
Trace images have white background which they probably shouldn't have, it should be transparent. Besides dark mode, this white background shows up in striped tables:
But we can make it behave as transparent by using blend modes:
> Invert trace images in dark mode + blend with background

- app/views/site/copyright.html.erb
- config/locales/en.yml
We are required to cite the source of open data in accordance with the Croatian Open License (Otvorena dozvola). This PR is adding proper copyright text for Croatia official sources.
Here is the license described in Croatian law: https://narodne-novine.nn.hr/clanci/sluzbeni/2017_07_67_1577.html
And here is the official English translation of the license: https://prod-data.gov.hr/en/open-license
> Adding information about Croatia sources

- app/views/site/_about_section.html.erb
`section` class is not in use since https://github.com/openstreetmap/openstreetmap-website/commit/304deb3ca7adb17b412b0fda4fad10d73d0b90b6#diff-e86a39e6d0b163f152db8843fc7d647a3f5d648de4a74f1732bef4474b6e5bc8L2693-L2699
But those are actually sections and can be replaced with `<section>` elements.
> Use section elements instead of div.section on about page
