openstreetmap/openstreetmap-website

vendor/assets/iD/iD.js, vendor/assets/iD/presets.js
This update contains fixes for 2 issues:
* Fix for 404 Error caused by duplicates in multi-fetch node request (#2626)
* Fix oil well preset (#2621)
=> Update to iD v1.7.2

INSTALL.md
=> typofix (bupported -> supported)

app/assets/javascripts/index/directions.js
=> Directions, read "to" location in URL

app/assets/javascripts/leaflet.layers.js
=> Close layers panel on double-clicking a layer

app/views/diary_entry/edit.html.erb, config/locales/en.yml
Saw this listed as TODO and thought it'd be something to try.
=> Implemented diary submit label changing depending on if new or editing

app/assets/javascripts/index/search.js
=> Hide .describe_location on push and popstate

vendor/assets/iD/iD.js, vendor/assets/iD/iD/locales/zh-HK.json
* Replace nonstandard Array `find` with `_.find` for IE11 (openstreetmap/iD#2871)
=> Update to iD v1.8.3

app/assets/javascripts/index.js
=> Consistent blue marker colour

config/locales/en.yml
Simply added State of the Map to the list of registered trademarks.
=> Reflect sucessful trademark registration of State of the Map

app/assets/stylesheets/small.scss
This PR removes the banner for small screens 
(closes #1247)
=> Remove banner for small screens

config/banners.yml
This just extends the donation banner end date to Oct 31
Sorry, my mistake! 😄
=> Extend donation drive banner end date to 2016-oct-31

test/controllers/changeset_controller_test.rb, test/controllers/diary_entry_controller_test.rb, test/controllers/user_controller_test.rb, test/factories/friends.rb, test/fixtures/friends.yml, test/models/friend_test.rb, test/models/user_test.rb
This replaces another fixture with a factory.
=> Replace friends fixture with a factory

app/views/diary_entry/rss.rss.builder, app/views/notes/_note.rss.builder, app/views/trace/georss.rss.builder
This pull request fixes a few minor RSS issues that I spotted while validating the feeds on https://validator.w3.org/feed/
=> RSS validation fixes

Vagrantfile, script/vagrant/setup/provision.sh
=> Switch vagrant Ubuntu Trusty -> Xenial

app/assets/javascripts/index/directions/graphhopper.js
Here is a little add, to have the feature of hovering instructions in GraphHopper too.
=> Add line segment to each steps of GraphHopper routing

VAGRANT.md
Notes on a couple of issues I encountered when setting up the vagrant environment on a Fedora Linux machine.
=> Add a couple of notes to the vagrant instructions

test/controllers/changeset_controller_test.rb, test/controllers/diary_entry_controller_test.rb, test/controllers/site_controller_test.rb, test/controllers/trace_controller_test.rb, test/controllers/user_controller_test.rb
This simplifies the code slightly.
=> Pass the user object, rather than the id, for sessions

test/controllers/api_controller_test.rb, test/controllers/notes_controller_test.rb
This is the next in the sequence of PRs converting to user factories.
=> Convert notes and api controller tests to user factories

test/controllers/browse_controller_test.rb, test/controllers/oauth_clients_controller_test.rb, test/controllers/site_controller_test.rb
These are all simple substitutions.
=> User factories for browse, oauth_clients and site controller tests

app/assets/javascripts/index/directions.js, app/assets/javascripts/index/directions/graphhopper.js, config/locales/en.yml
Here is a little improvment by adding Ascend and Descend.
Really needed when routing for bike or foot.
I want to add an elevation plot but as it's my first patch I do it slowly.
Thanks for futures reviews.
=> Add Ascend/Descend when routing with GraphHopper

test/controllers/redactions_controller_test.rb, test/controllers/user_blocks_controller_test.rb, test/controllers/user_preference_controller_test.rb
This pull request contains User factory conversions for redactions_controller, user_blocks_controller and user_preferences controller tests.
=> More user factories

test/controllers/trace_controller_test.rb, test/models/message_test.rb, test/models/node_test.rb, test/models/note_test.rb, test/models/oauth_token_test.rb, test/models/trace_test.rb, test/models/user_preference_test.rb
Slowly getting there, but still more to come...
=> More user factory replacements

test/helpers/application_helper_test.rb, test/helpers/note_helper_test.rb, test/integration/page_locale_test.rb, test/integration/user_blocks_test.rb, test/integration/user_creation_test.rb, test/integration/user_roles_test.rb
This is the next in the batch of user factory conversions, these were all straightforward.
=> More user factory conversions

test/factories/client_applications.rb, test/integration/oauth_test.rb, test/integration/user_terms_seen_test.rb
This converts the remaining integration tests over to user factories.
=> User factories for integration tests

test/controllers/changeset_controller_test.rb
Others are tightly interwoven with the fixtures and will be tackled seperately.
=> Use user factories for some changeset_controller tests.

test/controllers/browse_controller_test.rb, test/factories/changeset_comments.rb, test/factories/changesets.rb, test/factories/old_node.rb, test/helpers/changeset_helper_test.rb, test/models/changeset_comment_test.rb, test/models/changeset_test.rb, test/models/node_test.rb
This PR creates a changeset factory, and uses it for some of the tests.
=> Changeset factory

test/factories/node.rb, test/models/node_test.rb, test/models/old_node_test.rb, test/models/redaction_test.rb
This PR introduces the node factory, and starts using the node and old_node factories for more tests.
=> Node factories

test/controllers/node_controller_test.rb, test/factories/node_tags.rb, test/models/node_test.rb
Here's a few more refactorings, centred around the node factories.
=> Node factory refactorings

test/factories/old_relation.rb, test/factories/old_relation_member.rb, test/factories/old_way.rb, test/factories/old_way_node.rb, test/models/old_relation_test.rb, test/models/old_way_test.rb
This adds four more factories, for old_way, old_way_node, old_relation and old_relation_member.
=> Even more Factories

test/controllers/amf_controller_test.rb, test/controllers/way_controller_test.rb, test/factories/changeset_tags.rb, test/factories/old_node.rb, test/factories/old_node_tags.rb, test/factories/old_relation_tags.rb, test/factories/old_way_tags.rb, test/factories/relation.rb, test/factories/relation_tags.rb, test/factories/user_blocks.rb, test/factories/way.rb, test/factories/way_tags.rb
This cleans up some of the fixmes within the factories themselves, as well as standard refactoring of various tests.
=> More factory refactoring

test/controllers/amf_controller_test.rb
This PR refactors most, but not all, of the amf_controller tests to avoid using fixtures. I also spotted a couple of broken tests as I worked through them, and refactored a handful to use `result` for the amf_result array, for clarity.
=> Refactor amf_controller tests

app/assets/javascripts/index/directions.js
Cookie memory of the user's pulldown menu selection on "directions" pane. Scratching an itch; I hope this seems appropriate.
I wasn't sure what test would be worth adding for this. If needed please suggest.
=> Remember user's choice of directions engine

.rubocop_todo.yml, test/controllers/browse_controller_test.rb, test/controllers/changeset_controller_test.rb, test/controllers/relation_controller_test.rb, test/controllers/way_controller_test.rb, test/integration/user_changeset_comments_test.rb
More factory refactoring, mainly around the changeset controller tests.
=> More factories

.rubocop_todo.yml, test/controllers/amf_controller_test.rb, test/controllers/browse_controller_test.rb, test/controllers/changeset_controller_test.rb, test/controllers/relation_controller_test.rb, test/controllers/search_controller_test.rb, test/controllers/site_controller_test.rb, test/models/relation_test.rb, test/models/way_test.rb
This is the final refactoring of the test suite to use factories. Finally!
I will make a separate PR for removing the fixtures, since I expect to find some tests that have hidden dependencies on the fixtures being loaded.
=> Final Factory refactoring

app/controllers/api_controller.rb, app/controllers/browse_controller.rb, app/controllers/changeset_controller.rb, app/controllers/diary_entry_controller.rb, app/controllers/message_controller.rb, app/controllers/node_controller.rb, app/controllers/notes_controller.rb, app/controllers/oauth_clients_controller.rb, app/controllers/old_controller.rb, app/controllers/redactions_controller.rb, app/controllers/relation_controller.rb, app/controllers/site_controller.rb, app/controllers/trace_controller.rb, app/controllers/user_blocks_controller.rb, app/controllers/user_preference_controller.rb, app/controllers/user_roles_controller.rb, app/controllers/way_controller.rb
This is already used by the oauth plugin, and is a general rails convention.
I've left out the users_controller and the parts of the application_controller, since they will need a lot more scrutiny when changed. 
This helps make the controller code feel more familiar to new users, and is preparatory work for moving to a standard login system at some point in the future.
=> Use current_user to represent the currently logged in user

app/controllers/application_controller.rb, app/controllers/user_controller.rb, app/helpers/application_helper.rb, app/helpers/user_roles_helper.rb, app/views/user/account.html.erb, app/views/user/new.html.erb, test/helpers/application_helper_test.rb, test/helpers/user_roles_helper_test.rb
This (hopefully) completes the `@user` to `current_user` transition by fixing a few remaining issues and then removing the `@user` variable altogether.
=> Complete @user to current_user transition

vendor/assets/iD/iD/locales/en-GB.json, vendor/assets/iD/iD/locales/ko.json, vendor/assets/iD/iD/locales/nl.json, vendor/assets/iD/iD/locales/pt-BR.json, vendor/assets/iD/iD/locales/pt.json, vendor/assets/iD/iD/locales/sv.json, vendor/assets/iD/iD/locales/uk.json, vendor/assets/iD/iD/locales/zh-TW.json
* Write post-save count, not pre-save count to the changesets_count tag ([#4283])
[#4283]: https://github.com/openstreetmap/iD/issues/4283
=> Update to iD v2.4.1

FAQ.md
This tells people how to create a pull request to add a banner image for their event.
=> Add FAQ and information about creating a banner image

app/assets/javascripts/index/directions.js, app/assets/stylesheets/common.scss, app/views/layouts/_search.html.erb, config/locales/en.yml
Added a text link that reverses the directions of the planned route
See issue #1678
=> Added 'Reverse Directions' link

app/controllers/trace_controller.rb, app/views/trace/view.html.erb, test/controllers/trace_controller_test.rb
=> Allow admins and moderators to delete traces

app/controllers/user_roles_controller.rb, app/models/user.rb, app/views/browse/changeset.html.erb, app/views/diary_entry/_diary_comment.html.erb, app/views/diary_entry/_diary_entry.html.erb, app/views/message/_message_summary.html.erb, app/views/message/_sent_message_summary.html.erb, app/views/message/inbox.html.erb, app/views/message/new.html.erb, app/views/message/outbox.html.erb, app/views/message/read.html.erb, app/views/notes/_user.html.erb, app/views/redactions/show.html.erb, app/views/trace/_trace.html.erb, app/views/trace/edit.html.erb, app/views/trace/view.html.erb, app/views/user/_contact.html.erb, app/views/user/_popup.html.erb, app/views/user/account.html.erb, app/views/user_blocks/_block.html.erb, app/views/user_blocks/blocks_by.html.erb, app/views/user_blocks/blocks_on.html.erb, app/views/user_blocks/edit.html.erb, app/views/user_blocks/new.html.erb, app/views/user_blocks/revoke.html.erb, app/views/user_blocks/show.html.erb
=> Use user_path links

app/views/trace/edit.html.erb, app/views/trace/view.html.erb
I was starting to do this systematically for everything to do with traces, but there are many routes that don't yet have named paths. So here are a couple of changes anyway while the rest wait on larger refactoring of the routes.
=> Use named paths for a few trace links

config/routes.rb
This PR refactors some of the routes.rb file. I aim to slowly move towards standard "resourceful" routing, but that will take a while and I think is best done gradually. This PR includes a few general refactorings that touch on larger parts of the file.
=> Refactor routes.rb

app/assets/javascripts/index/directions.js
Thought it would be an improvement to have the Directions markers set to autoPan. Doesn't really have any negatives and only improves the functionality as far as I can tell
=> Add autoPan for Directions markers

app/controllers/application_controller.rb, app/controllers/diary_entry_controller.rb, app/controllers/message_controller.rb, app/controllers/notes_controller.rb, app/controllers/user_blocks_controller.rb, app/controllers/user_controller.rb, app/controllers/user_roles_controller.rb, app/views/diary_entry/_diary_entry.html.erb, app/views/diary_entry/comments.html.erb, app/views/diary_entry/list.html.erb, app/views/user/_contact.html.erb, app/views/user/api_read.builder, app/views/user/view.html.erb, app/views/user_blocks/blocks_by.html.erb, app/views/user_blocks/blocks_on.html.erb, app/views/user_blocks/new.html.erb
Historically we used `@user` for the currently logged in user, but this was changed to `current_user` in https://github.com/openstreetmap/openstreetmap-website/pull/1583 https://github.com/openstreetmap/openstreetmap-website/pull/1595 and https://github.com/openstreetmap/openstreetmap-website/pull/1597. That allows this refactoring from `@this_user` to `@user`.
=> Refactor @this_user to @user

app/assets/javascripts/index/directions.js
=> Remove error class when right-click-selecting destination

app/models/notifier.rb, app/views/diary_entry/_diary_entry.html.erb, app/views/message/_message_summary.html.erb, app/views/message/_sent_message_summary.html.erb, app/views/message/new.html.erb, app/views/message/read.html.erb, app/views/user/_contact.html.erb, app/views/user/view.html.erb, test/controllers/message_controller_test.rb
This PR uses the existing named routes for the messages controller.
=> Use named paths for messages

app/models/changeset.rb
=> Include changes_count in changeset xml response

app/controllers/diary_entry_controller.rb, app/views/diary_entry/_diary_entry.html.erb, app/views/diary_entry/_diary_index_entry.html.erb, app/views/diary_entry/_diary_list_entry.html.erb, app/views/diary_entry/index.html.erb, app/views/diary_entry/rss.rss.builder, app/views/diary_entry/show.html.erb, app/views/user/show.html.erb, config/locales/en.yml, config/routes.rb, test/controllers/diary_entry_controller_test.rb
Even more resourceful route renaming
=> Rename diary_entry#list to #index

app/assets/javascripts/index/history.js
=> Set minimum changeset boundary size

app/assets/javascripts/index/history.js
=> Turn changeset border darker orange on hover

test/controllers/users_controller_test.rb
These three tests cover parts of the codebase that weren't previous covered - see https://github.com/openstreetmap/openstreetmap-website/commit/22af018298047ece6a01daaa8ffc0b29f1bcaaed
=> Add some more user tests

app/abilities/ability.rb, app/abilities/capability.rb, app/controllers/application_controller.rb, app/controllers/notes_controller.rb, config/locales/en.yml, test/abilities/abilities_test.rb, test/abilities/capability_test.rb
Notes were also the last remaining thing using require_moderator, so I've removed this method and the corresponding translations.
=> Use CanCanCan for notes auth

app/abilities/ability.rb, app/controllers/user_roles_controller.rb, config/locales/en.yml, test/abilities/abilities_test.rb, test/controllers/user_roles_controller_test.rb
This refactors another controller to use CanCanCan, and removes some custom code for requiring administrators.
=> Use CanCanCan for user_roles auth

app/abilities/ability.rb, app/controllers/messages_controller.rb, app/controllers/oauth_clients_controller.rb
Another couple of controller refactorings to use CanCanCan, not many remaining now.
=> Authorization for Messages and Oauth Clients

config/locales/en.yml
Holiday Apartment is more specific for tourism=apartment
=> Holiday Apartment is more specific for tourism=apartment

app/abilities/ability.rb, app/abilities/capability.rb, app/controllers/amf_controller.rb, app/controllers/application_controller.rb, app/controllers/users_controller.rb, config/example.application.yml, test/controllers/changeset_comments_controller_test.rb, test/controllers/users_controller_test.rb, test/factories/user.rb, test/integration/user_terms_seen_test.rb
=> Remove require_terms_* configuration options

vendor/assets/iD/iD/locales/en.json, vendor/assets/iD/iD/locales/eo.json, vendor/assets/iD/iD/locales/zh-CN.json
* Fix an issue where ImproveOSM would not load due to non-HTTPS endpoints
=> Update to iD v2.14.1

app/controllers/notes_controller.rb, app/views/notes/_user.html.erb, app/views/notes/mine.html.erb, config/locales/en.yml
This is some minor refactoring of a view that I noticed. I felt it was more complicated than necessary.
=> Refactor notes#mine

public/robots.txt
=> Remove dead link to sitemap from robots.txt

CONTRIBUTING.md
I thought we had something somewhere else, but I can't find it. In any case, this appears to be the most appropriate place for it.
=> Add a note about avoiding commits to other locale files

app/abilities/ability.rb, app/views/diary_entries/_diary_comment.html.erb, app/views/diary_entries/_diary_entry.html.erb, test/abilities/abilities_test.rb, test/controllers/diary_entries_controller_test.rb
This arises from discussions with DWG.
=> Allow moderators to hide diary entries and comments

app/controllers/changesets_controller.rb, app/views/changesets/index.atom.builder, app/views/changesets/index.html.erb
Also makes it more obvious that a render call can be simplified
=> Rename @edits variable to @changesets, for clarity

.rubocop_todo.yml, test/helpers/user_roles_helper_test.rb
I'm not entirely convinced that testing walls of text like this is useful anyway, but at least this approach makes the lines significantly less long.
=> Split some extremely long strings over multiple lines using squiggly heredocs

config/locales/en.yml
As reported on https://translatewiki.net/wiki/Thread:Support/Found_typo_in_https://translatewiki.net/w/i.php%3Ftitle%3DOsm:Users.terms.tou_explain_html/en
=> Fix spellings from aggree to agree

app/controllers/notes_controller.rb, app/views/browse/note.html.erb, test/controllers/notes_controller_test.rb
=> do not allow anonymous users to comment on notes

config/locales/en.yml
I spotted this while working on #2392
=> DMCA page is now available over https

CONTRIBUTING.md
=> Add description of the nominatim key update process

CONFIGURE.md
=> Remove outdated reference to the external gpx importer

app/views/layouts/_flash.html.erb, app/views/layouts/_header.html.erb, app/views/layouts/error.html.erb
For html5 validator [1] this end tag is an error.
[1] https://html5.validator.nu/?doc=https%3A%2F%2Fwww.openstreetmap.org%2F&showimagereport=yes
=> removed end tag ("source" is a self-closing tag)

vendor/assets/iD/iD.css.erb
=> Fix errant CSS color properties

app/views/layouts/_header.html.erb
Fixed inattentiveness from my last commit.
=> fixed "end tag" -> "source"

app/assets/javascripts/leaflet.layers.js
=> Remove list styling from the lists used in the layers sidebar

app/views/users/login.html.erb
Follow fix for a bug I introduced in #2508
=> Use an unstyled list for the login buttons

Vendorfile, vendor/assets/leaflet/leaflet.js
Changelog: https://github.com/Leaflet/Leaflet/blob/master/CHANGELOG.md
=> Update leaflet to 1.6.0

test/controllers/changeset_comments_controller_test.rb, test/controllers/changesets_controller_test.rb, test/controllers/directions_controller_test.rb, test/controllers/errors_controller_test.rb
=> Refactor some more controller tests

config/routes.rb, test/controllers/api/nodes_controller_test.rb, test/controllers/api/old_nodes_controller_test.rb, test/controllers/api/old_relations_controller_test.rb, test/controllers/api/old_ways_controller_test.rb, test/controllers/api/relations_controller_test.rb, test/controllers/api/ways_controller_test.rb
There's definitely some future work in renaming the routes. In this PR I've added various names, which either a) match similar examples that already existed for other elements (like nodes when naming a relation route) or b) matched what the "resourceful routing" would give, when we eventually refactor the routes to be resourceful.
=> More controller test refactoring

app/assets/stylesheets/id.css
Quick fix for https://github.com/openstreetmap/iD/issues/7560 until we address it on the iD side.
=> Fix issue with iD embedded document sometimes showing scrollbars

app/models/concerns/consistency_validations.rb, app/models/concerns/redactable.rb
This PR converts two files from the `lib` dir to be model concerns.
=> Convert lib files to model concerns

app/assets/stylesheets/common.scss, app/assets/stylesheets/small.scss, app/views/traces/index.html.erb
The trace part is actually removing html, but I thought it was CSS when I first noticed the blank space on the page.
=> Remove some extraneous css

app/assets/javascripts/leaflet.layers.js, app/assets/javascripts/leaflet.share.js, app/assets/stylesheets/common.scss, app/assets/stylesheets/small.scss, app/views/browse/changeset.html.erb, app/views/browse/note.html.erb, app/views/diary_entries/_diary_comment.html.erb, app/views/diary_entries/_diary_entry.html.erb, app/views/issues/show.html.erb, app/views/traces/_trace.html.erb, app/views/users/_contact.html.erb, app/views/users/confirm.html.erb, app/views/users/login.html.erb, app/views/users/show.html.erb, app/views/users/terms.html.erb
This avoids changing anything related to forms, since they will be switched over to bootstrap separately.
=> Use bootstrap text-muted in place of custom deemphasze class

config/locales/en.yml, test/system/diary_entry_test.rb
=> Rephrase 'replying' text to clarify what will actually happen

script/deliver-message
=> Fix call to UserMailer in message delivery

.rubocop_todo.yml, test/controllers/api/map_controller_test.rb, test/controllers/api/old_nodes_controller_test.rb, test/controllers/api/old_relations_controller_test.rb, test/controllers/api/old_ways_controller_test.rb, test/helpers/browse_tags_helper_test.rb, test/lib/locale_test.rb
There's plenty more where these came from, but it's a start at least, and reducing the limit discourages more extra-long lines slipping through in the future.
=> Resolve some extra-long lines

.rubocop_todo.yml, app/helpers/note_helper.rb, app/helpers/title_helper.rb, app/views/browse/_relation_member.html.erb, app/views/issues/show.html.erb, app/views/layouts/_head.html.erb, app/views/oauth_clients/show.html.erb, app/views/traces/_trace.html.erb, app/views/users/_popup.html.erb, app/views/users/terms.html.erb, lib/bounding_box.rb, lib/osm.rb
Partial work on another `rubocop_todo` item
=> Prefer string interpolation to concatenation

app/views/diary_entries/_diary_entry.html.erb, config/locales/en.yml
=> Add last updated date to diary entry page

app/views/users/login.html.erb
Care has been taken to preserve exact tabindexes, field values etc.
=> Refactor login form to use bootstrap

app/assets/javascripts/embed.js.erb, app/assets/javascripts/leaflet.map.js, config/locales/en.yml, vendor/assets/leaflet/leaflet.osm.js
Following the decision of the OWG to add the CyclOSM layer. I try to implement it.
I can adjust the position of the layer if the second position is no right.
=> Add CyclOSM layer

app/views/user_blocks/edit.html.erb, app/views/user_blocks/new.html.erb, config/locales/en.yml
Further refactoring could involve a virtual attribute for duration.
=> Refactor user_blocks form to use bootstrap

app/views/browse/note.html.erb, app/views/issues/_comments.html.erb, app/views/redactions/edit.html.erb, app/views/redactions/new.html.erb, app/views/redactions/show.html.erb, config/locales/en.yml
This PR refactors various forms to use bootstrap, including notes, redactions, and issue comments.
=> More bootstrap form refactoring

app/views/users/account.html.erb, app/views/users/new.html.erb, config/locales/en.yml, test/controllers/users_controller_test.rb
I've made this a separate PR since it's our biggest and most complex form.
There's definitely room for further refactoring, particularly around the image radio boxes and their names and values, but I didn't want to do too much at the same time.
=> Refactor account form to use bootstrap

Gemfile.lock
=> Bump composite_primary_keys to 12.0.8

app/views/layouts/_search.html.erb
=> Prevent input group wrapping when sidebar is resized

.rubocop_todo.yml, app/controllers/application_controller.rb, app/controllers/messages_controller.rb, app/controllers/users_controller.rb, app/views/browse/changeset.html.erb, app/views/diary_entries/show.html.erb, test/controllers/changesets_controller_test.rb, test/controllers/diary_entries_controller_test.rb, test/controllers/site_controller_test.rb, test/controllers/traces_controller_test.rb, test/controllers/users_controller_test.rb, test/integration/client_applications_test.rb, test/integration/user_login_test.rb
I'm working on some refactoring of users_controller, and this is a minor part of that work that can be split off and reviewed/merged separately.
=> Use login_path instead of explicit controller and actions

app/validators/characters_validator.rb, app/validators/whitespace_validator.rb
This avoids a deprecation warning on rails 6.1
=> Use .add method for adding errors

app/views/traces/_trace.html.erb, app/views/traces/index.html.erb, config/locales/en.yml, test/controllers/traces_controller_test.rb
This is a reworking of #3036, based on the ideas in that PR but with some changes based on the review (mainly, sticking with a table to avoid floating everything around).
=> Refactor traces list display

config/initializers/sanitize.rb, test/lib/rich_text_test.rb
=> Prevent addition of style attributes to all elements

app/views/sessions/new.html.erb, test/system/user_signup_test.rb
=> Fix registration link

app/helpers/user_blocks_helper.rb, test/helpers/user_blocks_helper_test.rb
This PR fixes the two issues described in #3210 which, although technically different, can be taken together.
=> Fix user blocks short duration display issues

app/controllers/issues_controller.rb
=> Set updated_by when resolving issues

app/controllers/confirmations_controller.rb
=> Fix the email address that's suggested for whitelisting

app/controllers/traces_controller.rb, app/views/layouts/_content.html.erb, app/views/traces/index.html.erb, config/locales/en.yml
This is a rebased version of #3034 by @tordans and includes fixes by @migurski and a few small reworkings of the tabs by myself, mainly to make them look great on smaller screen widths.
=> Traces#index: Introduce tab navigation, fix tag-filter

app/assets/javascripts/oauth.js, app/controllers/application_controller.rb, app/helpers/application_helper.rb, app/models/user.rb, config/settings.yml, package.json, yarn.lock
This switches the web site to use OAuth 2 for authentication.
=> Switch web site to use OAuth 2

app/controllers/api/user_preferences_controller.rb, app/controllers/issues_controller.rb, app/helpers/banner_helper.rb, app/models/concerns/consistency_validations.rb, test/controllers/api/map_controller_test.rb, test/controllers/api/relations_controller_test.rb, test/controllers/api/tracepoints_controller_test.rb, test/controllers/api/traces_controller_test.rb, test/controllers/traces_controller_test.rb, test/lib/utf8_test.rb, test/models/message_test.rb, test/models/user_test.rb, test/test_helper.rb
These were found as part of #3233. I've separated them out as part of the review process.
=> Fix various code comments

config/locales/en.yml
Per request from the copyright holder to DWG updated to match requested attribution per https://data.gov.au/data/dataset/bdcf5b09-89bc-47ec-9281-6b8e9ee147aa
=> Update attribution for Australia

.editorconfig, .gitattributes
Force line endings using a `.gitattribute` file and and `.editorconfig` file
Likely fix for: #3312
=> Add gitattribute to fix line endings

app/views/diary_entries/index.html.erb, app/views/layouts/_meta.html.erb, app/views/user_mailer/diary_comment_notification.html.erb, app/views/user_mailer/message_notification.html.erb
These started being flagged after a recent update
=> Fix erblint errors from the Rails/ContentTag cop

app/models/user.rb
The corresponding code was removed in a65cb8428867d92d76bbf051bbd4614966636cf5
=> Remove unused require statement

CONFIGURE.md
=> Update documentation for how to confirm a new user account

app/views/oauth2_applications/index.html.erb, app/views/oauth2_applications/show.html.erb, app/views/oauth2_authorized_applications/index.html.erb, app/views/site/_id.html.erb, app/views/site/help.html.erb, app/views/site/id.html.erb, app/views/user_blocks/blocks_on.html.erb, test/controllers/oauth2_applications_controller_test.rb, test/controllers/oauth2_authorized_applications_controller_test.rb
Minor fixes I spotted while looking around the views
=> View html fixes

.rubocop_todo.yml, app/controllers/geocoder_controller.rb, app/models/user.rb, lib/bounding_box.rb, lib/osm.rb, lib/rich_text.rb, lib/short_link.rb, test/controllers/api/old_nodes_controller_test.rb, test/lib/short_link_test.rb
This simply adds braces to clarify which mathematical operator comes first.
=> Rubocop autofix: ambiguous operator precedence

app/assets/javascripts/application.js, app/assets/javascripts/leaflet.key.js, app/assets/javascripts/leaflet.layers.js, app/assets/javascripts/leaflet.note.js, app/assets/javascripts/leaflet.query.js, test/system/site_test.rb
=> Fix map key tooltip

app/assets/stylesheets/common.scss
=> Enable focus styling for leaflet control buttons

SECURITY.md
=> Add a basic security policy

app/views/browse/_common_details.html.erb, app/views/browse/changeset.html.erb, app/views/changesets/_changeset.html.erb, app/views/traces/_trace.html.erb
This was missed during the bootstrap 5 upgrade
=> Fix italic font styles

app/assets/stylesheets/common.scss
This is much clearer than relying on positional arguments, and is also required for future upgrades to bootstrap.
This PR is extracted from #3660 since it can be reviewed in isolation, and the 5.2 upgrade is a lot more complex than expected!
=> Use named arguments for button-variant mixins

app/assets/stylesheets/common.scss
Fix unexpected margin introduced in https://github.com/openstreetmap/openstreetmap-website/commit/34edfdb9bae297144331b46dfe52319d13e519a3#diff-7085085f26b51cc428bf0a4dce47f5399822c07573a8eaa0c85ac64ce1cb0387R1107
=> Fix margin

app/assets/javascripts/leaflet.map.js, app/assets/javascripts/leaflet.sidebar.js
Fixes https://github.com/openstreetmap/openstreetmap-website/issues/3180
=> Pan map when showing/hiding sidebars depending on ltr/rtl

app/views/browse/note.html.erb
See 6. in https://github.com/openstreetmap/openstreetmap-website/pull/3718#issuecomment-1261480992
=> Remove unused note id data attributes

INSTALL.md
State some ruby gems might not be supported and Docker is easiest solution.
=> Clarify Windows installation bad + alternatives

config/locales/en.yml
My editor does this too.  There's one more trailing space in this area of the file.
=> another trailing space

app/controllers/api/notes_controller.rb, test/controllers/api/notes_controller_test.rb
Fixes https://github.com/openstreetmap/openstreetmap-website/issues/3766
=> Pass bbox coordinates to note rss feed builders

vendor/assets/iD/iD.js
this is the bugfix release for:
* Fix crash when performing a multiselection of objects with differing tags values in a combo field (https://github.com/openstreetmap/iD/issues/9369)
=> Update to iD v2.23.2

app/helpers/browse_tags_helper.rb, config/locales/en.yml, test/helpers/browse_tags_helper_test.rb
This is easier than building a mailto link ourselves. Also implement the missing title tag and write a test for it.
=> Use the mail_to method to construct a mailto link for browse tag values

test/controllers/api/changesets_controller_test.rb
Extracted from pull request #1995
Closes #1995
=> Add more testcases to changesets_controller

test/models/user_test.rb
This ensures that tokens are revoked or invalidated when a user is soft destroyed.
Follow up for 445e8162e976a6894b2bc94
=> Add tests to ensure tokens are revoked

config/wiki_pages.yml, script/misc/update-wiki-pages
script/misc/update-wiki-pages hasn't been run in a while, so here's an updated version. The number of deleted rows seems a bit larger than usual. I can't tell for sure if the script is still working as expected and the results is fine, or if the underlying Wiki representation has been changed in a way that it breaks the update script.
Due to a large number of MediaWiki API calls and resulting issues with rate limiting, breaking network connections, and general stability issues, I've added another commit to define retry and timeout values for the API calls.
=> Update wiki pages

config/locales/en.yml
=> Fix some translation issues for diary_entry#new

app/assets/javascripts/index/directions.js, config/locales/en.yml
=> Make distances in directions translatable

app/controllers/issue_comments_controller.rb, app/controllers/issues_controller.rb, app/controllers/reports_controller.rb
=> Add database checks to issue and report controllers

app/helpers/browse_tags_helper.rb, test/helpers/browse_tags_helper_test.rb
=> Avoid converting conditional restriction tags into emails

app/views/confirmations/confirm.html.erb, app/views/shared/_markdown_help.html.erb, app/views/site/_potlatch.html.erb, app/views/site/communities.html.erb, app/views/site/fixthemap.html.erb, app/views/users/terms.html.erb, config/locales/en.yml
Refs #3936
This PR is a continuation of the work to remove all raw html from our translations.
=> Remove more raw html from translations

app/views/site/copyright.html.erb, config/locales/en.yml
This is one of an ongoing series of pull requests to remove raw html from our translations.
=> Avoid using raw html on the copyright page

script/vagrant/setup/provision.sh
This is to align with the INSTALL.md instructions
=> Use the db:create command for vagrant provisioning

DOCKER.md
=> Clarify that symlinks refers to git not the operating system

config/wiki_pages.yml
Update wiki_pages.yml, it is 6 months old now
=> rerun script/misc/update-wiki-pages

config/settings.yml
Issue: https://github.com/openstreetmap/openstreetmap-website/issues/4085
Original issue with broader description: https://github.com/openstreetmap/iD/issues/9708
=> Block mapy.cz as non-approved imagery

app/assets/stylesheets/common.scss, app/assets/stylesheets/parameters.scss
Here are three minor CSS fixups, which remove some unused parameters and clean up a duplicate `display` property.
=> Minor CSS fixups

app/controllers/diary_entries_controller.rb, app/views/diary_entries/index.html.erb, test/controllers/diary_entries_controller_test.rb
Based on he model used for trace paging...
=> Replace page numbers with ID based selection for diary indexes

app/controllers/api/changesets_controller.rb, app/views/api/capabilities/show.builder, config/settings.yml, test/controllers/api/changesets_controller_test.rb
https://github.com/openstreetmap/openstreetmap-website/pull/3933#issuecomment-1652088815 - followup for changesets
=> Add changeset limit settings, use them in capabilities and tests

app/assets/stylesheets/common.scss, app/views/users/show.html.erb
https://getbootstrap.com/docs/5.1/content/typography/#inline
=> Use Bootstrap inline lists for <dl>s on user pages

app/assets/stylesheets/common.scss, app/views/diary_entries/_diary_comment.html.erb, app/views/diary_entries/_diary_entry.html.erb, app/views/diary_entries/_form.html.erb, app/views/diary_entries/show.html.erb, test/controllers/diary_entries_controller_test.rb
- paddings and margins with bootstrap classes
- deleted post/comment background with bootstrap classes
- "Use map" in diary post form as a button
- `<article>` elements for posts
=> Various css/bootstrap updates to diary pages

app/views/diary_entries/_diary_entry.html.erb, app/views/diary_entries/show.html.erb
includes margin-top removal per https://github.com/openstreetmap/openstreetmap-website/pull/4144#issuecomment-1677076131
=> Small changes of diary comments

app/mailers/user_mailer.rb, app/views/user_mailer/_message_body.html.erb
=> Use correct extension and type for avatar images attached to mails

app/assets/stylesheets/common.scss, app/views/notes/index.html.erb
https://getbootstrap.com/docs/5.1/content/tables/#active-tables
=> Use Bootstrap highlight class in note tables

app/controllers/friendships_controller.rb, app/views/friendships/make_friend.html.erb
custom lookup to use with `before_action`, similar to
https://github.com/openstreetmap/openstreetmap-website/blob/7054cea48ee9728c155334b48777a5f25db89af8/app/controllers/user_blocks_controller.rb#L114
=> Lookup friend user before make/remove friend action

app/assets/stylesheets/parameters.scss
Fixes #4263
This is a simple fix for the incorrect parameters, without making other changes.
=> Fix border settings used in workaround

app/views/layouts/_search.html.erb
=> Decrease directions button height to match Go button

.github/workflows/lint.yml, Gemfile, app/models/changeset_comment.rb, app/models/friendship.rb, app/models/note_comment.rb, app/models/oauth2_application.rb, app/models/oauth_nonce.rb, app/models/old_relation.rb, app/models/old_relation_member.rb, app/models/old_relation_tag.rb, app/models/old_way.rb, app/models/old_way_tag.rb, app/models/tracetag.rb, app/models/user.rb, lib/tasks/auto_annotate_models.rake
Replacement PR for #4286 
The model annotations are not so useful when they are outdated. Automatically checking the model annotations ensures they are up to date.
=> .github/workflows/lint.yml: Check if annotate_models is up to date

app/assets/javascripts/index/directions.js, app/assets/stylesheets/common.scss, app/helpers/geocoder_helper.rb, app/views/geocoder/error.html.erb, test/controllers/geocoder_controller_test.rb, test/helpers/geocoder_helper_test.rb
Also change search/direction error to bootstrap alert:
=> Remove some search/directions custom css

app/assets/stylesheets/common.scss, app/views/layouts/_banner.html.erb
Continuing https://github.com/openstreetmap/openstreetmap-website/pull/4112#issuecomment-1662212137
=> Remove relative position from sidebar child divs other than banners

app/assets/stylesheets/common.scss, app/views/layouts/map.html.erb
=> Remove custom css and unnecessary div nesting of welcome panel

config/initializers/migrate.rb, db/migrate/007_add_relations.rb, db/migrate/039_add_more_controls_to_gpx_files.rb, db/migrate/044_create_user_roles.rb, db/migrate/051_add_status_to_user.rb, db/migrate/053_add_map_bug_tables.rb, db/migrate/057_add_map_bug_comment_event.rb, db/migrate/20110521142405_rename_bugs_to_notes.rb, db/migrate/20120214210114_add_text_format.rb, db/migrate/20160822153055_create_issues_and_reports.rb, db/migrate/20231029151516_add_importer_role.rb
Followup as suggested during the #4319 review.
=> Switch to using native rails support for managing Postgres enumerations

app/assets/javascripts/leaflet.share.js, config/locales/en.yml
fixes https://github.com/openstreetmap/openstreetmap-website/issues/4273
=> Disable html share button for tracestracktopo layer

app/controllers/site_controller.rb, app/views/site/key.html.erb, config/key.yml
Also allow to omit `max_zoom` if the next entry has `min_zoom`. This makes it easier to compare consecutive entries.
=> Add opnvkarte map key line widths on high zoom levels

app/assets/images/key/opnvkarte/main_road11.svg, app/assets/images/key/opnvkarte/main_road13.svg, app/assets/images/key/opnvkarte/main_road15.svg, app/assets/images/key/opnvkarte/main_road17.svg, app/assets/images/key/opnvkarte/motorway13.svg, app/assets/images/key/opnvkarte/motorway15.svg, app/assets/images/key/opnvkarte/motorway17.svg, app/assets/images/key/opnvkarte/motorway8.svg, config/key.yml
=> Add main road opnvkarte map key

app/helpers/browse_tags_helper.rb, test/helpers/browse_tags_helper_test.rb
=> Keep trailing semicolons in formatted tag values

config/key.yml
=> Update cyclemap map key landcover colors

app/assets/javascripts/messages.js, app/views/messages/_inbox_count.html.erb, app/views/messages/_muted_count.html.erb, app/views/messages/_outbox_count.html.erb, app/views/messages/destroy.json.jbuilder, app/views/messages/inbox.html.erb, app/views/messages/mark.json.jbuilder, app/views/messages/muted.html.erb, app/views/messages/outbox.html.erb, test/system/messages_test.rb
Fixes #4265 and similar bug for muted messages list.
=> Fix messages heading update when message is deleted

app/views/layouts/map.html.erb
=> Set sizes of welcome buttons to be as equal as possible

config/key.yml, config/locales/en.yml
Add features mentioned in https://github.com/openstreetmap/openstreetmap-website/issues/2956.
I don't know what cyclemap renders for [route=mtb](https://wiki.openstreetmap.org/wiki/Tag:route=mtb) combined with local/regional/national network.
=> Add bridleway and mtb route to cyclemap key

app/assets/images/key/mapnik/capital4.svg, app/assets/images/key/mapnik/capital7.svg, app/assets/images/key/mapnik/city4.svg, app/assets/images/key/mapnik/city6.svg, config/key.yml, config/locales/en.yml
=> Add cities to mapnik map key

app/mailers/user_mailer.rb, app/views/user_mailer/_gpx_description.html.erb, app/views/user_mailer/gpx_success.html.erb, config/locales/en.yml, test/mailers/user_mailer_test.rb
Fixes https://github.com/openstreetmap/openstreetmap-website/issues/2310
=> Link to GPX trace pages from successful import emails

INSTALL.md
The package lists elsewhere were simplified in d6d16dedb917d1e0339eced418de8ae908dba3e8
=> Update package exclusion list when using rbenv

config/locales/en.yml
=> Remove ":" from OpenID input label

app/views/oauth2_authorized_applications/_application.html.erb, app/views/oauth2_authorized_applications/index.html.erb, config/locales/en.yml
=> Show last authorization time for OAuth 2 applications

app/controllers/sessions_controller.rb, test/controllers/sessions_controller_test.rb
=> SessionsController: strip username

app/controllers/users_controller.rb, test/integration/user_creation_test.rb
=> Treat github and wikipedia provided emails as confirmed

.rubocop_todo.yml, Gemfile, Gemfile.lock, app/models/user.rb, app/validators/width_validator.rb, test/models/user_test.rb
=> Require display names to have a minimum unicode width of 3 columns

config/routes.rb
All of the controllers inside the "api/0.6" scope start with "api/". It's possible to write it once for everything inside the scope.
=> Use :module to specify api controllers module

app/models/redaction.rb, db/migrate/20240307180830_add_check_constraint_to_redaction_title_and_description.rb, db/migrate/20240307181018_validate_and_modify_redaction_title_and_description.rb, db/structure.sql, test/models/redaction_test.rb
Fixes: https://github.com/openstreetmap/openstreetmap-website/issues/2033
=> Enforce Not Null Constraints on Redaction Title and Description

test/controllers/nodes_controller_test.rb, test/controllers/relations_controller_test.rb, test/controllers/ways_controller_test.rb
Added tests that would have failed because https://github.com/openstreetmap/openstreetmap-website/pull/4579#issuecomment-2000202320
=> Test links to containing relations from element pages

app/helpers/changesets_helper.rb, app/views/browse/_containing_relation.html.erb, app/views/browse/_relation_member.html.erb, app/views/changesets/_heading.html.erb, app/views/changesets/show.html.erb, app/views/dashboards/_contact.html.erb, app/views/dashboards/_popup.html.erb, test/controllers/changesets_controller_test.rb
=> Simplify changeset/element-related link_to calls

app/views/messages/_message_summary.html.erb, app/views/messages/_sent_message_summary.html.erb, app/views/messages/new.html.erb, app/views/messages/show.html.erb, test/controllers/messages_controller_test.rb
also continuing https://github.com/openstreetmap/openstreetmap-website/pull/4584
=> Simplify link_to calls on message pages

app/views/issues/_comments.html.erb, app/views/issues/_reports.html.erb, app/views/issues/index.html.erb, app/views/issues/show.html.erb
also continuing https://github.com/openstreetmap/openstreetmap-website/pull/4584
=> Simplify link_to user calls on issue pages

app/views/user_blocks/_block.html.erb, app/views/user_blocks/blocks_by.html.erb, app/views/user_blocks/blocks_on.html.erb, app/views/user_blocks/edit.html.erb, app/views/user_blocks/new.html.erb, app/views/user_blocks/revoke.html.erb, app/views/user_blocks/revoke_all.html.erb, app/views/user_blocks/show.html.erb, test/controllers/user_blocks_controller_test.rb
=> Simplify link_to user calls on block pages

app/views/traces/_description.html.erb, app/views/traces/georss.rss.builder, test/controllers/traces_controller_test.rb
=> Fix trace feed image urls and local variable names

app/views/messages/_message_summary.html.erb, app/views/messages/_messages_table.html.erb, app/views/messages/_sent_message_summary.html.erb
see https://github.com/openstreetmap/openstreetmap-website/issues/4596#issuecomment-2009693014
=> Rename message local in message table partials

app/views/diary_entries/_diary_comment.html.erb, app/views/diary_entries/_diary_entry.html.erb, app/views/diary_entries/_diary_entry_heading.html.erb, app/views/diary_entries/_location.html.erb, app/views/diary_entries/comments.html.erb, app/views/diary_entries/show.html.erb, test/controllers/diary_entries_controller_test.rb
Similar to `link_to`/`*_path` simplifications I did before.
=> Simplify links on diary pages

test/controllers/api/notes_controller_test.rb, test/controllers/notes_controller_test.rb
=> Shorten note path helper calls in tests

app/views/users/show.html.erb
=> Add links for admins from user page to user list filtered by ip/status

app/abilities/ability.rb, app/controllers/traces/icons_controller.rb, app/controllers/traces/pictures_controller.rb, app/controllers/traces_controller.rb, config/routes.rb, test/controllers/traces/icons_controller_test.rb, test/controllers/traces/pictures_controller_test.rb, test/controllers/traces_controller_test.rb
I put them in a module, like was done in https://github.com/openstreetmap/openstreetmap-website/commit/6c1d73a509a1ac2216a704f3dc5534d573e5d7ae with DeletionsController.
=> Move trace pictures/icons into their own controllers

app/controllers/traces/icons_controller.rb, app/controllers/traces/pictures_controller.rb, app/controllers/traces_controller.rb
Allows to eliminate some :not_found branches.
=> Use "visible" scope when finding traces

app/assets/stylesheets/common.scss, app/helpers/user_helper.rb, app/views/browse/_tag.html.erb, app/views/browse/_tag_details.html.erb, app/views/dashboards/show.html.erb, app/views/diary_entries/_diary_entry.html.erb, app/views/diary_entries/_form.html.erb, app/views/diary_entries/show.html.erb, app/views/layouts/_header.html.erb, app/views/messages/show.html.erb, app/views/profiles/edit.html.erb, app/views/site/export.html.erb, app/views/users/terms.html.erb, test/helpers/user_helper_test.rb
No noticeable difference (#cccccc vs #cfcfcf) and no problems with dark mode.
=> Replace border-grey css class with border-secondary-subtle

app/assets/stylesheets/common.scss, app/views/layouts/map.html.erb
No custom css, adapts to dark mode.
=> Set sidebar background using Bootstrap class

app/assets/stylesheets/common.scss, app/views/layouts/_search.html.erb
=> Use secondary body color in search/direction forms

app/assets/stylesheets/common.scss
=> Fix export inputs rtl

app/assets/stylesheets/common.scss
=> Adapt right sidebar to dark mode

app/assets/stylesheets/common.scss
=> Adapt rich text to dark mode

app/assets/stylesheets/common.scss
=> Invert routing direction icons in dark mode

app/assets/stylesheets/common.scss, app/views/layouts/_header.html.erb
=> Support dark mode in header

app/views/issues/show.html.erb, app/views/shared/_richtext_field.html.erb
Read reports on show issue page:
Rich text help:
=> Replace bg-light with bg-body-tertiary

app/assets/stylesheets/common.scss, app/views/layouts/_search.html.erb
=> Set search input z-index with Bootstrap utility class

app/views/messages/_message_summary.html.erb, app/views/messages/_sent_message_summary.html.erb
Fixes https://github.com/AntonKhorev/openstreetmap-website/commit/8f946f13607c06df101d26b2b47087b342a29a45#commitcomment-140768884
Before:
After:
=> Fix message table action cell css display property

app/assets/javascripts/index/query.js, app/assets/stylesheets/common.scss, app/assets/stylesheets/parameters.scss
Similar to #4705, but for a [list-group](https://getbootstrap.com/docs/5.3/components/list-group/#links-and-buttons).
=> Use Bootstrap actionable items in query results

app/assets/javascripts/index/search.js, app/assets/stylesheets/common.scss, app/assets/stylesheets/parameters.scss, app/views/geocoder/results.html.erb
=> Use Bootstrap actionable items in search results lists

app/assets/javascripts/index/query.js, app/assets/stylesheets/common.scss
=> Stretch query result links

test/controllers/messages_controller_test.rb
See #4641 and previous similar pull requests.
=> Simplify message paths in tests

app/views/site/welcome.html.erb
Make it similar to the fixthemap page.
Before:
After:
=> Stack welcome page columns on small screens

app/assets/stylesheets/common.scss, app/views/site/_any_questions.html.erb, app/views/site/welcome.html.erb
Mostly I removed custom css and unnecessary markup, but I also changed the image placement from inlined/floated to their own column.
Before:
After:
=> Welcome page html and css cleanup

config/locales/en.yml
=> chore: clarify email reply text

app/views/sessions/new.html.erb, app/views/users/new.html.erb
=> Make the login and signup screens focus on the first input

app/assets/javascripts/index/browse.js, app/assets/stylesheets/common.scss
=> Remove custom css from "Load Data" button

config/initializers/content_security_policy.rb
=> Added gps.tile.openstreetmap.org as allowed source for images

app/controllers/diary_entries_controller.rb, app/helpers/open_graph_helper.rb, app/models/diary_entry.rb, app/views/layouts/_meta.html.erb, lib/rich_text.rb, test/controllers/diary_entries_controller_test.rb, test/lib/rich_text_test.rb
For `/user/:name/diary/:id` pages.
Part of #1361, which also asks for descriptions but I'm not sure what to put there.
=> Use first diary entry image in Open Graph

app/abilities/ability.rb, app/controllers/diary_comments_controller.rb, app/controllers/diary_entries_controller.rb, app/views/diary_entries/_diary_comment.html.erb, config/routes.rb, test/abilities/abilities_test.rb, test/controllers/diary_comments_controller_test.rb, test/controllers/diary_entries_controller_test.rb
=> Move diary comments hide/unhide actions to comments controller

README.md
This adds Anton to the list of our maintainers.
=> Add Anton as a maintainer

config/banners.yml
I got request from @wzbartczak that - based on feedback - linking event page would be better after all
sorry for the noise
=> link event website after all

app/views/api/map/index.json.jbuilder, app/views/api/nodes/index.json.jbuilder, app/views/api/nodes/show.json.jbuilder, app/views/api/old_nodes/history.json.jbuilder, app/views/api/old_nodes/show.json.jbuilder, app/views/api/old_relations/history.json.jbuilder, app/views/api/old_relations/show.json.jbuilder, app/views/api/old_ways/history.json.jbuilder, app/views/api/old_ways/show.json.jbuilder, app/views/api/relations/full.json.jbuilder, app/views/api/relations/index.json.jbuilder, app/views/api/relations/relations_for_node.json.jbuilder, app/views/api/relations/relations_for_relation.json.jbuilder, app/views/api/relations/relations_for_way.json.jbuilder, app/views/api/relations/show.json.jbuilder, app/views/api/ways/full.json.jbuilder, app/views/api/ways/index.json.jbuilder, app/views/api/ways/show.json.jbuilder, app/views/api/ways/ways_for_node.json.jbuilder
=> Avoid calling json.partial! in loop, render collections instead

test/lib/nominatim_test.rb
=> Test Nominatim.describe_location

app/abilities/ability.rb, app/controllers/diary_comments_controller.rb, app/controllers/diary_entries_controller.rb, app/views/diary_comments/new.html.erb, app/views/diary_entries/show.html.erb, config/locales/en.yml, config/routes.rb, test/abilities/abilities_test.rb, test/controllers/diary_comments_controller_test.rb, test/controllers/diary_entries_controller_test.rb
Continues #4905.
Supersedes #4634.
=> Move diary comment action to comments controller

test/controllers/changeset_comments_controller_test.rb
I'm not sure what [that](https://github.com/openstreetmap/openstreetmap-website/pull/4944#discussion_r1665980153) was about because comment ids are not inside CDATA or HTML or `<description>`, but rather inside `<link>` or `<guid>`:
The test picked numbers from
https://github.com/openstreetmap/openstreetmap-website/blob/a3441739ca4b70ee634e4e3c29415efe738df52e/test/factories/changeset_comments.rb#L3
which happens to also work because if they are descending so do the ids. But it's more complicated because of extra html parsing and more confusing because these numbers are called id yet they are not.
=> Check comment ids instead of factory sequence numbers in changeset feed tests

app/views/diary_entries/show.html.erb, test/controllers/api/changeset_comments_controller_test.rb, test/controllers/api/changesets_controller_test.rb
=> Simplify subscribe and hide path helper calls

test/controllers/api/changeset_comments_controller_test.rb, test/controllers/api/changesets_controller_test.rb, test/controllers/api/relations_controller_test.rb
=> Simplify api changeset path helper calls

app/controllers/user_blocks_controller.rb, app/views/user_blocks/_block.html.erb, app/views/user_blocks/show.html.erb, config/locales/en.yml, test/controllers/user_blocks_controller_test.rb
Part two of #5014. Those who revoke a block will be able to edit it.
=> Allow to edit revoked blocks

app/helpers/trace_helper.rb, app/views/traces/edit.html.erb, app/views/traces/show.html.erb
Follow up for https://github.com/openstreetmap/openstreetmap-website/pull/5030#issuecomment-2260651720
=> Trace picture with fixed size

app/views/user_mailer/_gpx_description.text.erb, app/views/user_mailer/gpx_failure.text.erb, app/views/user_mailer/gpx_success.text.erb, config/locales/en.yml
=> GPX Import email in text format

test/mailers/user_mailer_test.rb
Updated to test changes from #5031
=> Test plaintext trace emails

app/controllers/api/notes_controller.rb
As discussed in #4528, I'm proposing to add some note id locking as described here: https://api.rubyonrails.org/v7.1.3.4/classes/ActiveRecord/Locking/Pessimistic.html (first two examples).
The change covers destroy, comment, close and reopen methods, since all of them  are evaluating a note's visible and/or closed flag.
The important change is the "FOR UPDATE" addition when reading a note id initially. This way, two parallel processes cannot read the same note id at the same time and then both decide that e.g. reopening is permitted.
```
TRANSACTION (0.1ms)  BEGIN
↳ app/controllers/api/notes_controller.rb:208:in `block in reopen'
Note Load (14.7ms)  SELECT "notes".* FROM "notes" WHERE "notes"."id" = $1 LIMIT $2 FOR UPDATE  [["id", 3], ["LIMIT", 1]]
[...]
Note Update (0.3ms)  UPDATE …
```
=> Lock note during status update to avoid race condition

app/controllers/diary_comments_controller.rb, test/controllers/diary_comments_controller_test.rb
=> Redirect to newly created diary comment

test/controllers/api/nodes_controller_test.rb
=> Remove unused xml_parse method

test/system/user_blocks_test.rb
looks like I copypasted a wrong test name
=> Rename user blocks system test class

config/routes.rb, test/controllers/user_blocks_controller_test.rb
`/user_blocks/new` doesn't work because there's no username
=> Remove /user_blocks/new route

config/routes.rb
=> Define diary entry hide/unhide routes using post on members

app/views/dashboards/show.html.erb, test/controllers/dashboards_controller_test.rb, test/controllers/users_controller_test.rb, test/system/dashboard_test.rb
Addresses https://github.com/openstreetmap/openstreetmap-website/pull/5070#issuecomment-2304501335 about `dashboards_controller_test.rb`. I converted the test into a system test because this way it's easier to test for the displayed content. I'm checking for "You have not added any friends" where previously was no assertion. Also I don't rely on a html element id that was used only for testing.
=> Convert dashboard test into a system test

app/controllers/traces_controller.rb, test/controllers/traces_controller_test.rb
Missing locale string, see https://github.com/openstreetmap/openstreetmap-website/pull/5133#issuecomment-2322940489
=> Fix page title for failed trace updates

config/locales/en.yml
Unused since https://github.com/openstreetmap/openstreetmap-website/commit/2f9a4d03375e09279b33ff2530421b4cc69cd817
=> Remove unused layouts.donate string

config/locales/en.yml
Unused since https://github.com/openstreetmap/openstreetmap-website/commit/438e8be102a2ac4c0e92041da2866f1339715b40
=> Remove unused layouts.gps_traces_tooltip string

app/abilities/ability.rb
=> Remove :new abilities implied by :create abilities

config/i18n-tasks.yml, config/locales/en.yml
Some more cleanups for `bundle exec i18n-tasks health`.  Further details in respective commit messages.
=> Some more i18n unused translation fixes

app/views/changesets/show.html.erb
Does what https://github.com/openstreetmap/openstreetmap-website/pull/5223/commits/4564073106d5d48f3781a207693c39a13c130b66 did but without triggering extra ignores by i18n-tasks.
=> Don't use ?: in "Comment from user" changeset discussion strings

test/controllers/api/traces_controller_test.rb
While the discussion in #5038 is still ongoing, I have moved the unit test to a new PR.
Validating the results of trace import background job is useful for both scenarios
=> Trace import: validate background job results

vendor/assets/iD/iD.js
updates the editor layer index, adressing https://github.com/openstreetmap/iD/issues/10483
=> Update to iD v2.30.3

config/locales/en.yml
Fixes #5253. As requested by LWG.
=> Update link for Austria data sources

CONTRIBUTING.md
See https://github.com/openstreetmap/openstreetmap-website/issues/5258#issuecomment-2410282588
=> Remove Nominatim prefixes mention in contributors guide

config/locales/en.yml
wiki.osmfoundation.org redirects to osmfoundation.org, so we can update our links to point directly at the correct page.
=> Avoid linking to redirects on the osmfoundation website

app/assets/javascripts/index/query.js
=> Typos in docs

CONTRIBUTING.md, FAQ.md
This comes up repeatedly, and so let's document it. 
New users are encouraged by Github to read the CONTRIBUTING file, so that's where it's worth putting it. The explanation of why can be put elsewhere.
=> Add note on assigning issues

app/assets/javascripts/leaflet.layers.js
See https://github.com/openstreetmap/openstreetmap-website/issues/5329#issuecomment-2478786176
Before:
After:
=> Set background for layer buttons to secondary body color

app/models/user_block.rb
See https://github.com/openstreetmap/openstreetmap-website/pull/4301#discussion_r1367692119
=> Set max length of block reason

app/helpers/changesets_helper.rb, test/helpers/changesets_helper_test.rb
=> Truncate if necessary and set dir=auto for changeset usernames

app/assets/stylesheets/common.scss, app/views/messages/_message_summary.html.erb, app/views/messages/_sent_message_summary.html.erb
=> Truncate if necessary and set dir=auto for message usernames

app/views/issues/index.html.erb, config/locales/en.yml
in the search form on `/issues`
Before:
After:
=> Use translated model names in issue type select

app/assets/javascripts/diary_entry.js
=> Wrap diary entry location coordinates

app/views/api/messages/_message.json.jbuilder, app/views/api/messages/_message.xml.builder, test/controllers/api/messages_controller_test.rb
=> Include message_read attribute in api output of messages to self

app/assets/javascripts/embed.js.erb
Enable I18n fallback for the embed page to fix #5526.
=> Enable I18n fallback for the embed page

test/system/embed_test.rb
=> Test fallback locale on embed page

app/assets/javascripts/edit/id.js.erb, app/assets/javascripts/embed.js.erb, app/assets/javascripts/osm.js.erb
These have been flagged by the eslint-erb-plugin, and need to be fixed before that can be added.
Refs #5523
=> Fix some eslint errors (quotes spacing and parseInt radix) on .js.erb files

app/assets/javascripts/index/layers/notes.js
=> Abort loading when note layer is removed

app/assets/javascripts/embed.js.erb
Like #5571 but without fixup commits.
Closes #5550 and closes #5571
=> Refactor embed.js.erb and inlcude layers from layers.yml

app/assets/javascripts/embed.js.erb
=> Use dark mode map tiles in embed

app/assets/stylesheets/common.scss, app/views/issues/_page.html.erb, config/locales/en.yml
Reporter users isn't really grammatically correct so change it to reporting users instead.
=> Change "reporter users" to "reporting users"

test/controllers/api/changesets_controller_test.rb
Replaces lines like this
```ruby
assert_select "osm>changeset>discussion>comment:nth-child(1)>@id", comment1.id.to_s
```
with nested `assert_dom`s.
=> Refactor api changeset discussion tests

config/eslint.js
=> Remove Qs from eslint globals

app/assets/javascripts/user.js
Affects `/profile/edit` pages.
=> Fix missing zoom argument of OSM.cropLocation in home location

app/assets/javascripts/index.js, app/assets/javascripts/index/history.js, app/assets/javascripts/index/layers/notes.js, app/assets/javascripts/index/query.js, app/assets/javascripts/leaflet.layers.js, app/assets/javascripts/leaflet.share.js, app/assets/javascripts/router.js
Converts more loops to for..of loops due to increased readability and change .forEach() in combination with .push() to .map().
=> Reevaluate iteration methods

app/assets/javascripts/edit/id.js.erb
Over the years this script has grown an increasing amount of technical debt. I tried to remove some.
=> Simplify iD's initialisation

app/assets/javascripts/index/directions.js, test/system/directions_test.rb
Closes #5599 (literally)
Adding a conditional breakpoint in the site.
=> Close directions popup with sidebar

vendor/assets/iD/iD.css.erb, vendor/assets/iD/iD.js
Small bugfix release, fixing flickering when switching background layers or zooming (https://github.com/openstreetmap/iD/issues/10738).
=> Update to iD v2.31.1

app/assets/javascripts/index/directions/fossgis_osrm.js, app/assets/javascripts/index/directions/fossgis_valhalla.js, app/assets/javascripts/index/directions/graphhopper.js, app/assets/javascripts/social_share_button.js, config/eslint.js
I also changed the eslint rule to an error in a separate commit.
=> Fix all no-implicit-globals eslint errors

test/controllers/notes_controller_test.rb
Test for https://github.com/openstreetmap/openstreetmap-website/pull/5627/commits/cb51f46a4ff913985d535afed0fd8d7d1d955126.
=> Test showing note by suspended user with comment by other user

app/assets/javascripts/fixthemap.js, app/assets/javascripts/osm.js.erb, app/assets/javascripts/welcome.js
When parsing isn't required, I removed the calls, otherwise, I tried to bundle them so they get less in the way of things.
=> Reduce individual parsing of number strings

.vscode/settings.json
Add vscode style settings file which defines the location of eslint config file.
Load folder in editor and break eslint rule => direct visual feedback
fixes #5572
=> Add settings file for vscode derivates with eslint support

app/assets/javascripts/application.js, app/assets/javascripts/index.js, app/assets/javascripts/index/changeset.js, app/assets/javascripts/index/directions.js, app/assets/javascripts/leaflet.map.js, app/assets/javascripts/leaflet.note.js, app/assets/javascripts/leaflet.query.js, app/assets/javascripts/router.js
Simplifying if-else structures and condensing repeated expressions.
At least the things I found with my regex search.
=> Lessen code repetition

app/assets/javascripts/index/directions-endpoint.js, app/assets/javascripts/index/search.js, app/assets/javascripts/leaflet.share.js
Another few steps in embracing URLSearchParams.
=> Increase usage of URLSearchParams

app/assets/javascripts/application.js, app/assets/javascripts/index/contextmenu.js, app/assets/javascripts/index/layers/data.js, app/assets/javascripts/index/query.js, app/assets/javascripts/leaflet.locate.js, app/assets/javascripts/osm.js.erb, config/eslint.js
Found some that improve legibility.
=> Enable more linting rules

config/eslint.js
A less intrusive variant of #5647
=> Force only big objects in eslint configuration to be sorted

CONTRIBUTING.md
- a change that involv**es** ...
- (**for example** using ...
Render the markdown file 
see also:
https://www.merriam-webster.com/dictionary/e.g.#examples
=> Fix grammar and replace abbreviation in CONTRIBUTING md

config/eslint.js
A file comment combined with a config section is a bit confusing.
ref #5651
=> eslint: Move file config to eslint section

DOCKER.md
- not an avai**la**ble command ...
render the markdown file
=> Fix spelling of the word available in DOCKER md

app/controllers/accounts_controller.rb, app/controllers/concerns/user_methods.rb
This is the cleanups from #5453 without the main change to switch to turbo.
=> User settings fixes

.github/workflows/tests.yml
Adds ruby 3.4 to the test matrix...
=> Add ruby 3.4 to test matrix

test/system/browse_comment_links_test.rb
Tests for bugs fixed in #5679.
=> Test map panning when visiting changeset and note comment links

.overcommit.yml, .vscode/settings.json, config/eslint.config.mjs, lib/tasks/eslint.rake, package.json, yarn.lock
And upgrade `@stylistic/eslint-plugin-js` to `4.0.x`
closes #5708
=> Migrate eslint config to esmodules

app/assets/javascripts/index/directions.js, app/assets/javascripts/index/search.js
Split out of #5635 by the maintainers' suggestion.
=> Associate search input with route destination instead of departure

app/assets/javascripts/edit/id.js.erb, app/views/site/_id.html.erb
Follow-up to #5700 to include the zoom as well
=> Set zoom in id iframe data

app/controllers/api/changesets/downloads_controller.rb, test/controllers/api/changesets/downloads_controller_test.rb
This PR adds a missing feature in osm-website as compared to cgimap.
There's a `show_redactions` parameter which lets moderators see redacted element versions. In osm-website it works with element versions and histories. In cgimap it also works with changeset downloads. Without this parameter it's impossible to know which elements were changed in a given changeset. If you do a redaction and don't record all elements+versions somewhere, you won't be able to check whether everything was redacted correctly. You'll know that something in a changeset was redacted because the changes count won't match the number of elements in the download. But since the elements are missing, you won't be able to check their next versions, and you often need to redact the versions after the target changeset …
=> Add show_redactions param to changeset downloads

app/assets/javascripts/index/directions.js
Closes #5635, closes #5671
An event-based variant of #5671, vectorizing the coordinates for more compact fallback
=> Set directions departure to location

app/assets/javascripts/index/directions-endpoint.js
Moving even more requests away from XHR and jquery.
=> Replace jquery's getJSON with fetch

app/assets/javascripts/application.js, app/assets/javascripts/index/search.js, app/assets/javascripts/leaflet.key.js, app/assets/javascripts/leaflet.share.js, app/assets/javascripts/richtext.js, app/assets/javascripts/user.js
Continuing the move away from XHR.
There's probably a nice method to include the CSRF tokens under the hood, but at least this makes the need obvious.
=> Move jquery .load() to fetch

app/views/dashboards/_contact.html.erb, config/locales/en.yml
dashboards/contact template is the only place where these string are used.
=> Move a couple of i18n strings to dashboards/contact

app/controllers/issues/reporters_controller.rb, app/controllers/issues_controller.rb, app/views/issues/_page.html.erb, app/views/issues/reporters/_reporters.html.erb, app/views/issues/reporters/index.html.erb, config/locales/en.yml, config/routes.rb, test/controllers/issues/reporters_controller_test.rb
Implemented with Turbo frames.
=> Load more reporting users when clicking "and n more" in issues table

app/assets/javascripts/index/directions/fossgis_osrm.js, app/assets/javascripts/index/directions/fossgis_valhalla.js, app/assets/javascripts/index/directions/graphhopper.js, app/views/directions/search.html.erb
=> Add right u-turn for GraphHopper and Valhalla

config/locales/en.yml, test/system/dashboard_test.rb
See issue #5856.
I updated these strings to the best of my understanding, but I'm open to better suggestion to rephrase those strings.
Thank you!
=> Rephrase strings with the word "followings"

app/assets/javascripts/id.js, app/views/site/id.html.erb
Fixes #5864
With the dev tools
=> Propagate iD title to parent

app/assets/javascripts/index/directions.js, app/assets/javascripts/index/directions/fossgis_osrm.js, app/assets/javascripts/index/directions/fossgis_valhalla.js, app/assets/javascripts/index/directions/graphhopper.js, test/system/directions_test.rb
I took another look at the directions engines after #5898. I may have found too much, but I kept the commit size low this time.
in chrome and firefox
=> More directions refactoring

app/models/issue.rb
Continues #5786 by also sorting comments.
=> Order issue comments by id

app/assets/javascripts/index/search.js, test/system/search_test.rb
Fixes #5909.
With a test unlike the other PR.
=> Make reverse geocoding request with zoom using 'Where is this?'

test/system/search_test.rb
=> Test if 'Show address' includes zoom parameter

test/system/history_test.rb
=> Test if history shows changesets at expected locations

app/assets/javascripts/index/directions/fossgis_osrm.js, config/locales/en.yml
Closes #1000 again
Without the added translation
=> Add OSRM ferry support

app/assets/javascripts/index/history-changesets-layer.js
The goal is to have the following z-order:
1. areas of changeset bboxes outside the sidebar viewport
2. areas of changeset bboxes inside the sidebar viewport
3. borders of changeset bboxes outside the sidebar viewport
4. borders of changeset bboxes inside the sidebar viewport
This allows changesets inside the viewport to be selectable from a big pile of bboxes in one place and not completely prevent selecting smaller outside bboxes.
Here's a larger in-viewport bbox on top of the smaller out-of-viewport bboxes, even with the pointer inside one of these smaller bboxes:
But when the pointer is above a border of a smaller bbox, that bbox is highlighted:
The principle is that you should be able to select the things you see before anything else, and you actually see only the borders, not the …
=> Split interactive history layer into areas and borders above areas

app/assets/javascripts/index/directions.js
#5961's fix to #5959 was to delay starting the route request until the sidebar loaded, which isn't needed.
With this fix to #5959, I'm merging the page's pushstate/popstate with load and pulling out the sidebar requirement into a helper function also used in getRoute after the request, enabling the requests to be run in parallel.
This should remove half a second of extra latency for people with geostationary satellite internet.
=> Unify directions page handler and parallelize requests

app/assets/javascripts/heatmap.js, app/assets/stylesheets/common.scss, app/controllers/users_controller.rb, app/helpers/heatmap_helper.rb, app/views/users/_heatmap.html.erb, app/views/users/show.html.erb, test/controllers/users_controller_test.rb
Make the heatmap data generation more modular for yearly contribution calendars and address some points from the post merge discussion of #5998.
Also fixes #6021.
=> Extract heatmap data assembly into helper

app/assets/javascripts/index/directions.js, app/views/layouts/_search.html.erb, test/system/directions_test.rb
Reorganises the routing form according to proposals D/E of https://github.com/openstreetmap/openstreetmap-website/issues/3123#issuecomment-803143179.
=> Remove routing submit button

app/assets/javascripts/index/query.js, app/assets/javascripts/leaflet.map.js, app/assets/javascripts/osm.js.erb, test/javascripts/osm_test.js
Building on the changes from #6076 that didn't involve ripping out leaflet for consistency and instead prepare the bounds explicitly.
And another few things that caught my eye there.
=> Clean up query related code

app/assets/javascripts/leaflet.key.js, app/assets/javascripts/leaflet.sidebar-pane.js, app/views/map_keys/show.html.erb
Pulling this first part out of #6063.
=> Load map key only once

app/abilities/ability.rb, app/assets/javascripts/leaflet.share.js, app/controllers/share_panes_controller.rb, app/views/share_panes/show.html.erb, config/locales/en.yml, config/routes.rb, test/controllers/share_panes_controller_test.rb
Half of #6063 regarding the share sidebar
=> Move share sidebar to view

app/abilities/ability.rb, app/assets/javascripts/leaflet.layers.js, app/controllers/layers_panes_controller.rb, app/views/layers_panes/show.html.erb, config/locales/en.yml, config/routes.rb, test/controllers/layers_panes_controller_test.rb
Half of #6063 regarding the layers sidebar
=> Move layers sidebar to view

app/controllers/notes_controller.rb
=> Move set_locale as early as possible

test/controllers/notes_controller_test.rb
Tests the fix in c266f3c90a154dcb43ab0ff2b2e4337c510707d8.
=> Add test for set_locale fix in notes controller

app/assets/javascripts/leaflet.share.js, app/views/share_panes/show.html.erb, config/eslint.config.mjs
Trade extra JS for extra HTML since that's now a thing
=> Refactor share pane buttons to use Bootstrap tabs

vendor/assets/iD/iD.js
Bugfix release ([changelog](https://github.com/openstreetmap/iD/releases/tag/v2.35.2)). Fixes https://github.com/openstreetmap/iD/issues/11213, https://github.com/openstreetmap/iD/issues/11217 and https://github.com/openstreetmap/iD/issues/11220
=> Update to iD v2.35.2

vendor/assets/iD/iD.js
Includes a backported fix for issue https://github.com/openstreetmap/iD/issues/11225.
=> Update to iD v2.35.3

test/controllers/api/maps_controller_test.rb
=> Remove temporary debug code

app/assets/javascripts/leaflet.map.js
For the affected note makers, this makes them stand out more against the background and each other.
=> Always show marker shadows

app/controllers/notes_controller.rb, app/views/notes/_notes_paging_nav.html.erb, test/system/user_notes_test.rb
=> Fix next page boundary condition for user notes

config/locales/en.yml
https://github.com/openstreetmap/openstreetmap-website/commit/fc5f0f2ec064710caba8aa2aa693e0a515f97690#r163725641
=> Fix "Log in with Apple" title

config/locales/ce.yml, config/locales/da.yml, config/locales/eo.yml, config/locales/fi.yml, config/locales/hr.yml, config/locales/hsb.yml, config/locales/ja.yml, config/locales/sq.yml, test/lib/i18n_test.rb
Add test for GENDER macro in translations and fix broken translations as discussed in #6341.
=> Add test for mediawiki magic words in translations
